"""
Tests
"""

import pytest

from src.make2_bots.jobs_bots.te4_bots.t4_2018_jobs import te4_2018_Jobs

te4_2018_Jobs_data = {
    "egyptian male sport shooters": "لاعبو رماية ذكور مصريون",
    "egyptian sport shooters": "لاعبو رماية مصريون",
    "equatoguinean female footballers": "لاعبات كرة قدم غينيات استوائيات",
    "australian male sprinters": "عداؤون سريعون ذكور أستراليون",
    "canadian sports businesspeople": "شخصيات أعمال رياضيون كنديون",
    "cape verdean football managers": "مدراء كرة قدم أخضريون",
    "egyptian female sport shooters": "لاعبات رماية مصريات",
    "afghan competitors": "منافسون أفغان",
    "american basketball players": "لاعبو كرة سلة أمريكيون",
    "yemeni shi'a muslims": "يمنيون مسلمون شيعة",
    "shi'a muslims expatriates": "مسلمون شيعة مغتربون",
    "american men wheelchair racers": "متسابقو كراسي متحركة رجال أمريكيون",
    "american wheelchair racers": "متسابقو كراسي متحركة أمريكيون",
    "american women wheelchair racers": "متسابقات كراسي متحركة أمريكيات",
    "australian men wheelchair racers": "متسابقو كراسي متحركة رجال أستراليون",
    "australian wheelchair racers": "متسابقو كراسي متحركة أستراليون",
    "australian women wheelchair racers": "متسابقات كراسي متحركة أستراليات",
    "austrian men wheelchair racers": "متسابقو كراسي متحركة رجال نمساويون",
    "austrian wheelchair racers": "متسابقو كراسي متحركة نمساويون",
    "belgian men wheelchair racers": "متسابقو كراسي متحركة رجال بلجيكيون",
    "belgian wheelchair racers": "متسابقو كراسي متحركة بلجيكيون",
    "belgian women wheelchair racers": "متسابقات كراسي متحركة بلجيكيات",
    "brazilian men wheelchair racers": "متسابقو كراسي متحركة رجال برازيليون",
    "brazilian wheelchair racers": "متسابقو كراسي متحركة برازيليون",
    "brazilian women wheelchair racers": "متسابقات كراسي متحركة برازيليات",
    "british men wheelchair racers": "متسابقو كراسي متحركة رجال بريطانيون",
    "british wheelchair racers": "متسابقو كراسي متحركة بريطانيون",
    "british women wheelchair racers": "متسابقات كراسي متحركة بريطانيات",
    "canadian men wheelchair racers": "متسابقو كراسي متحركة رجال كنديون",
    "canadian wheelchair racers": "متسابقو كراسي متحركة كنديون",
    "canadian women wheelchair racers": "متسابقات كراسي متحركة كنديات",
    "chinese men wheelchair racers": "متسابقو كراسي متحركة رجال صينيون",
    "chinese wheelchair racers": "متسابقو كراسي متحركة صينيون",
    "chinese women wheelchair racers": "متسابقات كراسي متحركة صينيات",
    "czech wheelchair racers": "متسابقو كراسي متحركة تشيكيون",
    "danish wheelchair racers": "متسابقو كراسي متحركة دنماركيون",
    "dutch men wheelchair racers": "متسابقو كراسي متحركة رجال هولنديون",
    "dutch wheelchair racers": "متسابقو كراسي متحركة هولنديون",
    "dutch women wheelchair racers": "متسابقات كراسي متحركة هولنديات",
    "emirati wheelchair racers": "متسابقو كراسي متحركة إماراتيون",
    "english men wheelchair racers": "متسابقو كراسي متحركة رجال إنجليز",
    "english wheelchair racers": "متسابقو كراسي متحركة إنجليز",
    "english women wheelchair racers": "متسابقات كراسي متحركة إنجليزيات",
    "finnish men wheelchair racers": "متسابقو كراسي متحركة رجال فنلنديون",
    "finnish wheelchair racers": "متسابقو كراسي متحركة فنلنديون",
    "finnish women wheelchair racers": "متسابقات كراسي متحركة فنلنديات",
    "french men wheelchair racers": "متسابقو كراسي متحركة رجال فرنسيون",
    "french wheelchair racers": "متسابقو كراسي متحركة فرنسيون",
    "gabonese men wheelchair racers": "متسابقو كراسي متحركة رجال غابونيون",
    "gabonese wheelchair racers": "متسابقو كراسي متحركة غابونيون",
    "german men wheelchair racers": "متسابقو كراسي متحركة رجال ألمان",
    "german wheelchair racers": "متسابقو كراسي متحركة ألمان",
    "irish men wheelchair racers": "متسابقو كراسي متحركة رجال أيرلنديون",
    "irish wheelchair racers": "متسابقو كراسي متحركة أيرلنديون",
    "irish women wheelchair racers": "متسابقات كراسي متحركة أيرلنديات",
    "israeli men wheelchair racers": "متسابقو كراسي متحركة رجال إسرائيليون",
    "israeli wheelchair racers": "متسابقو كراسي متحركة إسرائيليون",
    "italian wheelchair racers": "متسابقو كراسي متحركة إيطاليون",
    "japanese men wheelchair racers": "متسابقو كراسي متحركة رجال يابانيون",
    "japanese wheelchair racers": "متسابقو كراسي متحركة يابانيون",
    "japanese women wheelchair racers": "متسابقات كراسي متحركة يابانيات",
    "kuwaiti wheelchair racers": "متسابقو كراسي متحركة كويتيون",
    "lithuanian wheelchair racers": "متسابقو كراسي متحركة ليتوانيون",
    "macedonian wheelchair racers": "متسابقو كراسي متحركة مقدونيون",
    "mexican men wheelchair racers": "متسابقو كراسي متحركة رجال مكسيكيون",
    "mexican wheelchair racers": "متسابقو كراسي متحركة مكسيكيون",
    "mexican women wheelchair racers": "متسابقات كراسي متحركة مكسيكيات",
    "norwegian wheelchair racers": "متسابقو كراسي متحركة نرويجيون",
    "russian wheelchair racers": "متسابقو كراسي متحركة روس",
    "wheelchair racers": "متسابقو كراسي متحركة",
    "polish wheelchair racers": "متسابقو كراسي متحركة بولنديون",
    "sammarinese wheelchair racers": "متسابقو كراسي متحركة سان مارينيون",
    "scottish wheelchair racers": "متسابقو كراسي متحركة إسكتلنديون",
    "scottish women wheelchair racers": "متسابقات كراسي متحركة إسكتلنديات",
    "south african men wheelchair racers": "متسابقو كراسي متحركة رجال جنوب إفريقيون",
    "south african wheelchair racers": "متسابقو كراسي متحركة جنوب إفريقيون",
    "south korean wheelchair racers": "متسابقو كراسي متحركة كوريون جنوبيون",
    "spanish wheelchair racers": "متسابقو كراسي متحركة إسبان",
    "swedish wheelchair racers": "متسابقو كراسي متحركة سويديون",
    "swiss men wheelchair racers": "متسابقو كراسي متحركة رجال سويسريون",
    "swiss wheelchair racers": "متسابقو كراسي متحركة سويسريون",
    "swiss women wheelchair racers": "متسابقات كراسي متحركة سويسريات",
    "thai wheelchair racers": "متسابقو كراسي متحركة تايلنديون",
    "tunisian wheelchair racers": "متسابقو كراسي متحركة تونسيون",
    "turkish wheelchair racers": "متسابقو كراسي متحركة أتراك",
    "turkish women wheelchair racers": "متسابقات كراسي متحركة تركيات",
    "welsh men wheelchair racers": "متسابقو كراسي متحركة رجال ويلزيون",
    "welsh wheelchair racers": "متسابقو كراسي متحركة ويلزيون",
    "welsh women wheelchair racers": "متسابقات كراسي متحركة ويلزيات",
    "zambian wheelchair racers": "متسابقو كراسي متحركة زامبيون",
    "american wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة أمريكيون",
    "american wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة أمريكيون",
    "american wheelchair curling champions": "أبطال الكيرلنغ على الكراسي المتحركة أمريكيون",
    "american wheelchair discus throwers": "رماة قرص على الكراسي المتحركة أمريكيون",
    "american wheelchair rugby players": "لاعبو رجبي على كراسي متحركة أمريكيون",
    "american wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة أمريكيون",
    "australian wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة أستراليون",
    "australian wheelchair rugby players": "لاعبو رجبي على كراسي متحركة أستراليون",
    "australian wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة أستراليون",
    "british wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة بريطانيون",
    "british wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة بريطانيون",
    "british wheelchair rugby players": "لاعبو رجبي على كراسي متحركة بريطانيون",
    "british wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة بريطانيون",
    "cameroonian wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة كاميرونيون",
    "canadian male wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة ذكور كنديون",
    "canadian wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة كنديون",
    "canadian wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة كنديون",
    "canadian wheelchair curling champions": "أبطال الكيرلنغ على الكراسي المتحركة كنديون",
    "canadian wheelchair rugby players": "لاعبو رجبي على كراسي متحركة كنديون",
    "chinese wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة صينيون",
    "danish wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة دنماركيون",
    "dutch wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة هولنديون",
    "dutch wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة هولنديون",
    "english wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة إنجليز",
    "finnish wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة فنلنديون",
    "finnish wheelchair curling champions": "أبطال الكيرلنغ على الكراسي المتحركة فنلنديون",
    "french wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة فرنسيون",
    "french wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة فرنسيون",
    "german wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة ألمان",
    "german wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة ألمان",
    "german wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة ألمان",
    "israeli wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة إسرائيليون",
    "israeli wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة إسرائيليون",
    "italian wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة إيطاليون",
    "japanese wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة يابانيون",
    "japanese wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة يابانيون",
    "japanese wheelchair rugby players": "لاعبو رجبي على كراسي متحركة يابانيون",
    "japanese wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة يابانيون",
    "kuwaiti wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة كويتيون",
    "latvian wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة لاتفيون",
    "norwegian wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة نرويجيون",
    "israeli women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية إسرائيليات",
    "japanese men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية يابانيون",
    "german women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية ألمانيات",
    "israeli men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية إسرائيليون",
    "french women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية فرنسيات",
    "german men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية ألمان",
    "french men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية فرنسيون",
    "dutch women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية هولنديات",
    "dutch men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية هولنديون",
    "canadian women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية كنديات",
    "canadian men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية كنديون",
    "british women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية بريطانيات",
    "cameroonian men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية كاميرونيون",
    "australian women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية أستراليات",
    "british men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية بريطانيون",
    "american men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية أمريكيون",
    "american women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية أمريكيات",
    "australian men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية أستراليون",
    "kuwaiti men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية كويتيون",
    "wheelchair basketball coaches": "مدربو كرة سلة على كراسي متحركة",
    "wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة",
    "wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة",
    "wheelchair fencers": "مبارزون على الكراسي المتحركة",
    "wheelchair rugby coaches": "مدربو رجبي على كراسي متحركة",
    "wheelchair rugby players": "لاعبو رجبي على كراسي متحركة",
    "wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة",
    "russian wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة روس",
    "scottish wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة إسكتلنديون",
    "scottish wheelchair curling champions": "أبطال الكيرلنغ على الكراسي المتحركة إسكتلنديون",
    "slovak wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة سلوفاكيون",
    "south african wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة جنوب إفريقيون",
    "south korean wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة كوريون جنوبيون",
    "spanish men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية إسبان",
    "spanish wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة إسبان",
    "spanish wheelchair fencers": "مبارزون على الكراسي المتحركة إسبان",
    "spanish wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة إسبان",
    "swedish wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة سويديون",
    "swedish wheelchair curling champions": "أبطال الكيرلنغ على الكراسي المتحركة سويديون",
    "swedish wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة سويديون",
    "swiss men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية سويسريون",
    "swiss wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة سويسريون",
    "swiss wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة سويسريون",
    "swiss wheelchair curling champions": "أبطال الكيرلنغ على الكراسي المتحركة سويسريون",
    "swiss wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة سويسريون",
    "thai wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة تايلنديون",
    "turkish men's wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة رجالية أتراك",
    "turkish wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة أتراك",
    "turkish wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة أتراك",
    "turkish women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية تركيات",
    "welsh wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة ويلزيون",
    "german footballers": "لاعبو كرة قدم ألمان",
    "ethiopian basketball players": "لاعبو كرة سلة إثيوبيون",
    "indian cricketers": "لاعبو كريكت هنود",
    "african people by nationality": "أفارقة حسب الجنسية",
    "african tennis players": "لاعبو كرة مضرب أفارقة",
    "albanian male tennis players": "لاعبو كرة مضرب ذكور ألبان",
    "albanian physicians": "أطباء ألبان",
    "albanian writers": "كتاب ألبان",
    "algerian expatriate sprtspeople": "رياضيون جزائريون مغتربون",
    "american agronomists": "مهندسون زراعيون أمريكيون",
    "american artists": "فنانون أمريكيون",
    "american bluegrass musicians": "موسيقيو بلوغراس أمريكيون",
    "american cricketers": "لاعبو كريكت أمريكيون",
    "american expatriates": "أمريكيون مغتربون",
    "american explorers": "مستكشفون أمريكيون",
    "american female athletes": "لاعبات قوى أمريكيات",
    "american folk musicians": "موسيقيو فولك أمريكيون",
    "american gospel singers": "مغنو غوسبل أمريكيون",
    "american novelists": "روائيون أمريكيون",
    "american people executed abroad": "أمريكيون أعدموا في الخارج",
    "american playback singers": "مغنو أفلام أمريكيون",
    "american women folk singers": "مغنيات فولك أمريكيات",
    "american women geographers": "جغرافيات أمريكيات",
    "american women guitarists": "عازفات قيثارة أمريكيات",
    "andy warhol": "آندي وارهول",
    "angolan radio journalists": "صحفيو راديو أنغوليون",
    "argentine expatriate sprtspeople": "رياضيون أرجنتينيون مغتربون",
    "argentine expatriates": "أرجنتينيون مغتربون",
    "argentine industrial designers": "مصممون صناعيون أرجنتينيون",
    "armenian cross-country skiers": "متزحلقون ريفيون أرمن",
    "armenian expatriate sprtspeople": "رياضيون أرمن مغتربون",
    "asian politicians": "سياسيون آسيويين",
    "athletes": "لاعبو قوى",
    "australian comedy writers": "كتاب كوميدي أستراليون",
    "australian expatriate sprtspeople": "رياضيون أستراليون مغتربون",
    "australian heavy metal singers": "مغنو هيفي ميتال أستراليون",
    "australian male sculptors": "نحاتون ذكور أستراليون",
    "australian oncologists": "أطباء أورام أستراليون",
    "australian science writers": "كتاب علم أستراليون",
    "austrian classical violinists": "عازفو كمان كلاسيكية نمساويون",
    "austrian film directors": "مخرجو أفلام نمساويون",
    "austrian pianists": "عازفو بيانو نمساويون",
    "austrian religious workers": "عمال دينيون نمساويون",
    "azerbaijani judges": "قضاة أذربيجانيون",
    "azerbaijani logicians": "منطقيون أذربيجانيون",
    "bangladeshi women artists": "فنانات بنغلاديشيات",
    "belarusian computer programmers": "مبرمجون بيلاروسيون",
    "belarusian female tennis players": "لاعبات كرة مضرب بيلاروسيات",
    "belarusian science fiction writers": "كتاب خيال علمي بيلاروسيون",
    "belizean expatriates": "بليزيون مغتربون",
    "beninese male boxers": "ملاكمون ذكور بنينيون",
    "bissau-guinean expatriate sprtspeople": "رياضيون غينيون بيساويون مغتربون",
    "bolivian expatriate sprtspeople": "رياضيون بوليفيون مغتربون",
    "bolivian lawyers": "محامون بوليفيون",
    "bolivian pianists": "عازفو بيانو بوليفيون",
    "bosnia and herzegovina artists": "فنانون بوسنيون",
    "bosnia and herzegovina female judoka": "لاعبات جودو بوسنيات",
    "brazilian artists": "فنانون برازيليون",
    "brazilian eugenicists": "علماء برازيليون متخصصون في تحسين النسل",
    "brazilian graphic novelists": "روائيو رويات مصورة برازيليون",
    "brazilian heavy metal guitarists": "عازفو قيثارة هيفي ميتال برازيليون",
    "brazilian women's rights activists": "برازيليون ناشطون في حقوق المرأة",
    "breton language activists": "ناشطون بلغة بريتانية",
    "british cardinals": "كرادلة بريطانيون",
    "british conceptual artists": "فنانون تصويريون بريطانيون",
    "british disability rights activists": "بريطانيون ناشطون في حقوق الإعاقة",
    "british emigrants": "بريطانيون مهاجرون",
    "british engineers": "مهندسون بريطانيون",
    "british expatriate field hockey players": "لاعبو هوكي ميدان بريطانيون مغتربون",
    "british expatriate sprtspeople": "رياضيون بريطانيون مغتربون",
    "british military personnel": "أفراد عسكريون بريطانيون",
    "british music industry executives": "مدراء صناعة الموسيقى بريطانيون",
    "bulgarian actors": "ممثلون بلغاريون",
    "bulgarian male opera singers": "مغنو أوبرا ذكور بلغاريون",
    "bulgarian priests": "كهنة بلغاريون",
    "bulgarian producers": "منتجون بلغاريون",
    "burkinabe expatriates": "بوركينابيون مغتربون",
    "burkinabe theatre people": "مسرحيون بوركينابيون",
    "burmese men marathon runners": "عداؤو ماراثون رجال بورميون",
    "cambodian radio journalists": "صحفيو راديو كمبوديون",
    "cameroonian communists": "شيوعيون كاميرونيون",
    "canadian expatriate ice hockey players": "لاعبو هوكي جليد كنديون مغتربون",
    "canadian expatriate sprtspeople": "رياضيون كنديون مغتربون",
    "canadian expatriates": "كنديون مغتربون",
    "canadian folk rock musicians": "موسيقيو فولك روك كنديون",
    "canadian ice dancers": "راقصو جليد كنديون",
    "canadian male biathletes": "لاعبو بياثلون ذكور كنديون",
    "canadian male kickboxers": "مقاتلو كيك بوكسنغ ذكور كنديون",
    "canadian men": "رجال كنديون",
    "canadian musicians": "موسيقيون كنديون",
    "canadian sportsmen": "رياضيون رجال كنديون",
    "cape verdean essayists": "كتاب مقالات أخضريون",
    "catherine the great": "كاترين الثانية",
    "caymanian expatriates": "كايمانيون مغتربون",
    "chechen rebels": "متمردون شيشانيون",
    "chilean expatriates": "تشيليون مغتربون",
    "chilean freestyle skiers": "ممارسو تزلج حر تشيليون",
    "chilean short story writers": "كتاب قصة قصيرة تشيليون",
    "chinese automotive engineers": "مهندسو سيارات صينيون",
    "chinese emigrants": "صينيون مهاجرون",
    "chinese expatriate sprtspeople": "رياضيون صينيون مغتربون",
    "chinese gamblers": "مقامرون صينيون",
    "chinese stage actors": "ممثلو مسرح صينيون",
    "chinese urban planners": "مخططون حضريون صينيون",
    "colombian composers": "ملحنون كولومبيون",
    "colombian expatriate baseball peoplee": "أعلام كرة قاعدة كولومبيون مغتربون",
    "colombian expatriate sprtspeople": "رياضيون كولومبيون مغتربون",
    "colombian folk singers": "مغنو فولك كولومبيون",
    "croatian baroque composers": "ملحنو باروك كروات",
    "croatian emigrants": "كروات مهاجرون",
    "croatian endocrinologists": "أطباء غدد صماء كروات",
    "croatian expatriates": "كروات مغتربون",
    "cuban christians": "كوبيون مسيحيون",
    "cuban poets": "شعراء كوبيون",
    "cypriot emigrants": "قبرصيون مهاجرون",
    "cypriot rugby union players": "لاعبو اتحاد رجبي قبرصيون",
    "czech painters": "رسامون تشيكيون",
    "czechoslovak ice hockey coaches": "مدربو هوكي جليد تشيكوسلوفاكيون",
    "danish ceramists": "خزفيون دنماركيون",
    "danish musicians": "موسيقيون دنماركيون",
    "democratic-republic-of-the-congo expatriate sprtspeople": "رياضيون كونغويون ديمقراطيون مغتربون",
    "dutch surveyors": "مساحون هولنديون",
    "eddie murphy": "إيدي ميرفي",
    "egyptian lawyers": "محامون مصريون",
    "english artists": "فنانون إنجليز",
    "english book and manuscript collectors": "جامعو كتب ومقتنيات إنجليز",
    "english cartographers": "علماء رسم خرائط إنجليز",
    "english expatriates": "إنجليز مغتربون",
    "english singer-songwriters": "مغنون وكتاب أغاني إنجليز",
    "english women": "إنجليزيات",
    "english-language culture": "ثقافة اللغة الإنجليزية",
    "english-language fantasy adventure films": "أفلام فانتازيا مغامرات باللغة الإنجليزية",
    "english-language radio stations": "محطات إذاعية باللغة الإنجليزية",
    "equatoguinean women": "غينيات استوائيات",
    "estonian astrologers": "منجمون إستونيون",
    "estonian motorcycle racers": "متسابقو دراجات نارية إستونيون",
    "estonian racing drivers": "سائقو سيارات سباق إستونيون",
    "estonian screenwriters": "كتاب سيناريو إستونيون",
    "ethiopian people imprisoned abroad": "إثيوبيون مسجونون في الخارج",
    "european sports coaches": "مدربو رياضية أوروبيون",
    "fijian football managers": "مدراء كرة قدم فيجيون",
    "fijian language": "لغة فيجية",
    "fijian long jumpers": "لاعبو قفز طويل فيجيون",
    "filipino newspaper people": "شخصيات صحف فلبينيون",
    "finnish expatriate sprtspeople": "رياضيون فنلنديون مغتربون",
    "finnish expatriates": "فنلنديون مغتربون",
    "finnish women archaeologists": "عالمات آثار فنلنديات",
    "finnish women's ice hockey defencemen": "مدافعات هوكي جليد فنلنديات",
    "francisco goya": "فرانثيسكو غويا",
    "french male painters": "رسامون ذكور فرنسيون",
    "french male singer-songwriters": "مغنون وكتاب أغاني ذكور فرنسيون",
    "french scholars-of-islam": "فرنسيون باحثون عن الإسلام",
    "french sportsmen": "رياضيون رجال فرنسيون",
    "french women performance artists": "فنانات أدائيات فرنسيات",
    "french-language albums": "ألبومات باللغة الفرنسية",
    "french-language singers": "مغنون باللغة الفرنسية",
    "french-language television": "تلفاز باللغة الفرنسية",
    "german advertising executives": "مدراء إعلانات ألمان",
    "german emigrants": "ألمان مهاجرون",
    "german expatriate sprtspeople": "رياضيون ألمان مغتربون",
    "german expatriates": "ألمان مغتربون",
    "german male pianists": "عازفو بيانو ذكور ألمان",
    "german people by occupation": "ألمان حسب المهنة",
    "german women civil servants": "موظفات خدمة مدنية ألمانيات",
    "german-language films": "أفلام باللغة الألمانية",
    "ghanaian expatriates": "غانيون مغتربون",
    "ghanaian women editors": "محررات غانيات",
    "greek expatriates": "يونانيون مغتربون",
    "greek female prostitutes": "داعرات يونانيات",
    "greek male dancers": "راقصون ذكور يونانيون",
    "greek prisoners": "مسجونون يونانيون",
    "greek slaves": "عبيد يونانيون",
    "greek sprtspeople": "رياضيون يونانيون",
    "greek women writers": "كاتبات يونانيات",
    "haitian expatriate sprtspeople": "رياضيون هايتيون مغتربون",
    "haitian officials": "مسؤولون هايتيون",
    "honduran economists": "اقتصاديون هندوراسيون",
    "honduran women poets": "شاعرات هندوراسيات",
    "hong kong female rowers": "مجدفات هونغ كونغيات",
    "hungarian flautists": "عازفو فولت مجريون",
    "hungarian male opera singers": "مغنو أوبرا ذكور مجريون",
    "icelandic actresses": "ممثلات آيسلنديات",
    "icelandic emigrants": "آيسلنديون مهاجرون",
    "idina menzel": "إيدينا مينزيل",
    "igor stravinsky": "إيغور سترافينسكي",
    "indian explorers": "مستكشفون هنود",
    "indian muslim missionaries": "مبشرون مسلمون هنود",
    "indian politicians": "سياسيون هنود",
    "indian scholars": "دارسون هنود",
    "indian translators": "مترجمون هنود",
    "indian women flautists": "عازفات فولت هنديات",
    "indian women lawyers": "محاميات هنديات",
    "indian women writers": "كاتبات هنديات",
    "iranian criminals": "مجرمون إيرانيون",
    "iranian photographers": "مصورون إيرانيون",
    "iranian poets": "شعراء إيرانيون",
    "irish female sailors (sport)": "بحارات رياضيات أيرلنديات",
    "irish male musicians": "موسيقيون ذكور أيرلنديون",
    "irish women aviators": "طيارات أيرلنديات",
    "irish women fashion designers": "مصممات أزياء أيرلنديات",
    "israeli agronomists": "مهندسون زراعيون إسرائيليون",
    "israeli artists": "فنانون إسرائيليون",
    "israeli criminals": "مجرمون إسرائيليون",
    "israeli expatriate sprtspeople": "رياضيون إسرائيليون مغتربون",
    "israeli male stage actors": "ممثلو مسرح ذكور إسرائيليون",
    "italian emigrants": "إيطاليون مهاجرون",
    "italian male mixed martial artists": "مقاتلو فنون قتالية مختلطة ذكور إيطاليون",
    "italian medical historians": "مؤرخون طبيون إيطاليون",
    "italian military personnel": "أفراد عسكريون إيطاليون",
    "italian physicians": "أطباء إيطاليون",
    "italian rowers": "مجدفون إيطاليون",
    "italian women librarians": "أمينات مكتبات إيطاليات",
    "italian writers": "كتاب إيطاليون",
    "ivorian expatriate sprtspeople": "رياضيون إيفواريون مغتربون",
    "ivorian writers": "كتاب إيفواريون",
    "jamaican expatriate sprtspeople": "رياضيون جامايكيون مغتربون",
    "jamaican expatriates": "جامايكيون مغتربون",
    "jamaican women poets": "شاعرات جامايكيات",
    "japanese language": "لغة يابانية",
    "japanese prisoners": "مسجونون يابانيون",
    "japanese social scientists": "مختصون بالعلوم الاجتماعية يابانيون",
    "johann wolfgang von goethe": "يوهان فولفغانغ فون غوته",
    "jordanian equestrians": "فرسان خيول أردنيون",
    "jordanian expatriate sprtspeople": "رياضيون أردنيون مغتربون",
    "judoka": "لاعبو جودو",
    "kazakhstani artists": "فنانون كازاخستانيون",
    "kazakhstani expatriates": "كازاخستانيون مغتربون",
    "kazakhstani football referees": "حكام كرة قدم كازاخستانيون",
    "korean scientists": "علماء كوريون",
    "kosovan pianists": "عازفو بيانو كوسوفيون",
    "kosovan victims of crime": "ضحايا جرائم كوسوفيون",
    "kuwaiti female cyclists": "دراجات كويتيات",
    "kuwaiti nationalists": "قوميون كويتيون",
    "kuwaiti women writers": "كاتبات كويتيات",
    "latvian expatriate sprtspeople": "رياضيون لاتفيون مغتربون",
    "latvian kickboxers": "مقاتلو كيك بوكسنغ لاتفيون",
    "lithuanian children": "أطفال ليتوانيون",
    "lithuanian expatriates": "ليتوانيون مغتربون",
    "lithuanian men's footballers": "لاعبو كرة قدم رجالية ليتوانيون",
    "luxembourgian cross-country skiers": "متزحلقون ريفيون لوكسمبورغيون",
    "macedonian expatriate female footballers": "لاعبات كرة قدم مقدونيات مغتربات",
    "macedonian male taekwondo practitioners": "لاعبو تايكوندو ذكور مقدونيون",
    "malaysian expatriates": "ماليزيون مغتربون",
    "malian artists": "فنانون ماليون",
    "maltese artisans": "حرفيون مالطيون",
    "maltese christian missionaries": "مبشرون مسيحيون مالطيون",
    "manx sailors (sport)": "بحارة رياضيون مانكسيون",
    "marathi films": "أفلام باللغة الماراثية",
    "mexican actresses": "ممثلات مكسيكيات",
    "mexican comedians": "كوميديون مكسيكيون",
    "mexican crime fiction writers": "كتاب خيال الجريمة مكسيكيون",
    "mexican expatriates": "مكسيكيون مغتربون",
    "michael porter": "مايكل بورتر",
    "moldovan expatriates": "مولدوفيون مغتربون",
    "mongolian cross-country skiers": "متزحلقون ريفيون منغوليون",
    "mongolian female skiers": "متزحلقات منغوليات",
    "montenegrin expatriate basketball peoplee": "أعلام كرة سلة مونتينيغريون مغتربون",
    "moravian bishops": "أساقفة مورافيون",
    "moroccan expatriate sprtspeople": "رياضيون مغاربة مغتربون",
    "moroccan male mixed martial artists": "مقاتلو فنون قتالية مختلطة ذكور مغاربة",
    "namibian long jumpers": "لاعبو قفز طويل ناميبيون",
    "native american aviators": "طيارون أمريكيون أصليون",
    "nepalese clergy": "رجال دين نيباليون",
    "nepalese cross-country skiers": "متزحلقون ريفيون نيباليون",
    "new caledonian women runners": "عداءات كاليدونيات",
    "nigerian expatriate sprtspeople": "رياضيون نيجيريون مغتربون",
    "nigerian musicians": "موسيقيون نيجيريون",
    "north korean women athletes": "لاعبات قوى كوريات شماليات",
    "norwegian artists": "فنانون نرويجيون",
    "norwegian botanists": "علماء نباتات نرويجيون",
    "norwegian expatriates": "نرويجيون مغتربون",
    "omani politicians": "سياسيون عمانيون",
    "pakistani expatriate actors": "ممثلون باكستانيون مغتربون",
    "pakistani pop singers": "مغنو بوب باكستانيون",
    "panamanian anti-communists": "بنميون مناهضون للشيوعية",
    "panamanian expatriates": "بنميون مغتربون",
    "paraguayan classical musicians": "موسيقيو كلاسيكية بارغوايانيون",
    "paraguayan male actors": "ممثلون ذكور بارغوايانيون",
    "paraguayan singers": "مغنون بارغوايانيون",
    "paraguayan surgeons": "جراحون بارغوايانيون",
    "peruvian female freestyle swimmers": "سباحات تزلج حر بيرويات",
    "peruvian women": "بيرويات",
    "polish contraltos": "كونترالتويون بولنديون",
    "polish emigrants": "بولنديون مهاجرون",
    "polish expatriate sprtspeople": "رياضيون بولنديون مغتربون",
    "polish fascists": "فاشيون بولنديون",
    "polish magazine founders": "مؤسسو مجلات بولنديون",
    "polish rock singers": "مغنو روك بولنديون",
    "polish screenwriters": "كتاب سيناريو بولنديون",
    "polish sports executives and administrators": "مسيرون رياضيون بولنديون",
    "polish sportswomen": "رياضيات بولنديات",
    "polish-language films": "أفلام باللغة البولندية",
    "portuguese composers": "ملحنون برتغاليون",
    "portuguese expatriate sprtspeople": "رياضيون برتغاليون مغتربون",
    "portuguese monarchs": "ملكيون برتغاليون",
    "portuguese poets": "شعراء برتغاليون",
    "prussian military personnel": "أفراد عسكريون بروسيون",
    "puerto rican equestrians": "فرسان خيول بورتوريكيون",
    "puerto rican expatriate basketball peoplee": "أعلام كرة سلة بورتوريكيون مغتربون",
    "puerto rican men high jumpers": "متسابقو قفز عالي رجال بورتوريكيون",
    "puerto rican rhythmic gymnasts": "لاعبو جمباز إيقاعي بورتوريكيون",
    "puerto rican sportsmen": "رياضيون رجال بورتوريكيون",
    "puerto rican women": "بورتوريكيات",
    "republic-of-the-congo expatriate sprtspeople": "رياضيون كونغويون مغتربون",
    "roman governors": "حكام رومانيون",
    "romanian geodesists": "جيوديسيون رومانيون",
    "romanian women radio presenters": "مذيعات راديو رومانيات",
    "russian artists": "فنانون روس",
    "russian botanists": "علماء نباتات روس",
    "russian expatriate sprtspeople": "رياضيون روس مغتربون",
    "russian expatriates": "روس مغتربون",
    "russian male voice actors": "ممثلو أداء صوتي ذكور روس",
    "salvadoran sportswomen": "رياضيات سلفادوريات",
    "sara bareilles": "سارة باريلز",
    "saudiarabian astronauts": "رواد فضاء سعوديون",
    "scottish expatriates": "إسكتلنديون مغتربون",
    "scottish fashion designers": "مصممو أزياء إسكتلنديون",
    "scottish male golfers": "لاعبو غولف ذكور إسكتلنديون",
    "scottish women civil servants": "موظفات خدمة مدنية إسكتلنديات",
    "senegalese expatriate sprtspeople": "رياضيون سنغاليون مغتربون",
    "serbian expatriates": "صرب مغتربون",
    "serbian journalists": "صحفيون صرب",
    "serbian muay thai practitioners": "ممارسو موياي تاي صرب",
    "serbian political philosophers": "فلاسفة سياسيون صرب",
    "sierra leonean expatriate sprtspeople": "رياضيون سيراليونيون مغتربون",
    "sierra leonean lawyers": "محامون سيراليونيون",
    "singaporean artists": "فنانون سنغافوريون",
    "slovak expatriate sprtspeople": "رياضيون سلوفاكيون مغتربون",
    "slovak jazz singers": "مغنو جاز سلوفاكيون",
    "slovak musicians": "موسيقيون سلوفاكيون",
    "slovak sprtspeople": "رياضيون سلوفاكيون",
    "slovenian explorers": "مستكشفون سلوفينيون",
    "slovenian football referees": "حكام كرة قدم سلوفينيون",
    "south korean expatriates": "كوريون جنوبيون مغتربون",
    "south korean male biathletes": "لاعبو بياثلون ذكور كوريون جنوبيون",
    "south korean songwriters": "كتاب أغان كوريون جنوبيون",
    "south sudanese expatriate sprtspeople": "رياضيون جنوبيون سودانيون مغتربون",
    "soviet biochemists": "كيميائيون حيويون سوفيت",
    "soviet filmmakers": "صانعو أفلام سوفيت",
    "soviet male figure skaters": "متزلجون فنيون ذكور سوفيت",
    "soviet theatre people": "مسرحيون سوفيت",
    "spanish composers": "ملحنون إسبان",
    "spanish graphic novelists": "روائيو رويات مصورة إسبان",
    "spanish journalists": "صحفيون إسبان",
    "spanish male biographers": "كتاب سيرة ذكور إسبان",
    "spanish nuns": "راهبات إسبانيات",
    "spanish philosophers": "فلاسفة إسبان",
    "spanish women fashion designers": "مصممات أزياء إسبانيات",
    "spanish-language mass media": "إعلام اللغة الإسبانية",
    "sri lankan emigrants": "سريلانكيون مهاجرون",
    "sri lankan male kabaddi players": "لاعبو كابادي ذكور سريلانكيون",
    "sri lankan mechanical engineers": "مهندسو ميكانيك سريلانكيون",
    "sri lankan military personnel": "أفراد عسكريون سريلانكيون",
    "sri lankan television actresses": "ممثلات تلفزيون سريلانكيات",
    "surinamese women children's writers": "كاتبات أطفال سوريناميات",
    "swedish artists": "فنانون سويديون",
    "swedish badminton players": "لاعبو تنس ريشة سويديون",
    "swedish dancers": "راقصون سويديون",
    "swedish expatriates": "سويديون مغتربون",
    "swedish inventors": "مخترعون سويديون",
    "swedish male archers": "نبالون ذكور سويديون",
    "swedish women guitarists": "عازفات قيثارة سويديات",
    "swedish-language albums": "ألبومات باللغة السويدية",
    "swimmers": "سباحون",
    "swiss emigrants": "سويسريون مهاجرون",
    "swiss expatriate sprtspeople": "رياضيون سويسريون مغتربون",
    "swiss lugers": "زاحفون ثلجيون سويسريون",
    "swiss murder victims": "ضحايا قتل سويسريون",
    "swiss radio actors": "ممثلو راديو سويسريون",
    "swiss rowers": "مجدفون سويسريون",
    "syrian female table tennis players": "لاعبات كرة طاولة سوريات",
    "taiwanese catholics": "كاثوليك تايوانيون",
    "taiwanese emigrants": "تايوانيون مهاجرون",
    "taiwanese female cyclists": "دراجات تايوانيات",
    "taiwanese politicians": "سياسيون تايوانيون",
    "tanzanian expatriate sprtspeople": "رياضيون تنزانيون مغتربون",
    "thai lesbians": "سحاقيات تايلنديات",
    "togolese bishops": "أساقفة توغويون",
    "togolese expatriate sprtspeople": "رياضيون توغويون مغتربون",
    "togolese female footballers": "لاعبات كرة قدم توغويات",
    "tongan rugby league coaches": "مدربو دوري رجبي تونغانيون",
    "trinidad and tobago rugby union players": "لاعبو اتحاد رجبي ترنيداديون",
    "tunisian male fencers": "مبارزون ذكور تونسيون",
    "turkish women athletes": "لاعبات قوى تركيات",
    "turkish women's rights activists": "أتراك ناشطون في حقوق المرأة",
    "ukrainian artists": "فنانون أوكرانيون",
    "ukrainian expatriate sprtspeople": "رياضيون أوكرانيون مغتربون",
    "ukrainian female pair skaters": "متزلجات فنيات على الجليد أوكرانيات",
    "urdu-language musical comedy films": "أفلام موسيقية كوميدية باللغة الأردية",
    "uruguayan actors": "ممثلون أوروغويانيون",
    "uruguayan dramatists and playwrights": "كتاب دراما ومسرح أوروغويانيون",
    "uruguayan dramatists": "دراميون أوروغويانيون",
    "uzbekistani environmentalists": "بيئيون أوزبكستانيون",
    "venezuelan emigrants": "فنزويليون مهاجرون",
    "venezuelan expatriate sprtspeople": "رياضيون فنزويليون مغتربون",
    "venezuelan male poets": "شعراء ذكور فنزويليون",
    "venezuelan surgeons": "جراحون فنزويليون",
    "vietnamese female freestyle swimmers": "سباحات تزلج حر فيتناميات",
    "vietnamese sprtspeople": "رياضيون فيتناميون",
    "weightlifters": "رباعون",
    "welsh athletes": "لاعبو قوى ويلزيون",
    "welsh classical scholars": "باحثون كلاسيكيون ويلزيون",
    "welsh clergy": "رجال دين ويلزيون",
    "welsh comedians": "كوميديون ويلزيون",
    "welsh expatriate footballers": "لاعبو كرة قدم ويلزيون مغتربون",
    "welsh expatriates": "ويلزيون مغتربون",
    "welsh jazz composers": "ملحنو جاز ويلزيون",
    "welsh musicians": "موسيقيون ويلزيون",
    "welsh satirists": "كتاب هجائيون ويلزيون",
    "welsh sports businesspeople": "شخصيات أعمال رياضيون ويلزيون",
    "yugoslav sprinters": "عداؤون سريعون يوغوسلافيون",
    "zambian emigrants": "زامبيون مهاجرون",
    "zambian writers": "كتاب زامبيون",
    "zimbabwean expatriates": "زيمبابويون مغتربون",
    "zimbabwean marxists": "ماركسيون زيمبابويون",
    "football players": "لاعبو كرة قدم",
    "pan-africanists": "وحدويون أفارقة",
    "south american pan-africanists": "وحدويون أفارقة أمريكيون جنوبيون",
}


@pytest.mark.parametrize("category, expected_key", te4_2018_Jobs_data.items(), ids=list(te4_2018_Jobs_data.keys()))
@pytest.mark.slow
def test_te4_2018_Jobs_data(category, expected_key) -> None:
    label = te4_2018_Jobs(category)
    assert label.strip() == expected_key


data_fast = {
    "american basketball coaches": "مدربو كرة سلة أمريكيون",
    "polish women": "بولنديات",
    "portuguese healthcare managers": "مدراء رعاية صحية برتغاليون",
    "iranian nuclear medicine physicians": "أطباء طب نووي إيرانيون",
    "italian defectors": "إيطاليون منشقون",
    "canadian nuclear medicine physicians": "أطباء طب نووي كنديون",
    "croatian nuclear medicine physicians": "أطباء طب نووي كروات",
    "german nuclear medicine physicians": "أطباء طب نووي ألمان",
    "afghan diplomats": "دبلوماسيون أفغان",
    "american nuclear medicine physicians": "أطباء طب نووي أمريكيون",
    "argentine multi-instrumentalists": "عازفون على عدة آلات أرجنتينيون",
    "australian internet celebrities": "مشاهير إنترنت أستراليون",
    "afghan emigrants": "أفغان مهاجرون",
    "afghan expatriates": "أفغان مغتربون",
    "european women": "أوروبيات",
    "ivorian emigrants": "إيفواريون مهاجرون",
    "ivorian expatriates": "إيفواريون مغتربون",
    "cross-country skiers": "متزحلقون ريفيون",
    "dutch explorers": "مستكشفون هولنديون",
    "albanian sports coaches": "مدربو رياضية ألبان",
    "competitors": "منافسون",
    "american cinema editors": "محررون سينمائون أمريكيون",
    "argentine songwriters": "كتاب أغان أرجنتينيون",
    "british editorial cartoonists": "محررون كارتونيون بريطانيون",
    "british television chefs": "طباخو تلفاز بريطانيون",
    "peruvian television actors": "ممثلو تلفزيون بيرويون",
    "american award winners": "حائزو جوائز أمريكيون",
    "egyptian oncologists": "أطباء أورام مصريون",
    "pakistani psychiatrists": "أطباء نفسيون باكستانيون",
    "swedish oncologists": "أطباء أورام سويديون",
    "irish football managers": "مدراء كرة قدم أيرلنديون",
    "male long-distance runners": "عداؤو مسافات طويلة ذكور",
    "moroccan competitors": "منافسون مغاربة",
    "moroccan male middle-distance runners": "عداؤو مسافات متوسطة ذكور مغاربة",
    "norwegian figure skaters": "متزلجون فنيون نرويجيون",
    "norwegian male pair skaters": "متزلجون فنيون على الجليد ذكور نرويجيون",
    "norwegian male single skaters": "متزلجون فرديون ذكور نرويجيون",
    "belgian athletics coaches": "مدربو ألعاب قوى بلجيكيون",
    "norwegian pair skaters": "متزلجون فنيون على الجليد نرويجيون",
    "norwegian short track speed skaters": "متزلجون على مسار قصير نرويجيون",
    "republic-of ireland football managers": "مدراء كرة قدم أيرلنديون",
    "turkish expatriate sprtspeople": "رياضيون أتراك مغتربون",
    "icelandic male athletes": "لاعبو قوى ذكور آيسلنديون",
    "icelandic male runners": "عداؤون ذكور آيسلنديون",
    "icelandic male steeplechase runners": "عداؤو موانع ذكور آيسلنديون",
}


@pytest.mark.parametrize("category, expected_key", data_fast.items(), ids=list(data_fast.keys()))
@pytest.mark.fast
def test_data_fast(category, expected_key) -> None:
    label = te4_2018_Jobs(category)
    assert label.strip() == expected_key


def test_te4_2018_Jobs():
    # Test with a basic input
    result = te4_2018_Jobs("test job")
    assert isinstance(result, str)

    result_empty = te4_2018_Jobs("")
    assert isinstance(result_empty, str)

    # Test with various inputs
    result_various = te4_2018_Jobs("football players")
    assert isinstance(result_various, str)
