"""
Tests
"""

import pytest

from src.make2_bots.jobs_bots.te4_bots.for_me import (
    Work_for_me,
    Work_for_New_2018_men_Keys_with_all,
    add_all,
)

fast_data = [
    {"cate": "asian games bronze medalists", "nat": "asian", "con_3": "games bronze medalists", "output": "فائزون بميداليات برونزية في الألعاب الآسيوية"},
    {"cate": "australian black metal musical groups", "nat": "australian", "con_3": "black metal musical groups", "output": "فرق موسيقى بلاك ميتال أسترالية"},
    {"cate": "australian electronic dance music", "nat": "australian", "con_3": "electronic dance music", "output": "موسيقى الرقص الإلكترونية أسترالي"},
    {"cate": "australian musicals", "nat": "australian", "con_3": "musicals", "output": "مسرحيات غنائية أسترالية"},
    {"cate": "australian rugby union", "nat": "australian", "con_3": "rugby union", "output": "اتحاد الرجبي الأسترالي"},
    {"cate": "australian tennis", "nat": "australian", "con_3": "tennis", "output": "كرة مضرب أسترالية"},
    {"cate": "australian women's ice hockey league", "nat": "australian", "con_3": "women's ice hockey league", "output": "الدوري الأسترالي لهوكي الجليد للسيدات"},
    {"cate": "austrian rock", "nat": "austrian", "con_3": "rock", "output": "روك نمساوي"},
    {"cate": "azerbaijani encyclopedias", "nat": "azerbaijani", "con_3": "encyclopedias", "output": "موسوعات أذربيجانية"},
    {"cate": "azerbaijani football club seasons", "nat": "azerbaijani", "con_3": "football club seasons", "output": "مواسم أندية كرة قدم أذربيجانية"},
    {"cate": "azerbaijani heavy metal musical groups", "nat": "azerbaijani", "con_3": "heavy metal musical groups", "output": "فرق موسيقى هيفي ميتال أذربيجانية"},
    {"cate": "bahamian awards", "nat": "bahamian", "con_3": "awards", "output": "جوائز بهامية"},
    {"cate": "bangladesh cinema", "nat": "bangladesh", "con_3": "cinema", "output": "السينما البنغلاديشية"},
    {"cate": "bangladeshi awards", "nat": "bangladeshi", "con_3": "awards", "output": "جوائز بنغلاديشية"},
    {"cate": "bangladeshi companies", "nat": "bangladeshi", "con_3": "companies", "output": "شركات بنغلاديشية"},
    {"cate": "bangladeshi folk music", "nat": "bangladeshi", "con_3": "folk music", "output": "موسيقى فلكلورية بنغلاديشية"},
    {"cate": "belarusian sport", "nat": "belarusian", "con_3": "sport", "output": "رياضة بيلاروسية"},
    {"cate": "belgian companies", "nat": "belgian", "con_3": "companies", "output": "شركات بلجيكية"},
    {"cate": "belgian detention", "nat": "belgian", "con_3": "detention", "output": "المعتقلات البلجيكية"},
    {"cate": "belgian novels", "nat": "belgian", "con_3": "novels", "output": "روايات بلجيكية"},
    {"cate": "belgian tennis", "nat": "belgian", "con_3": "tennis", "output": "كرة مضرب بلجيكية"},
    {"cate": "beninese sport", "nat": "beninese", "con_3": "sport", "output": "رياضة بنينية"},
    {"cate": "bolivian television series", "nat": "bolivian", "con_3": "television series", "output": "مسلسلات تلفزيونية بوليفية"},
    {"cate": "brazilian design", "nat": "brazilian", "con_3": "design", "output": "تصميم برازيلي"},
    {"cate": "brazilian rugby league players", "nat": "brazilian", "con_3": "rugby league players", "output": "لاعبو الدوري البرازيلي للرجبي"},
    {"cate": "brazilian television series", "nat": "brazilian", "con_3": "television series", "output": "مسلسلات تلفزيونية برازيلية"},
    {"cate": "brazilian tennis", "nat": "brazilian", "con_3": "tennis", "output": "كرة مضرب برازيلية"},
    {"cate": "british black metal musical groups", "nat": "british", "con_3": "black metal musical groups", "output": "فرق موسيقى بلاك ميتال بريطانية"},
    {"cate": "british descent", "nat": "british", "con_3": "descent", "output": "أصل بريطاني"},
    {"cate": "british international schools", "nat": "british", "con_3": "international schools", "output": "مدارس دولية بريطانية"},
    {"cate": "british medical association", "nat": "british", "con_3": "medical association", "output": "الجمعية الطبية البريطانية"},
    {"cate": "british music", "nat": "british", "con_3": "music", "output": "موسيقى بريطانية"},
    {"cate": "british plays", "nat": "british", "con_3": "plays", "output": "مسرحيات بريطانية"},
    {"cate": "british restaurants", "nat": "british", "con_3": "restaurants", "output": "مطاعم بريطانية"},
    {"cate": "british rugby union", "nat": "british", "con_3": "rugby union", "output": "اتحاد الرجبي البريطاني"},
    {"cate": "british women's sport", "nat": "british", "con_3": "women's sport", "output": "رياضة بريطانية نسائية"},
    {"cate": "bulgarian cup", "nat": "bulgarian", "con_3": "cup", "output": "كأس بلغاريا"},
    {"cate": "burkinabe design", "nat": "burkinabe", "con_3": "design", "output": "تصميم بوركينابي"},
    {"cate": "burmese sport", "nat": "burmese", "con_3": "sport", "output": "رياضة بورمية"},
    {"cate": "cambodian sport", "nat": "cambodian", "con_3": "sport", "output": "رياضة كمبودية"},
    {"cate": "cameroonian football", "nat": "cameroonian", "con_3": "football", "output": "كرة القدم الكاميرونية"},
    {"cate": "canadian contemporary r&b musical groups", "nat": "canadian", "con_3": "contemporary r&b musical groups", "output": "فرق موسيقى آر أند بي معاصر كندية"},
    {"cate": "canadian football", "nat": "canadian", "con_3": "football", "output": "كرة القدم الكندية"},
    {"cate": "canadian journalism", "nat": "canadian", "con_3": "journalism", "output": "صحافة كندية"},
    {"cate": "canadian magazines", "nat": "canadian", "con_3": "magazines", "output": "مجلات كندية"},
    {"cate": "canadian military", "nat": "canadian", "con_3": "military", "output": "الجيش الكندي"},
    {"cate": "canadian sports", "nat": "canadian", "con_3": "sports", "output": "رياضة كندية"},
    {"cate": "cape verdean awards", "nat": "cape verdean", "con_3": "awards", "output": "جوائز رأس أخضرية"},
    {"cate": "central american cinema", "nat": "central american", "con_3": "cinema", "output": "السينما الأمريكية الأوسطية"},
    {"cate": "chilean football", "nat": "chilean", "con_3": "football", "output": "كرة القدم التشيلية"},
    {"cate": "chilean navy", "nat": "chilean", "con_3": "navy", "output": "البحرية التشيلية"},
    {"cate": "chilean sport", "nat": "chilean", "con_3": "sport", "output": "رياضة تشيلية"},
    {"cate": "chilean tennis", "nat": "chilean", "con_3": "tennis", "output": "كرة مضرب تشيلية"},
    {"cate": "chinese australian culture", "nat": "chinese", "con_3": "australian culture", "output": "ثقافة أسترالية صينية"},
    {"cate": "chinese businesspeople", "nat": "chinese", "con_3": "businesspeople", "output": "شخصيات أعمال صينية"},
    {"cate": "chinese cookbooks", "nat": "chinese", "con_3": "cookbooks", "output": "كتب طبخ صينية"},
    {"cate": "chinese motorsport", "nat": "chinese", "con_3": "motorsport", "output": "رياضة محركات صينية"},
    {"cate": "chinese sport", "nat": "chinese", "con_3": "sport", "output": "رياضة صينية"},
    {"cate": "christian radio stations", "nat": "christian", "con_3": "radio stations", "output": "محطات إذاعية مسيحية"},
    {"cate": "comorian football", "nat": "comorian", "con_3": "football", "output": "كرة القدم القمرية"},
    {"cate": "congolese movement", "nat": "congolese", "con_3": "movement", "output": "الحركة الكونغوية"},
    {"cate": "corsican descent", "nat": "corsican", "con_3": "descent", "output": "أصل كورسيكي"},
    {"cate": "croatian television people", "nat": "croatian", "con_3": "television people", "output": "شخصيات التلفزة الكرواتية"},
    {"cate": "croatian war crimes", "nat": "croatian", "con_3": "war crimes", "output": "جرائم حرب كرواتية"},
    {"cate": "cypriot descent", "nat": "cypriot", "con_3": "descent", "output": "أصل قبرصي"},
    {"cate": "cypriot football", "nat": "cypriot", "con_3": "football", "output": "كرة القدم القبرصية"},
    {"cate": "czech air force", "nat": "czech", "con_3": "air force", "output": "القوات الجوية التشيكية"},
    {"cate": "czech politics", "nat": "czech", "con_3": "politics", "output": "السياسة التشيكية"},
    {"cate": "czech rock music groups", "nat": "czech", "con_3": "rock music groups", "output": "فرق موسيقى الروك تشيكية"},
    {"cate": "czechoslovak television", "nat": "czechoslovak", "con_3": "television", "output": "التلفزة التشيكوسلوفاكية"},
    {"cate": "danish american culture", "nat": "danish", "con_3": "american culture", "output": "ثقافة أمريكية دنماركية"},
    {"cate": "danish football", "nat": "danish", "con_3": "football", "output": "كرة القدم الدنماركية"},
    {"cate": "danish islands", "nat": "danish", "con_3": "islands", "output": "جزر دنماركية"},
    {"cate": "danish sport", "nat": "danish", "con_3": "sport", "output": "رياضة دنماركية"},
    {"cate": "danish television", "nat": "danish", "con_3": "television", "output": "التلفزة الدنماركية"},
    {"cate": "dominican culture", "nat": "dominican", "con_3": "culture", "output": "ثقافة دومينيكية"},
    {"cate": "dutch diaspora", "nat": "dutch", "con_3": "diaspora", "output": "شتات هولندي"},
    {"cate": "dutch jewish culture", "nat": "dutch", "con_3": "jewish culture", "output": "ثقافة يهودية هولندية"},
    {"cate": "dutch jews", "nat": "dutch", "con_3": "jews", "output": "يهود هولنديون"},
    {"cate": "dutch novels", "nat": "dutch", "con_3": "novels", "output": "روايات هولندية"},
    {"cate": "ecuadorian descent", "nat": "ecuadorian", "con_3": "descent", "output": "أصل إكوادوري"},
    {"cate": "egyptian league", "nat": "egyptian", "con_3": "league", "output": "الدوري المصري"},
    {"cate": "emirati motorsport", "nat": "emirati", "con_3": "motorsport", "output": "رياضة محركات إماراتية"},
    {"cate": "english folk", "nat": "english", "con_3": "folk", "output": "فولك إنجليزي"},
    {"cate": "english football league", "nat": "english", "con_3": "football league", "output": "الدوري الإنجليزي لكرة القدم"},
    {"cate": "english gothic architecture", "nat": "english", "con_3": "gothic architecture", "output": "عمارة قوطية إنجليزية"},
    {"cate": "english rugby league", "nat": "english", "con_3": "rugby league", "output": "الدوري الإنجليزي للرجبي"},
    {"cate": "english women's sport", "nat": "english", "con_3": "women's sport", "output": "رياضة إنجليزية نسائية"},
    {"cate": "equatoguinean sport", "nat": "equatoguinean", "con_3": "sport", "output": "رياضة غينية استوائية"},
    {"cate": "estonian sport", "nat": "estonian", "con_3": "sport", "output": "رياضة إستونية"},
    {"cate": "ethiopian sport", "nat": "ethiopian", "con_3": "sport", "output": "رياضة إثيوبية"},
    {"cate": "european american", "nat": "european", "con_3": "american", "output": "أمريكيون أوروبيون"},
    {"cate": "european border", "nat": "european", "con_3": "border", "output": "حدود أوروبية"},
    {"cate": "european games silver medalists", "nat": "european", "con_3": "games silver medalists", "output": "فائزون بميداليات فضية في الألعاب الأوروبية"},
    {"cate": "european jewish descent", "nat": "european", "con_3": "jewish descent", "output": "أصل يهودي أوروبي"},
    {"cate": "european music", "nat": "european", "con_3": "music", "output": "موسيقى أوروبية"},
    {"cate": "european political websites", "nat": "european", "con_3": "political websites", "output": "مواقع ويب سياسية أوروبية"},
    {"cate": "fijian football", "nat": "fijian", "con_3": "football", "output": "كرة القدم الفيجية"},
    {"cate": "filipino descent", "nat": "filipino", "con_3": "descent", "output": "أصل فلبيني"},
    {"cate": "finnish awards and decorations", "nat": "finnish", "con_3": "awards and decorations", "output": "جوائز وأوسمة فنلندية"},
    {"cate": "finnish navy", "nat": "finnish", "con_3": "navy", "output": "البحرية الفنلندية"},
    {"cate": "finnish novels", "nat": "finnish", "con_3": "novels", "output": "روايات فنلندية"},
    {"cate": "finnish sport", "nat": "finnish", "con_3": "sport", "output": "رياضة فنلندية"},
    {"cate": "finnish television series", "nat": "finnish", "con_3": "television series", "output": "مسلسلات تلفزيونية فنلندية"},
    {"cate": "french cinema", "nat": "french", "con_3": "cinema", "output": "السينما الفرنسية"},
    {"cate": "french descent", "nat": "french", "con_3": "descent", "output": "أصل فرنسي"},
    {"cate": "french legal films", "nat": "french", "con_3": "legal films", "output": "أفلام قانونية فرنسية"},
    {"cate": "french motorsport", "nat": "french", "con_3": "motorsport", "output": "رياضة محركات فرنسية"},
    {"cate": "french mythology", "nat": "french", "con_3": "mythology", "output": "أساطير فرنسية"},
    {"cate": "french navy", "nat": "french", "con_3": "navy", "output": "البحرية الفرنسية"},
    {"cate": "french rugby league", "nat": "french", "con_3": "rugby league", "output": "الدوري الفرنسي للرجبي"},
    {"cate": "french rugby union", "nat": "french", "con_3": "rugby union", "output": "اتحاد الرجبي الفرنسي"},
    {"cate": "french sport", "nat": "french", "con_3": "sport", "output": "رياضة فرنسية"},
    {"cate": "french war crimes", "nat": "french", "con_3": "war crimes", "output": "جرائم حرب فرنسية"},
    {"cate": "german hip hop", "nat": "german", "con_3": "hip hop", "output": "هيب هوب ألماني"},
    {"cate": "german motorsport", "nat": "german", "con_3": "motorsport", "output": "رياضة محركات ألمانية"},
    {"cate": "german music", "nat": "german", "con_3": "music", "output": "موسيقى ألمانية"},
    {"cate": "german romanian descent", "nat": "german", "con_3": "romanian descent", "output": "أصل روماني ألماني"},
    {"cate": "german women's sport", "nat": "german", "con_3": "women's sport", "output": "رياضة ألمانية نسائية"},
    {"cate": "gothic architecture", "nat": "gothic", "con_3": "architecture", "output": "عمارة قوطية"},
    {"cate": "greek companies", "nat": "greek", "con_3": "companies", "output": "شركات يونانية"},
    {"cate": "greek descent", "nat": "greek", "con_3": "descent", "output": "أصل يوناني"},
    {"cate": "greek hip hop groups", "nat": "greek", "con_3": "hip hop groups", "output": "فرق هيب هوب يونانية"},
    {"cate": "greek novels", "nat": "greek", "con_3": "novels", "output": "روايات يونانية"},
    {"cate": "greek organized crime", "nat": "greek", "con_3": "organized crime", "output": "جريمة منظمة يونانية"},
    {"cate": "greek poems", "nat": "greek", "con_3": "poems", "output": "قصائد يونانية"},
    {"cate": "greek women's sport", "nat": "greek", "con_3": "women's sport", "output": "رياضة يونانية نسائية"},
    {"cate": "greenlandic sport", "nat": "greenlandic", "con_3": "sport", "output": "رياضة جرينلاندية"},
    {"cate": "guamanian football", "nat": "guamanian", "con_3": "football", "output": "كرة القدم الغوامية"},
    {"cate": "guatemalan diaspora", "nat": "guatemalan", "con_3": "diaspora", "output": "شتات غواتيمالي"},
    {"cate": "guatemalan musical instruments", "nat": "guatemalan", "con_3": "musical instruments", "output": "آلات موسيقية غواتيمالية"},
    {"cate": "gujarati films", "nat": "gujarati", "con_3": "films", "output": "أفلام غجراتية"},
    {"cate": "hong kong descent", "nat": "hong kong", "con_3": "descent", "output": "أصل هونغ كونغي"},
    {"cate": "hong kong fa cup", "nat": "hong kong", "con_3": "fa cup", "output": "كأس الاتحاد الهونغ الكونغي"},
    {"cate": "hong kong sport", "nat": "hong kong", "con_3": "sport", "output": "رياضة هونغ كونغية"},
    {"cate": "hungarian sport", "nat": "hungarian", "con_3": "sport", "output": "رياضة مجرية"},
    {"cate": "hungarian women's sport", "nat": "hungarian", "con_3": "women's sport", "output": "رياضة مجرية نسائية"},
    {"cate": "icelandic descent", "nat": "icelandic", "con_3": "descent", "output": "أصل آيسلندي"},
    {"cate": "indian descent", "nat": "indian", "con_3": "descent", "output": "أصل هندي"},
    {"cate": "indian federation cup", "nat": "indian", "con_3": "federation cup", "output": "كأس الاتحاد الهندي"},
    {"cate": "indian funk musical groups", "nat": "indian", "con_3": "funk musical groups", "output": "فرق موسيقى فانك هندية"},
    {"cate": "indian literature", "nat": "indian", "con_3": "literature", "output": "أدب هندي"},
    {"cate": "indian muslims", "nat": "indian", "con_3": "muslims", "output": "مسلمون هنود"},
    {"cate": "indian politics", "nat": "indian", "con_3": "politics", "output": "السياسة الهندية"},
    {"cate": "indonesian rock music groups", "nat": "indonesian", "con_3": "rock music groups", "output": "فرق موسيقى الروك إندونيسية"},
    {"cate": "indonesian websites", "nat": "indonesian", "con_3": "websites", "output": "مواقع ويب إندونيسية"},
    {"cate": "iranian jews", "nat": "iranian", "con_3": "jews", "output": "يهود إيرانيون"},
    {"cate": "iranian television series", "nat": "iranian", "con_3": "television series", "output": "مسلسلات تلفزيونية إيرانية"},
    {"cate": "iraqi descent", "nat": "iraqi", "con_3": "descent", "output": "أصل عراقي"},
    {"cate": "irish american gangs", "nat": "irish", "con_3": "american gangs", "output": "عصابات أمريكية أيرلندية"},
    {"cate": "irish films", "nat": "irish", "con_3": "films", "output": "أفلام أيرلندية"},
    {"cate": "irish folklore", "nat": "irish", "con_3": "folklore", "output": "فلكور أيرلندي"},
    {"cate": "irish general election", "nat": "irish", "con_3": "general election", "output": "الانتخابات العامة الأيرلندية"},
    {"cate": "israeli brands", "nat": "israeli", "con_3": "brands", "output": "ماركات إسرائيلية"},
    {"cate": "israeli sport", "nat": "israeli", "con_3": "sport", "output": "رياضة إسرائيلية"},
    {"cate": "israeli women's sport", "nat": "israeli", "con_3": "women's sport", "output": "رياضة إسرائيلية نسائية"},
    {"cate": "italian canadian culture", "nat": "italian", "con_3": "canadian culture", "output": "ثقافة كندية إيطالية"},
    {"cate": "italian rugby union", "nat": "italian", "con_3": "rugby union", "output": "اتحاد الرجبي الإيطالي"},
    {"cate": "italian tennis", "nat": "italian", "con_3": "tennis", "output": "كرة مضرب إيطالية"},
    {"cate": "jamaican brands", "nat": "jamaican", "con_3": "brands", "output": "ماركات جامايكية"},
    {"cate": "japanese americans", "nat": "japanese", "con_3": "americans", "output": "أمريكيون يابانيون"},
    {"cate": "japanese army", "nat": "japanese", "con_3": "army", "output": "الجيش الياباني"},
    {"cate": "japanese companies", "nat": "japanese", "con_3": "companies", "output": "شركات يابانية"},
    {"cate": "japanese descent", "nat": "japanese", "con_3": "descent", "output": "أصل ياباني"},
    {"cate": "japanese indie pop groups", "nat": "japanese", "con_3": "indie pop groups", "output": "فرق إيندي بوب يابانية"},
    {"cate": "japanese music", "nat": "japanese", "con_3": "music", "output": "موسيقى يابانية"},
    {"cate": "japanese politics", "nat": "japanese", "con_3": "politics", "output": "السياسة اليابانية"},
    {"cate": "japanese sport", "nat": "japanese", "con_3": "sport", "output": "رياضة يابانية"},
    {"cate": "jewish american people", "nat": "jewish", "con_3": "american people", "output": "أمريكيون يهود"},
    {"cate": "jewish american television series", "nat": "jewish", "con_3": "american television series", "output": "مسلسلات تلفزيونية أمريكية يهودية"},
    {"cate": "jewish american tennis", "nat": "jewish", "con_3": "american tennis", "output": "كرة مضرب أمريكية يهودية"},
    {"cate": "jewish manuscripts", "nat": "jewish", "con_3": "manuscripts", "output": "مخطوطات يهودية"},
    {"cate": "jordanian football", "nat": "jordanian", "con_3": "football", "output": "كرة القدم الأردنية"},
    {"cate": "kazakh brands", "nat": "kazakh", "con_3": "brands", "output": "ماركات كازاخية"},
    {"cate": "kazakhstani descent", "nat": "kazakhstani", "con_3": "descent", "output": "أصل كازاخستاني"},
    {"cate": "kenyan novels", "nat": "kenyan", "con_3": "novels", "output": "روايات كينية"},
    {"cate": "kenyan television series", "nat": "kenyan", "con_3": "television series", "output": "مسلسلات تلفزيونية كينية"},
    {"cate": "korean american culture", "nat": "korean", "con_3": "american culture", "output": "ثقافة أمريكية كورية"},
    {"cate": "korean businesspeople", "nat": "korean", "con_3": "businesspeople", "output": "شخصيات أعمال كورية"},
    {"cate": "korean international schools", "nat": "korean", "con_3": "international schools", "output": "مدارس دولية كورية"},
    {"cate": "kurdish folklore", "nat": "kurdish", "con_3": "folklore", "output": "فلكور كردي"},
    {"cate": "kyrgyzstani football", "nat": "kyrgyzstani", "con_3": "football", "output": "كرة القدم القيرغيزستانية"},
    {"cate": "lebanese federation cup", "nat": "lebanese", "con_3": "federation cup", "output": "كأس الاتحاد اللبناني"},
    {"cate": "lithuanian art", "nat": "lithuanian", "con_3": "art", "output": "فن ليتواني"},
    {"cate": "luxembourgian sport", "nat": "luxembourgian", "con_3": "sport", "output": "رياضة لوكسمبورغية"},
    {"cate": "luxembourgish inventions", "nat": "luxembourgish", "con_3": "inventions", "output": "اختراعات لوكسمبورغية"},
    {"cate": "malagasy world music groups", "nat": "malagasy", "con_3": "world music groups", "output": "فرق موسيقى العالم مدغشقرية"},
    {"cate": "malaysian football", "nat": "malaysian", "con_3": "football", "output": "كرة القدم الماليزية"},
    {"cate": "malaysian sport", "nat": "malaysian", "con_3": "sport", "output": "رياضة ماليزية"},
    {"cate": "maldivian descent", "nat": "maldivian", "con_3": "descent", "output": "أصل مالديفي"},
    {"cate": "mexican businesspeople", "nat": "mexican", "con_3": "businesspeople", "output": "شخصيات أعمال مكسيكية"},
    {"cate": "mexican motorsport", "nat": "mexican", "con_3": "motorsport", "output": "رياضة محركات مكسيكية"},
    {"cate": "mexican novels", "nat": "mexican", "con_3": "novels", "output": "روايات مكسيكية"},
    {"cate": "mexican politics", "nat": "mexican", "con_3": "politics", "output": "السياسة المكسيكية"},
    {"cate": "mexican sports", "nat": "mexican", "con_3": "sports", "output": "رياضة مكسيكية"},
    {"cate": "mexican television series", "nat": "mexican", "con_3": "television series", "output": "مسلسلات تلفزيونية مكسيكية"},
    {"cate": "montserratian descent", "nat": "montserratian", "con_3": "descent", "output": "أصل مونتسراتي"},
    {"cate": "monégasque sport", "nat": "monégasque", "con_3": "sport", "output": "رياضة موناكية"},
    {"cate": "moroccan army", "nat": "moroccan", "con_3": "army", "output": "الجيش المغربي"},
    {"cate": "native american films", "nat": "native american", "con_3": "films", "output": "أفلام أمريكية أصلية"},
    {"cate": "nicaraguan football", "nat": "nicaraguan", "con_3": "football", "output": "كرة القدم النيكاراغوية"},
    {"cate": "nigerian sport", "nat": "nigerian", "con_3": "sport", "output": "رياضة نيجيرية"},
    {"cate": "north american hockey league", "nat": "north american", "con_3": "hockey league", "output": "الدوري الأمريكي الشمالي للهوكي"},
    {"cate": "north american soccer league", "nat": "north american", "con_3": "soccer league", "output": "الدوري الأمريكي الشمالي لكرة القدم"},
    {"cate": "north american sport", "nat": "north american", "con_3": "sport", "output": "رياضة أمريكية شمالية"},
    {"cate": "norwegian military academy", "nat": "norwegian", "con_3": "military academy", "output": "الأكاديمية العسكرية النرويجية"},
    {"cate": "norwegian music", "nat": "norwegian", "con_3": "music", "output": "موسيقى نرويجية"},
    {"cate": "oceanian rugby union", "nat": "oceanian", "con_3": "rugby union", "output": "اتحاد الرجبي الأوقيانوسي"},
    {"cate": "ossetian diaspora", "nat": "ossetian", "con_3": "diaspora", "output": "شتات أوسيتي"},
    {"cate": "pakistani descent", "nat": "pakistani", "con_3": "descent", "output": "أصل باكستاني"},
    {"cate": "pakistani law", "nat": "pakistani", "con_3": "law", "output": "قانون باكستاني"},
    {"cate": "pakistani politics", "nat": "pakistani", "con_3": "politics", "output": "السياسة الباكستانية"},
    {"cate": "pakistani sport", "nat": "pakistani", "con_3": "sport", "output": "رياضة باكستانية"},
    {"cate": "pakistani television", "nat": "pakistani", "con_3": "television", "output": "التلفزة الباكستانية"},
    {"cate": "palestinian organizations", "nat": "palestinian", "con_3": "organizations", "output": "منظمات فلسطينية"},
    {"cate": "paraguayan films", "nat": "paraguayan", "con_3": "films", "output": "أفلام بارغوايانية"},
    {"cate": "peruvian sport", "nat": "peruvian", "con_3": "sport", "output": "رياضة بيروية"},
    {"cate": "peruvian television series", "nat": "peruvian", "con_3": "television series", "output": "مسلسلات تلفزيونية بيروية"},
    {"cate": "peruvian television", "nat": "peruvian", "con_3": "television", "output": "التلفزة البيروية"},
    {"cate": "philippine revolution", "nat": "philippine", "con_3": "revolution", "output": "الثورة الفلبينية"},
    {"cate": "polish biographical dictionaries", "nat": "polish", "con_3": "biographical dictionaries", "output": "قواميس سير ذاتية بولندية"},
    {"cate": "polish companies", "nat": "polish", "con_3": "companies", "output": "شركات بولندية"},
    {"cate": "polish football", "nat": "polish", "con_3": "football", "output": "كرة القدم البولندية"},
    {"cate": "polish jews", "nat": "polish", "con_3": "jews", "output": "يهود بولنديون"},
    {"cate": "polish music", "nat": "polish", "con_3": "music", "output": "موسيقى بولندية"},
    {"cate": "polish sport", "nat": "polish", "con_3": "sport", "output": "رياضة بولندية"},
    {"cate": "polish television", "nat": "polish", "con_3": "television", "output": "التلفزة البولندية"},
    {"cate": "portuguese companies", "nat": "portuguese", "con_3": "companies", "output": "شركات برتغالية"},
    {"cate": "portuguese motorsport", "nat": "portuguese", "con_3": "motorsport", "output": "رياضة محركات برتغالية"},
    {"cate": "portuguese sport", "nat": "portuguese", "con_3": "sport", "output": "رياضة برتغالية"},
    {"cate": "puerto rican brands", "nat": "puerto rican", "con_3": "brands", "output": "ماركات بورتوريكية"},
    {"cate": "qatari musical instruments", "nat": "qatari", "con_3": "musical instruments", "output": "آلات موسيقية قطرية"},
    {"cate": "romanian tennis", "nat": "romanian", "con_3": "tennis", "output": "كرة مضرب رومانية"},
    {"cate": "russian journalism", "nat": "russian", "con_3": "journalism", "output": "صحافة روسية"},
    {"cate": "russian literature", "nat": "russian", "con_3": "literature", "output": "أدب روسي"},
    {"cate": "russian revolution", "nat": "russian", "con_3": "revolution", "output": "الثورة الروسية"},
    {"cate": "russian rugby union", "nat": "russian", "con_3": "rugby union", "output": "اتحاد الرجبي الروسي"},
    {"cate": "russian songs", "nat": "russian", "con_3": "songs", "output": "أغاني روسية"},
    {"cate": "samoan islands", "nat": "samoan", "con_3": "islands", "output": "جزر ساموية"},
    {"cate": "saudiarabian black metal musical groups", "nat": "saudiarabian", "con_3": "black metal musical groups", "output": "فرق موسيقى بلاك ميتال سعودية"},
    {"cate": "saudiarabian motorsport", "nat": "saudiarabian", "con_3": "motorsport", "output": "رياضة محركات سعودية"},
    {"cate": "scottish businesspeople", "nat": "scottish", "con_3": "businesspeople", "output": "شخصيات أعمال إسكتلندية"},
    {"cate": "scottish television", "nat": "scottish", "con_3": "television", "output": "التلفزة الإسكتلندية"},
    {"cate": "sierra leonean sport", "nat": "sierra leonean", "con_3": "sport", "output": "رياضة سيراليونية"},
    {"cate": "singaporean art", "nat": "singaporean", "con_3": "art", "output": "فن سنغافوري"},
    {"cate": "singaporean descent", "nat": "singaporean", "con_3": "descent", "output": "أصل سنغافوري"},
    {"cate": "singaporean media personalities", "nat": "singaporean", "con_3": "media personalities", "output": "شخصيات إعلامية سنغافورية"},
    {"cate": "singaporean plays", "nat": "singaporean", "con_3": "plays", "output": "مسرحيات سنغافورية"},
    {"cate": "slovak music", "nat": "slovak", "con_3": "music", "output": "موسيقى سلوفاكية"},
    {"cate": "slovak romani", "nat": "slovak", "con_3": "romani", "output": "غجرية سلوفاكي"},
    {"cate": "slovenian novels", "nat": "slovenian", "con_3": "novels", "output": "روايات سلوفينية"},
    {"cate": "slovenian rock music groups", "nat": "slovenian", "con_3": "rock music groups", "output": "فرق موسيقى الروك سلوفينية"},
    {"cate": "south african sport", "nat": "south african", "con_3": "sport", "output": "رياضة جنوبية إفريقية"},
    {"cate": "south american descent", "nat": "south american", "con_3": "descent", "output": "أصل أمريكي جنوبي"},
    {"cate": "south american rugby union", "nat": "south american", "con_3": "rugby union", "output": "اتحاد الرجبي الأمريكي الجنوبي"},
    {"cate": "south american sport", "nat": "south american", "con_3": "sport", "output": "رياضة أمريكية جنوبية"},
    {"cate": "south korean sport", "nat": "south korean", "con_3": "sport", "output": "رياضة كورية جنوبية"},
    {"cate": "soviet football", "nat": "soviet", "con_3": "football", "output": "كرة القدم السوفيتية"},
    {"cate": "soviet musical groups", "nat": "soviet", "con_3": "musical groups", "output": "مجموعات موسيقية سوفيتية"},
    {"cate": "soviet muslims", "nat": "soviet", "con_3": "muslims", "output": "مسلمون سوفيت"},
    {"cate": "soviet navy", "nat": "soviet", "con_3": "navy", "output": "البحرية السوفيتية"},
    {"cate": "spanish companies", "nat": "spanish", "con_3": "companies", "output": "شركات إسبانية"},
    {"cate": "spanish diaspora", "nat": "spanish", "con_3": "diaspora", "output": "شتات إسباني"},
    {"cate": "spanish tennis", "nat": "spanish", "con_3": "tennis", "output": "كرة مضرب إسبانية"},
    {"cate": "sri lankan novels", "nat": "sri lankan", "con_3": "novels", "output": "روايات سريلانكية"},
    {"cate": "sri lankan television", "nat": "sri lankan", "con_3": "television", "output": "التلفزة السريلانكية"},
    {"cate": "sudanese jews", "nat": "sudanese", "con_3": "jews", "output": "يهود سودانيون"},
    {"cate": "swedish inventions", "nat": "swedish", "con_3": "inventions", "output": "اختراعات سويدية"},
    {"cate": "swedish novels", "nat": "swedish", "con_3": "novels", "output": "روايات سويدية"},
    {"cate": "swedish plays", "nat": "swedish", "con_3": "plays", "output": "مسرحيات سويدية"},
    {"cate": "swedish ska groups", "nat": "swedish", "con_3": "ska groups", "output": "فرق سكا سويدية"},
    {"cate": "swedish war", "nat": "swedish", "con_3": "war", "output": "الحرب السويدية"},
    {"cate": "swiss books", "nat": "swiss", "con_3": "books", "output": "كتب سويسرية"},
    {"cate": "swiss detention", "nat": "swiss", "con_3": "detention", "output": "المعتقلات السويسرية"},
    {"cate": "swiss grand prix", "nat": "swiss", "con_3": "grand prix", "output": "جائزة سويسرا الكبرى"},
    {"cate": "swiss websites", "nat": "swiss", "con_3": "websites", "output": "مواقع ويب سويسرية"},
    {"cate": "syrian navy", "nat": "syrian", "con_3": "navy", "output": "البحرية السورية"},
    {"cate": "syrian rock music groups", "nat": "syrian", "con_3": "rock music groups", "output": "فرق موسيقى الروك سورية"},
    {"cate": "syrian sport", "nat": "syrian", "con_3": "sport", "output": "رياضة سورية"},
    {"cate": "taiwanese hip hop", "nat": "taiwanese", "con_3": "hip hop", "output": "هيب هوب تايواني"},
    {"cate": "taiwanese muslims", "nat": "taiwanese", "con_3": "muslims", "output": "مسلمون تايوانيون"},
    {"cate": "tajikistani rock music groups", "nat": "tajikistani", "con_3": "rock music groups", "output": "فرق موسيقى الروك طاجيكستانية"},
    {"cate": "tamil diaspora", "nat": "tamil", "con_3": "diaspora", "output": "شتات تاميلي"},
    {"cate": "tanzanian brands", "nat": "tanzanian", "con_3": "brands", "output": "ماركات تنزانية"},
    {"cate": "tanzanian sport", "nat": "tanzanian", "con_3": "sport", "output": "رياضة تنزانية"},
    {"cate": "thai diaspora", "nat": "thai", "con_3": "diaspora", "output": "شتات تايلندي"},
    {"cate": "thai families", "nat": "thai", "con_3": "families", "output": "عائلات تايلندية"},
    {"cate": "thai films", "nat": "thai", "con_3": "films", "output": "أفلام تايلندية"},
    {"cate": "turkish awards", "nat": "turkish", "con_3": "awards", "output": "جوائز تركية"},
    {"cate": "turkish kurdish people", "nat": "turkish", "con_3": "kurdish people", "output": "أكراد أتراك"},
    {"cate": "tuvaluan football", "nat": "tuvaluan", "con_3": "football", "output": "كرة القدم التوفالية"},
    {"cate": "ugandan television", "nat": "ugandan", "con_3": "television", "output": "التلفزة الأوغندية"},
    {"cate": "ukrainian diaspora", "nat": "ukrainian", "con_3": "diaspora", "output": "شتات أوكراني"},
    {"cate": "ukrainian films", "nat": "ukrainian", "con_3": "films", "output": "أفلام أوكرانية"},
    {"cate": "ukrainian sport", "nat": "ukrainian", "con_3": "sport", "output": "رياضة أوكرانية"},
    {"cate": "ukrainian television", "nat": "ukrainian", "con_3": "television", "output": "التلفزة الأوكرانية"},
    {"cate": "ukrainian works", "nat": "ukrainian", "con_3": "works", "output": "أعمال أوكرانية"},
    {"cate": "uruguayan tennis", "nat": "uruguayan", "con_3": "tennis", "output": "كرة مضرب أوروغويانية"},
    {"cate": "uruguayan war", "nat": "uruguayan", "con_3": "war", "output": "الحرب الأوروغويانية"},
    {"cate": "uzbekistani films", "nat": "uzbekistani", "con_3": "films", "output": "أفلام أوزبكستانية"},
    {"cate": "venezuelan spanish", "nat": "venezuelan", "con_3": "spanish", "output": "إسبان فنزويليون"},
    {"cate": "venezuelan sport", "nat": "venezuelan", "con_3": "sport", "output": "رياضة فنزويلية"},
    {"cate": "venezuelan television", "nat": "venezuelan", "con_3": "television", "output": "التلفزة الفنزويلية"},
    {"cate": "vietnamese companies", "nat": "vietnamese", "con_3": "companies", "output": "شركات فيتنامية"},
    {"cate": "vietnamese women's sport", "nat": "vietnamese", "con_3": "women's sport", "output": "رياضة فيتنامية نسائية"},
    {"cate": "welsh descent", "nat": "welsh", "con_3": "descent", "output": "أصل ويلزي"},
    {"cate": "welsh rugby league", "nat": "welsh", "con_3": "rugby league", "output": "الدوري الويلزي للرجبي"},
    {"cate": "welsh sport", "nat": "welsh", "con_3": "sport", "output": "رياضة ويلزية"},
    {"cate": "yemeni descent", "nat": "yemeni", "con_3": "descent", "output": "أصل يمني"},
    {"cate": "yemeni sport", "nat": "yemeni", "con_3": "sport", "output": "رياضة يمنية"},
    {"cate": "yoruba descent", "nat": "yoruba", "con_3": "descent", "output": "أصل يوروبي"},
    {"cate": "yugoslav descent", "nat": "yugoslav", "con_3": "descent", "output": "أصل يوغوسلافي"},
    {"cate": "yugoslav sport", "nat": "yugoslav", "con_3": "sport", "output": "رياضة يوغوسلافية"},
    {"cate": "zimbabwean companies", "nat": "zimbabwean", "con_3": "companies", "output": "شركات زيمبابوية"},
    {"cate": "zimbabwean descent", "nat": "zimbabwean", "con_3": "descent", "output": "أصل زيمبابوي"},
    {"cate": "zimbabwean general election", "nat": "zimbabwean", "con_3": "general election", "output": "الانتخابات العامة الزيمبابوية"},
]


@pytest.mark.parametrize("data", fast_data, ids=lambda x: x["cate"])
@pytest.mark.fast
def test_fast_data(data) -> None:
    label = Work_for_me(data["cate"], data["nat"], data["con_3"])
    assert label == data["output"]


with_all_data = [
    {"cate": "african rugby union", "nat": "african", "con_3": "rugby union", "output": "اتحاد الرجبي الإفريقي"},
    {"cate": "american basketball league", "nat": "american", "con_3": "basketball league", "output": "الدوري الأمريكي لكرة السلة"},
    {"cate": "american football league", "nat": "american", "con_3": "football league", "output": "الدوري الأمريكي لكرة القدم"},
    {"cate": "american indoor soccer league", "nat": "american", "con_3": "indoor soccer league", "output": "الدوري الأمريكي لكرة القدم داخل الصالات"},
    {"cate": "american rugby league players", "nat": "american", "con_3": "rugby league players", "output": "لاعبو الدوري الأمريكي للرجبي"},
    {"cate": "american rugby union", "nat": "american", "con_3": "rugby union", "output": "اتحاد الرجبي الأمريكي"},
    {"cate": "arab league", "nat": "arab", "con_3": "league", "output": "الدوري العربي"},
    {"cate": "argentine army", "nat": "argentine", "con_3": "army", "output": "الجيش الأرجنتيني"},
    {"cate": "argentine military", "nat": "argentine", "con_3": "military", "output": "الجيش الأرجنتيني"},
    {"cate": "argentine rugby union", "nat": "argentine", "con_3": "rugby union", "output": "اتحاد الرجبي الأرجنتيني"},
    {"cate": "asian rugby union", "nat": "asian", "con_3": "rugby union", "output": "اتحاد الرجبي الآسيوي"},
    {"cate": "australian hockey league", "nat": "australian", "con_3": "hockey league", "output": "الدوري الأسترالي للهوكي"},
    {"cate": "australian involvement", "nat": "australian", "con_3": "involvement", "output": "التدخل الأسترالي"},
    {"cate": "australian rugby league players", "nat": "australian", "con_3": "rugby league players", "output": "لاعبو الدوري الأسترالي للرجبي"},
    {"cate": "australian rugby league", "nat": "australian", "con_3": "rugby league", "output": "الدوري الأسترالي للرجبي"},
    {"cate": "australian rugby union", "nat": "australian", "con_3": "rugby union", "output": "اتحاد الرجبي الأسترالي"},
    {"cate": "australian women's ice hockey league", "nat": "australian", "con_3": "women's ice hockey league", "output": "الدوري الأسترالي لهوكي الجليد للسيدات"},
    {"cate": "belgian hockey league", "nat": "belgian", "con_3": "hockey league", "output": "الدوري البلجيكي للهوكي"},
    {"cate": "belgian rugby union", "nat": "belgian", "con_3": "rugby union", "output": "اتحاد الرجبي البلجيكي"},
    {"cate": "beninese presidential pardons", "nat": "beninese", "con_3": "presidential pardons", "output": "العفو الرئاسي البنيني"},
    {"cate": "bohemian football league", "nat": "bohemian", "con_3": "football league", "output": "الدوري البوهيمي لكرة القدم"},
    {"cate": "bosnia and herzegovina hockey league", "nat": "bosnia and herzegovina", "con_3": "hockey league", "output": "الدوري البوسني للهوكي"},
    {"cate": "brazilian rugby league players", "nat": "brazilian", "con_3": "rugby league players", "output": "لاعبو الدوري البرازيلي للرجبي"},
    {"cate": "british army", "nat": "british", "con_3": "army", "output": "الجيش البريطاني"},
    {"cate": "british hockey league", "nat": "british", "con_3": "hockey league", "output": "الدوري البريطاني للهوكي"},
    {"cate": "british national party", "nat": "british", "con_3": "national party", "output": "الحزب الوطني البريطاني"},
    {"cate": "british rugby union", "nat": "british", "con_3": "rugby union", "output": "اتحاد الرجبي البريطاني"},
    {"cate": "canadian army", "nat": "canadian", "con_3": "army", "output": "الجيش الكندي"},
    {"cate": "canadian football league", "nat": "canadian", "con_3": "football league", "output": "الدوري الكندي لكرة القدم"},
    {"cate": "canadian military", "nat": "canadian", "con_3": "military", "output": "الجيش الكندي"},
    {"cate": "canadian premier league", "nat": "canadian", "con_3": "premier league", "output": "الدوري الكندي الممتاز"},
    {"cate": "canadian rugby union", "nat": "canadian", "con_3": "rugby union", "output": "اتحاد الرجبي الكندي"},
    {"cate": "canadian women's hockey league", "nat": "canadian", "con_3": "women's hockey league", "output": "الدوري الكندي للهوكي للسيدات"},
    {"cate": "celtic league", "nat": "celtic", "con_3": "league", "output": "الدوري الكلتي"},
    {"cate": "chinese football league", "nat": "chinese", "con_3": "football league", "output": "الدوري الصيني لكرة القدم"},
    {"cate": "chinese professional baseball league", "nat": "chinese", "con_3": "professional baseball league", "output": "دوري كرة القاعدة الصيني للمحترفين"},
    {"cate": "cuban league", "nat": "cuban", "con_3": "league", "output": "الدوري الكوبي"},
    {"cate": "czech military", "nat": "czech", "con_3": "military", "output": "الجيش التشيكي"},
    {"cate": "dominican professional baseball league", "nat": "dominican", "con_3": "professional baseball league", "output": "دوري كرة القاعدة الدومينيكي للمحترفين"},
    {"cate": "egyptian league", "nat": "egyptian", "con_3": "league", "output": "الدوري المصري"},
    {"cate": "egyptian military", "nat": "egyptian", "con_3": "military", "output": "الجيش المصري"},
    {"cate": "english football league", "nat": "english", "con_3": "football league", "output": "الدوري الإنجليزي لكرة القدم"},
    {"cate": "english rugby league players", "nat": "english", "con_3": "rugby league players", "output": "لاعبو الدوري الإنجليزي للرجبي"},
    {"cate": "english rugby league", "nat": "english", "con_3": "rugby league", "output": "الدوري الإنجليزي للرجبي"},
    {"cate": "english rugby union leagues", "nat": "english", "con_3": "rugby union leagues", "output": "اتحاد دوري الرجبي الإنجليزي"},
    {"cate": "english rugby union", "nat": "english", "con_3": "rugby union", "output": "اتحاد الرجبي الإنجليزي"},
    {"cate": "eritrean premier league", "nat": "eritrean", "con_3": "premier league", "output": "الدوري الإريتري الممتاز"},
    {"cate": "european league", "nat": "european", "con_3": "league", "output": "الدوري الأوروبي"},
    {"cate": "european rugby union leagues", "nat": "european", "con_3": "rugby union leagues", "output": "اتحاد دوري الرجبي الأوروبي"},
    {"cate": "european rugby union", "nat": "european", "con_3": "rugby union", "output": "اتحاد الرجبي الأوروبي"},
    {"cate": "european women's hockey league", "nat": "european", "con_3": "women's hockey league", "output": "الدوري الأوروبي للهوكي للسيدات"},
    {"cate": "european women's rugby union", "nat": "european", "con_3": "women's rugby union", "output": "اتحاد الرجبي الأوروبي للنساء"},
    {"cate": "fijian rugby union", "nat": "fijian", "con_3": "rugby union", "output": "اتحاد الرجبي الفيجي"},
    {"cate": "french military", "nat": "french", "con_3": "military", "output": "الجيش الفرنسي"},
    {"cate": "french rugby league", "nat": "french", "con_3": "rugby league", "output": "الدوري الفرنسي للرجبي"},
    {"cate": "french rugby union leagues", "nat": "french", "con_3": "rugby union leagues", "output": "اتحاد دوري الرجبي الفرنسي"},
    {"cate": "french rugby union", "nat": "french", "con_3": "rugby union", "output": "اتحاد الرجبي الفرنسي"},
    {"cate": "german army", "nat": "german", "con_3": "army", "output": "الجيش الألماني"},
    {"cate": "german family law", "nat": "german", "con_3": "family law", "output": "قانون الأسرة الألماني"},
    {"cate": "german football league", "nat": "german", "con_3": "football league", "output": "الدوري الألماني لكرة القدم"},
    {"cate": "german occupation", "nat": "german", "con_3": "occupation", "output": "الاحتلال الألماني"},
    {"cate": "german rugby league players", "nat": "german", "con_3": "rugby league players", "output": "لاعبو الدوري الألماني للرجبي"},
    {"cate": "german rugby union", "nat": "german", "con_3": "rugby union", "output": "اتحاد الرجبي الألماني"},
    {"cate": "hong kong fa cup", "nat": "hong kong", "con_3": "fa cup", "output": "كأس الاتحاد الهونغ الكونغي"},
    {"cate": "hong kong labour law", "nat": "hong kong", "con_3": "labour law", "output": "قانون العمل الهونغ الكونغي"},
    {"cate": "indian army", "nat": "indian", "con_3": "army", "output": "الجيش الهندي"},
    {"cate": "indian federation cup", "nat": "indian", "con_3": "federation cup", "output": "كأس الاتحاد الهندي"},
    {"cate": "indian premier league", "nat": "indian", "con_3": "premier league", "output": "الدوري الهندي الممتاز"},
    {"cate": "iranian futsal super league", "nat": "iranian", "con_3": "futsal super league", "output": "دوري السوبر كرة صالات الإيراني"},
    {"cate": "irish rugby union", "nat": "irish", "con_3": "rugby union", "output": "اتحاد الرجبي الأيرلندي"},
    {"cate": "israeli beach soccer league", "nat": "israeli", "con_3": "beach soccer league", "output": "الدوري الإسرائيلي لكرة القدم الشاطئية"},
    {"cate": "israeli futsal league", "nat": "israeli", "con_3": "futsal league", "output": "الدوري الإسرائيلي لكرة الصالات"},
    {"cate": "italian rugby union", "nat": "italian", "con_3": "rugby union", "output": "اتحاد الرجبي الإيطالي"},
    {"cate": "jamaican rugby league", "nat": "jamaican", "con_3": "rugby league", "output": "الدوري الجامايكي للرجبي"},
    {"cate": "japanese army", "nat": "japanese", "con_3": "army", "output": "الجيش الياباني"},
    {"cate": "japanese criminal law", "nat": "japanese", "con_3": "criminal law", "output": "القانون الجنائي الياباني"},
    {"cate": "japanese occupation", "nat": "japanese", "con_3": "occupation", "output": "الاحتلال الياباني"},
    {"cate": "japanese rugby union", "nat": "japanese", "con_3": "rugby union", "output": "اتحاد الرجبي الياباني"},
    {"cate": "jewish rugby league players", "nat": "jewish", "con_3": "rugby league players", "output": "لاعبو الدوري اليهودي للرجبي"},
    {"cate": "jordanian involvement", "nat": "jordanian", "con_3": "involvement", "output": "التدخل الأردني"},
    {"cate": "kenyan super cup", "nat": "kenyan", "con_3": "super cup", "output": "كأس السوبر الكيني"},
    {"cate": "lebanese federation cup", "nat": "lebanese", "con_3": "federation cup", "output": "كأس الاتحاد اللبناني"},
    {"cate": "lebanese involvement", "nat": "lebanese", "con_3": "involvement", "output": "التدخل اللبناني"},
    {"cate": "lebanese premier league", "nat": "lebanese", "con_3": "premier league", "output": "الدوري اللبناني الممتاز"},
    {"cate": "lithuanian women's handball league", "nat": "lithuanian", "con_3": "women's handball league", "output": "الدوري الليتواني لكرة اليد للسيدات"},
    {"cate": "malaysian army", "nat": "malaysian", "con_3": "army", "output": "الجيش الماليزي"},
    {"cate": "malaysian rugby union", "nat": "malaysian", "con_3": "rugby union", "output": "اتحاد الرجبي الماليزي"},
    {"cate": "maltese rugby league players", "nat": "maltese", "con_3": "rugby league players", "output": "لاعبو الدوري المالطي للرجبي"},
    {"cate": "mexican league", "nat": "mexican", "con_3": "league", "output": "الدوري المكسيكي"},
    {"cate": "mexican softball league players", "nat": "mexican", "con_3": "softball league players", "output": "لاعبو الدوري المكسيكي للكرة اللينة"},
    {"cate": "moroccan army", "nat": "moroccan", "con_3": "army", "output": "الجيش المغربي"},
    {"cate": "namibian labour law", "nat": "namibian", "con_3": "labour law", "output": "قانون العمل الناميبي"},
    {"cate": "nicaraguan professional baseball league", "nat": "nicaraguan", "con_3": "professional baseball league", "output": "دوري كرة القاعدة النيكاراغوي للمحترفين"},
    {"cate": "nigerian military", "nat": "nigerian", "con_3": "military", "output": "الجيش النيجيري"},
    {"cate": "north american football league", "nat": "north american", "con_3": "football league", "output": "الدوري الأمريكي الشمالي لكرة القدم"},
    {"cate": "north american hockey league", "nat": "north american", "con_3": "hockey league", "output": "الدوري الأمريكي الشمالي للهوكي"},
    {"cate": "north american rugby union", "nat": "north american", "con_3": "rugby union", "output": "اتحاد الرجبي الأمريكي الشمالي"},
    {"cate": "north american soccer league", "nat": "north american", "con_3": "soccer league", "output": "الدوري الأمريكي الشمالي لكرة القدم"},
    {"cate": "north korean pardons", "nat": "north korean", "con_3": "pardons", "output": "العفو الكوري الشمالي"},
    {"cate": "oceanian rugby union", "nat": "oceanian", "con_3": "rugby union", "output": "اتحاد الرجبي الأوقيانوسي"},
    {"cate": "pakistani criminal law", "nat": "pakistani", "con_3": "criminal law", "output": "القانون الجنائي الباكستاني"},
    {"cate": "palestinian solidarity movement", "nat": "palestinian", "con_3": "solidarity movement", "output": "حركة التضامن الفلسطيني"},
    {"cate": "peruvian army", "nat": "peruvian", "con_3": "army", "output": "الجيش البيروي"},
    {"cate": "romanian hockey league", "nat": "romanian", "con_3": "hockey league", "output": "الدوري الروماني للهوكي"},
    {"cate": "romanian military", "nat": "romanian", "con_3": "military", "output": "الجيش الروماني"},
    {"cate": "romanian rugby union", "nat": "romanian", "con_3": "rugby union", "output": "اتحاد الرجبي الروماني"},
    {"cate": "russian futsal super league", "nat": "russian", "con_3": "futsal super league", "output": "دوري السوبر كرة صالات الروسي"},
    {"cate": "russian invasion", "nat": "russian", "con_3": "invasion", "output": "الغزو الروسي"},
    {"cate": "russian presidential pardons", "nat": "russian", "con_3": "presidential pardons", "output": "العفو الرئاسي الروسي"},
    {"cate": "russian rugby union", "nat": "russian", "con_3": "rugby union", "output": "اتحاد الرجبي الروسي"},
    {"cate": "samoan rugby league", "nat": "samoan", "con_3": "rugby league", "output": "الدوري الساموي للرجبي"},
    {"cate": "samoan rugby union", "nat": "samoan", "con_3": "rugby union", "output": "اتحاد الرجبي الساموي"},
    {"cate": "saudi federation cup", "nat": "saudi", "con_3": "federation cup", "output": "كأس الاتحاد السعودي"},
    {"cate": "scottish football league", "nat": "scottish", "con_3": "football league", "output": "الدوري الإسكتلندي لكرة القدم"},
    {"cate": "scottish league", "nat": "scottish", "con_3": "league", "output": "الدوري الإسكتلندي"},
    {"cate": "scottish national party", "nat": "scottish", "con_3": "national party", "output": "الحزب الوطني الإسكتلندي"},
    {"cate": "scottish rugby union", "nat": "scottish", "con_3": "rugby union", "output": "اتحاد الرجبي الإسكتلندي"},
    {"cate": "singapore league", "nat": "singapore", "con_3": "league", "output": "الدوري السنغافوري"},
    {"cate": "slovenian ice hockey league", "nat": "slovenian", "con_3": "ice hockey league", "output": "الدوري السلوفيني لهوكي الجليد"},
    {"cate": "south african rugby union", "nat": "south african", "con_3": "rugby union", "output": "اتحاد الرجبي الجنوب الإفريقي"},
    {"cate": "south american rugby union", "nat": "south american", "con_3": "rugby union", "output": "اتحاد الرجبي الأمريكي الجنوبي"},
    {"cate": "south korean army", "nat": "south korean", "con_3": "army", "output": "الجيش الكوري الجنوبي"},
    {"cate": "soviet invasion", "nat": "soviet", "con_3": "invasion", "output": "الغزو السوفيتي"},
    {"cate": "spanish football league", "nat": "spanish", "con_3": "football league", "output": "الدوري الإسباني لكرة القدم"},
    {"cate": "spanish military", "nat": "spanish", "con_3": "military", "output": "الجيش الإسباني"},
    {"cate": "spanish rugby union leagues", "nat": "spanish", "con_3": "rugby union leagues", "output": "اتحاد دوري الرجبي الإسباني"},
    {"cate": "swedish hockey league", "nat": "swedish", "con_3": "hockey league", "output": "الدوري السويدي للهوكي"},
    {"cate": "swiss league", "nat": "swiss", "con_3": "league", "output": "الدوري السويسري"},
    {"cate": "tongan rugby union", "nat": "tongan", "con_3": "rugby union", "output": "اتحاد الرجبي التونغاني"},
    {"cate": "turkish army", "nat": "turkish", "con_3": "army", "output": "الجيش التركي"},
    {"cate": "turkish invasion", "nat": "turkish", "con_3": "invasion", "output": "الغزو التركي"},
    {"cate": "vanuatuan rugby league players", "nat": "vanuatuan", "con_3": "rugby league players", "output": "لاعبو الدوري الفانواتي للرجبي"},
    {"cate": "venezuelan professional baseball league", "nat": "venezuelan", "con_3": "professional baseball league", "output": "دوري كرة القاعدة الفنزويلي للمحترفين"},
    {"cate": "welsh football league", "nat": "welsh", "con_3": "football league", "output": "الدوري الويلزي لكرة القدم"},
    {"cate": "welsh rugby league", "nat": "welsh", "con_3": "rugby league", "output": "الدوري الويلزي للرجبي"},
    {"cate": "welsh rugby union", "nat": "welsh", "con_3": "rugby union", "output": "اتحاد الرجبي الويلزي"},
]


@pytest.mark.parametrize("data", with_all_data, ids=lambda x: x["cate"])
@pytest.mark.fast
def test_work_for_new_2018_men_keys_with_all(data) -> None:
    label = Work_for_New_2018_men_Keys_with_all(data["cate"], data["nat"], data["con_3"])
    assert label == data["output"]


@pytest.mark.skip
def test_work_for_me():
    # Test with basic inputs using a valid country code
    result = Work_for_me("test category", "united states", "players")
    assert isinstance(result, str)

    result_empty = Work_for_me("", "", "")
    assert isinstance(result_empty, str)

    # Test with various inputs using valid country codes
    result_various = Work_for_me("sports", "france", "athletes")
    assert isinstance(result_various, str)


def test_add_all():
    # Test with a basic input
    result = add_all("test label")
    assert isinstance(result, str)
    assert "ال" in result  # The function adds "ال" prefix

    # Test with empty string
    result_empty = add_all("")
    assert isinstance(result_empty, str)

    # Test with various inputs
    result_various = add_all("another label")
    assert isinstance(result_various, str)
