"""
"""
import pytest
from ArWikiCats.make_bots.format_bots.pf_keys import change_key_secondary_replacements, change_key_mappings_replacements

data1 = {
    "africa cup of nations": "africa cup-of-nations",
    "african-american muslims": "africanamerican muslims",
    "amphibious warfare vessels of islamic republic of iran navy": "amphibious warfare vessels of islamic republic-of iran navy",
    "auxiliary ships of islamic republic of iran navy": "auxiliary ships of islamic republic-of iran navy",
    "category:1980 sports events in europe": "category:1980 sports-events in europe",
    "category:2006 in northern ireland sport": "category:2006 in northern-ireland sport",
    "category:2016 women's africa cup of nations squad navigational boxes": "category:2016 women's africa cup-of-nations squad navigational boxes",
    "category:2016 women's africa cup of nations": "category:2016 women's africa cup-of-nations",
    "category:2017 american television seasons": "category:2017 american television-seasons",
    "category:2017 american television series debuts": "category:2017 american television series-debuts",
    "category:2017 american television series endings": "category:2017 american television series-endings",
    "category:2017 sports events": "category:2017 sports-events",
    "category:2018 women's africa cup of nations squad navigational boxes": "category:2018 women's africa cup-of-nations squad navigational boxes",
    "category:2018 women's africa cup of nations": "category:2018 women's africa cup-of-nations",
    "category:2022 women's africa cup of nations players": "category:2022 women's africa cup-of-nations players",
    "category:2022 women's africa cup of nations squad navigational boxes": "category:2022 women's africa cup-of-nations squad navigational boxes",
    "category:2022 women's africa cup of nations": "category:2022 women's africa cup-of-nations",
    "category:2024 women's africa cup of nations players": "category:2024 women's africa cup-of-nations players",
    "category:2024 women's africa cup of nations": "category:2024 women's africa cup-of-nations",
    "category:adaptations of works by greek writers": "category:adaptations-of-works by greek writers",
    "category:adaptations of works by irish writers": "category:adaptations-of-works by irish writers",
    "category:adaptations of works by italian writers": "category:adaptations-of-works by italian writers",
    "category:african-american coaches of canadian football": "category:africanamerican coaches of canadian-football",
    "category:african-american history by state": "category:africanamerican history by state",
    "category:african-american non-fiction writers": "category:africanamerican non-fiction writers",
    "category:ambassadors of federated states of micronesia in yemen by year": "category:ambassadors of federated states-of micronesia in yemen by year",
    "category:american players of canadian football by populated place": "category:american players of canadian-football by populated place",
    "category:american players of canadian football by state": "category:american players of canadian-football by state",
    "category:american players of canadian football": "category:american players of canadian-football",
    "category:april 1983 sports events": "category:april 1983 sports-events",
    "category:australian players of canadian football": "category:australian players of canadian-football",
    "category:bahamian players of canadian football": "category:bahamian players of canadian-football",
    "category:bodies of water of carmarthenshire": "category:bodies-of-water of carmarthenshire",
    "category:bodies of water of germany by state": "category:bodies-of-water of germany by state",
    "category:cameroonian players of canadian football": "category:cameroonian players of canadian-football",
    "category:canadian football by city": "category:canadian-football by city",
    "category:canadian football by country": "category:canadian-football by country",
    "category:canadian football by province or territory": "category:canadian-football by province or territory",
    "category:canadian football centres": "category:canadian-football centres",
    "category:canadian football defensive backs": "category:canadian-football defensive backs",
    "category:canadian football defensive linemen": "category:canadian-football defensive linemen",
    "category:canadian football fullbacks": "category:canadian-football fullbacks",
    "category:canadian football guards": "category:canadian-football guards",
    "category:canadian football in alberta": "category:canadian-football in alberta",
    "category:canadian football in british columbia": "category:canadian-football in british columbia",
    "category:canadian football in calgary": "category:canadian-football in calgary",
    "category:canadian football in canada by city": "category:canadian-football in canada by city",
    "category:canadian football in canada": "category:canadian-football in canada",
    "category:canadian football in edmonton": "category:canadian-football in edmonton",
    "category:canadian football in hamilton, ontario": "category:canadian-football in hamilton, ontario",
    "category:canadian football in manitoba": "category:canadian-football in manitoba",
    "category:canadian football in montreal": "category:canadian-football in montreal",
    "category:canadian football in nova scotia": "category:canadian-football in nova scotia",
    "category:canadian football in ontario": "category:canadian-football in ontario",
    "category:canadian football in ottawa": "category:canadian-football in ottawa",
    "category:canadian football in quebec": "category:canadian-football in quebec",
    "category:canadian football in saskatchewan": "category:canadian-football in saskatchewan",
    "category:canadian football in toronto": "category:canadian-football in toronto",
    "category:canadian football in vancouver": "category:canadian-football in vancouver",
    "category:canadian football in winnipeg": "category:canadian-football in winnipeg",
    "category:canadian football leagues": "category:canadian-football leagues",
    "category:canadian football linebackers": "category:canadian-football linebackers",
    "category:canadian football media": "category:canadian-football media",
    "category:canadian football offensive linemen": "category:canadian-football offensive linemen",
    "category:canadian football on television": "category:canadian-football on television",
    "category:canadian football people from calgary": "category:canadian-football people from calgary",
    "category:canadian football people from edmonton": "category:canadian-football people from edmonton",
    "category:canadian football people from greater sudbury": "category:canadian-football people from greater sudbury",
    "category:canadian football people from halifax, nova scotia": "category:canadian-football people from halifax, nova scotia",
    "category:canadian football people from hamilton, ontario": "category:canadian-football people from hamilton, ontario",
    "category:canadian football people from london, ontario": "category:canadian-football people from london, ontario",
    "category:canadian football people from mississauga": "category:canadian-football people from mississauga",
    "category:canadian football people from montreal": "category:canadian-football people from montreal",
    "category:canadian football people from new westminster": "category:canadian-football people from new westminster",
    "category:canadian football people from ottawa": "category:canadian-football people from ottawa",
    "category:canadian football people from quebec city": "category:canadian-football people from quebec city",
    "category:canadian football people from regina, saskatchewan": "category:canadian-football people from regina, saskatchewan",
    "category:canadian football people from saskatoon": "category:canadian-football people from saskatoon",
    "category:canadian football people from toronto": "category:canadian-football people from toronto",
    "category:canadian football people from vancouver": "category:canadian-football people from vancouver",
    "category:canadian football people from victoria, british columbia": "category:canadian-football people from victoria, british columbia",
    "category:canadian football people from windsor, ontario": "category:canadian-football people from windsor, ontario",
    "category:canadian football people from winnipeg": "category:canadian-football people from winnipeg",
    "category:canadian football people": "category:canadian-football people",
    "category:canadian football placekickers": "category:canadian-football placekickers",
    "category:canadian football players in edmonton": "category:canadian-football playerss in edmonton",
    "category:canadian football quarterbacks": "category:canadian-football quarterbacks",
    "category:canadian football running backs": "category:canadian-football running backs",
    "category:canadian football scouts": "category:canadian-football scouts",
    "category:canadian football tackles": "category:canadian-football tackles",
    "category:canadian football teams by city": "category:canadian-football teams by city",
    "category:canadian football teams by league": "category:canadian-football teams by league",
    "category:canadian football teams by province or territory": "category:canadian-football teams by province or territory",
    "category:canadian football teams in alberta": "category:canadian-football teams in alberta",
    "category:canadian football teams in calgary": "category:canadian-football teams in calgary",
    "category:canadian football teams in edmonton": "category:canadian-football teams in edmonton",
    "category:canadian football teams in manitoba": "category:canadian-football teams in manitoba",
    "category:canadian football teams in ontario": "category:canadian-football teams in ontario",
    "category:canadian football teams in ottawa": "category:canadian-football teams in ottawa",
    "category:canadian football teams in saskatchewan": "category:canadian-football teams in saskatchewan",
    "category:canadian football teams in toronto": "category:canadian-football teams in toronto",
    "category:canadian football teams in vancouver": "category:canadian-football teams in vancouver",
    "category:canadian football teams in winnipeg": "category:canadian-football teams in winnipeg",
    "category:canadian football teams": "category:canadian-football teams",
    "category:canadian football templates": "category:canadian-football templates",
    "category:canadian football terminology": "category:canadian-football terminology",
    "category:canadian football venues in british columbia": "category:canadian-football venues in british columbia",
    "category:canadian football venues in manitoba": "category:canadian-football venues in manitoba",
    "category:canadian football venues in ontario": "category:canadian-football venues in ontario",
    "category:canadian football venues in quebec": "category:canadian-football venues in quebec",
    "category:canadian football venues in united states": "category:canadian-football venues in united states",
    "category:canadian football venues": "category:canadian-football venues",
    "category:canadian football wide receivers": "category:canadian-football wide receivers",
    "category:canadian football": "category:canadian-football",
    "category:canadian players of canadian football by populated place": "category:canadian players of canadian-football by populated place",
    "category:canadian players of canadian football": "category:canadian players of canadian-football",
    "category:coaches of canadian football": "category:coaches of canadian-football",
    "category:cuban players of canadian football": "category:cuban players of canadian-football",
    "category:deaths by american airstrikes during world war ii": "category:deaths by american airstrikes during world-war-ii",
    "category:deaths by car bomb by country": "category:deaths by-car-bomb by country",
    "category:deaths by car bomb in afghanistan": "category:deaths by-car-bomb in afghanistan",
    "category:deaths by car bomb in england": "category:deaths by-car-bomb in england",
    "category:deaths by car bomb in france": "category:deaths by-car-bomb in france",
    "category:deaths by car bomb in iran": "category:deaths by-car-bomb in iran",
    "category:deaths by car bomb in iraq": "category:deaths by-car-bomb in iraq",
    "category:deaths by car bomb in italy": "category:deaths by-car-bomb in italy",
    "category:deaths by car bomb in lebanon": "category:deaths by-car-bomb in lebanon",
    "category:deaths by car bomb in malta": "category:deaths by-car-bomb in malta",
    "category:deaths by car bomb in northern ireland": "category:deaths by-car-bomb in northern-ireland",
    "category:deaths by car bomb in somalia": "category:deaths by-car-bomb in somalia",
    "category:deaths by car bomb in spain": "category:deaths by-car-bomb in spain",
    "category:deaths by car bomb in syria": "category:deaths by-car-bomb in syria",
    "category:deaths by car bomb in turkey": "category:deaths by-car-bomb in turkey",
    "category:deaths by car bomb in united kingdom": "category:deaths by-car-bomb in united kingdom",
    "category:deaths by car bomb in united states": "category:deaths by-car-bomb in united states",
    "category:deaths by car bomb in yemen": "category:deaths by-car-bomb in yemen",
    "category:deaths by firearm in afghanistan": "category:deaths by-firearm-in afghanistan",
    "category:deaths by firearm in alabama": "category:deaths by-firearm-in alabama",
    "category:deaths by firearm in alaska": "category:deaths by-firearm-in alaska",
    "category:deaths by firearm in albania": "category:deaths by-firearm-in albania",
    "category:deaths by firearm in alberta": "category:deaths by-firearm-in alberta",
    "category:deaths by firearm in angola": "category:deaths by-firearm-in angola",
    "category:deaths by firearm in argentina": "category:deaths by-firearm-in argentina",
    "category:deaths by firearm in arizona": "category:deaths by-firearm-in arizona",
    "category:deaths by firearm in arkansas": "category:deaths by-firearm-in arkansas",
    "category:deaths by firearm in armenia": "category:deaths by-firearm-in armenia",
    "category:deaths by firearm in australia": "category:deaths by-firearm-in australia",
    "category:deaths by firearm in azerbaijan": "category:deaths by-firearm-in azerbaijan",
    "category:deaths by firearm in bangladesh": "category:deaths by-firearm-in bangladesh",
    "category:deaths by firearm in belgium": "category:deaths by-firearm-in belgium",
    "category:deaths by firearm in bolivia": "category:deaths by-firearm-in bolivia",
    "category:deaths by firearm in bosnia and herzegovina": "category:deaths by-firearm-in bosnia and herzegovina",
    "category:deaths by firearm in brazil": "category:deaths by-firearm-in brazil",
    "category:deaths by firearm in british columbia": "category:deaths by-firearm-in british columbia",
    "category:deaths by firearm in british malaya": "category:deaths by-firearm-in british malaya",
    "category:deaths by firearm in bronx": "category:deaths by-firearm-in bronx",
    "category:deaths by firearm in brooklyn": "category:deaths by-firearm-in brooklyn",
    "category:deaths by firearm in bulgaria": "category:deaths by-firearm-in bulgaria",
    "category:deaths by firearm in burundi": "category:deaths by-firearm-in burundi",
    "category:deaths by firearm in california": "category:deaths by-firearm-in california",
    "category:deaths by firearm in cambodia": "category:deaths by-firearm-in cambodia",
    "category:deaths by firearm in canada": "category:deaths by-firearm-in canada",
    "category:deaths by firearm in central african republic": "category:deaths by-firearm-in central african republic",
    "category:deaths by firearm in chad": "category:deaths by-firearm-in chad",
    "category:deaths by firearm in chile": "category:deaths by-firearm-in chile",
    "category:deaths by firearm in colombia": "category:deaths by-firearm-in colombia",
    "category:deaths by firearm in colorado": "category:deaths by-firearm-in colorado",
    "category:deaths by firearm in comoros": "category:deaths by-firearm-in comoros",
    "category:deaths by firearm in connecticut": "category:deaths by-firearm-in connecticut",
    "category:deaths by firearm in costa rica": "category:deaths by-firearm-in costa rica",
    "category:deaths by firearm in croatia": "category:deaths by-firearm-in croatia",
    "category:deaths by firearm in cuba": "category:deaths by-firearm-in cuba",
    "category:deaths by firearm in cyprus": "category:deaths by-firearm-in cyprus",
    "category:deaths by firearm in czech republic": "category:deaths by-firearm-in czech republic",
    "category:deaths by firearm in czechoslovakia": "category:deaths by-firearm-in czechoslovakia",
    "category:deaths by firearm in democratic-republic-of-congo": "category:deaths by-firearm-in democratic-republic-of-congo",
    "category:deaths by firearm in denmark": "category:deaths by-firearm-in denmark",
    "category:deaths by firearm in dominican republic": "category:deaths by-firearm-in dominican republic",
    "category:deaths by firearm in east germany": "category:deaths by-firearm-in east germany",
    "category:deaths by firearm in east timor": "category:deaths by-firearm-in east timor",
    "category:deaths by firearm in ecuador": "category:deaths by-firearm-in ecuador",
    "category:deaths by firearm in egypt": "category:deaths by-firearm-in egypt",
    "category:deaths by firearm in el salvador": "category:deaths by-firearm-in el salvador",
    "category:deaths by firearm in england": "category:deaths by-firearm-in england",
    "category:deaths by firearm in equatorial guinea": "category:deaths by-firearm-in equatorial guinea",
    "category:deaths by firearm in estonia": "category:deaths by-firearm-in estonia",
    "category:deaths by firearm in ethiopia": "category:deaths by-firearm-in ethiopia",
    "category:deaths by firearm in finland": "category:deaths by-firearm-in finland",
    "category:deaths by firearm in gaza strip": "category:deaths by-firearm-in gaza strip",
    "category:deaths by firearm in georgia (country)": "category:deaths by-firearm-in georgia (country)",
    "category:deaths by firearm in georgia (u.s. state)": "category:deaths by-firearm-in georgia (u.s. state)",
    "category:deaths by firearm in germany": "category:deaths by-firearm-in germany",
    "category:deaths by firearm in ghana": "category:deaths by-firearm-in ghana",
    "category:deaths by firearm in gibraltar": "category:deaths by-firearm-in gibraltar",
    "category:deaths by firearm in guadeloupe": "category:deaths by-firearm-in guadeloupe",
    "category:deaths by firearm in guatemala": "category:deaths by-firearm-in guatemala",
    "category:deaths by firearm in guinea": "category:deaths by-firearm-in guinea",
    "category:deaths by firearm in guinea-bissau": "category:deaths by-firearm-in guinea-bissau",
    "category:deaths by firearm in guyana": "category:deaths by-firearm-in guyana",
    "category:deaths by firearm in haiti": "category:deaths by-firearm-in haiti",
    "category:deaths by firearm in hawaii": "category:deaths by-firearm-in hawaii",
    "category:deaths by firearm in hungary": "category:deaths by-firearm-in hungary",
    "category:deaths by firearm in idaho": "category:deaths by-firearm-in idaho",
    "category:deaths by firearm in illinois": "category:deaths by-firearm-in illinois",
    "category:deaths by firearm in india": "category:deaths by-firearm-in india",
    "category:deaths by firearm in indiana": "category:deaths by-firearm-in indiana",
    "category:deaths by firearm in indonesia": "category:deaths by-firearm-in indonesia",
    "category:deaths by firearm in insular areas of united states": "category:deaths by-firearm-in insular areas of united states",
    "category:deaths by firearm in iowa": "category:deaths by-firearm-in iowa",
    "category:deaths by firearm in ireland": "category:deaths by-firearm-in ireland",
    "category:deaths by firearm in islamabad": "category:deaths by-firearm-in islamabad",
    "category:deaths by firearm in israel": "category:deaths by-firearm-in israel",
    "category:deaths by firearm in italy": "category:deaths by-firearm-in italy",
    "category:deaths by firearm in ivory coast": "category:deaths by-firearm-in ivory coast",
    "category:deaths by firearm in jamaica": "category:deaths by-firearm-in jamaica",
    "category:deaths by firearm in japan": "category:deaths by-firearm-in japan",
    "category:deaths by firearm in kansas": "category:deaths by-firearm-in kansas",
    "category:deaths by firearm in kentucky": "category:deaths by-firearm-in kentucky",
    "category:deaths by firearm in kenya": "category:deaths by-firearm-in kenya",
    "category:deaths by firearm in korea": "category:deaths by-firearm-in korea",
    "category:deaths by firearm in kosovo": "category:deaths by-firearm-in kosovo",
    "category:deaths by firearm in kuwait": "category:deaths by-firearm-in kuwait",
    "category:deaths by firearm in liberia": "category:deaths by-firearm-in liberia",
    "category:deaths by firearm in libya": "category:deaths by-firearm-in libya",
    "category:deaths by firearm in lithuania": "category:deaths by-firearm-in lithuania",
    "category:deaths by firearm in london": "category:deaths by-firearm-in london",
    "category:deaths by firearm in louisiana": "category:deaths by-firearm-in louisiana",
    "category:deaths by firearm in luxembourg": "category:deaths by-firearm-in luxembourg",
    "category:deaths by firearm in maine": "category:deaths by-firearm-in maine",
    "category:deaths by firearm in malaysia": "category:deaths by-firearm-in malaysia",
    "category:deaths by firearm in mali": "category:deaths by-firearm-in mali",
    "category:deaths by firearm in malta": "category:deaths by-firearm-in malta",
    "category:deaths by firearm in mandatory palestine": "category:deaths by-firearm-in mandatory palestine",
    "category:deaths by firearm in manhattan": "category:deaths by-firearm-in manhattan",
    "category:deaths by firearm in maryland": "category:deaths by-firearm-in maryland",
    "category:deaths by firearm in massachusetts": "category:deaths by-firearm-in massachusetts",
    "category:deaths by firearm in mauritania": "category:deaths by-firearm-in mauritania",
    "category:deaths by firearm in mexico": "category:deaths by-firearm-in mexico",
    "category:deaths by firearm in michigan": "category:deaths by-firearm-in michigan",
    "category:deaths by firearm in mississippi": "category:deaths by-firearm-in mississippi",
    "category:deaths by firearm in missouri": "category:deaths by-firearm-in missouri",
    "category:deaths by firearm in montana": "category:deaths by-firearm-in montana",
    "category:deaths by firearm in montenegro": "category:deaths by-firearm-in montenegro",
    "category:deaths by firearm in montreal": "category:deaths by-firearm-in montreal",
    "category:deaths by firearm in morocco": "category:deaths by-firearm-in morocco",
    "category:deaths by firearm in mozambique": "category:deaths by-firearm-in mozambique",
    "category:deaths by firearm in myanmar": "category:deaths by-firearm-in myanmar",
    "category:deaths by firearm in nebraska": "category:deaths by-firearm-in nebraska",
    "category:deaths by firearm in nepal": "category:deaths by-firearm-in nepal",
    "category:deaths by firearm in netherlands": "category:deaths by-firearm-in netherlands",
    "category:deaths by firearm in nevada": "category:deaths by-firearm-in nevada",
    "category:deaths by firearm in new hampshire": "category:deaths by-firearm-in new hampshire",
    "category:deaths by firearm in new jersey": "category:deaths by-firearm-in new jersey",
    "category:deaths by firearm in new mexico": "category:deaths by-firearm-in new mexico",
    "category:deaths by firearm in new south wales": "category:deaths by-firearm-in new south wales",
    "category:deaths by firearm in new york (state)": "category:deaths by-firearm-in new york (state)",
    "category:deaths by firearm in new york city": "category:deaths by-firearm-in new york city",
    "category:deaths by firearm in new zealand": "category:deaths by-firearm-in new zealand",
    "category:deaths by firearm in nicaragua": "category:deaths by-firearm-in nicaragua",
    "category:deaths by firearm in niger": "category:deaths by-firearm-in niger",
    "category:deaths by firearm in nigeria": "category:deaths by-firearm-in nigeria",
    "category:deaths by firearm in north america": "category:deaths by-firearm-in north america",
    "category:deaths by firearm in north carolina": "category:deaths by-firearm-in north carolina",
    "category:deaths by firearm in north korea": "category:deaths by-firearm-in north korea",
    "category:deaths by firearm in northern ireland": "category:deaths by-firearm-in northern-ireland",
    "category:deaths by firearm in northern mariana islands": "category:deaths by-firearm-in northern mariana islands",
    "category:deaths by firearm in northern territory": "category:deaths by-firearm-in northern territory",
    "category:deaths by firearm in norway": "category:deaths by-firearm-in norway",
    "category:deaths by firearm in nova scotia": "category:deaths by-firearm-in nova scotia",
    "category:deaths by firearm in ohio": "category:deaths by-firearm-in ohio",
    "category:deaths by firearm in oklahoma": "category:deaths by-firearm-in oklahoma",
    "category:deaths by firearm in ontario": "category:deaths by-firearm-in ontario",
    "category:deaths by firearm in pakistan": "category:deaths by-firearm-in pakistan",
    "category:deaths by firearm in palau": "category:deaths by-firearm-in palau",
    "category:deaths by firearm in palestine": "category:deaths by-firearm-in palestine",
    "category:deaths by firearm in palestinian territories": "category:deaths by-firearm-in palestinian territories",
    "category:deaths by firearm in panama": "category:deaths by-firearm-in panama",
    "category:deaths by firearm in papua new guinea": "category:deaths by-firearm-in papua new guinea",
    "category:deaths by firearm in paraguay": "category:deaths by-firearm-in paraguay",
    "category:deaths by firearm in pennsylvania": "category:deaths by-firearm-in pennsylvania",
    "category:deaths by firearm in peru": "category:deaths by-firearm-in peru",
    "category:deaths by firearm in philippines": "category:deaths by-firearm-in philippines",
    "category:deaths by firearm in poland": "category:deaths by-firearm-in poland",
    "category:deaths by firearm in portugal": "category:deaths by-firearm-in portugal",
    "category:deaths by firearm in puerto rico": "category:deaths by-firearm-in puerto rico",
    "category:deaths by firearm in quebec": "category:deaths by-firearm-in quebec",
    "category:deaths by firearm in queens, new york": "category:deaths by-firearm-in queens, new york",
    "category:deaths by firearm in queensland": "category:deaths by-firearm-in queensland",
    "category:deaths by firearm in republic of ireland": "category:deaths by-firearm-in republic-of ireland",
    "category:deaths by firearm in republic-of-congo": "category:deaths by-firearm-in republic-of-congo",
    "category:deaths by firearm in rhode island": "category:deaths by-firearm-in rhode island",
    "category:deaths by firearm in rhodesia": "category:deaths by-firearm-in rhodesia",
    "category:deaths by firearm in romania": "category:deaths by-firearm-in romania",
    "category:deaths by firearm in russia": "category:deaths by-firearm-in russia",
    "category:deaths by firearm in rwanda": "category:deaths by-firearm-in rwanda",
    "category:deaths by firearm in san francisco": "category:deaths by-firearm-in san francisco",
    "category:deaths by firearm in scotland": "category:deaths by-firearm-in scotland",
    "category:deaths by firearm in senegal": "category:deaths by-firearm-in senegal",
    "category:deaths by firearm in serbia": "category:deaths by-firearm-in serbia",
    "category:deaths by firearm in sindh": "category:deaths by-firearm-in sindh",
    "category:deaths by firearm in slovakia": "category:deaths by-firearm-in slovakia",
    "category:deaths by firearm in slovenia": "category:deaths by-firearm-in slovenia",
    "category:deaths by firearm in somalia": "category:deaths by-firearm-in somalia",
    "category:deaths by firearm in south carolina": "category:deaths by-firearm-in south carolina",
    "category:deaths by firearm in south dakota": "category:deaths by-firearm-in south dakota",
    "category:deaths by firearm in south korea": "category:deaths by-firearm-in south korea",
    "category:deaths by firearm in soviet union": "category:deaths by-firearm-in soviet union",
    "category:deaths by firearm in spain": "category:deaths by-firearm-in spain",
    "category:deaths by firearm in sri lanka": "category:deaths by-firearm-in sri lanka",
    "category:deaths by firearm in suriname": "category:deaths by-firearm-in suriname",
    "category:deaths by firearm in sweden": "category:deaths by-firearm-in sweden",
    "category:deaths by firearm in switzerland": "category:deaths by-firearm-in switzerland",
    "category:deaths by firearm in taiwan": "category:deaths by-firearm-in taiwan",
    "category:deaths by firearm in tanzania": "category:deaths by-firearm-in tanzania",
    "category:deaths by firearm in tennessee": "category:deaths by-firearm-in tennessee",
    "category:deaths by firearm in togo": "category:deaths by-firearm-in togo",
    "category:deaths by firearm in uganda": "category:deaths by-firearm-in uganda",
    "category:deaths by firearm in ukraine": "category:deaths by-firearm-in ukraine",
    "category:deaths by firearm in united arab emirates": "category:deaths by-firearm-in united arab emirates",
    "category:deaths by firearm in united kingdom": "category:deaths by-firearm-in united kingdom",
    "category:deaths by firearm in utah": "category:deaths by-firearm-in utah",
    "category:deaths by firearm in vermont": "category:deaths by-firearm-in vermont",
    "category:deaths by firearm in vietnam": "category:deaths by-firearm-in vietnam",
    "category:deaths by firearm in virginia": "category:deaths by-firearm-in virginia",
    "category:deaths by firearm in wales": "category:deaths by-firearm-in wales",
    "category:deaths by firearm in washington (state)": "category:deaths by-firearm-in washington (state)",
    "category:deaths by firearm in washington, d.c.": "category:deaths by-firearm-in washington, d.c.",
    "category:deaths by firearm in west bank": "category:deaths by-firearm-in west bank",
    "category:deaths by firearm in western australia": "category:deaths by-firearm-in western australia",
    "category:deaths by firearm in wisconsin": "category:deaths by-firearm-in wisconsin",
    "category:deaths by firearm in yugoslavia": "category:deaths by-firearm-in yugoslavia",
    "category:deaths by firearm in zimbabwe": "category:deaths by-firearm-in zimbabwe",
    "category:deaths from brain cancer in northern ireland": "category:deaths from brain cancer in northern-ireland",
    "category:deaths from brain cancer in republic of ireland": "category:deaths from brain cancer in republic-of ireland",
    "category:deaths from cancer in federated states of micronesia": "category:deaths from cancer in federated states-of micronesia",
    "category:deaths from cancer in isle of man": "category:deaths from cancer in isle-of man",
    "category:deaths from cancer in northern ireland": "category:deaths from cancer in northern-ireland",
    "category:deaths from cancer in people's republic of china": "category:deaths from cancer in people's republic-of china",
    "category:deaths from cancer in republic of ireland": "category:deaths from cancer in republic-of ireland",
    "category:deaths from covid-19 pandemic in northern ireland": "category:deaths from covid-19 pandemic in northern-ireland",
    "category:deaths from lung cancer in northern ireland": "category:deaths from lung cancer in northern-ireland",
    "category:deaths from lung cancer in people's republic of china": "category:deaths from lung cancer in people's republic-of china",
    "category:deaths from lung cancer in republic of ireland": "category:deaths from lung cancer in republic-of ireland",
    "category:deaths from pneumonia in people's republic of china": "category:deaths from pneumonia in people's republic-of china",
    "category:deaths from pneumonia in republic of ireland": "category:deaths from pneumonia in republic-of ireland",
    "category:democratic-republic-of-congo players of canadian football": "category:democratic-republic-of-congo players of canadian-football",
    "category:dominican republic players of canadian football": "category:dominican republic players of canadian-football",
    "category:english players of canadian football": "category:english players of canadian-football",
    "category:expatriate women's futsal players in kuwait": "category:expatriate women's futsal playerss in kuwait",
    "category:expatriate women's futsal players in maldives": "category:expatriate women's futsal playerss in maldives",
    "category:female handball players in turkey by club": "category:female handball playerss in turkey by club",
    "category:georgia (u.s. state) attorney general elections": "category:georgia (u.s. state) attorney general-elections",
    "category:georgia (u.s. state) labor commissioners": "category:georgia (u.s. state) labour commissioners",
    "category:georgia (u.s. state) presidential primaries": "category:georgia (u.s. state) presidential-primaries",
    "category:guyanese players of canadian football": "category:guyanese players of canadian-football",
    "category:honduran players of canadian football": "category:honduran players of canadian-football",
    "category:jamaican players of canadian football": "category:jamaican players of canadian-football",
    "category:lebanese players of canadian football": "category:lebanese players of canadian-football",
    "category:ministers for foreign affairs of abkhazia": "category:ministers-for foreign affairs of abkhazia",
    "category:ministers for foreign affairs of luxembourg": "category:ministers-for foreign affairs of luxembourg",
    "category:ministers for foreign affairs of singapore": "category:ministers-for foreign affairs of singapore",
    "category:ministers for internal affairs of abkhazia": "category:ministers-for internal affairs of abkhazia",
    "category:ministers for public works of luxembourg": "category:ministers-for public works of luxembourg",
    "category:ministers of labour and social security of turkey": "category:ministers of labour-and-social security of turkey",
    "category:national register of historic places in westchester county, new york": "category:national-register-of-historic-places in westchester county, new york",
    "category:nigerian players of canadian football": "category:nigerian players of canadian-football",
    "category:non-profit organizations based in northern ireland": "category:non-profit organizations based in northern-ireland",
    "category:non-profit organizations based in republic of ireland": "category:non-profit organizations based in republic-of ireland",
    "category:panamanian players of canadian football": "category:panamanian players of canadian-football",
    "category:players of canadian football by nationality": "category:players of canadian-football by nationality",
    "category:players of canadian football by position": "category:players of canadian-football by position",
    "category:players of canadian football from alabama": "category:players of canadian-football from alabama",
    "category:players of canadian football from alaska": "category:players of canadian-football from alaska",
    "category:players of canadian football from alberta": "category:players of canadian-football from alberta",
    "category:players of canadian football from arizona": "category:players of canadian-football from arizona",
    "category:players of canadian football from arkansas": "category:players of canadian-football from arkansas",
    "category:players of canadian football from atlanta": "category:players of canadian-football from atlanta",
    "category:players of canadian football from baltimore": "category:players of canadian-football from baltimore",
    "category:players of canadian football from birmingham, alabama": "category:players of canadian-football from birmingham, alabama",
    "category:players of canadian football from brampton": "category:players of canadian-football from brampton",
    "category:players of canadian football from british columbia": "category:players of canadian-football from british columbia",
    "category:players of canadian football from brooklyn": "category:players of canadian-football from brooklyn",
    "category:players of canadian football from california": "category:players of canadian-football from california",
    "category:players of canadian football from chicago": "category:players of canadian-football from chicago",
    "category:players of canadian football from cincinnati": "category:players of canadian-football from cincinnati",
    "category:players of canadian football from cleveland": "category:players of canadian-football from cleveland",
    "category:players of canadian football from colorado": "category:players of canadian-football from colorado",
    "category:players of canadian football from columbia, south carolina": "category:players of canadian-football from columbia, south carolina",
    "category:players of canadian football from columbus, ohio": "category:players of canadian-football from columbus, ohio",
    "category:players of canadian football from connecticut": "category:players of canadian-football from connecticut",
    "category:players of canadian football from dallas": "category:players of canadian-football from dallas",
    "category:players of canadian football from dayton, ohio": "category:players of canadian-football from dayton, ohio",
    "category:players of canadian football from delaware": "category:players of canadian-football from delaware",
    "category:players of canadian football from denver": "category:players of canadian-football from denver",
    "category:players of canadian football from detroit": "category:players of canadian-football from detroit",
    "category:players of canadian football from florida": "category:players of canadian-football from florida",
    "category:players of canadian football from fort lauderdale, florida": "category:players of canadian-football from fort lauderdale, florida",
    "category:players of canadian football from georgia (u.s. state)": "category:players of canadian-football from georgia (u.s. state)",
    "category:players of canadian football from hawaii": "category:players of canadian-football from hawaii",
    "category:players of canadian football from honolulu": "category:players of canadian-football from honolulu",
    "category:players of canadian football from houston": "category:players of canadian-football from houston",
    "category:players of canadian football from idaho": "category:players of canadian-football from idaho",
    "category:players of canadian football from illinois": "category:players of canadian-football from illinois",
    "category:players of canadian football from indiana": "category:players of canadian-football from indiana",
    "category:players of canadian football from indianapolis": "category:players of canadian-football from indianapolis",
    "category:players of canadian football from jackson, mississippi": "category:players of canadian-football from jackson, mississippi",
    "category:players of canadian football from jacksonville, florida": "category:players of canadian-football from jacksonville, florida",
    "category:players of canadian football from kansas city, missouri": "category:players of canadian-football from kansas city, missouri",
    "category:players of canadian football from kansas": "category:players of canadian-football from kansas",
    "category:players of canadian football from kentucky": "category:players of canadian-football from kentucky",
    "category:players of canadian football from kingston, jamaica": "category:players of canadian-football from kingston, jamaica",
    "category:players of canadian football from lagos": "category:players of canadian-football from lagos",
    "category:players of canadian football from las vegas": "category:players of canadian-football from las vegas",
    "category:players of canadian football from long beach, california": "category:players of canadian-football from long beach, california",
    "category:players of canadian football from los angeles": "category:players of canadian-football from los angeles",
    "category:players of canadian football from louisiana": "category:players of canadian-football from louisiana",
    "category:players of canadian football from louisville, kentucky": "category:players of canadian-football from louisville, kentucky",
    "category:players of canadian football from manitoba": "category:players of canadian-football from manitoba",
    "category:players of canadian football from maryland": "category:players of canadian-football from maryland",
    "category:players of canadian football from massachusetts": "category:players of canadian-football from massachusetts",
    "category:players of canadian football from memphis, tennessee": "category:players of canadian-football from memphis, tennessee",
    "category:players of canadian football from miami": "category:players of canadian-football from miami",
    "category:players of canadian football from michigan": "category:players of canadian-football from michigan",
    "category:players of canadian football from minneapolis": "category:players of canadian-football from minneapolis",
    "category:players of canadian football from minnesota": "category:players of canadian-football from minnesota",
    "category:players of canadian football from mississippi": "category:players of canadian-football from mississippi",
    "category:players of canadian football from missouri": "category:players of canadian-football from missouri",
    "category:players of canadian football from montana": "category:players of canadian-football from montana",
    "category:players of canadian football from nevada": "category:players of canadian-football from nevada",
    "category:players of canadian football from new brunswick": "category:players of canadian-football from new brunswick",
    "category:players of canadian football from new jersey": "category:players of canadian-football from new jersey",
    "category:players of canadian football from new mexico": "category:players of canadian-football from new mexico",
    "category:players of canadian football from new orleans": "category:players of canadian-football from new orleans",
    "category:players of canadian football from new york (state)": "category:players of canadian-football from new york (state)",
    "category:players of canadian football from new york city": "category:players of canadian-football from new york city",
    "category:players of canadian football from newark, new jersey": "category:players of canadian-football from newark, new jersey",
    "category:players of canadian football from norfolk, virginia": "category:players of canadian-football from norfolk, virginia",
    "category:players of canadian football from north carolina": "category:players of canadian-football from north carolina",
    "category:players of canadian football from north dakota": "category:players of canadian-football from north dakota",
    "category:players of canadian football from nova scotia": "category:players of canadian-football from nova scotia",
    "category:players of canadian football from oakland, california": "category:players of canadian-football from oakland, california",
    "category:players of canadian football from ohio": "category:players of canadian-football from ohio",
    "category:players of canadian football from oklahoma city": "category:players of canadian-football from oklahoma city",
    "category:players of canadian football from oklahoma": "category:players of canadian-football from oklahoma",
    "category:players of canadian football from ontario": "category:players of canadian-football from ontario",
    "category:players of canadian football from oregon": "category:players of canadian-football from oregon",
    "category:players of canadian football from orlando, florida": "category:players of canadian-football from orlando, florida",
    "category:players of canadian football from pasadena, california": "category:players of canadian-football from pasadena, california",
    "category:players of canadian football from pennsylvania": "category:players of canadian-football from pennsylvania",
    "category:players of canadian football from pensacola, florida": "category:players of canadian-football from pensacola, florida",
    "category:players of canadian football from philadelphia": "category:players of canadian-football from philadelphia",
    "category:players of canadian football from phoenix, arizona": "category:players of canadian-football from phoenix, arizona",
    "category:players of canadian football from pittsburgh": "category:players of canadian-football from pittsburgh",
    "category:players of canadian football from quebec": "category:players of canadian-football from quebec",
    "category:players of canadian football from queens, new york": "category:players of canadian-football from queens, new york",
    "category:players of canadian football from sacramento, california": "category:players of canadian-football from sacramento, california",
    "category:players of canadian football from san antonio": "category:players of canadian-football from san antonio",
    "category:players of canadian football from san diego": "category:players of canadian-football from san diego",
    "category:players of canadian football from san francisco": "category:players of canadian-football from san francisco",
    "category:players of canadian football from san jose, california": "category:players of canadian-football from san jose, california",
    "category:players of canadian football from saskatchewan": "category:players of canadian-football from saskatchewan",
    "category:players of canadian football from seattle": "category:players of canadian-football from seattle",
    "category:players of canadian football from south carolina": "category:players of canadian-football from south carolina",
    "category:players of canadian football from st. louis": "category:players of canadian-football from st. louis",
    "category:players of canadian football from st. petersburg, florida": "category:players of canadian-football from st. petersburg, florida",
    "category:players of canadian football from stockton, california": "category:players of canadian-football from stockton, california",
    "category:players of canadian football from tampa, florida": "category:players of canadian-football from tampa, florida",
    "category:players of canadian football from tennessee": "category:players of canadian-football from tennessee",
    "category:players of canadian football from texas": "category:players of canadian-football from texas",
    "category:players of canadian football from utah": "category:players of canadian-football from utah",
    "category:players of canadian football from vermont": "category:players of canadian-football from vermont",
    "category:players of canadian football from virginia": "category:players of canadian-football from virginia",
    "category:players of canadian football from washington (state)": "category:players of canadian-football from washington (state)",
    "category:players of canadian football from washington, d.c.": "category:players of canadian-football from washington, d.c.",
    "category:players of canadian football from west virginia": "category:players of canadian-football from west virginia",
    "category:players of canadian football from wisconsin": "category:players of canadian-football from wisconsin",
    "category:players of canadian football from wyoming": "category:players of canadian-football from wyoming",
    "category:players of canadian football": "category:players of canadian-football",
    "category:puerto rican players of canadian football": "category:puerto rican players of canadian-football",
    "category:republic of ireland association football leagues": "category:republic-of ireland association football leagues",
    "category:republic of ireland football managers": "category:republic-of ireland football managers",
    "category:republic of ireland national women's football team managers": "category:republic-of ireland national women's football team managers",
    "category:republic of ireland national women's football team navigational boxes": "category:republic-of ireland national women's football team navigational boxes",
    "category:republic of ireland national women's football team": "category:republic-of ireland national women's football team",
    "category:republic of ireland national women's football teams": "category:republic-of ireland national women's football teams",
    "category:republic of ireland women's association football": "category:republic-of ireland women's association football",
    "category:republic of ireland women's association footballers": "category:republic-of ireland women's association footballers",
    "category:republic of ireland women's international footballers": "category:republic-of ireland women's international footballers",
    "category:republic of ireland women's international rugby union players": "category:republic-of ireland women's international rugby union players",
    "category:republic of ireland women's youth international footballers": "category:republic-of ireland women's youth international footballers",
    "category:samoan players of canadian football": "category:samoan players of canadian-football",
    "category:saudi arabian non-fiction writers": "category:saudiarabian non-fiction writers",
    "category:secretaries-of labor and employment of philippines": "category:secretaries-of labour and employment of philippines",
    "category:secretaries-of labor of mexico": "category:secretaries-of labour of mexico",
    "category:sierra leonean players of canadian football": "category:sierra leonean players of canadian-football",
    "category:television series endings by year": "category:television series-endings by year",
    "category:united states deputy secretaries-of labor": "category:united states deputy secretaries-of labour",
    "category:united states secretaries-of labor": "category:united states secretaries-of labour",
    "category:venezuelan players of canadian football": "category:venezuelan players of canadian-football",
    "category:wheelchair basketball players in 2020 parapan american games": "category:wheelchair basketball playerss in 2020 parapan american games",
    "category:wheelchair basketball players in 2020 summer paralympics": "category:wheelchair basketball playerss in 2020 summer paralympics",
    "category:wheelchair basketball players in turkey by team": "category:wheelchair basketball playerss in turkey by team",
    "category:wheelchair rugby players in 2020 parapan american games": "category:wheelchair rugby playerss in 2020 parapan american games",
    "category:wheelchair rugby players in 2020 summer paralympics": "category:wheelchair rugby playerss in 2020 summer paralympics",
    "category:wheelchair tennis players in 2020 asian para games": "category:wheelchair tennis playerss in 2020 asian para games",
    "category:wheelchair tennis players in 2020 parapan american games": "category:wheelchair tennis playerss in 2020 parapan american games",
    "category:wheelchair tennis players in 2020 summer paralympics": "category:wheelchair tennis playerss in 2020 summer paralympics",
    "category:women singers from kingdom of prussia": "category:women singers from kingdom-of prussia",
    "category:women's africa cup of nations players": "category:women's africa cup-of-nations players",
    "category:women's africa cup of nations qualification": "category:women's africa cup-of-nations qualification",
    "category:women's africa cup of nations tournaments": "category:women's africa cup-of-nations tournaments",
    "category:women's africa cup of nations": "category:women's africa cup-of-nations",
    "category:women's basketball players in united states by league": "category:women's basketball playerss in united states by league",
    "category:women's field hockey players in england": "category:women's field hockey playerss in england",
    "category:women's field hockey players in ireland": "category:women's field hockey playerss in ireland",
    "category:women's futsal players in kuwait": "category:women's futsal playerss in kuwait",
    "category:women's futsal players in maldives": "category:women's futsal playerss in maldives",
    "category:women's soccer players in australia by competition": "category:women's soccer playerss in australia by competition",
    "destroyers of islamic republic of iran navy": "destroyers of islamic republic-of iran navy",
    "frigates of islamic republic of iran navy": "frigates of islamic republic-of iran navy",
    "kingdom of hungary in middle ages": "kingdom-of hungary in middle ages",
    "mine warfare vessels of islamic republic of iran navy": "mine warfare vessels of islamic republic-of iran navy",
    "missile boats of islamic republic of iran navy": "missile boats of islamic republic-of iran navy",
    "saudi arabian muslims": "saudiarabian muslims",
    "ship classes of islamic republic of iran navy": "ship classes of islamic republic-of iran navy",
    "ships of islamic republic of iran navy": "ships of islamic republic-of iran navy",
    "submarines of islamic republic of iran navy": "submarines of islamic republic-of iran navy",
    "women in federated states of micronesia": "women in federated states-of micronesia",
}

data2 = {

    "archery at 2004 summer olympics": "archery in 2004 summer olympics",
    "category:100 metres at african championships in athletics": "category:100 metres in african championships in athletics",
    "category:100 metres at iaaf world youth championships in athletics": "category:100 metres in iaaf world youth championships in athletics",
    "category:100 metres at world para athletics championships": "category:100 metres in world para athletics championships",
    "category:american television series based on british television series": "category:american television series basedon british television series",
    "category:american television series based on non-american television series": "category:american television series basedon non-american television series",
    "category:argentina at universiade": "category:argentina in universiade",
    "category:argentina at winter olympics": "category:argentina in winter olympics",
    "category:arizona house of representatives": "category:arizona house-of-representatives",
    "category:athletics at summer universiade navigational boxes": "category:athletics in summer universiade navigational boxes",
    "category:athletics at universiade navigational boxes": "category:athletics in universiade navigational boxes",
    "category:australia at summer universiade": "category:australia in summer universiade",
    "category:australian television series based on non-australian television series": "category:australian television series basedon non-australian television series",
    "category:austrian television series based on non-austrian television series": "category:austrian television series basedon non-austrian television series",
    "category:belgian television series based on non-belgian television series": "category:belgian television series basedon non-belgian television series",
    "category:brazilian television series based on non-brazilian television series": "category:brazilian television series basedon non-brazilian television series",
    "category:british television series based on non-british television series": "category:british television series basedon non-british television series",
    "category:bulgarian television series based on non-bulgarian television series": "category:bulgarian television series basedon non-bulgarian television series",
    "category:canadian television series based on non-canadian television series": "category:canadian television series basedon non-canadian television series",
    "category:cape verde at paralympics": "category:cape verde in paralympics",
    "category:chinese television series based on non-chinese television series": "category:chinese television series basedon non-chinese television series",
    "category:comics based on films": "category:comics basedon films",
    "category:croatian television series based on non-croatian television series": "category:croatian television series basedon non-croatian television series",
    "category:cross-country skiers at 1992 winter paralympics": "category:cross-country skiers in 1992 winter paralympics",
    "category:czech television series based on non-czech television series": "category:czech television series basedon non-czech television series",
    "category:dutch television series based on non-dutch television series": "category:dutch television series basedon non-dutch television series",
    "category:equatoguinean women's footballers": "category:equatoguinean female footballers",
    "category:estonian television series based on non-estonian television series": "category:estonian television series basedon non-estonian television series",
    "category:expatriate association football managers by country of residence": "category:expatriate association football managers by country-of-residence",
    "category:figure skaters at 2002 winter olympics": "category:figure skaters in 2002 winter olympics",
    "category:figure skaters at 2003 asian winter games": "category:figure skaters in 2003 asian winter games",
    "category:figure skaters at 2007 winter universiade": "category:figure skaters in 2007 winter universiade",
    "category:film set at metropolitan museum of art": "category:film set in metropolitan museum of art",
    "category:films based on american comics": "category:films basedon american comics",
    "category:films based on comics": "category:films basedon comics",
    "category:films based on non-fiction books about organized crime": "category:films basedon non-fiction books about organized crime",
    "category:films based on non-fiction books": "category:films basedon non-fiction books",
    "category:films based on television series": "category:films basedon television series",
    "category:finnish television series based on non-finnish television series": "category:finnish television series basedon non-finnish television series",
    "category:french television series based on non-french television series": "category:french television series basedon non-french television series",
    "category:game of thrones (season 1) episodes": "category:game-of-thrones (season 1) episodes",
    "category:georgia (country) television series based on non-georgia (country) television series": "category:georgia (country) television series basedon non-georgia (country) television series",
    "category:georgia (u.s. state) house of representatives": "category:georgia (u.s. state) house-of-representatives",
    "category:german television series based on non-german television series": "category:german television series basedon non-german television series",
    "category:hungarian television series based on non-hungarian television series": "category:hungarian television series basedon non-hungarian television series",
    "category:indian television series based on non-indian television series": "category:indian television series basedon non-indian television series",
    "category:indonesian television series based on non-indonesian television series": "category:indonesian television series basedon non-indonesian television series",
    "category:internees at sheberghan prison": "category:internees in sheberghan prison",
    "category:iowa house of representatives": "category:iowa house-of-representatives",
    "category:irish television series based on non-irish television series": "category:irish television series basedon non-irish television series",
    "category:israeli television series based on non-israeli television series": "category:israeli television series basedon non-israeli television series",
    "category:italian television series based on non-italian television series": "category:italian television series basedon non-italian television series",
    "category:japanese television series based on non-japanese television series": "category:japanese television series basedon non-japanese television series",
    "category:lithuanian television series based on non-lithuanian television series": "category:lithuanian television series basedon non-lithuanian television series",
    "category:malaysian television series based on non-malaysian television series": "category:malaysian television series basedon non-malaysian television series",
    "category:mexican television series based on non-mexican television series": "category:mexican television series basedon non-mexican television series",
    "category:montana house of representatives": "category:montana house-of-representatives",
    "category:multi-sport events at yemen": "category:multi-sport events in yemen",
    "category:nations at 2010 summer youth olympics": "category:nations in 2010 summer youth olympics",
    "category:nations at universiade": "category:nations in universiade",
    "category:nebraska house of representatives": "category:nebraska house-of-representatives",
    "category:new mexico house of representatives": "category:new mexico house-of-representatives",
    "category:non-american television series based on american television series": "category:non-american television series basedon american television series",
    "category:non-argentine television series based on argentine television series": "category:non-argentine television series basedon argentine television series",
    "category:non-australian television series based on australian television series": "category:non-australian television series basedon australian television series",
    "category:non-british television series based on british television series": "category:non-british television series basedon british television series",
    "category:non-canadian television series based on canadian television series": "category:non-canadian television series basedon canadian television series",
    "category:non-colombian television series based on colombian television series": "category:non-colombian television series basedon colombian television series",
    "category:non-french television series based on french television series": "category:non-french television series basedon french television series",
    "category:non-japanese television series based on japanese television series": "category:non-japanese television series basedon japanese television series",
    "category:non-pakistani television series based on pakistani television series": "category:non-pakistani television series basedon pakistani television series",
    "category:non-south korean television series based on south korean television series": "category:non-south korean television series basedon south korean television series",
    "category:non-spanish television series based on spanish television series": "category:non-spanish television series basedon spanish television series",
    "category:non-taiwanese television series based on taiwanese television series": "category:non-taiwanese television series basedon taiwanese television series",
    "category:non-turkish television series based on turkish television series": "category:non-turkish television series basedon turkish television series",
    "category:pakistani television series based on non-pakistani television series": "category:pakistani television series basedon non-pakistani television series",
    "category:philippine television series based on non-philippine television series": "category:philippine television series basedon non-philippine television series",
    "category:portuguese television series based on non-portuguese television series": "category:portuguese television series basedon non-portuguese television series",
    "category:roller skaters at 2003 pan american games": "category:roller skaters in 2003 pan american games",
    "category:romanian television series based on non-romanian television series": "category:romanian television series basedon non-romanian television series",
    "category:russian television series based on non-russian television series": "category:russian television series basedon non-russian television series",
    "category:schools for deaf in new york (state)": "category:schools for-deaf in new york (state)",
    "category:singaporean television series based on non-singaporean television series": "category:singaporean television series basedon non-singaporean television series",
    "category:ski jumpers at 2007 winter universiade": "category:ski jumpers in 2007 winter universiade",
    "category:ski jumping at winter universiade": "category:ski jumping in winter universiade",
    "category:south korean television series based on non-south korean television series": "category:south korean television series basedon non-south korean television series",
    "category:soviet union at multi-sport events": "category:soviet union in multi-sport events",
    "category:spanish television series based on non-spanish television series": "category:spanish television series basedon non-spanish television series",
    "category:sports at summer universiade": "category:sports in summer universiade",
    "category:swaziland at multi-sport events": "category:swaziland in multi-sport events",
    "category:taiwanese television series based on non-taiwanese television series": "category:taiwanese television series basedon non-taiwanese television series",
    "category:television shows based on non-fiction books": "category:television shows basedon non-fiction books",
    "category:turkish television series based on non-turkish television series": "category:turkish television series basedon non-turkish television series",
    "category:uruguayan television series based on non-uruguayan television series": "category:uruguayan television series basedon non-uruguayan television series",
    "category:video games based on egyptian mythology": "category:video games basedon egyptian mythology",
    "category:video games based on mythology": "category:video games basedon mythology",
    "category:vietnamese television series based on non-vietnamese television series": "category:vietnamese television series basedon non-vietnamese television series",
    "category:water polo at summer universiade": "category:water polo in summer universiade",
    "category:wheelchair basketball at 2020 asean para games": "category:wheelchair basketball in 2020 asean para games",
    "category:wheelchair basketball at 2020 parapan american games": "category:wheelchair basketball in 2020 parapan american games",
    "category:wheelchair basketball at 2020 summer paralympics": "category:wheelchair basketball in 2020 summer paralympics",
    "category:wheelchair basketball at asean para games": "category:wheelchair basketball in asean para games",
    "category:wheelchair basketball at asian para games": "category:wheelchair basketball in asian para games",
    "category:wheelchair basketball at multi-sport events": "category:wheelchair basketball in multi-sport events",
    "category:wheelchair basketball at parapan american games": "category:wheelchair basketball in parapan american games",
    "category:wheelchair basketball at summer paralympics navigational boxes": "category:wheelchair basketball in summer paralympics navigational boxes",
    "category:wheelchair basketball at summer paralympics": "category:wheelchair basketball in summer paralympics",
    "category:wheelchair basketball players at 2020 parapan american games": "category:wheelchair basketball players in 2020 parapan american games",
    "category:wheelchair basketball players at 2020 summer paralympics": "category:wheelchair basketball players in 2020 summer paralympics",
    "category:wheelchair curlers at 2020 winter paralympics": "category:wheelchair curlers in 2020 winter paralympics",
    "category:wheelchair curling at 2020 winter paralympics": "category:wheelchair curling in 2020 winter paralympics",
    "category:wheelchair curling at winter paralympics": "category:wheelchair curling in winter paralympics",
    "category:wheelchair fencers at 2020 summer paralympics": "category:wheelchair fencers in 2020 summer paralympics",
    "category:wheelchair fencing at 2020 asean para games": "category:wheelchair fencing in 2020 asean para games",
    "category:wheelchair fencing at 2020 summer paralympics": "category:wheelchair fencing in 2020 summer paralympics",
    "category:wheelchair fencing at asean para games": "category:wheelchair fencing in asean para games",
    "category:wheelchair fencing at summer paralympics navigational boxes": "category:wheelchair fencing in summer paralympics navigational boxes",
    "category:wheelchair fencing at summer paralympics": "category:wheelchair fencing in summer paralympics",
    "category:wheelchair racers at 2020 summer olympics": "category:wheelchair racers in 2020 summer olympics",
    "category:wheelchair racing at summer olympics": "category:wheelchair racing in summer olympics",
    "category:wheelchair rugby at 2020 parapan american games": "category:wheelchair rugby in 2020 parapan american games",
    "category:wheelchair rugby at 2020 summer paralympics": "category:wheelchair rugby in 2020 summer paralympics",
    "category:wheelchair rugby at 2020 world games": "category:wheelchair rugby in 2020 world games",
    "category:wheelchair rugby at parapan american games": "category:wheelchair rugby in parapan american games",
    "category:wheelchair rugby at summer paralympics": "category:wheelchair rugby in summer paralympics",
    "category:wheelchair rugby at world games": "category:wheelchair rugby in world games",
    "category:wheelchair rugby players at 2020 parapan american games": "category:wheelchair rugby players in 2020 parapan american games",
    "category:wheelchair rugby players at 2020 summer paralympics": "category:wheelchair rugby players in 2020 summer paralympics",
    "category:wheelchair tennis at 2020 asean para games": "category:wheelchair tennis in 2020 asean para games",
    "category:wheelchair tennis at 2020 parapan american games": "category:wheelchair tennis in 2020 parapan american games",
    "category:wheelchair tennis at 2020 summer paralympics": "category:wheelchair tennis in 2020 summer paralympics",
    "category:wheelchair tennis at asean para games": "category:wheelchair tennis in asean para games",
    "category:wheelchair tennis at asian para games": "category:wheelchair tennis in asian para games",
    "category:wheelchair tennis at multi-sport events": "category:wheelchair tennis in multi-sport events",
    "category:wheelchair tennis at parapan american games": "category:wheelchair tennis in parapan american games",
    "category:wheelchair tennis at summer paralympics navigational boxes": "category:wheelchair tennis in summer paralympics navigational boxes",
    "category:wheelchair tennis at summer paralympics": "category:wheelchair tennis in summer paralympics",
    "category:wheelchair tennis players at 2020 asian para games": "category:wheelchair tennis players in 2020 asian para games",
    "category:wheelchair tennis players at 2020 parapan american games": "category:wheelchair tennis players in 2020 parapan american games",
    "category:wheelchair tennis players at 2020 summer paralympics": "category:wheelchair tennis players in 2020 summer paralympics",
    "category:wisconsin house of representatives": "category:wisconsin house-of-representatives",
    "category:works based on non-fiction books": "category:works basedon non-fiction books",
    "first league of serbia and montenegro": "first league of serbia-and-montenegro",
    "synchronized swimming at 2004 summer olympics": "synchronized swimming in 2004 summer olympics",
    "taekwondo at 2004 summer olympics": "taekwondo in 2004 summer olympics",
    "taekwondo at 2021 islamic solidarity games": "taekwondo in 2021 islamic solidarity games",
    "taekwondo at islamic solidarity games": "taekwondo in islamic solidarity games",
    "tour de france": "tour of france",
    "triathlon at 2004 summer olympics": "triathlon in 2004 summer olympics",
    "water polo at world aquatics championships": "water polo in world aquatics championships",
    "wrestling at 2004 summer olympics": "wrestling in 2004 summer olympics",
}


@pytest.mark.parametrize("category, expected", data1.items(), ids=data1.keys())
def test_pf_keys_1(category: str, expected: str) -> None:
    assert change_key_mappings_replacements(category) == expected


@pytest.mark.parametrize("category, expected", data2.items(), ids=data2.keys())
def test_pf_keys_2(category: str, expected: str) -> None:
    assert change_key_secondary_replacements(category) == expected
