"""
Tests
"""

import pytest

from src.make2_bots.ma_bots.country2_bots.c_1_c_2_labs import c_1_1_lab, c_2_1_lab

fast_data_c_1_1_lab = [
    {"tat_o": " in ", "cone_1": "cultural depictions of competitors", "output": "تصوير ثقافي عن منافسون"},

    {"tat_o": " about ", "cone_1": "american documentary television series", "output": "مسلسلات تلفزيونية وثائقية أمريكية"},
    {"tat_o": " about ", "cone_1": "american propaganda films", "output": "أفلام دعائية أمريكية"},
    {"tat_o": " about ", "cone_1": "animated television series", "output": "مسلسلات تلفزيونية رسوم متحركة"},
    {"tat_o": " about ", "cone_1": "brazilian television shows", "output": "عروض تلفزيونية برازيلية"},
    {"tat_o": " about ", "cone_1": "british television series", "output": "مسلسلات تلفزيونية بريطانية"},
    {"tat_o": " about ", "cone_1": "documentary television series", "output": "مسلسلات تلفزيونية وثائقية"},
    {"tat_o": " based in ", "cone_1": "defunct lgbtq organizations", "output": "منظمات إل جي بي تي كيو سابقة"},
    {"tat_o": " based in ", "cone_1": "defunct political organizations", "output": "منظمات سياسية سابقة"},
    {"tat_o": " based in ", "cone_1": "defunct professional associations", "output": "جمعيات تخصصية سابقة"},
    {"tat_o": " by ", "cone_1": "american football teams", "output": "فرق كرة قدم أمريكية"},
    {"tat_o": " by ", "cone_1": "american rock musicians", "output": "موسيقيو روك أمريكيون"},
    {"tat_o": " by ", "cone_1": "amphibious warfare vessels", "output": "سفن حربية برمائية"},
    {"tat_o": " by ", "cone_1": "animated television series", "output": "مسلسلات تلفزيونية رسوم متحركة"},
    {"tat_o": " by ", "cone_1": "anime and manga", "output": "أنمي ومانغا"},
    {"tat_o": " by ", "cone_1": "australian open tennis", "output": "بطولة أستراليا المفتوحة للتنس"},
    {"tat_o": " by ", "cone_1": "australian rules football clubs", "output": "أندية كرة قدم أسترالية"},
    {"tat_o": " by ", "cone_1": "australian rules football", "output": "كرة القدم الأسترالية"},
    {"tat_o": " by ", "cone_1": "buildings and structures demolished", "output": "مبان ومنشآت هدمت"},
    {"tat_o": " by ", "cone_1": "buildings and structures", "output": "مبان ومنشآت"},
    {"tat_o": " by ", "cone_1": "canadian football teams", "output": "فرق كرة قدم كندية"},
    {"tat_o": " by ", "cone_1": "christian buildings and structures", "output": "مبان ومنشآت مسيحية"},
    {"tat_o": " by ", "cone_1": "christian music albums", "output": "ألبومات موسيقى مسيحية"},
    {"tat_o": " by ", "cone_1": "christian universities and colleges", "output": "جامعات وكليات مسيحية"},
    {"tat_o": " by ", "cone_1": "dance music albums", "output": "ألبومات موسيقى الرقص"},
    {"tat_o": " by ", "cone_1": "death metal albums", "output": "ألبومات ديث ميتال"},
    {"tat_o": " by ", "cone_1": "defunct baseball venues", "output": "ملاعب كرة قاعدة سابقة"},
    {"tat_o": " by ", "cone_1": "defunct clubs and societies", "output": "أندية وجمعيات سابقة"},
    {"tat_o": " by ", "cone_1": "defunct liberal political parties", "output": "أحزاب سياسية ليبرالية سابقة"},
    {"tat_o": " by ", "cone_1": "defunct railway stations", "output": "محطات السكك الحديدية سابقة"},
    {"tat_o": " by ", "cone_1": "defunct shopping malls", "output": "مراكز تسوق سابقة"},
    {"tat_o": " by ", "cone_1": "defunct socialist parties", "output": "أحزاب اشتراكية سابقة"},
    {"tat_o": " by ", "cone_1": "defunct tennis tournaments", "output": "بطولات كرة مضرب سابقة"},
    {"tat_o": " by ", "cone_1": "east german people", "output": "ألمانيون شرقيون"},
    {"tat_o": " by ", "cone_1": "east german sprtspeople", "output": "رياضيون ألمانيون شرقيون"},
    {"tat_o": " by ", "cone_1": "eastern orthodox cathedrals", "output": "كاتدرائيات أرثوذكسية شرقية"},
    {"tat_o": " by ", "cone_1": "english lgbtq people", "output": "أعلام إل جي بي تي كيو إنجليزية"},
    {"tat_o": " by ", "cone_1": "english male actors", "output": "ممثلون ذكور إنجليز"},
    {"tat_o": " by ", "cone_1": "folk rock albums", "output": "ألبومات فولك روك"},
    {"tat_o": " by ", "cone_1": "hardcore punk albums", "output": "ألبومات هاردكور بانك"},
    {"tat_o": " by ", "cone_1": "heavy metal albums", "output": "ألبومات هيفي ميتال"},
    {"tat_o": " by ", "cone_1": "ice hockey leagues", "output": "دوريات هوكي جليد"},
    {"tat_o": " by ", "cone_1": "ice hockey teams", "output": "فرق هوكي على الجليد"},
    {"tat_o": " by ", "cone_1": "indie pop albums", "output": "ألبومات إيندي بوب"},
    {"tat_o": " by ", "cone_1": "indie rock albums", "output": "ألبومات إيندي روك"},
    {"tat_o": " by ", "cone_1": "international baseball competitions", "output": "منافسات كرة قاعدة دولية"},
    {"tat_o": " by ", "cone_1": "latin music albums", "output": "ألبومات موسيقى لاتينية"},
    {"tat_o": " by ", "cone_1": "law enforcement operations", "output": "عمليات تطبيق القانون"},
    {"tat_o": " by ", "cone_1": "major league baseball players", "output": "لاعبو دوري كرة القاعدة الرئيسي"},
    {"tat_o": " by ", "cone_1": "noise music albums", "output": "ألبومات موسيقى نويز"},
    {"tat_o": " by ", "cone_1": "north american culture", "output": "ثقافة أمريكية شمالية"},
    {"tat_o": " by ", "cone_1": "olympic games bids", "output": "عروض الألعاب الأوليمبية"},
    {"tat_o": " by ", "cone_1": "palestinian people imprisoned", "output": "فلسطينيون مسجونون"},
    {"tat_o": " by ", "cone_1": "pop punk albums", "output": "ألبومات بوب بانك"},
    {"tat_o": " by ", "cone_1": "ports and harbours", "output": "مرافئ وموانئ"},
    {"tat_o": " by ", "cone_1": "prisoners sentenced to death", "output": "سجناء حكم عليهم بالإعدام"},
    {"tat_o": " by ", "cone_1": "prisoners sentenced to life imprisonment", "output": "سجناء حكم عليهم بالحبس المؤبد"},
    {"tat_o": " by ", "cone_1": "protestant religious leaders", "output": "قادة دينيون بروتستانتيون"},
    {"tat_o": " by ", "cone_1": "psychedelic music albums", "output": "ألبومات موسيقى سايكيديلية"},
    {"tat_o": " by ", "cone_1": "roman catholic archbishops", "output": "رؤساء أساقفة رومان كاثوليك"},
    {"tat_o": " by ", "cone_1": "roman catholic bishops", "output": "أساقفة كاثوليك رومان"},
    {"tat_o": " by ", "cone_1": "rugby league coaches", "output": "مدربو دوري رجبي"},
    {"tat_o": " by ", "cone_1": "samoan rugby league players", "output": "لاعبو الدوري الساموي للرجبي"},
    {"tat_o": " by ", "cone_1": "science fiction films", "output": "أفلام خيال علمي"},
    {"tat_o": " by ", "cone_1": "science fiction novels", "output": "روايات خيال علمي"},
    {"tat_o": " by ", "cone_1": "serbian basketball players", "output": "لاعبو كرة سلة صرب"},
    {"tat_o": " by ", "cone_1": "sierra leonean people", "output": "سيراليونيون"},
    {"tat_o": " by ", "cone_1": "south african people", "output": "جنوب إفريقيون"},
    {"tat_o": " by ", "cone_1": "spoken word albums", "output": "ألبومات كلمة منطوقة"},
    {"tat_o": " by ", "cone_1": "television series produced", "output": "مسلسلات تلفزيونية أنتجت"},
    {"tat_o": " by ", "cone_1": "television shows produced", "output": "عروض تلفزيونية أنتجت"},
    {"tat_o": " by ", "cone_1": "the united arab emirates", "output": "الإمارات العربية المتحدة"},
    {"tat_o": " by ", "cone_1": "the united kingdom", "output": "المملكة المتحدة"},
    {"tat_o": " by ", "cone_1": "the united states", "output": "الولايات المتحدة"},
    {"tat_o": " by ", "cone_1": "u.s. national championships tennis", "output": "البطولات الوطنية الأمريكية لكرة المضرب"},
    {"tat_o": " by ", "cone_1": "united arab emirates", "output": "الإمارات العربية المتحدة"},
    {"tat_o": " by ", "cone_1": "us open tennis", "output": "بطولة أمريكا المفتوحة للتنس"},
    {"tat_o": " by ", "cone_1": "world heritage sites", "output": "مواقع التراث العالمي"},
    {"tat_o": " from ", "cone_1": "australian rules footballers", "output": "لاعبو كرة قدم أسترالية"},
    {"tat_o": " from ", "cone_1": "field hockey people", "output": "أعلام هوكي ميدان"},
    {"tat_o": " from ", "cone_1": "field hockey players", "output": "لاعبو هوكي ميدان"},
    {"tat_o": " from ", "cone_1": "ice hockey people", "output": "أعلام هوكي جليد"},
    {"tat_o": " from ", "cone_1": "male voice actors", "output": "ممثلو أداء صوتي ذكور"},
    {"tat_o": " from ", "cone_1": "rugby league players", "output": "لاعبو دوري رجبي"},
    {"tat_o": " from ", "cone_1": "rugby union players", "output": "لاعبو اتحاد رجبي"},
    {"tat_o": " from ", "cone_1": "united states house-of-representatives", "output": "مجلس النواب الأمريكي"},
    {"tat_o": " from ", "cone_1": "water polo players", "output": "لاعبو كرة ماء"},
    {"tat_o": " in ", "cone_1": "1st century bc", "output": "القرن 1 ق م"},
    {"tat_o": " in ", "cone_1": "american football teams", "output": "فرق كرة قدم أمريكية"},
    {"tat_o": " in ", "cone_1": "argentine people executed", "output": "معدومون أرجنتينيون"},
    {"tat_o": " in ", "cone_1": "art museums and galleries", "output": "متاحف فنية ومعارض"},
    {"tat_o": " in ", "cone_1": "asian games medalists", "output": "فائزون بميداليات الألعاب الآسيوية"},
    {"tat_o": " in ", "cone_1": "belgian people executed", "output": "معدومون بلجيكيون"},
    {"tat_o": " in ", "cone_1": "bosnia and herzegovina", "output": "البوسنة والهرسك"},
    {"tat_o": " in ", "cone_1": "buildings and structures", "output": "مبان ومنشآت"},
    {"tat_o": " in ", "cone_1": "by francisco de zurbarán", "output": "بواسطة فرانسيسكو دي زورباران"},
    {"tat_o": " in ", "cone_1": "by high school", "output": "حسب المدرسة الثانوية"},
    {"tat_o": " in ", "cone_1": "by populated place and occupation", "output": "حسب المكان المأهول والمهنة"},
    {"tat_o": " in ", "cone_1": "canadian chief executives", "output": "رؤساء تنفيذيون كنديون"},
    {"tat_o": " in ", "cone_1": "canadian lgbtq people", "output": "أعلام إل جي بي تي كيو كندية"},
    {"tat_o": " in ", "cone_1": "cities and towns", "output": "مدن وبلدات"},
    {"tat_o": " in ", "cone_1": "clubs and societies", "output": "أندية وجمعيات"},
    {"tat_o": " in ", "cone_1": "czech people executed", "output": "معدومون تشيكيون"},
    {"tat_o": " in ", "cone_1": "deaths due to animal attacks", "output": "وفيات ناجمة عن هجمات الحيوانات"},
    {"tat_o": " in ", "cone_1": "deaths from cancer", "output": "وفيات السرطان"},
    {"tat_o": " in ", "cone_1": "defunct american football venues", "output": "ملاعب كرة قدم أمريكية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct amusement parks", "output": "متنزهات ملاهي سابقة"},
    {"tat_o": " in ", "cone_1": "defunct art museums and galleries", "output": "متاحف فنية ومعارض سابقة"},
    {"tat_o": " in ", "cone_1": "defunct asian restaurants", "output": "مطاعم آسيوية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct athletics venues", "output": "ملاعب ألعاب قوى سابقة"},
    {"tat_o": " in ", "cone_1": "defunct baseball venues", "output": "ملاعب كرة قاعدة سابقة"},
    {"tat_o": " in ", "cone_1": "defunct basketball venues", "output": "ملاعب كرة سلة سابقة"},
    {"tat_o": " in ", "cone_1": "defunct clubs and societies", "output": "أندية وجمعيات سابقة"},
    {"tat_o": " in ", "cone_1": "defunct comedy clubs", "output": "أندية كوميدية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct communist parties", "output": "أحزاب شيوعية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct cycling races", "output": "سباقات سباق دراجات هوائية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct elementary schools", "output": "مدارس إبتدائية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct european restaurants", "output": "مطاعم أوروبية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct far-right political parties", "output": "أحزاب اليمين المتطرف سابقة"},
    {"tat_o": " in ", "cone_1": "defunct feminist organizations", "output": "منظمات نسوية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct football clubs", "output": "أندية كرة قدم سابقة"},
    {"tat_o": " in ", "cone_1": "defunct football venues", "output": "ملاعب كرة قدم سابقة"},
    {"tat_o": " in ", "cone_1": "defunct french restaurants", "output": "مطاعم فرنسية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct golf tournaments", "output": "بطولات غولف سابقة"},
    {"tat_o": " in ", "cone_1": "defunct high schools", "output": "مدارس ثانوية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct ice hockey venues", "output": "ملاعب هوكي جليد سابقة"},
    {"tat_o": " in ", "cone_1": "defunct italian restaurants", "output": "مطاعم إيطالية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct japanese restaurants", "output": "مطاعم يابانية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct liberal parties", "output": "أحزاب ليبرالية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct lower houses", "output": "المجالس الدنيا سابقة"},
    {"tat_o": " in ", "cone_1": "defunct mexican restaurants", "output": "مطاعم مكسيكية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct middle schools", "output": "مدارس إعدادية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct motorsport venues", "output": "ملاعب رياضة محركات سابقة"},
    {"tat_o": " in ", "cone_1": "defunct multi-national basketball leagues", "output": "دوريات كرة سلة متعددة الجنسيات سابقة"},
    {"tat_o": " in ", "cone_1": "defunct private schools", "output": "مدارس خاصة سابقة"},
    {"tat_o": " in ", "cone_1": "defunct private universities and colleges", "output": "جامعات وكليات خاصة سابقة"},
    {"tat_o": " in ", "cone_1": "defunct professional sports leagues", "output": "دوريات رياضية للمحترفين سابقة"},
    {"tat_o": " in ", "cone_1": "defunct public high schools", "output": "مدارس ثانوية عامة سابقة"},
    {"tat_o": " in ", "cone_1": "defunct radio networks", "output": "شبكات مذياع سابقة"},
    {"tat_o": " in ", "cone_1": "defunct radio stations", "output": "محطات إذاعية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct railway stations", "output": "محطات السكك الحديدية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct right-wing parties", "output": "أحزاب يمينية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct rugby league venues", "output": "ملاعب دوري رجبي سابقة"},
    {"tat_o": " in ", "cone_1": "defunct rugby union stadiums", "output": "ملاعب اتحاد رجبي سابقة"},
    {"tat_o": " in ", "cone_1": "defunct soccer clubs", "output": "أندية كرة قدم سابقة"},
    {"tat_o": " in ", "cone_1": "defunct soccer venues", "output": "ملاعب كرة قدم سابقة"},
    {"tat_o": " in ", "cone_1": "defunct socialist parties", "output": "أحزاب اشتراكية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct softball venues", "output": "ملاعب كرة لينة سابقة"},
    {"tat_o": " in ", "cone_1": "defunct sports governing bodies", "output": "هيئات تنظيم رياضية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct television channels", "output": "قنوات تلفزيونية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct television networks", "output": "شبكات تلفزيونية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct tennis tournaments", "output": "بطولات كرة مضرب سابقة"},
    {"tat_o": " in ", "cone_1": "defunct tourist attractions", "output": "مواقع جذب سياحي سابقة"},
    {"tat_o": " in ", "cone_1": "defunct trade unions", "output": "نقابات عمالية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct women's basketball competitions", "output": "منافسات كرة سلة نسائية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct women's basketball leagues", "output": "دوريات كرة سلة نسائية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct women's football clubs", "output": "أندية كرة قدم نسائية سابقة"},
    {"tat_o": " in ", "cone_1": "defunct women's soccer leagues", "output": "دوريات كرة قدم نسائية سابقة"},
    {"tat_o": " in ", "cone_1": "disused railway stations", "output": "محطات سكك حديدية مهجورة"},
    {"tat_o": " in ", "cone_1": "dutch chief executives", "output": "رؤساء تنفيذيون هولنديون"},
    {"tat_o": " in ", "cone_1": "dutch people executed", "output": "معدومون هولنديون"},
    {"tat_o": " in ", "cone_1": "electric power infrastructure", "output": "بنية تحتية للقدرة الكهربائية"},
    {"tat_o": " in ", "cone_1": "eritrean war crimes", "output": "جرائم حرب إريترية"},
    {"tat_o": " in ", "cone_1": "ethiopian war crimes", "output": "جرائم حرب إثيوبية"},
    {"tat_o": " in ", "cone_1": "field hockey clubs", "output": "أندية هوكي ميدان"},
    {"tat_o": " in ", "cone_1": "field hockey playerss", "output": "لاعبو هوكي ميدان"},
    {"tat_o": " in ", "cone_1": "finnish military personnel", "output": "أفراد عسكريون فنلنديون"},
    {"tat_o": " in ", "cone_1": "food and drink", "output": "أطعمة ومشروبات"},
    {"tat_o": " in ", "cone_1": "former buildings and structures", "output": "مبان ومنشآت سابقة"},
    {"tat_o": " in ", "cone_1": "former populated places", "output": "أماكن كانت مأهولة"},
    {"tat_o": " in ", "cone_1": "french-language radio stations", "output": "محطات إذاعية باللغة الفرنسية"},
    {"tat_o": " in ", "cone_1": "gaelic football clubs", "output": "أندية كرة قدم غالية"},
    {"tat_o": " in ", "cone_1": "german people executed", "output": "معدومون ألمان"},
    {"tat_o": " in ", "cone_1": "german prisoners of war", "output": "أسرى ألمان"},
    {"tat_o": " in ", "cone_1": "historic american buildings survey", "output": "مسح المبان التاريخية الأمريكية"},
    {"tat_o": " in ", "cone_1": "hong kong businesspeople", "output": "شخصيات أعمال هونغ كونغية"},
    {"tat_o": " in ", "cone_1": "ice hockey playerss", "output": "لاعبو هوكي جليد"},
    {"tat_o": " in ", "cone_1": "indonesian expatriate sprtspeople", "output": "رياضيون إندونيسيون مغتربون"},
    {"tat_o": " in ", "cone_1": "jews and judaism", "output": "اليهود واليهودية"},
    {"tat_o": " in ", "cone_1": "libertarian party-of-canada candidates", "output": "مرشحو الحزب التحرري الكندي"},
    {"tat_o": " in ", "cone_1": "mayors of places", "output": "رؤساء بلديات"},
    {"tat_o": " in ", "cone_1": "media and communications", "output": "الإعلام والاتصالات"},
    {"tat_o": " in ", "cone_1": "medical research institutes", "output": "معاهد أبحاث طبية"},
    {"tat_o": " in ", "cone_1": "military units and formations", "output": "وحدات وتشكيلات عسكرية"},
    {"tat_o": " in ", "cone_1": "missing person cases", "output": "قضايا أشخاص مفقودين"},
    {"tat_o": " in ", "cone_1": "monuments and memorials", "output": "معالم أثرية ونصب تذكارية"},
    {"tat_o": " in ", "cone_1": "new democratic party candidates", "output": "مرشحو الحزب الديمقراطي الجديد"},
    {"tat_o": " in ", "cone_1": "north american competitors", "output": "منافسون أمريكيون شماليون"},
    {"tat_o": " in ", "cone_1": "olympic gold medalists", "output": "فائزون بميداليات ذهبية أولمبية"},
    {"tat_o": " in ", "cone_1": "pan american games silver medalists", "output": "فائزون بميداليات فضية دورة الألعاب الأمريكية"},
    {"tat_o": " in ", "cone_1": "papua new guinea", "output": "بابوا غينيا الجديدة"},
    {"tat_o": " in ", "cone_1": "parks and open spaces", "output": "متنزهات ومساحات مفتوحة"},
    {"tat_o": " in ", "cone_1": "places of worship", "output": "أماكن عبادة"},
    {"tat_o": " in ", "cone_1": "polish air force", "output": "القوات الجوية البولندية"},
    {"tat_o": " in ", "cone_1": "polish political prisoners", "output": "مسجونون سياسيون بولنديون"},
    {"tat_o": " in ", "cone_1": "populated coastal places", "output": "أماكن ساحلية مأهولة"},
    {"tat_o": " in ", "cone_1": "portuguese international schools", "output": "مدارس دولية برتغالية"},
    {"tat_o": " in ", "cone_1": "road incident deaths", "output": "وفيات حوادث الطرق"},
    {"tat_o": " in ", "cone_1": "roman catholic archbishops", "output": "رؤساء أساقفة رومان كاثوليك"},
    {"tat_o": " in ", "cone_1": "roman catholic bishops", "output": "أساقفة كاثوليك رومان"},
    {"tat_o": " in ", "cone_1": "roman catholic churches", "output": "كنائس رومانية كاثوليكية"},
    {"tat_o": " in ", "cone_1": "rugby league playerss", "output": "لاعبو دوري رجبي"},
    {"tat_o": " in ", "cone_1": "rugby union leagues", "output": "اتحاد دوري الرجبي"},
    {"tat_o": " in ", "cone_1": "rugby union teams", "output": "فرق اتحاد رجبي"},
    {"tat_o": " in ", "cone_1": "science and technology", "output": "العلوم والتكنولوجيا"},
    {"tat_o": " in ", "cone_1": "sierra leonean expatriates", "output": "سيراليونيون مغتربون"},
    {"tat_o": " in ", "cone_1": "south african businesspeople", "output": "شخصيات أعمال جنوبية إفريقية"},
    {"tat_o": " in ", "cone_1": "south american competitors", "output": "منافسون أمريكيون جنوبيون"},
    {"tat_o": " in ", "cone_1": "television series produced", "output": "مسلسلات تلفزيونية أنتجت"},
    {"tat_o": " in ", "cone_1": "television series set", "output": "مسلسلات تلفزيونية تقع أحداثها"},
    {"tat_o": " in ", "cone_1": "television shows filmed", "output": "عروض تلفزيونية صورت"},
    {"tat_o": " in ", "cone_1": "television shows set", "output": "عروض تلفزيونية تقع أحداثها"},
    {"tat_o": " in ", "cone_1": "television shows shot", "output": "عروض تلفزيونية مصورة"},
    {"tat_o": " in ", "cone_1": "the covid-19 pandemic", "output": "جائحة فيروس كورونا"},
    {"tat_o": " in ", "cone_1": "towns and villages", "output": "بلدات وقرى"},
    {"tat_o": " in ", "cone_1": "track and field athletes", "output": "رياضيو المسار والميدان"},
    {"tat_o": " in ", "cone_1": "transport buildings and structures", "output": "مبان ومنشآت نقل"},
    {"tat_o": " in ", "cone_1": "united states house-of-representatives elections", "output": "انتخابات مجلس النواب الأمريكي"},
    {"tat_o": " in ", "cone_1": "universities and colleges", "output": "جامعات وكليات"},
    {"tat_o": " in ", "cone_1": "university of tennessee", "output": "جامعة تينيسي"},
    {"tat_o": " in ", "cone_1": "video games set", "output": "ألعاب فيديو تقع أحداثها"},
    {"tat_o": " in ", "cone_1": "welsh football clubs", "output": "أندية كرة قدم ويلزية"},
    {"tat_o": " in ", "cone_1": "world heritage sites", "output": "مواقع التراث العالمي"},
    {"tat_o": " of ", "cone_1": "archaeological sites of", "output": "مواقع أثرية في"},
    {"tat_o": " of ", "cone_1": "azerbaijan university of", "output": "جامعة أذربيجان"},
    {"tat_o": " of ", "cone_1": "bangladesh university of", "output": "جامعة بنغلاديش"},
    {"tat_o": " of ", "cone_1": "battles and operations of", "output": "معارك وعمليات"},
    {"tat_o": " of ", "cone_1": "burial sites of", "output": "مواقع دفن"},
    {"tat_o": " of ", "cone_1": "canyons and gorges of", "output": "أخاديد في"},
    {"tat_o": " of ", "cone_1": "chemical technology of", "output": "تقنية كيميائية في"},
    {"tat_o": " of ", "cone_1": "chief justices of", "output": "رؤساء قضاء"},
    {"tat_o": " of ", "cone_1": "congressional districts of", "output": "مقاطعات الكونغرس في"},
    {"tat_o": " of ", "cone_1": "cultural depictions of", "output": "تصوير ثقافي عن"},
    {"tat_o": " of ", "cone_1": "defunct bodies of", "output": "هيئات سابقة"},
    {"tat_o": " of ", "cone_1": "defunct clubs and societies of", "output": "أندية وجمعيات في سابقة"},
    {"tat_o": " of ", "cone_1": "defunct companies of", "output": "شركات سابقة في"},
    {"tat_o": " of ", "cone_1": "defunct diplomatic missions of", "output": "بعثات دبلوماسية في سابقة"},
    {"tat_o": " of ", "cone_1": "defunct locomotive manufacturers of", "output": "مصانع القاطرات في سابقة"},
    {"tat_o": " of ", "cone_1": "defunct state agencies of", "output": "أجهزة الدولة في سابقة"},
    {"tat_o": " of ", "cone_1": "defunct university of", "output": "جامعة سابقة"},
    {"tat_o": " of ", "cone_1": "drainage basins of", "output": "أحواض تصريف في"},
    {"tat_o": " of ", "cone_1": "eastern front of", "output": "الجبهة الشرقية في"},
    {"tat_o": " of ", "cone_1": "featured pictures of", "output": "صور مميزة عن"},
    {"tat_o": " of ", "cone_1": "fictional depictions of", "output": "تصوير خيالي عن"},
    {"tat_o": " of ", "cone_1": "government ministers of", "output": "وزراء"},
    {"tat_o": " of ", "cone_1": "governors general of", "output": "حكام عموم"},
    {"tat_o": " of ", "cone_1": "indigenous peoples of", "output": "شعوب أصلية في"},
    {"tat_o": " of ", "cone_1": "lieutenant governors of", "output": "نواب حكام"},
    {"tat_o": " of ", "cone_1": "mass murder of", "output": "قتل جماعي في"},
    {"tat_o": " of ", "cone_1": "military operations of", "output": "عمليات عسكرية في"},
    {"tat_o": " of ", "cone_1": "ministers-of state of", "output": "وزراء خارجية"},
    {"tat_o": " of ", "cone_1": "mountain passes of", "output": "ممرات جبلية في"},
    {"tat_o": " of ", "cone_1": "mountain ranges of", "output": "سلاسل جبلية في"},
    {"tat_o": " of ", "cone_1": "mountains and hills of", "output": "جبال وتلال"},
    {"tat_o": " of ", "cone_1": "national parks of", "output": "متنزهات وطنية في"},
    {"tat_o": " of ", "cone_1": "national sports teams of", "output": "منتخبات رياضية وطنية في"},
    {"tat_o": " of ", "cone_1": "native birds of", "output": "طيور محلية في"},
    {"tat_o": " of ", "cone_1": "naval battles of", "output": "معارك بحرية"},
    {"tat_o": " of ", "cone_1": "peace treaties of", "output": "معاهدات سلام"},
    {"tat_o": " of ", "cone_1": "ports and harbours of", "output": "مرافئ وموانئ"},
    {"tat_o": " of ", "cone_1": "prime ministers of", "output": "رؤساء وزراء"},
    {"tat_o": " of ", "cone_1": "prisoners and detainees of", "output": "سجناء ومعتقلون في"},
    {"tat_o": " of ", "cone_1": "protected areas of", "output": "مناطق محمية في"},
    {"tat_o": " of ", "cone_1": "rock formations of", "output": "تكوينات صخرية في"},
    {"tat_o": " of ", "cone_1": "sports organizations of", "output": "منظمات رياضية في"},
    {"tat_o": " of ", "cone_1": "state constitutional officers of", "output": "مسؤولون دستوريون في"},
    {"tat_o": " of ", "cone_1": "the order of", "output": "وسام"},
    {"tat_o": " of ", "cone_1": "uninhabited islands of", "output": "جزر غير مأهولة في"},
    {"tat_o": " of ", "cone_1": "vice presidents of", "output": "نواب رؤساء"},
    {"tat_o": " of ", "cone_1": "women government ministers of", "output": "وزيرات"},
    {"tat_o": " on ", "cone_1": "art museums and galleries", "output": "متاحف فنية ومعارض"},
    {"tat_o": " on ", "cone_1": "buildings and structures", "output": "مبان ومنشآت"},
    {"tat_o": " on ", "cone_1": "demolished buildings and structures", "output": "مبان ومنشآت مهدمة"},
    {"tat_o": " on ", "cone_1": "disused railway stations", "output": "محطات سكك حديدية مهجورة"},
    {"tat_o": " on ", "cone_1": "major league baseball", "output": "دوري كرة القاعدة الرئيسي"},
    {"tat_o": " on ", "cone_1": "military units and formations", "output": "وحدات وتشكيلات عسكرية"},
    {"tat_o": " on ", "cone_1": "pakistani people imprisoned", "output": "باكستانيون مسجونون"},
    {"tat_o": " on ", "cone_1": "parks and open spaces", "output": "متنزهات ومساحات مفتوحة"},
    {"tat_o": " on ", "cone_1": "roman catholic churches", "output": "كنائس رومانية كاثوليكية"},
    {"tat_o": " on ", "cone_1": "sierra leonean judges", "output": "قضاة سيراليونيون"},
    {"tat_o": " on ", "cone_1": "south african judges", "output": "قضاة جنوب إفريقيون"},
    {"tat_o": " on ", "cone_1": "television series set", "output": "مسلسلات تلفزيونية تقع أحداثها"},
    {"tat_o": " on ", "cone_1": "united states capitol", "output": "كابيتول الولايات المتحدة"},
    {"tat_o": " on ", "cone_1": "video games set", "output": "ألعاب فيديو تقع أحداثها"},
    {"tat_o": " to ", "cone_1": "monuments and memorials", "output": "معالم أثرية ونصب تذكارية"},
    {"tat_o": " to ", "cone_1": "united states navy", "output": "البحرية الأمريكية"},
    {"tat_o": "-of ", "cone_1": "cabinet secretaries of", "output": "أعضاء مجلس وزراء"},
    {"tat_o": "-of ", "cone_1": "state cabinet secretaries of", "output": "أعضاء مجلس وزراء"},
]


@pytest.mark.parametrize("data", fast_data_c_1_1_lab, ids=lambda x: x["cone_1"])
@pytest.mark.fast
def test_c_1_1_lab(data) -> None:
    label = c_1_1_lab(data["tat_o"], data["cone_1"], With_Years=False)
    assert label == data["output"]


fast_data_c_2_1_lab = {
    "12th iranian majlis": "المجلس الإيراني الثاني عشر",
    "13th iranian majlis": "المجلس الإيراني الثالث عشر",
    "15th iranian majlis": "المجلس الإيراني الخامس عشر",
    "1866 asian winter games": "الألعاب الآسيوية الشتوية 1866",
    "1866 european games": "الألعاب الأوروبية 1866",
    "1866 indian general election": "الانتخابات العامة الهندية 1866",
    "1866 pan american games": "دورة الألعاب الأمريكية 1866",
    "1866 parapan american games": "ألعاب بارابان الأمريكية 1866",
    "1866 presidential candidates": "مرشحون رئاسيون 1866",
    "1866 sea games": "ألعاب البحر 1866",
    "1866 summer olympics": "الألعاب الأولمبية الصيفية 1866",
    "1866 summer paralympics": "الألعاب البارالمبية الصيفية 1866",
    "1866 united states elections": "انتخابات الولايات المتحدة 1866",
    "1866 united states": "الولايات المتحدة 1866",
    "akrotiri and dhekelia": "أكروتيري ودكليا",
    "alberta by city": "ألبرتا حسب المدينة",
    "alexander the great": "الإسكندر الأكبر",
    "algerian civil war": "الحرب الأهلية الجزائرية",
    "amazonas (brazilian state)": "الأمازون (ولاية)",
    "american civil war": "الحرب الأهلية الأمريكية",
    "american football executives": "مسيرو كرة قدم أمريكية",
    "american football players": "لاعبو كرة قدم أمريكية",
    "ancient indian philosophy": "فلسفة هندية قديمة",
    "andaman and nicobar islands": "جزر أندمان ونيكوبار",
    "andorra la vella": "أندورا لا فيلا",
    "ang thong province": "محافظة أنغ ثونغ",
    "angus and dundee": "أنغوس ودندي",
    "animated television series": "مسلسلات تلفزيونية رسوم متحركة",
    "anime and manga": "أنمي ومانغا",
    "antarctica by country": "القارة القطبية الجنوبية حسب البلد",
    "antigua and barbuda": "أنتيغوا وباربودا",
    "archelaus of macedon": "أرخيلاوس الأول المقدوني",
    "architecture and construction": "هندسة معمارية وبناء",
    "architecture and planning": "هندسة معمارية وتخطيط",
    "architecture and technology": "هندسة معمارية والتقانة",
    "argyll and bute": "أرغيل وبوت",
    "art and design": "الفن وتصميم",
    "art museums and galleries": "متاحف فنية ومعارض",
    "arts and architecture": "الفنون وهندسة معمارية",
    "arts and design": "الفنون وتصميم",
    "arts and sciences": "الفنون وعلوم",
    "asia by country": "آسيا حسب البلد",
    "asia by region": "آسيا حسب المنطقة",
    "asian football confederation": "الاتحاد الآسيوي لكرة القدم",
    "asian tennis federation": "الاتحاد الآسيوي لكرة المضرب",
    "athletics navigational boxes": "صناديق تصفح ألعاب قوى",
    "australia by city": "أستراليا حسب المدينة",
    "australia by populated place": "أستراليا حسب المكان المأهول",
    "australia by state or territory": "أستراليا حسب الولاية أو الإقليم",
    "australian capital territory": "إقليم العاصمة الأسترالية",
    "australian national university": "جامعة أستراليا الوطنية",
    "australian royal air force": "القوات الجوية الملكية الأسترالية",
    "australian royal navy": "البحرية الأسترالية",
    "australian rules football": "كرة القدم الأسترالية",
    "austria by city": "النمسا حسب المدينة",
    "aviation accidents or incidents": "حوادث طيران",
    "azerbaijan soviet socialist republic": "الجمهورية الأذرية السوفيتية الاشتراكية",
    "b. r. ambedkar": "أمبيدكار",
    "baal shem tov": "بعل شيم توف",
    "baja california sur": "ولاية باخا كاليفورنيا سور",
    "bangka belitung islands": "بانغكا - بليتونغ",
    "banteay meanchey province": "محافظة بانتياي مينتشي",
    "belgium by region": "بلجيكا حسب المنطقة",
    "boadilla del monte": "بواديلا ديل مونتي",
    "bocas del toro province": "محافظة بوكاس ديل تورو",
    "bosnia and herzegovina soldiers": "مجندون بوسنيون",
    "bosnia and herzegovina": "البوسنة والهرسك",
    "brazil by state": "البرازيل حسب الولاية",
    "brighton and hove": "برايتون أند هوف",
    "british columbia (1866–1866)": "كولومبيا البريطانية (1866–1866)",
    "british columbia and vancouver island": "كولومبيا البريطانية وجزيرة فانكوفر",
    "british columbia and yukon": "كولومبيا البريطانية ويوكون",
    "british medical association": "الجمعية الطبية البريطانية",
    "british virgin islands": "جزر العذراء البريطانية",
    "budapest by line": "بودابست حسب الخط",
    "buenos aires province": "مقاطعة بوينس آيرس",
    "business and economics": "أعمال والاقتصاد",
    "oliveira de azeméis": "أوليفيرا دي ازميس",
    "orange free state": "دولة البرتقال الحرة",
    "osama bin laden": "أسامة بن لادن",
    "ottoman classical music": "موسيقى كلاسيكية عثمانية",
    "palestinian national authority": "السلطة الوطنية الفلسطينية",
    "palestinian political parties": "أحزاب سياسية فلسطينية",
    "papua new guinea": "بابوا غينيا الجديدة",
    "parliament of india": "برلمان الهند",
    "paschim medinipur district": "مقاطعة باشيم مدينبور",
    "pays de la loire": "وادي اللوار",
    "people and nations": "أشخاص وبلدان",
    "people's liberation army air force": "القوات الجوية لجيش التحرير الشعبي الصيني",
    "people's liberation army navy": "بحرية جيش التحرير الشعبي",
    "perth and kinross": "بيرث وكينروس",
    "peru by province": "بيرو حسب الإقليم",
    "pesaro and urbino": "بيزارو وأوربينو",
    "philosophy and religion": "الفلسفة والدين",
    "pisa and sardinia": "بيزا وسردينيا",
    "poland and ukraine": "بولندا وأوكرانيا",
    "polish air force": "القوات الجوية البولندية",
    "politics by state": "سياسة حسب الولاية",
    "pope alexander vi": "إسكندر السادس",
    "pope john paul ii": "البابا يوحنا بولص الثاني",
    "pope leo xiii": "ليون الثالث عشر",
    "pope paul vi": "بولس السادس",
    "pope pius xi": "بيوس الحادي عشر",
    "preah vihear province": "محافظة برياه فيهير",
    "prince edward island": "جزيرة الأمير إدوارد",
    "principality of serbia": "إمارة صربيا",
    "province of canada": "مقاطعة كندا",
    "province of tarragona": "طراغونة (مقاطعة)",
    "puerto rican descent": "أصل بورتوريكي",
    "purba medinipur district": "مقاطعة بوبا مدينبور",
    "póvoa de varzim": "بوفوا دي فارزيم",
    "rajanna sircilla district": "مقاطعة راجانا سيرسيلا",
    "ras al khaimah": "رأس الخيمة (مدينة)",
    "revolutionary socialist party (india)": "الحزب الاشتراكي الثوري",
    "rhondda cynon taf": "روندا كينون تاف",
    "richmond upon thames": "ريتشموند (لندن)",
    "rio de janeiro (city)": "ريو دي جانيرو",
    "rio de janeiro (state)": "ولاية ريو دي جانيرو",
    "rio de janeiro": "ريو دي جانيرو",
    "rio grande do norte": "ريو غراندي دو نورتي",
    "rio grande do sul": "ريو غراندي دو سول",
    "rio negro (amazon)": "ريو نيغرو (الأمازون)",
    "road transport and bridges": "نقل بري وجسور",
    "romanian naval forces": "البحرية الرومانية",
    "ross and cromarty": "روس وكرومارتي",
    "royal air force": "القوات الجوية الملكية",
    "royal canadian mounted police": "شرطة الخيالة الكندية الملكية",
    "royal college of nursing": "كلية التمريض الملكية",
    "royal danish army": "القوات البرية الدانماركية",
    "rugby union players": "لاعبو اتحاد رجبي",
    "russia and the soviet union": "روسيا والاتحاد السوفيتي",
    "russia by city": "روسيا حسب المدينة",
    "russian academy of arts": "الأكاديمية الروسية للفنون",
    "russian air force": "القوات الجوية الروسية",
    "russian soviet federative socialist republic": "جمهورية روسيا السوفيتية الاتحادية الاشتراكية",
    "río de la plata": "ريو دي لا بلاتا (نهر)",
    "río negro province": "محافظة ريو نيغرو",
    "saint kitts and nevis": "سانت كيتس ونيفيس",
    "saint pierre and miquelon": "سان بيير وميكلون",
    "saint vincent and the grenadines": "سانت فينسنت والغرينادين",
    "salt lake city": "سولت ليك (مدينة)",
    "san francisco bay area": "منطقة خليج سان فرانسيسكو",
    "san luis potosí": "ولاية سان لويس بوتوسي",
    "san luis province": "محافظة سان لويس",
    "san quentin state prison": "سجن سان كوينتن",
    "santa catarina (state)": "ولاية سانتا كاتارينا",
    "santa cruz de tenerife": "سانتا كروث دي تينيريفه",
    "santa fe province": "محافظة سانتا في",
    "santa maria da feira": "سانتا ماريا دا فييرا",
    "santiago de cuba": "سانتياغو دي كوبا",
    "santiago del estero province": "محافظة سانتياغو ديل استيرو",
    "santiago do cacém": "سانتياغو دو كاسيم",
    "santiago metropolitan region": "إقليم سانتياغو متروبوليتان",
    "satu mare county": "مقاطعة ساتو ماري",
    "saxe-coburg and gotha": "دوقية ساكسونيا كوبورغ وغوتا",
    "schools and colleges": "مدارس وكليات",
    "science and engineering": "العلم وهندسة",
    "science and mathematics": "العلم والرياضيات",
    "science and technology": "العلوم والتكنولوجيا",
    "science fiction magazines": "مجلات خيال علمي",
    "second bulgarian empire": "الإمبراطورية البلغارية الثانية",
    "second congo war": "حرب الكونغو الثانية",
    "second polish republic (1866–1866)": "الجمهورية البولندية الثانية (1866–1866)",
    "second polish republic": "الجمهورية البولندية الثانية",
    "security service of ukraine": "خدمة أمن أوكرانيا",
    "senate of pakistan": "مجلس الشيوخ الباكستان",
    "siem reap province": "محافظة سيم رياب",
    "singapore air force personnel": "أفراد القوات الجوية السنغافورية",
    "sixth dynasty of egypt": "الأسرة المصرية السادسة",
    "slovenia by populated place": "سلوفينيا حسب المكان المأهول",
    "sogn og fjordane": "سوغن وفيوردانه",
    "south africa by city": "جنوب إفريقيا حسب المدينة",
    "south african artists": "فنانون جنوب إفريقيون",
    "south african descent": "أصل جنوب إفريقي",
    "sovereign military order of malta": "فرسان مالطة",
    "spain by autonomous community": "إسبانيا حسب الحكم الذاتي",
    "spain by populated place": "إسبانيا حسب المكان المأهول",
    "spain by year": "إسبانيا حسب السنة",
    "spanish civil war": "الحرب الأهلية الإسبانية",
    "sports clubs and teams": "أندية رياضية وفرق",
    "sri lanka air force": "القوات الجوية السريلانكية",
    "sri lanka by city": "سريلانكا حسب المدينة",
    "sri lanka navy": "البحرية السريلانكية",
    "sri lankan civil war": "الحرب الأهلية السريلانكية",
    "sri lankan descent": "أصل سريلانكي",
    "sri lankan english": "إنجليز سريلانكيون",
    "sri lankan tamil descent": "أصل تاميلي سريلانكي",
    "st. johns river": "نهر سانت جونز",
    "state lower houses": "مجالس نواب الولايات",
    "sultanate of zanzibar": "سلطنة زنجبار",
    "supreme court of israel": "المحكمة العليا (إسرائيل)",
    "sweden by diocese": "السويد حسب الأبرشية",
    "sweden by populated place": "السويد حسب المكان المأهول",
    "swedish royal navy": "البحرية السويدية",
    "sydney opera house": "دار أوبرا سيدني",
    "syrian civil war": "الحرب الأهلية السورية",
    "são paulo (city)": "ساو باولو",
    "são paulo (state)": "ولاية ساو باولو",
    "são tomé and príncipe": "ساو تومي وبرينسيب",
    "tai po district": "مقاطعة تاي بو",
    "telugu desam party": "حزب تيلوغو ديسام",
    "thai royal air force": "القوات الجوية الملكية التايلندية",
    "thai royal navy": "البحرية التايلندية",
    "the 6th century bc": "القرن 6 ق م",
    "the 7th century bc": "القرن 7 ق م",
    "the 8th century bc": "القرن 8 ق م",
    "the abbasid caliphate": "الدولة العباسية",
    "the american civil war": "الحرب الأهلية الأمريكية",
    "the american revolution": "الثورة الأمريكية",
    "the arab world": "الوطن العربي",
    "the british empire": "الإمبراطورية البريطانية",
    "the british virgin islands": "جزر العذراء البريطانية",
    "the byzantine empire": "الإمبراطورية البيزنطية",
    "the caribbean by country": "الكاريبي حسب البلد",
    "the caribbean by dependent territory": "الكاريبي حسب الأقاليم التابعة",
    "the cayman islands": "جزر كايمان",
    "the central african republic": "جمهورية إفريقيا الوسطى",
    "the channel islands": "جزر القنال الإنجليزي",
    "the church of jesus christ of latter-day saints": "كنيسة يسوع المسيح لقديسي الأيام الأخيرة",
    "the cocos (keeling) islands": "جزر كوكوس",
    "the cook islands": "جزر كوك",
    "the covid-19 pandemic": "جائحة فيروس كورونا",
    "the czech republic by city": "التشيك حسب المدينة",
    "the czech republic": "التشيك",
    "the dominican republic": "جمهورية الدومينيكان",
    "the dutch east indies": "الهند الشرقية الهولندية",
    "the dutch republic": "جمهورية هولندا",
    "the east midlands": "شرق ميدلاندز",
    "the european union": "الاتحاد الأوروبي",
    "the falkland islands": "جزر فوكلاند",
    "the faroe islands": "جزر فارو",
    "the fatimid caliphate": "الدولة الفاطمية",
    "the federated states-of micronesia": "ولايات ميكرونيسيا المتحدة",
    "the gaza strip": "قطاع غزة",
    "the holy roman empire": "الإمبراطورية الرومانية المقدسة",
    # "the islamic state of iraq and the levant": "تنظيم داعش",
    "the israel–hamas war": "الحرب الفلسطينية الإسرائيلية",
    "the marshall islands": "جزر مارشال",
    "the middle east": "الشرق الأوسط",
    "the netherlands by city": "هولندا حسب المدينة",
    "the netherlands by province": "هولندا حسب الإقليم",
    "the new republic": "ذا نيو ريببلك",
    "the new york review of books": "نيويورك ريفيو أوف بوكس",
    "the northern mariana islands": "جزر ماريانا الشمالية",
    "the olympic games": "الألعاب الأولمبية",
    "the order of": "وسام",
    "the ottoman empire": "الدولة العثمانية",
    "the philippines by architectural style": "الفلبين حسب الطراز المعماري",
    "the philippines by region": "الفلبين حسب المنطقة",
    "the philippines by type": "الفلبين حسب الفئة",
    "the pitcairn islands": "جزر بيتكيرن",
    "the polish–lithuanian commonwealth": "الكومنولث البولندي الليتواني",
    "the republic-of ireland by year": "جمهورية أيرلندا حسب السنة",
    "the sasanian empire": "الإمبراطورية الساسانية",
    "the solomon islands": "جزر سليمان",
    "the soviet union": "الاتحاد السوفيتي",
    "the sri lankan civil war by decade": "الحرب الأهلية السريلانكية حسب العقد",
    "the summer olympics by year": "الألعاب الأولمبية الصيفية حسب السنة",
    "the thirteen colonies": "المستعمرات الثلاث عشرة",
    "the turks and caicos islands": "جزر توركس وكايكوس",
    "the united kingdom (1866–1866)": "المملكة المتحدة (1866–1866)",
    "the united kingdom by city": "المملكة المتحدة حسب المدينة",
    "the united kingdom": "المملكة المتحدة",
    "the united nations": "الأمم المتحدة",
    "the united states by architectural style": "الولايات المتحدة حسب الطراز المعماري",
    "the united states by century": "الولايات المتحدة حسب القرن",
    "the united states by city": "الولايات المتحدة حسب المدينة",
    "the united states by county": "الولايات المتحدة حسب المقاطعة",
    "the united states by decade": "الولايات المتحدة حسب العقد",
    "the united states by industry": "الولايات المتحدة حسب الصناعة",
    "the united states by issue": "الولايات المتحدة حسب القضية",
    "the united states by populated place": "الولايات المتحدة حسب المكان المأهول",
    "the united states by school": "الولايات المتحدة حسب المدرسة",
    "the united states by state or region": "الولايات المتحدة حسب الولاية أو المنطقة",
    "the united states by state or territory": "الولايات المتحدة حسب الولاية أو الإقليم",
    "the united states by state": "الولايات المتحدة حسب الولاية",
    "the united states by team": "الولايات المتحدة حسب الفريق",
    "the united states by time": "الولايات المتحدة حسب الوقت",
    "the united states by year": "الولايات المتحدة حسب السنة",
    "the united states virgin islands": "جزر العذراء الأمريكية",
    "the united states": "الولايات المتحدة",
    "the war in iraq (1866–1866)": "الحرب في العراق (1866–1866)",
    "the west bank": "الضفة الغربية",
    "the west indies": "الهند الغربية",
    "the west midlands (county)": "مقاطعة ميدلاند الغربية",
    "the west midlands (region)": "منطقة ميدلاند الغربية",
    "the winter olympics by year": "الألعاب الأولمبية الشتوية حسب السنة",
    "theatre and film": "المسرح وأفلام",
    "third dynasty of egypt": "الأسرة المصرية الثالثة",
    "thirtieth dynasty of egypt": "الأسرة المصرية الثلاثون",
    "tokyo metropolitan police department": "قسم شرطة العاصمة طوكيو",
    "trinidad and tobago coast guard": "خفر السواحل الترنيدادي",
    "trinidad and tobago descent": "أصل ترنيدادي",
    "trinidad and tobago": "ترينيداد وتوباغو",
    "turkey by province": "تركيا حسب الإقليم",
    "turkish air force": "القوات الجوية التركية",
    "turks and caicos islands": "جزر توركس وكايكوس",
    "twelfth dynasty of egypt": "الأسرة المصرية الثانية عشر",
    "twenty-fifth dynasty of egypt": "الأسرة المصرية الخامسة والعشرون",
    "twenty-fourth dynasty of egypt": "الأسرة المصرية الرابعة والعشرون",
    "twenty-second dynasty of egypt": "الأسرة المصرية الثانية والعشرون",
    "tyne and wear": "تاين و وير",
    "u.s. virgin islands": "جزر العذراء الأمريكية",
    "uefa euro 1866": "بطولة أمم أوروبا 1866",
    "ukraine by region": "أوكرانيا حسب المنطقة",
    "ukrainian soviet socialist republic": "جمهورية أوكرانيا السوفيتية الاشتراكية",
    "united arab emirates": "الإمارات العربية المتحدة",
    "united kingdom government": "حكومة المملكة المتحدة",
}


@pytest.mark.parametrize("category, expected", fast_data_c_2_1_lab.items(), ids=list(fast_data_c_2_1_lab.keys()))
@pytest.mark.fast
def test_c_2_1_lab(category, expected) -> None:
    label = c_2_1_lab(category, With_Years=True)
    assert label == expected
