# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en"
early_access: false

reviews:
    profile: "chill"
    request_changes_workflow: false
    high_level_summary: true
    poem: true
    review_status: true
    collapse_walkthrough: false
    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT MERGE"
        drafts: false
    path_filters:
        - "!**/old/**"
chat:
    auto_reply: true
reports:
    - title: "CHANGELOG Update"
      instructions: |
          Generate an updated changelog section for CHANGELOG.md based on the modifications in this pull request.
          Include:
              - Added (new features)
              - Changed (refactors or improvements)
              - Fixed (bug fixes)
              - Removed (deprecated or deleted parts)
          Format the section in Markdown, starting with a header:
              ## [<PR title>] - <date>
          Do NOT duplicate existing entries.
      format: "markdown"
