"""
Tests
"""

import pytest

from src.make2_bots.sports_bots.sport_lab_suffixes import get_teams_new

get_teams_new_data = {
    "defunct ice hockey teams": "فرق هوكي جليد سابقة",
    "professional sports leagues": "دوريات رياضية للمحترفين",
    "basketball awards": "جوائز كرة سلة",
    "domestic football": "كرة قدم محلية",
    "international football competitions": "منافسات كرة قدم دولية",
    "defunct football leagues": "دوريات كرة قدم سابقة",
    "international weightlifting competitions": "منافسات رفع أثقال دولية",
    "national junior men's handball teams": "منتخبات كرة يد وطنية للناشئين",
    "international figure skating competitions": "منافسات تزلج فني دولية",
    "international fencing competitions": "منافسات مبارزة سيف شيش دولية",
    "bowling television series": "مسلسلات تلفزيونية بولينج",
    "international volleyball competitions": "منافسات كرة طائرة دولية",
    "defunct soccer clubs": "أندية كرة قدم سابقة",
    "international women's field hockey competitions": "منافسات هوكي ميدان نسائية دولية",
    "women's international football": "كرة قدم دولية للسيدات",
    "world netball championships": "بطولة العالم لكرة الشبكة",
    "international baseball competitions": "منافسات كرة قاعدة دولية",
    "football cup competitions": "منافسات كؤوس كرة قدم",
    "world rowing championships medalists": "فائزون بميداليات بطولة العالم للتجديف",
    "international basketball competitions": "منافسات كرة سلة دولية",
    "professional ice hockey leagues": "دوريات هوكي جليد للمحترفين",
    "domestic football cups": "كؤوس كرة قدم محلية",
    "international water polo competitions": "منافسات كرة ماء دولية",
    "summer olympics water polo": "كرة الماء في الألعاب الأولمبية الصيفية",
    "defunct cycling teams": "فرق سباق دراجات هوائية سابقة",
    "under-23 cycle racing": "سباق دراجات تحت 23 سنة",
    "baseball video games": "ألعاب فيديو كرة قاعدة",
    "domestic football leagues": "دوريات كرة قدم محلية",
    "defunct football clubs": "أندية كرة قدم سابقة",
    "international field hockey competitions": "منافسات هوكي ميدان دولية",
    "summer olympics volleyball": "كرة الطائرة في الألعاب الأولمبية الصيفية",
    "world athletics championships": "بطولة العالم لألعاب القوى",
    "international boxing competitions": "منافسات بوكسينغ دولية",
    "international gymnastics competitions": "منافسات جمباز دولية",
    "defunct ice hockey leagues": "دوريات هوكي جليد سابقة",
    "defunct sports competitions": "منافسات رياضية سابقة",
    "defunct american football teams": "فرق كرة قدم أمريكية سابقة",
    "defunct water polo competitions": "منافسات كرة ماء سابقة",
    "international women's basketball competitions": "منافسات كرة سلة نسائية دولية",
    "international ice hockey competitions": "منافسات هوكي جليد دولية",
    "domestic handball leagues": "دوريات كرة يد محلية",
    "national football team results": "نتائج منتخبات كرة قدم وطنية",
    "netball world cup": "كأس العالم لكرة الشبكة",
    "international youth football competitions": "منافسات كرة قدم شبابية دولية",
    "defunct baseball teams": "فرق كرة قاعدة سابقة",
    "defunct sports clubs": "أندية رياضية سابقة",
    "international athletics competitions": "منافسات ألعاب قوى دولية",
    "defunct esports competitions": "منافسات رياضة إلكترونية سابقة",
}


@pytest.mark.parametrize("category, expected_key", get_teams_new_data.items(), ids=list(get_teams_new_data.keys()))
@pytest.mark.fast
def test_get_teams_new_data(category, expected_key) -> None:

    label = get_teams_new(category)
    assert label.strip() == expected_key


data_slow = {
    "defunct ice hockey teams": "فرق هوكي جليد سابقة",
    "professional sports leagues": "دوريات رياضية للمحترفين",
    "basketball awards": "جوائز كرة سلة",
    "domestic football": "كرة قدم محلية",
    "international football competitions": "منافسات كرة قدم دولية",
    "defunct football leagues": "دوريات كرة قدم سابقة",
    "international weightlifting competitions": "منافسات رفع أثقال دولية",
    "national junior men's handball teams": "منتخبات كرة يد وطنية للناشئين",
    "international figure skating competitions": "منافسات تزلج فني دولية",
    "international fencing competitions": "منافسات مبارزة سيف شيش دولية",
    "bowling television series": "مسلسلات تلفزيونية بولينج",
    "international volleyball competitions": "منافسات كرة طائرة دولية",
    "defunct soccer clubs": "أندية كرة قدم سابقة",
    "international women's field hockey competitions": "منافسات هوكي ميدان نسائية دولية",
    "women's international football": "كرة قدم دولية للسيدات",
    "world netball championships": "بطولة العالم لكرة الشبكة",
    "international baseball competitions": "منافسات كرة قاعدة دولية",
    "football cup competitions": "منافسات كؤوس كرة قدم",
    "world rowing championships medalists": "فائزون بميداليات بطولة العالم للتجديف",
    "international basketball competitions": "منافسات كرة سلة دولية",
    "professional ice hockey leagues": "دوريات هوكي جليد للمحترفين",
    "domestic football cups": "كؤوس كرة قدم محلية",
    "international water polo competitions": "منافسات كرة ماء دولية",
    "summer olympics water polo": "كرة الماء في الألعاب الأولمبية الصيفية",
    "defunct cycling teams": "فرق سباق دراجات هوائية سابقة",
    "under-23 cycle racing": "سباق دراجات تحت 23 سنة",
    "baseball video games": "ألعاب فيديو كرة قاعدة",
    "domestic football leagues": "دوريات كرة قدم محلية",
    "defunct football clubs": "أندية كرة قدم سابقة",
    "international field hockey competitions": "منافسات هوكي ميدان دولية",
    "summer olympics volleyball": "كرة الطائرة في الألعاب الأولمبية الصيفية",
    "world athletics championships": "بطولة العالم لألعاب القوى",
    "international boxing competitions": "منافسات بوكسينغ دولية",
    "international gymnastics competitions": "منافسات جمباز دولية",
    "defunct ice hockey leagues": "دوريات هوكي جليد سابقة",
    "defunct sports competitions": "منافسات رياضية سابقة",
    "defunct american football teams": "فرق كرة قدم أمريكية سابقة",
    "defunct water polo competitions": "منافسات كرة ماء سابقة",
    "international women's basketball competitions": "منافسات كرة سلة نسائية دولية",
    "international ice hockey competitions": "منافسات هوكي جليد دولية",
    "domestic handball leagues": "دوريات كرة يد محلية",
    "national football team results": "نتائج منتخبات كرة قدم وطنية",
    "netball world cup": "كأس العالم لكرة الشبكة",
    "international youth football competitions": "منافسات كرة قدم شبابية دولية",
    "defunct baseball teams": "فرق كرة قاعدة سابقة",
    "defunct sports clubs": "أندية رياضية سابقة",
    "international athletics competitions": "منافسات ألعاب قوى دولية",
    "defunct esports competitions": "منافسات رياضة إلكترونية سابقة",
    "under-16 basketball": "كرة سلة تحت 16 سنة",
    "women's cricket world cup": "كأس العالم للكريكت للسيدات",
    "rugby league world cup": "كأس العالم لدوري الرجبي",
    "football league": "دوري كرة القدم",
    "international cricket competitions": "منافسات كريكت دولية",
    "international softball competitions": "منافسات كرة لينة دولية",
    "international bandy competitions": "منافسات باندي دولية",
    "defunct rugby union teams": "فرق اتحاد رجبي سابقة",
    "summer olympics football": "كرة القدم في الألعاب الأولمبية الصيفية",
    "men's international football": "كرة قدم دولية للرجال",
    "defunct indoor soccer leagues": "دوريات كرة قدم داخل الصالات سابقة",
    "defunct gaelic football competitions": "منافسات كرة قدم غالية سابقة",
    "international rugby union competitions": "منافسات اتحاد رجبي دولية",
    "international cricket records and statistics": "سجلات وإحصائيات كريكت دولية",
    "women's hockey world cup": "كأس العالم للهوكي للسيدات",
    "national women's under-19 basketball teams": "منتخبات كرة سلة وطنية تحت 19 سنة للسيدات",
    "defunct rugby union cup competitions": "منافسات كؤوس اتحاد رجبي سابقة",
    "defunct rugby league teams": "فرق دوري رجبي سابقة",
    "international wrestling competitions": "منافسات مصارعة دولية",
    "indoor track and field": "سباقات مضمار وميدان داخل الصالات",
    "biathlon world cup": "كأس العالم للبياثلون",
    "cycling television series": "مسلسلات تلفزيونية سباق دراجات هوائية",
    "international shooting competitions": "منافسات رماية دولية",
    "domestic cricket competitions": "منافسات كريكت محلية",
    "international women's cricket competitions": "منافسات كريكت نسائية دولية",
    "defunct water polo clubs": "أندية كرة ماء سابقة",
    "defunct basketball teams": "فرق كرة سلة سابقة",
    "baseball music": "موسيقى كرة قاعدة",
    "world taekwondo championships": "بطولة العالم للتايكوندو",
    "men's hockey world cup": "كأس العالم للهوكي للرجال",
    "international kickboxing competitions": "منافسات كيك بوكسينغ دولية",
    "defunct sports leagues": "دوريات رياضية سابقة",
    "fencing logos": "شعارات مبارزة سيف شيش",
    "world netball championship": "بطولة العالم لكرة الشبكة",
    "defunct basketball competitions": "منافسات كرة سلة سابقة",
    "international handball competitions": "منافسات كرة يد دولية",
    "international speed skating competitions": "منافسات تزلج سريع دولية",
    "premier lacrosse league": "دوريات لاكروس من الدرجة الممتازة",
    "defunct football competitions": "منافسات كرة قدم سابقة",
    "national water polo teams": "منتخبات كرة ماء وطنية",
    "rowing equipment": "معدات تجديف",
    "defunct baseball leagues": "دوريات كرة قاعدة سابقة",
    "international women's football competitions": "منافسات كرة قدم نسائية دولية",
    "canoeing logos": "شعارات ركوب الكنو",
    "sports cup competitions": "منافسات كؤوس رياضية",
    "domestic women's football leagues": "دوريات كرة قدم محلية للسيدات",
    "international archery competitions": "منافسات نبالة دولية",
    "national basketball team results": "نتائج منتخبات كرة سلة وطنية",
    "cycling races": "سباقات سباق دراجات هوائية",
    "basketball terminology": "مصطلحات كرة سلة",
    "indoor hockey": "هوكي داخل الصالات",
    "defunct football cup competitions": "منافسات كؤوس كرة قدم سابقة",
    "national ice hockey teams": "منتخبات هوكي جليد وطنية",
    "international men's football competitions": "منافسات كرة قدم رجالية دولية",
    "international cycle races": "سباقات دراجات دولية",
    "defunct hockey competitions": "منافسات هوكي سابقة",
    "water polo competition": "منافسات كرة ماء",
    "international futsal competitions": "منافسات كرة صالات دولية",
    "shooting sports equipment": "معدات رماية",
    "national women's under-20 football teams": "منتخبات كرة قدم وطنية تحت 20 سنة للسيدات",
    "rugby league chairmen and investors": "رؤساء ومسيرو دوري رجبي",
    "roller hockey logos": "شعارات هوكي دحرجة",
    "basketball cup competitions": "منافسات كؤوس كرة سلة",
    "tennis logos": "شعارات كرة مضرب",
    "national women's artistic gymnastics teams": "منتخبات جمباز فني وطنية للسيدات",
    "national rugby union teams": "منتخبات اتحاد رجبي وطنية",
    "international rugby league competitions": "منافسات دوري رجبي دولية",
    "gocomics": "قصص مصورة غو",
    "defunct netball leagues": "دوريات كرة شبكة سابقة",
    "basketball comics": "قصص مصورة كرة سلة",
    "international aquatics competitions": "منافسات رياضات مائية دولية",
    "defunct rugby union leagues": "دوريات اتحاد رجبي سابقة",
    "national lacrosse league": "دوريات لاكروس وطنية",
    "national shooting championships": "بطولات رماية وطنية",
    "national squash teams": "منتخبات اسكواش وطنية",
    "baseball commissioners": "مفوضو كرة قاعدة",
    "national youth basketball teams": "منتخبات كرة سلة وطنية للشباب",
    "men's international basketball": "كرة سلة دولية للرجال",
    "boxing world cup": "كأس العالم للبوكسينغ",
    "national under-21 field hockey teams": "منتخبات هوكي ميدان وطنية تحت 21 سنة",
    "water polo comics": "قصص مصورة كرة ماء",
    "soccer cup competitions": "منافسات كؤوس كرة قدم",
    "australian rules football awards": "جوائز كرة قدم أسترالية",
    "international netball players": "لاعبو كرة شبكة دوليون",
    "international karate competitions": "منافسات كاراتيه دولية",
    "muay thai video games": "ألعاب فيديو موياي تاي",
    "international youth basketball competitions": "منافسات كرة سلة شبابية دولية",
    "national cycling champions": "أبطال بطولات سباق دراجات هوائية وطنية",
    "national junior football teams": "منتخبات كرة قدم وطنية للناشئين",
    "international roller hockey competitions": "منافسات هوكي دحرجة دولية",
    "national under-19 basketball teams": "منتخبات كرة سلة وطنية تحت 19 سنة",
    "multi-national basketball leagues": "دوريات كرة سلة متعددة الجنسيات",
    "outdoor ice hockey": "هوكي جليد في الهواء الطلق",
    "bowling broadcasters": "مذيعو بولينج",
    "first-class cricket": "كريكت من الدرجة الأولى",
    "basketball league": "دوري كرة السلة",
    "under-19 basketball": "كرة سلة تحت 19 سنة",
    "women's softball world cup": "كأس العالم للكرة اللينة للسيدات",
    "badminton world cup": "كأس العالم لتنس الريشة",
    "national youth baseball teams": "منتخبات كرة قاعدة وطنية للشباب",
    "snooker terminology": "مصطلحات سنوكر",
    "ju-jitsu world championships": "بطولة العالم للجوجوتسو",
    "national rugby union premier leagues": "دوريات اتحاد رجبي وطنية من الدرجة الممتازة",
    "wrestling world cup": "كأس العالم للمصارعة",
    "women's international futsal": "كرة صالات دولية للسيدات",
    "national under-20 basketball teams": "منتخبات كرة سلة وطنية تحت 20 سنة",
}


@pytest.mark.parametrize("category, expected_key", data_slow.items(), ids=list(data_slow.keys()))
@pytest.mark.slow
def test_data_slow(category, expected_key) -> None:

    label = get_teams_new(category)
    assert label.strip() == expected_key


def test_get_teams_new():
    # Test with a basic input
    result = get_teams_new("football team")
    assert isinstance(result, str)

    result_empty = get_teams_new("")
    assert isinstance(result_empty, str)

    # Test with various inputs
    result_various = get_teams_new("basketball team")
    assert isinstance(result_various, str)
