# black:skip_file
""" """

import pytest

# from ArWikiCats.new_resolvers.nationalities_resolvers import resolve_nationalities_main
from ArWikiCats.make_bots.countries_formats.for_me import (
    Work_for_me_main,
    Work_for_me,
    Work_for_New_2018_men_Keys_with_all,
)

data_n = {
    "zulu history": "تاريخ زولي",
    "ukrainian descent": "أصل أوكراني",
    "samoan diaspora": "شتات ساموي",
    "peruvian descent": "أصل بيروي",
    "ossetian descent": "أصل أوسيتي",
    "north korean literature": "أدب كوري شمالي",
    "javanese diaspora": "شتات جاوي",
    "japanese folklore": "فلكور ياباني",
    "iraqi diaspora": "شتات عراقي",
    "hungarian diaspora": "شتات مجري",
    "german literature": "أدب ألماني",
    "finnish descent": "أصل فنلندي",
    "coptic calendar": "تقويم قبطي",
    "croatian diaspora": "شتات كرواتي",
    "chilean law": "قانون تشيلي",
    "austrian descent": "أصل نمساوي",
    "Category:Dominican Republic people of Corsican descent": "تصنيف:دومينيكانيون من أصل كورسيكي",
    "Category:20th-century Ghanaian literature": "تصنيف:أدب غاني في القرن 20",
    "Category:20th-century Mexican literature": "تصنيف:أدب مكسيكي في القرن 20",
    "Category:20th-century Taiwanese literature": "تصنيف:أدب تايواني في القرن 20",
    "Category:20th-century Zimbabwean literature": "تصنيف:أدب زيمبابوي في القرن 20",
    "Category:21st-century Ghanaian literature": "تصنيف:أدب غاني في القرن 21",
    "Category:21st-century Moroccan literature": "تصنيف:أدب مغربي في القرن 21",
    "Category:21st-century Taiwanese literature": "تصنيف:أدب تايواني في القرن 21",
    "Category:21st-century Zimbabwean literature": "تصنيف:أدب زيمبابوي في القرن 21"
}

fast_data = [
    {
        "cate": "asian games bronze medalists",
        "nat": "asian",
        "suffix": "games bronze medalists",
        "output": "فائزون بميداليات برونزية في الألعاب الآسيوية",
    },
    {
        "cate": "australian black metal musical groups",
        "nat": "australian",
        "suffix": "black metal musical groups",
        "output": "فرق موسيقى بلاك ميتال أسترالية",
    },
    {"cate": "australian musicals", "nat": "australian", "suffix": "musicals", "output": "مسرحيات غنائية أسترالية"},
    {
        "cate": "australian rugby union",
        "nat": "australian",
        "suffix": "rugby union",
        "output": "اتحاد الرجبي الأسترالي",
    },
    {"cate": "australian tennis", "nat": "australian", "suffix": "tennis", "output": "كرة مضرب أسترالية"},
    {
        "cate": "australian women's ice hockey league",
        "nat": "australian",
        "suffix": "women's ice hockey league",
        "output": "الدوري الأسترالي لهوكي الجليد للسيدات",
    },
    {
        "cate": "azerbaijani encyclopedias",
        "nat": "azerbaijani",
        "suffix": "encyclopedias",
        "output": "موسوعات أذربيجانية",
    },
    {
        "cate": "azerbaijani football club seasons",
        "nat": "azerbaijani",
        "suffix": "football club seasons",
        "output": "مواسم أندية كرة قدم أذربيجانية",
    },
    {
        "cate": "azerbaijani heavy metal musical groups",
        "nat": "azerbaijani",
        "suffix": "heavy metal musical groups",
        "output": "فرق موسيقى هيفي ميتال أذربيجانية",
    },
    {"cate": "bahamian awards", "nat": "bahamian", "suffix": "awards", "output": "جوائز بهامية"},
    {"cate": "bangladesh cinema", "nat": "bangladesh", "suffix": "cinema", "output": "السينما البنغلاديشية"},
    {"cate": "bangladeshi awards", "nat": "bangladeshi", "suffix": "awards", "output": "جوائز بنغلاديشية"},
    {"cate": "bangladeshi companies", "nat": "bangladeshi", "suffix": "companies", "output": "شركات بنغلاديشية"},
    {
        "cate": "bangladeshi folk music",
        "nat": "bangladeshi",
        "suffix": "folk music",
        "output": "موسيقى فلكلورية بنغلاديشية",
    },
    {"cate": "belarusian sport", "nat": "belarusian", "suffix": "sport", "output": "رياضة بيلاروسية"},
    {"cate": "belgian companies", "nat": "belgian", "suffix": "companies", "output": "شركات بلجيكية"},
    {"cate": "belgian detention", "nat": "belgian", "suffix": "detention", "output": "المعتقلات البلجيكية"},
    {"cate": "belgian novels", "nat": "belgian", "suffix": "novels", "output": "روايات بلجيكية"},
    {"cate": "belgian tennis", "nat": "belgian", "suffix": "tennis", "output": "كرة مضرب بلجيكية"},
    {"cate": "beninese sport", "nat": "beninese", "suffix": "sport", "output": "رياضة بنينية"},
    {
        "cate": "bolivian television series",
        "nat": "bolivian",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية بوليفية",
    },
    {"cate": "brazilian design", "nat": "brazilian", "suffix": "design", "output": "تصميم برازيلي"},
    {
        "cate": "brazilian rugby league players",
        "nat": "brazilian",
        "suffix": "rugby league players",
        "output": "لاعبو الدوري البرازيلي للرجبي",
    },
    {
        "cate": "brazilian television series",
        "nat": "brazilian",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية برازيلية",
    },
    {"cate": "brazilian tennis", "nat": "brazilian", "suffix": "tennis", "output": "كرة مضرب برازيلية"},
    {
        "cate": "british black metal musical groups",
        "nat": "british",
        "suffix": "black metal musical groups",
        "output": "فرق موسيقى بلاك ميتال بريطانية",
    },
    {"cate": "british descent", "nat": "british", "suffix": "descent", "output": "أصل بريطاني"},
    {
        "cate": "british international schools",
        "nat": "british",
        "suffix": "international schools",
        "output": "مدارس دولية بريطانية",
    },
    {
        "cate": "british medical association",
        "nat": "british",
        "suffix": "medical association",
        "output": "الجمعية الطبية البريطانية",
    },
    {"cate": "british music", "nat": "british", "suffix": "music", "output": "موسيقى بريطانية"},
    {"cate": "british plays", "nat": "british", "suffix": "plays", "output": "مسرحيات بريطانية"},
    {"cate": "british restaurants", "nat": "british", "suffix": "restaurants", "output": "مطاعم بريطانية"},
    {"cate": "british rugby union", "nat": "british", "suffix": "rugby union", "output": "اتحاد الرجبي البريطاني"},
    {"cate": "british women's sport", "nat": "british", "suffix": "women's sport", "output": "رياضة بريطانية نسائية"},
    {"cate": "bulgarian cup", "nat": "bulgarian", "suffix": "cup", "output": "كأس بلغاريا"},
    {"cate": "burkinabe design", "nat": "burkinabe", "suffix": "design", "output": "تصميم بوركينابي"},
    {"cate": "burmese sport", "nat": "burmese", "suffix": "sport", "output": "رياضة بورمية"},
    {"cate": "cambodian sport", "nat": "cambodian", "suffix": "sport", "output": "رياضة كمبودية"},
    {"cate": "cameroonian football", "nat": "cameroonian", "suffix": "football", "output": "كرة القدم الكاميرونية"},
    {
        "cate": "canadian contemporary r&b musical groups",
        "nat": "canadian",
        "suffix": "contemporary r&b musical groups",
        "output": "فرق موسيقى آر أند بي معاصر كندية",
    },
    {"cate": "canadian journalism", "nat": "canadian", "suffix": "journalism", "output": "صحافة كندية"},
    {"cate": "canadian magazines", "nat": "canadian", "suffix": "magazines", "output": "مجلات كندية"},
    {"cate": "canadian military", "nat": "canadian", "suffix": "military", "output": "الجيش الكندي"},
    {"cate": "canadian sports", "nat": "canadian", "suffix": "sports", "output": "رياضة كندية"},
    {"cate": "cape verdean awards", "nat": "cape verdean", "suffix": "awards", "output": "جوائز رأس أخضرية"},
    {
        "cate": "central american cinema",
        "nat": "central american",
        "suffix": "cinema",
        "output": "السينما الأمريكية الأوسطية",
    },
    {"cate": "chilean football", "nat": "chilean", "suffix": "football", "output": "كرة القدم التشيلية"},
    {"cate": "chilean navy", "nat": "chilean", "suffix": "navy", "output": "البحرية التشيلية"},
    {"cate": "chilean sport", "nat": "chilean", "suffix": "sport", "output": "رياضة تشيلية"},
    {"cate": "chilean tennis", "nat": "chilean", "suffix": "tennis", "output": "كرة مضرب تشيلية"},
    {
        "cate": "chinese australian culture",
        "nat": "chinese",
        "suffix": "australian culture",
        "output": "ثقافة أسترالية صينية",
    },
    {"cate": "chinese businesspeople", "nat": "chinese", "suffix": "businesspeople", "output": "شخصيات أعمال صينية"},
    {"cate": "chinese cookbooks", "nat": "chinese", "suffix": "cookbooks", "output": "كتب طبخ صينية"},
    {"cate": "chinese motorsport", "nat": "chinese", "suffix": "motorsport", "output": "رياضة محركات صينية"},
    {"cate": "chinese sport", "nat": "chinese", "suffix": "sport", "output": "رياضة صينية"},
    {
        "cate": "christian radio stations",
        "nat": "christian",
        "suffix": "radio stations",
        "output": "محطات إذاعية مسيحية",
    },
    {"cate": "comorian football", "nat": "comorian", "suffix": "football", "output": "كرة القدم القمرية"},
    {"cate": "congolese movement", "nat": "congolese", "suffix": "movement", "output": "الحركة الكونغوية"},
    {"cate": "corsican descent", "nat": "corsican", "suffix": "descent", "output": "أصل كورسيكي"},
    {
        "cate": "croatian television people",
        "nat": "croatian",
        "suffix": "television people",
        "output": "شخصيات التلفزة الكرواتية",
    },
    {"cate": "croatian war crimes", "nat": "croatian", "suffix": "war crimes", "output": "جرائم حرب كرواتية"},
    {"cate": "cypriot descent", "nat": "cypriot", "suffix": "descent", "output": "أصل قبرصي"},
    {"cate": "cypriot football", "nat": "cypriot", "suffix": "football", "output": "كرة القدم القبرصية"},
    {"cate": "czech air force", "nat": "czech", "suffix": "air force", "output": "القوات الجوية التشيكية"},
    {"cate": "czech politics", "nat": "czech", "suffix": "politics", "output": "السياسة التشيكية"},
    {
        "cate": "czech rock music groups",
        "nat": "czech",
        "suffix": "rock music groups",
        "output": "فرق موسيقى الروك تشيكية",
    },
    {
        "cate": "czechoslovak television",
        "nat": "czechoslovak",
        "suffix": "television",
        "output": "التلفزة التشيكوسلوفاكية",
    },
    {
        "cate": "danish american culture",
        "nat": "danish",
        "suffix": "american culture",
        "output": "ثقافة أمريكية دنماركية",
    },
    {"cate": "danish football", "nat": "danish", "suffix": "football", "output": "كرة القدم الدنماركية"},
    {"cate": "danish islands", "nat": "danish", "suffix": "islands", "output": "جزر دنماركية"},
    {"cate": "danish sport", "nat": "danish", "suffix": "sport", "output": "رياضة دنماركية"},
    {"cate": "danish television", "nat": "danish", "suffix": "television", "output": "التلفزة الدنماركية"},
    {"cate": "dominican culture", "nat": "dominican", "suffix": "culture", "output": "ثقافة دومينيكية"},
    {"cate": "dutch diaspora", "nat": "dutch", "suffix": "diaspora", "output": "شتات هولندي"},
    {"cate": "dutch jewish culture", "nat": "dutch", "suffix": "jewish culture", "output": "ثقافة يهودية هولندية"},
    {"cate": "dutch jews", "nat": "dutch", "suffix": "jews", "output": "يهود هولنديون"},
    {"cate": "dutch novels", "nat": "dutch", "suffix": "novels", "output": "روايات هولندية"},
    {"cate": "ecuadorian descent", "nat": "ecuadorian", "suffix": "descent", "output": "أصل إكوادوري"},
    {"cate": "egyptian league", "nat": "egyptian", "suffix": "league", "output": "الدوري المصري"},
    {"cate": "emirati motorsport", "nat": "emirati", "suffix": "motorsport", "output": "رياضة محركات إماراتية"},
    {
        "cate": "english football league",
        "nat": "english",
        "suffix": "football league",
        "output": "الدوري الإنجليزي لكرة القدم",
    },
    {
        "cate": "english gothic architecture",
        "nat": "english",
        "suffix": "gothic architecture",
        "output": "عمارة قوطية إنجليزية",
    },
    {"cate": "english rugby league", "nat": "english", "suffix": "rugby league", "output": "الدوري الإنجليزي للرجبي"},
    {"cate": "english women's sport", "nat": "english", "suffix": "women's sport", "output": "رياضة إنجليزية نسائية"},
    {"cate": "equatoguinean sport", "nat": "equatoguinean", "suffix": "sport", "output": "رياضة غينية استوائية"},
    {"cate": "estonian sport", "nat": "estonian", "suffix": "sport", "output": "رياضة إستونية"},
    {"cate": "ethiopian sport", "nat": "ethiopian", "suffix": "sport", "output": "رياضة إثيوبية"},
    {"cate": "european american", "nat": "european", "suffix": "american", "output": "أمريكيون أوروبيون"},
    {"cate": "european border", "nat": "european", "suffix": "border", "output": "حدود أوروبية"},
    {
        "cate": "european games silver medalists",
        "nat": "european",
        "suffix": "games silver medalists",
        "output": "فائزون بميداليات فضية في الألعاب الأوروبية",
    },
    {"cate": "european jewish descent", "nat": "european", "suffix": "jewish descent", "output": "أصل يهودي أوروبي"},
    {"cate": "european music", "nat": "european", "suffix": "music", "output": "موسيقى أوروبية"},
    {
        "cate": "european political websites",
        "nat": "european",
        "suffix": "political websites",
        "output": "مواقع ويب سياسية أوروبية",
    },
    {"cate": "fijian football", "nat": "fijian", "suffix": "football", "output": "كرة القدم الفيجية"},
    {"cate": "filipino descent", "nat": "filipino", "suffix": "descent", "output": "أصل فلبيني"},
    {
        "cate": "finnish awards and decorations",
        "nat": "finnish",
        "suffix": "awards and decorations",
        "output": "جوائز وأوسمة فنلندية",
    },
    {"cate": "finnish navy", "nat": "finnish", "suffix": "navy", "output": "البحرية الفنلندية"},
    {"cate": "finnish novels", "nat": "finnish", "suffix": "novels", "output": "روايات فنلندية"},
    {"cate": "finnish sport", "nat": "finnish", "suffix": "sport", "output": "رياضة فنلندية"},
    {
        "cate": "finnish television series",
        "nat": "finnish",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية فنلندية",
    },
    {"cate": "french cinema", "nat": "french", "suffix": "cinema", "output": "السينما الفرنسية"},
    {"cate": "french descent", "nat": "french", "suffix": "descent", "output": "أصل فرنسي"},
    {"cate": "french legal films", "nat": "french", "suffix": "legal films", "output": "أفلام قانونية فرنسية"},
    {"cate": "french motorsport", "nat": "french", "suffix": "motorsport", "output": "رياضة محركات فرنسية"},
    {"cate": "french mythology", "nat": "french", "suffix": "mythology", "output": "أساطير فرنسية"},
    {"cate": "french navy", "nat": "french", "suffix": "navy", "output": "البحرية الفرنسية"},
    {"cate": "french rugby league", "nat": "french", "suffix": "rugby league", "output": "الدوري الفرنسي للرجبي"},
    {"cate": "french rugby union", "nat": "french", "suffix": "rugby union", "output": "اتحاد الرجبي الفرنسي"},
    {"cate": "french sport", "nat": "french", "suffix": "sport", "output": "رياضة فرنسية"},
    {"cate": "french war crimes", "nat": "french", "suffix": "war crimes", "output": "جرائم حرب فرنسية"},
    {"cate": "german motorsport", "nat": "german", "suffix": "motorsport", "output": "رياضة محركات ألمانية"},
    {"cate": "german music", "nat": "german", "suffix": "music", "output": "موسيقى ألمانية"},
    {"cate": "german romanian descent", "nat": "german", "suffix": "romanian descent", "output": "أصل روماني ألماني"},
    {"cate": "german women's sport", "nat": "german", "suffix": "women's sport", "output": "رياضة ألمانية نسائية"},
    {"cate": "gothic architecture", "nat": "gothic", "suffix": "architecture", "output": "عمارة قوطية"},
    {"cate": "greek companies", "nat": "greek", "suffix": "companies", "output": "شركات يونانية"},
    {"cate": "greek descent", "nat": "greek", "suffix": "descent", "output": "أصل يوناني"},
    {"cate": "greek novels", "nat": "greek", "suffix": "novels", "output": "روايات يونانية"},
    {"cate": "greek organized crime", "nat": "greek", "suffix": "organized crime", "output": "جريمة منظمة يونانية"},
    {"cate": "greek poems", "nat": "greek", "suffix": "poems", "output": "قصائد يونانية"},
    {"cate": "greek women's sport", "nat": "greek", "suffix": "women's sport", "output": "رياضة يونانية نسائية"},
    {"cate": "greenlandic sport", "nat": "greenlandic", "suffix": "sport", "output": "رياضة جرينلاندية"},
    {"cate": "guamanian football", "nat": "guamanian", "suffix": "football", "output": "كرة القدم الغوامية"},
    {"cate": "guatemalan diaspora", "nat": "guatemalan", "suffix": "diaspora", "output": "شتات غواتيمالي"},
    {
        "cate": "guatemalan musical instruments",
        "nat": "guatemalan",
        "suffix": "musical instruments",
        "output": "آلات موسيقية غواتيمالية",
    },
    {"cate": "gujarati films", "nat": "gujarati", "suffix": "films", "output": "أفلام غجراتية"},
    {"cate": "hong kong descent", "nat": "hong kong", "suffix": "descent", "output": "أصل هونغ كونغي"},
    {"cate": "hong kong fa cup", "nat": "hong kong", "suffix": "fa cup", "output": "كأس الاتحاد الهونغ الكونغي"},
    {"cate": "hong kong sport", "nat": "hong kong", "suffix": "sport", "output": "رياضة هونغ كونغية"},
    {"cate": "hungarian sport", "nat": "hungarian", "suffix": "sport", "output": "رياضة مجرية"},
    {"cate": "hungarian women's sport", "nat": "hungarian", "suffix": "women's sport", "output": "رياضة مجرية نسائية"},
    {"cate": "icelandic descent", "nat": "icelandic", "suffix": "descent", "output": "أصل آيسلندي"},
    {"cate": "indian descent", "nat": "indian", "suffix": "descent", "output": "أصل هندي"},
    {"cate": "indian federation cup", "nat": "indian", "suffix": "federation cup", "output": "كأس الاتحاد الهندي"},
    {
        "cate": "indian funk musical groups",
        "nat": "indian",
        "suffix": "funk musical groups",
        "output": "فرق موسيقى فانك هندية",
    },
    {"cate": "indian literature", "nat": "indian", "suffix": "literature", "output": "أدب هندي"},
    {"cate": "indian politics", "nat": "indian", "suffix": "politics", "output": "السياسة الهندية"},
    {
        "cate": "indonesian rock music groups",
        "nat": "indonesian",
        "suffix": "rock music groups",
        "output": "فرق موسيقى الروك إندونيسية",
    },
    {"cate": "indonesian websites", "nat": "indonesian", "suffix": "websites", "output": "مواقع ويب إندونيسية"},
    {"cate": "iranian jews", "nat": "iranian", "suffix": "jews", "output": "يهود إيرانيون"},
    {
        "cate": "iranian television series",
        "nat": "iranian",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية إيرانية",
    },
    {"cate": "iraqi descent", "nat": "iraqi", "suffix": "descent", "output": "أصل عراقي"},
    {"cate": "irish american gangs", "nat": "irish", "suffix": "american gangs", "output": "عصابات أمريكية أيرلندية"},
    {"cate": "irish films", "nat": "irish", "suffix": "films", "output": "أفلام أيرلندية"},
    {"cate": "irish folklore", "nat": "irish", "suffix": "folklore", "output": "فلكور أيرلندي"},
    {
        "cate": "irish general election",
        "nat": "irish",
        "suffix": "general election",
        "output": "الانتخابات العامة الأيرلندية",
    },
    {"cate": "israeli brands", "nat": "israeli", "suffix": "brands", "output": "ماركات إسرائيلية"},
    {"cate": "israeli sport", "nat": "israeli", "suffix": "sport", "output": "رياضة إسرائيلية"},
    {"cate": "israeli women's sport", "nat": "israeli", "suffix": "women's sport", "output": "رياضة إسرائيلية نسائية"},
    {
        "cate": "italian canadian culture",
        "nat": "italian",
        "suffix": "canadian culture",
        "output": "ثقافة كندية إيطالية",
    },
    {"cate": "italian rugby union", "nat": "italian", "suffix": "rugby union", "output": "اتحاد الرجبي الإيطالي"},
    {"cate": "italian tennis", "nat": "italian", "suffix": "tennis", "output": "كرة مضرب إيطالية"},
    {"cate": "jamaican brands", "nat": "jamaican", "suffix": "brands", "output": "ماركات جامايكية"},
    {"cate": "japanese americans", "nat": "japanese", "suffix": "americans", "output": "أمريكيون يابانيون"},
    {"cate": "japanese army", "nat": "japanese", "suffix": "army", "output": "الجيش الياباني"},
    {"cate": "japanese companies", "nat": "japanese", "suffix": "companies", "output": "شركات يابانية"},
    {"cate": "japanese descent", "nat": "japanese", "suffix": "descent", "output": "أصل ياباني"},
    {
        "cate": "japanese indie pop groups",
        "nat": "japanese",
        "suffix": "indie pop groups",
        "output": "فرق إيندي بوب يابانية",
    },
    {"cate": "japanese music", "nat": "japanese", "suffix": "music", "output": "موسيقى يابانية"},
    {"cate": "japanese politics", "nat": "japanese", "suffix": "politics", "output": "السياسة اليابانية"},
    {"cate": "japanese sport", "nat": "japanese", "suffix": "sport", "output": "رياضة يابانية"},
    {"cate": "jewish american people", "nat": "jewish", "suffix": "american people", "output": "أمريكيون يهود"},
    {
        "cate": "jewish american television series",
        "nat": "jewish",
        "suffix": "american television series",
        "output": "مسلسلات تلفزيونية أمريكية يهودية",
    },
    {
        "cate": "jewish american tennis",
        "nat": "jewish",
        "suffix": "american tennis",
        "output": "كرة مضرب أمريكية يهودية",
    },
    {"cate": "jewish manuscripts", "nat": "jewish", "suffix": "manuscripts", "output": "مخطوطات يهودية"},
    {"cate": "jordanian football", "nat": "jordanian", "suffix": "football", "output": "كرة القدم الأردنية"},
    {"cate": "kazakh brands", "nat": "kazakh", "suffix": "brands", "output": "ماركات كازاخية"},
    {"cate": "kazakhstani descent", "nat": "kazakhstani", "suffix": "descent", "output": "أصل كازاخستاني"},
    {"cate": "kenyan novels", "nat": "kenyan", "suffix": "novels", "output": "روايات كينية"},
    {
        "cate": "kenyan television series",
        "nat": "kenyan",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية كينية",
    },
    {"cate": "korean american culture", "nat": "korean", "suffix": "american culture", "output": "ثقافة أمريكية كورية"},
    {"cate": "korean businesspeople", "nat": "korean", "suffix": "businesspeople", "output": "شخصيات أعمال كورية"},
    {
        "cate": "korean international schools",
        "nat": "korean",
        "suffix": "international schools",
        "output": "مدارس دولية كورية",
    },
    {"cate": "kurdish folklore", "nat": "kurdish", "suffix": "folklore", "output": "فلكور كردي"},
    {"cate": "kyrgyzstani football", "nat": "kyrgyzstani", "suffix": "football", "output": "كرة القدم القيرغيزستانية"},
    {
        "cate": "lebanese federation cup",
        "nat": "lebanese",
        "suffix": "federation cup",
        "output": "كأس الاتحاد اللبناني",
    },
    {"cate": "lithuanian art", "nat": "lithuanian", "suffix": "art", "output": "فن ليتواني"},
    {"cate": "luxembourgian sport", "nat": "luxembourgian", "suffix": "sport", "output": "رياضة لوكسمبورغية"},
    {
        "cate": "luxembourgish inventions",
        "nat": "luxembourgish",
        "suffix": "inventions",
        "output": "اختراعات لوكسمبورغية",
    },
    {
        "cate": "malagasy world music groups",
        "nat": "malagasy",
        "suffix": "world music groups",
        "output": "فرق موسيقى العالم مدغشقرية",
    },
    {"cate": "malaysian football", "nat": "malaysian", "suffix": "football", "output": "كرة القدم الماليزية"},
    {"cate": "malaysian sport", "nat": "malaysian", "suffix": "sport", "output": "رياضة ماليزية"},
    {"cate": "maldivian descent", "nat": "maldivian", "suffix": "descent", "output": "أصل مالديفي"},
    {"cate": "mexican businesspeople", "nat": "mexican", "suffix": "businesspeople", "output": "شخصيات أعمال مكسيكية"},
    {"cate": "mexican motorsport", "nat": "mexican", "suffix": "motorsport", "output": "رياضة محركات مكسيكية"},
    {"cate": "mexican novels", "nat": "mexican", "suffix": "novels", "output": "روايات مكسيكية"},
    {"cate": "mexican politics", "nat": "mexican", "suffix": "politics", "output": "السياسة المكسيكية"},
    {"cate": "mexican sports", "nat": "mexican", "suffix": "sports", "output": "رياضة مكسيكية"},
    {
        "cate": "mexican television series",
        "nat": "mexican",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية مكسيكية",
    },
    {"cate": "montserratian descent", "nat": "montserratian", "suffix": "descent", "output": "أصل مونتسراتي"},
    {"cate": "monégasque sport", "nat": "monégasque", "suffix": "sport", "output": "رياضة موناكية"},
    {"cate": "moroccan army", "nat": "moroccan", "suffix": "army", "output": "الجيش المغربي"},
    {"cate": "native american films", "nat": "native american", "suffix": "films", "output": "أفلام أمريكية أصلية"},
    {"cate": "nicaraguan football", "nat": "nicaraguan", "suffix": "football", "output": "كرة القدم النيكاراغوية"},
    {"cate": "nigerian sport", "nat": "nigerian", "suffix": "sport", "output": "رياضة نيجيرية"},
    {
        "cate": "north american hockey league",
        "nat": "north american",
        "suffix": "hockey league",
        "output": "الدوري الأمريكي الشمالي للهوكي",
    },
    {
        "cate": "north american soccer league",
        "nat": "north american",
        "suffix": "soccer league",
        "output": "الدوري الأمريكي الشمالي لكرة القدم",
    },
    {"cate": "north american sport", "nat": "north american", "suffix": "sport", "output": "رياضة أمريكية شمالية"},
    {
        "cate": "norwegian military academy",
        "nat": "norwegian",
        "suffix": "military academy",
        "output": "الأكاديمية العسكرية النرويجية",
    },
    {"cate": "norwegian music", "nat": "norwegian", "suffix": "music", "output": "موسيقى نرويجية"},
    {"cate": "oceanian rugby union", "nat": "oceanian", "suffix": "rugby union", "output": "اتحاد الرجبي الأوقيانوسي"},
    {"cate": "ossetian diaspora", "nat": "ossetian", "suffix": "diaspora", "output": "شتات أوسيتي"},
    {"cate": "pakistani descent", "nat": "pakistani", "suffix": "descent", "output": "أصل باكستاني"},
    {"cate": "pakistani law", "nat": "pakistani", "suffix": "law", "output": "قانون باكستاني"},
    {"cate": "pakistani politics", "nat": "pakistani", "suffix": "politics", "output": "السياسة الباكستانية"},
    {"cate": "pakistani sport", "nat": "pakistani", "suffix": "sport", "output": "رياضة باكستانية"},
    {"cate": "pakistani television", "nat": "pakistani", "suffix": "television", "output": "التلفزة الباكستانية"},
    {"cate": "palestinian organizations", "nat": "palestinian", "suffix": "organizations", "output": "منظمات فلسطينية"},
    {"cate": "paraguayan films", "nat": "paraguayan", "suffix": "films", "output": "أفلام بارغوايانية"},
    {"cate": "peruvian sport", "nat": "peruvian", "suffix": "sport", "output": "رياضة بيروية"},
    {
        "cate": "peruvian television series",
        "nat": "peruvian",
        "suffix": "television series",
        "output": "مسلسلات تلفزيونية بيروية",
    },
    {"cate": "peruvian television", "nat": "peruvian", "suffix": "television", "output": "التلفزة البيروية"},
    {"cate": "philippine revolution", "nat": "philippine", "suffix": "revolution", "output": "الثورة الفلبينية"},
    {
        "cate": "polish biographical dictionaries",
        "nat": "polish",
        "suffix": "biographical dictionaries",
        "output": "قواميس سير ذاتية بولندية",
    },
    {"cate": "polish companies", "nat": "polish", "suffix": "companies", "output": "شركات بولندية"},
    {"cate": "polish football", "nat": "polish", "suffix": "football", "output": "كرة القدم البولندية"},
    {"cate": "polish jews", "nat": "polish", "suffix": "jews", "output": "يهود بولنديون"},
    {"cate": "polish music", "nat": "polish", "suffix": "music", "output": "موسيقى بولندية"},
    {"cate": "polish sport", "nat": "polish", "suffix": "sport", "output": "رياضة بولندية"},
    {"cate": "polish television", "nat": "polish", "suffix": "television", "output": "التلفزة البولندية"},
    {"cate": "portuguese companies", "nat": "portuguese", "suffix": "companies", "output": "شركات برتغالية"},
    {"cate": "portuguese motorsport", "nat": "portuguese", "suffix": "motorsport", "output": "رياضة محركات برتغالية"},
    {"cate": "portuguese sport", "nat": "portuguese", "suffix": "sport", "output": "رياضة برتغالية"},
    {"cate": "puerto rican brands", "nat": "puerto rican", "suffix": "brands", "output": "ماركات بورتوريكية"},
    {
        "cate": "qatari musical instruments",
        "nat": "qatari",
        "suffix": "musical instruments",
        "output": "آلات موسيقية قطرية",
    },
    {"cate": "romanian tennis", "nat": "romanian", "suffix": "tennis", "output": "كرة مضرب رومانية"},
    {"cate": "russian journalism", "nat": "russian", "suffix": "journalism", "output": "صحافة روسية"},
    {"cate": "russian literature", "nat": "russian", "suffix": "literature", "output": "أدب روسي"},
    {"cate": "russian revolution", "nat": "russian", "suffix": "revolution", "output": "الثورة الروسية"},
    {"cate": "russian rugby union", "nat": "russian", "suffix": "rugby union", "output": "اتحاد الرجبي الروسي"},
    {"cate": "russian songs", "nat": "russian", "suffix": "songs", "output": "أغاني روسية"},
    {"cate": "samoan islands", "nat": "samoan", "suffix": "islands", "output": "جزر ساموية"},
    {
        "cate": "saudiarabian black metal musical groups",
        "nat": "saudiarabian",
        "suffix": "black metal musical groups",
        "output": "فرق موسيقى بلاك ميتال سعودية",
    },
    {"cate": "saudiarabian motorsport", "nat": "saudiarabian", "suffix": "motorsport", "output": "رياضة محركات سعودية"},
    {
        "cate": "scottish businesspeople",
        "nat": "scottish",
        "suffix": "businesspeople",
        "output": "شخصيات أعمال إسكتلندية",
    },
    {"cate": "scottish television", "nat": "scottish", "suffix": "television", "output": "التلفزة الإسكتلندية"},
    {"cate": "sierra leonean sport", "nat": "sierra leonean", "suffix": "sport", "output": "رياضة سيراليونية"},
    {"cate": "singaporean art", "nat": "singaporean", "suffix": "art", "output": "فن سنغافوري"},
    {"cate": "singaporean descent", "nat": "singaporean", "suffix": "descent", "output": "أصل سنغافوري"},
    {
        "cate": "singaporean media personalities",
        "nat": "singaporean",
        "suffix": "media personalities",
        "output": "شخصيات إعلامية سنغافورية",
    },
    {"cate": "singaporean plays", "nat": "singaporean", "suffix": "plays", "output": "مسرحيات سنغافورية"},
    {"cate": "slovak music", "nat": "slovak", "suffix": "music", "output": "موسيقى سلوفاكية"},
    {"cate": "slovenian novels", "nat": "slovenian", "suffix": "novels", "output": "روايات سلوفينية"},
    {
        "cate": "slovenian rock music groups",
        "nat": "slovenian",
        "suffix": "rock music groups",
        "output": "فرق موسيقى الروك سلوفينية",
    },
    {"cate": "south african sport", "nat": "south african", "suffix": "sport", "output": "رياضة جنوبية إفريقية"},
    {"cate": "south american descent", "nat": "south american", "suffix": "descent", "output": "أصل أمريكي جنوبي"},
    {
        "cate": "south american rugby union",
        "nat": "south american",
        "suffix": "rugby union",
        "output": "اتحاد الرجبي الأمريكي الجنوبي",
    },
    {"cate": "south american sport", "nat": "south american", "suffix": "sport", "output": "رياضة أمريكية جنوبية"},
    {"cate": "south korean sport", "nat": "south korean", "suffix": "sport", "output": "رياضة كورية جنوبية"},
    {"cate": "soviet football", "nat": "soviet", "suffix": "football", "output": "كرة القدم السوفيتية"},
    {"cate": "soviet musical groups", "nat": "soviet", "suffix": "musical groups", "output": "مجموعات موسيقية سوفيتية"},
    {"cate": "soviet navy", "nat": "soviet", "suffix": "navy", "output": "البحرية السوفيتية"},
    {"cate": "spanish companies", "nat": "spanish", "suffix": "companies", "output": "شركات إسبانية"},
    {"cate": "spanish diaspora", "nat": "spanish", "suffix": "diaspora", "output": "شتات إسباني"},
    {"cate": "spanish tennis", "nat": "spanish", "suffix": "tennis", "output": "كرة مضرب إسبانية"},
    {"cate": "sri lankan novels", "nat": "sri lankan", "suffix": "novels", "output": "روايات سريلانكية"},
    {"cate": "sri lankan television", "nat": "sri lankan", "suffix": "television", "output": "التلفزة السريلانكية"},
    {"cate": "sudanese jews", "nat": "sudanese", "suffix": "jews", "output": "يهود سودانيون"},
    {"cate": "swedish inventions", "nat": "swedish", "suffix": "inventions", "output": "اختراعات سويدية"},
    {"cate": "swedish novels", "nat": "swedish", "suffix": "novels", "output": "روايات سويدية"},
    {"cate": "swedish plays", "nat": "swedish", "suffix": "plays", "output": "مسرحيات سويدية"},
    {"cate": "swedish ska groups", "nat": "swedish", "suffix": "ska groups", "output": "فرق سكا سويدية"},
    {"cate": "swedish war", "nat": "swedish", "suffix": "war", "output": "الحرب السويدية"},
    {"cate": "swiss books", "nat": "swiss", "suffix": "books", "output": "كتب سويسرية"},
    {"cate": "swiss detention", "nat": "swiss", "suffix": "detention", "output": "المعتقلات السويسرية"},
    {"cate": "swiss grand prix", "nat": "swiss", "suffix": "grand prix", "output": "جائزة سويسرا الكبرى"},
    {"cate": "swiss websites", "nat": "swiss", "suffix": "websites", "output": "مواقع ويب سويسرية"},
    {"cate": "syrian navy", "nat": "syrian", "suffix": "navy", "output": "البحرية السورية"},
    {
        "cate": "syrian rock music groups",
        "nat": "syrian",
        "suffix": "rock music groups",
        "output": "فرق موسيقى الروك سورية",
    },
    {"cate": "syrian sport", "nat": "syrian", "suffix": "sport", "output": "رياضة سورية"},
    {
        "cate": "tajikistani rock music groups",
        "nat": "tajikistani",
        "suffix": "rock music groups",
        "output": "فرق موسيقى الروك طاجيكستانية",
    },
    {"cate": "tamil diaspora", "nat": "tamil", "suffix": "diaspora", "output": "شتات تاميلي"},
    {"cate": "tanzanian brands", "nat": "tanzanian", "suffix": "brands", "output": "ماركات تنزانية"},
    {"cate": "tanzanian sport", "nat": "tanzanian", "suffix": "sport", "output": "رياضة تنزانية"},
    {"cate": "thai diaspora", "nat": "thai", "suffix": "diaspora", "output": "شتات تايلندي"},
    {"cate": "thai families", "nat": "thai", "suffix": "families", "output": "عائلات تايلندية"},
    {"cate": "thai films", "nat": "thai", "suffix": "films", "output": "أفلام تايلندية"},
    {"cate": "turkish awards", "nat": "turkish", "suffix": "awards", "output": "جوائز تركية"},
    {"cate": "turkish kurdish people", "nat": "turkish", "suffix": "kurdish people", "output": "أكراد أتراك"},
    {"cate": "tuvaluan football", "nat": "tuvaluan", "suffix": "football", "output": "كرة القدم التوفالية"},
    {"cate": "ugandan television", "nat": "ugandan", "suffix": "television", "output": "التلفزة الأوغندية"},
    {"cate": "ukrainian diaspora", "nat": "ukrainian", "suffix": "diaspora", "output": "شتات أوكراني"},
    {"cate": "ukrainian films", "nat": "ukrainian", "suffix": "films", "output": "أفلام أوكرانية"},
    {"cate": "ukrainian sport", "nat": "ukrainian", "suffix": "sport", "output": "رياضة أوكرانية"},
    {"cate": "ukrainian television", "nat": "ukrainian", "suffix": "television", "output": "التلفزة الأوكرانية"},
    {"cate": "ukrainian works", "nat": "ukrainian", "suffix": "works", "output": "أعمال أوكرانية"},
    {"cate": "uruguayan tennis", "nat": "uruguayan", "suffix": "tennis", "output": "كرة مضرب أوروغويانية"},
    {"cate": "uruguayan war", "nat": "uruguayan", "suffix": "war", "output": "الحرب الأوروغويانية"},
    {"cate": "uzbekistani films", "nat": "uzbekistani", "suffix": "films", "output": "أفلام أوزبكستانية"},
    {"cate": "venezuelan spanish", "nat": "venezuelan", "suffix": "spanish", "output": "إسبان فنزويليون"},
    {"cate": "venezuelan sport", "nat": "venezuelan", "suffix": "sport", "output": "رياضة فنزويلية"},
    {"cate": "venezuelan television", "nat": "venezuelan", "suffix": "television", "output": "التلفزة الفنزويلية"},
    {"cate": "vietnamese companies", "nat": "vietnamese", "suffix": "companies", "output": "شركات فيتنامية"},
    {
        "cate": "vietnamese women's sport",
        "nat": "vietnamese",
        "suffix": "women's sport",
        "output": "رياضة فيتنامية نسائية",
    },
    {"cate": "welsh descent", "nat": "welsh", "suffix": "descent", "output": "أصل ويلزي"},
    {"cate": "welsh rugby league", "nat": "welsh", "suffix": "rugby league", "output": "الدوري الويلزي للرجبي"},
    {"cate": "welsh sport", "nat": "welsh", "suffix": "sport", "output": "رياضة ويلزية"},
    {"cate": "yemeni descent", "nat": "yemeni", "suffix": "descent", "output": "أصل يمني"},
    {"cate": "yemeni sport", "nat": "yemeni", "suffix": "sport", "output": "رياضة يمنية"},
    {"cate": "yoruba descent", "nat": "yoruba", "suffix": "descent", "output": "أصل يوروبي"},
    {"cate": "yugoslav descent", "nat": "yugoslav", "suffix": "descent", "output": "أصل يوغسلافي"},
    {"cate": "yugoslav sport", "nat": "yugoslav", "suffix": "sport", "output": "رياضة يوغسلافية"},
    {"cate": "zimbabwean companies", "nat": "zimbabwean", "suffix": "companies", "output": "شركات زيمبابوية"},
    {"cate": "zimbabwean descent", "nat": "zimbabwean", "suffix": "descent", "output": "أصل زيمبابوي"},
    {
        "cate": "zimbabwean general election",
        "nat": "zimbabwean",
        "suffix": "general election",
        "output": "الانتخابات العامة الزيمبابوية",
    },
]


@pytest.mark.parametrize("data", fast_data, ids=lambda x: x["cate"])
@pytest.mark.fast
def test_fast_data(data: dict[str, str]) -> None:
    # label1 = Work_for_me(data["cate"], data["nat"], data["suffix"])
    label1 = Work_for_me_main(data["cate"])
    assert label1 == data["output"]

    # label2 = resolve_by_nats(data["cate"])
    # assert label2 == data["output"]
