"""
Tests
"""

import pytest

from ArWikiCats.make_bots.jobs_bots.get_helps import get_suffix

data_contries_from_nat = {
    "afghanistan national football team managers": ("national football team managers", "afghanistan"),
    "argentina women's international footballers": ("women's international footballers", "argentina"),
    "australia international soccer players": ("international soccer players", "australia"),
    "australia national women's wheelchair basketball team": (
        "national women's wheelchair basketball team",
        "australia",
    ),
    "canada men's international soccer players": ("men's international soccer players", "canada"),
    "england amateur international footballers": ("amateur international footballers", "england"),
    "georgia (country)": ("(country)", "georgia"),
    "georgia (u.s. state)": ("(u.s. state)", "georgia"),
    "new zealand wheelchair racers": ("wheelchair racers", "new zealand"),
    "new zealand wheelchair rugby players": ("wheelchair rugby players", "new zealand"),
    "new zealand wheelchair rugby": ("wheelchair rugby", "new zealand"),
    "south africa international soccer players": ("international soccer players", "south africa"),
    "united kingdom from aden": ("from aden", "united kingdom"),
    "united states by state": ("by state", "united states"),
}


@pytest.mark.parametrize("category, expected", data_contries_from_nat.items(), ids=lambda x: x[0])
def test_contries_from_nat(category, expected) -> None:
    # Test with a valid category and nat
    result = get_suffix(category, "contries_from_nat")
    assert result == expected


def test_get_suffix() -> None:
    # Test with an empty list of keys (should return empty tuple)
    result = get_suffix("test category", "nat")
    assert isinstance(result, tuple)
    assert len(result) == 2
    assert isinstance(result[0], str)
    assert isinstance(result[1], str)


data_religions = {
    "anglican abidat rma pianists": ("abidat rma pianists", "anglican"),
    "anglican abidat rma record producers": ("abidat rma record producers", "anglican"),
    "anglican abidat rma saxophonists": ("abidat rma saxophonists", "anglican"),
    "anglican abidat rma singer-songwriters": ("abidat rma singer-songwriters", "anglican"),
    "anglican classical europop cheerleaders": ("classical europop cheerleaders", "anglican"),
    "anglican classical europop composers": ("classical europop composers", "anglican"),
    "anglican convicted-of-murder": ("convicted-of-murder", "anglican"),
    "anglican expatriates": ("expatriates", "anglican"),
    "anglican historical house music bloggers": ("historical house music bloggers", "anglican"),
    "anglican historical objectivists": ("historical objectivists", "anglican"),
    "anglican historical opera authors": ("historical opera authors", "anglican"),
    "anglican men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "anglican"),
    "anglican men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "anglican"),
    "anglican men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "anglican"),
    "anglican scholars of islam": ("scholars of islam", "anglican"),
    "anglican ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "anglican"),
    "anglican women's rights activists": ("women's rights activists", "anglican"),
    "anglicans abidat rma pianists": ("abidat rma pianists", "anglicans"),
    "anglicans abidat rma record producers": ("abidat rma record producers", "anglicans"),
    "anglicans abidat rma saxophonists": ("abidat rma saxophonists", "anglicans"),
    "anglicans abidat rma singer-songwriters": ("abidat rma singer-songwriters", "anglicans"),
    "anglicans classical europop cheerleaders": ("classical europop cheerleaders", "anglicans"),
    "anglicans classical europop composers": ("classical europop composers", "anglicans"),
    "anglicans convicted-of-murder": ("convicted-of-murder", "anglicans"),
    "anglicans expatriates": ("expatriates", "anglicans"),
    "anglicans historical house music bloggers": ("historical house music bloggers", "anglicans"),
    "anglicans historical objectivists": ("historical objectivists", "anglicans"),
    "anglicans historical opera authors": ("historical opera authors", "anglicans"),
    "anglicans men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "anglicans"),
    "anglicans men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "anglicans"),
    "anglicans men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "anglicans"),
    "anglicans scholars of islam": ("scholars of islam", "anglicans"),
    "anglicans ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "anglicans"),
    "anglicans women's rights activists": ("women's rights activists", "anglicans"),
    "bahá'ís abidat rma pianists": ("abidat rma pianists", "bahá'ís"),
    "bahá'ís abidat rma record producers": ("abidat rma record producers", "bahá'ís"),
    "bahá'ís abidat rma saxophonists": ("abidat rma saxophonists", "bahá'ís"),
    "bahá'ís abidat rma singer-songwriters": ("abidat rma singer-songwriters", "bahá'ís"),
    "bahá'ís classical europop cheerleaders": ("classical europop cheerleaders", "bahá'ís"),
    "bahá'ís classical europop composers": ("classical europop composers", "bahá'ís"),
    "bahá'ís convicted-of-murder": ("convicted-of-murder", "bahá'ís"),
    "bahá'ís expatriates": ("expatriates", "bahá'ís"),
    "bahá'ís historical house music bloggers": ("historical house music bloggers", "bahá'ís"),
    "bahá'ís historical objectivists": ("historical objectivists", "bahá'ís"),
    "bahá'ís historical opera authors": ("historical opera authors", "bahá'ís"),
    "bahá'ís men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "bahá'ís"),
    "bahá'ís men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "bahá'ís"),
    "bahá'ís men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "bahá'ís"),
    "bahá'ís scholars of islam": ("scholars of islam", "bahá'ís"),
    "bahá'ís ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "bahá'ís"),
    "bahá'ís women's rights activists": ("women's rights activists", "bahá'ís"),
    "buddhist abidat rma pianists": ("abidat rma pianists", "buddhist"),
    "buddhist abidat rma record producers": ("abidat rma record producers", "buddhist"),
    "buddhist abidat rma saxophonists": ("abidat rma saxophonists", "buddhist"),
    "buddhist abidat rma singer-songwriters": ("abidat rma singer-songwriters", "buddhist"),
    "buddhist classical europop cheerleaders": ("classical europop cheerleaders", "buddhist"),
    "buddhist classical europop composers": ("classical europop composers", "buddhist"),
    "buddhist convicted-of-murder": ("convicted-of-murder", "buddhist"),
    "buddhist expatriates": ("expatriates", "buddhist"),
    "buddhist historical house music bloggers": ("historical house music bloggers", "buddhist"),
    "buddhist historical objectivists": ("historical objectivists", "buddhist"),
    "buddhist historical opera authors": ("historical opera authors", "buddhist"),
    "buddhist men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "buddhist"),
    "buddhist men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "buddhist"),
    "buddhist men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "buddhist"),
    "buddhist scholars of islam": ("scholars of islam", "buddhist"),
    "buddhist ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "buddhist"),
    "buddhist women's rights activists": ("women's rights activists", "buddhist"),
    "christian abidat rma pianists": ("abidat rma pianists", "christian"),
    "christian abidat rma record producers": ("abidat rma record producers", "christian"),
    "christian abidat rma saxophonists": ("abidat rma saxophonists", "christian"),
    "christian abidat rma singer-songwriters": ("abidat rma singer-songwriters", "christian"),
    "christian classical europop cheerleaders": ("classical europop cheerleaders", "christian"),
    "christian classical europop composers": ("classical europop composers", "christian"),
    "christian convicted-of-murder": ("convicted-of-murder", "christian"),
    "christian expatriates": ("expatriates", "christian"),
    "christian historical house music bloggers": ("historical house music bloggers", "christian"),
    "christian historical objectivists": ("historical objectivists", "christian"),
    "christian historical opera authors": ("historical opera authors", "christian"),
    "christian men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "christian"),
    "christian men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "christian"),
    "christian men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "christian"),
    "christian scholars of islam": ("scholars of islam", "christian"),
    "christian ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "christian"),
    "christian women's rights activists": ("women's rights activists", "christian"),
    "christians abidat rma pianists": ("abidat rma pianists", "christians"),
    "christians abidat rma record producers": ("abidat rma record producers", "christians"),
    "christians abidat rma saxophonists": ("abidat rma saxophonists", "christians"),
    "christians abidat rma singer-songwriters": ("abidat rma singer-songwriters", "christians"),
    "christians classical europop cheerleaders": ("classical europop cheerleaders", "christians"),
    "christians classical europop composers": ("classical europop composers", "christians"),
    "christians convicted-of-murder": ("convicted-of-murder", "christians"),
    "christians expatriates": ("expatriates", "christians"),
    "christians historical house music bloggers": ("historical house music bloggers", "christians"),
    "christians historical objectivists": ("historical objectivists", "christians"),
    "christians historical opera authors": ("historical opera authors", "christians"),
    "christians men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "christians"),
    "christians men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "christians"),
    "christians men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "christians"),
    "christians scholars of islam": ("scholars of islam", "christians"),
    "christians ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "christians"),
    "christians women's rights activists": ("women's rights activists", "christians"),
    "coptic historical house music bloggers": ("historical house music bloggers", "coptic"),
    "episcopalians abidat rma pianists": ("abidat rma pianists", "episcopalians"),
    "episcopalians abidat rma record producers": ("abidat rma record producers", "episcopalians"),
    "episcopalians abidat rma saxophonists": ("abidat rma saxophonists", "episcopalians"),
    "episcopalians abidat rma singer-songwriters": ("abidat rma singer-songwriters", "episcopalians"),
    "episcopalians classical europop cheerleaders": ("classical europop cheerleaders", "episcopalians"),
    "episcopalians classical europop composers": ("classical europop composers", "episcopalians"),
    "episcopalians convicted-of-murder": ("convicted-of-murder", "episcopalians"),
    "episcopalians expatriates": ("expatriates", "episcopalians"),
    "episcopalians historical house music bloggers": ("historical house music bloggers", "episcopalians"),
    "episcopalians historical objectivists": ("historical objectivists", "episcopalians"),
    "episcopalians historical opera authors": ("historical opera authors", "episcopalians"),
    "episcopalians men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "episcopalians"),
    "episcopalians men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "episcopalians"),
    "episcopalians men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "episcopalians"),
    "episcopalians scholars of islam": ("scholars of islam", "episcopalians"),
    "episcopalians ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "episcopalians"),
    "episcopalians women's rights activists": ("women's rights activists", "episcopalians"),
    "hindu historical house music bloggers": ("historical house music bloggers", "hindu"),
    "hindus historical house music bloggers": ("historical house music bloggers", "hindus"),
    "islamic historical house music bloggers": ("historical house music bloggers", "islamic"),
    "jewish historical house music bloggers": ("historical house music bloggers", "jewish"),
    "jews historical house music bloggers": ("historical house music bloggers", "jews"),
    "methodist historical house music bloggers": ("historical house music bloggers", "methodist"),
    "muslim abidat rma pianists": ("abidat rma pianists", "muslim"),
    "muslim abidat rma record producers": ("abidat rma record producers", "muslim"),
    "muslim abidat rma saxophonists": ("abidat rma saxophonists", "muslim"),
    "muslim abidat rma singer-songwriters": ("abidat rma singer-songwriters", "muslim"),
    "muslim classical europop cheerleaders": ("classical europop cheerleaders", "muslim"),
    "muslim classical europop composers": ("classical europop composers", "muslim"),
    "muslim convicted-of-murder": ("convicted-of-murder", "muslim"),
    "muslim expatriates": ("expatriates", "muslim"),
    "muslim historical house music bloggers": ("historical house music bloggers", "muslim"),
    "muslim historical objectivists": ("historical objectivists", "muslim"),
    "muslim historical opera authors": ("historical opera authors", "muslim"),
    "muslim men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "muslim"),
    "muslim men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "muslim"),
    "muslim men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "muslim"),
    "muslim scholars of islam": ("scholars of islam", "muslim"),
    "muslim ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "muslim"),
    "muslim women's rights activists": ("women's rights activists", "muslim"),
    "nazi abidat rma pianists": ("abidat rma pianists", "nazi"),
    "nazi abidat rma record producers": ("abidat rma record producers", "nazi"),
    "nazi abidat rma saxophonists": ("abidat rma saxophonists", "nazi"),
    "nazi abidat rma singer-songwriters": ("abidat rma singer-songwriters", "nazi"),
    "nazi classical europop cheerleaders": ("classical europop cheerleaders", "nazi"),
    "nazi classical europop composers": ("classical europop composers", "nazi"),
    "nazi convicted-of-murder": ("convicted-of-murder", "nazi"),
    "nazi expatriates": ("expatriates", "nazi"),
    "nazi historical house music bloggers": ("historical house music bloggers", "nazi"),
    "nazi historical objectivists": ("historical objectivists", "nazi"),
    "nazi historical opera authors": ("historical opera authors", "nazi"),
    "nazi men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "nazi"),
    "nazi men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "nazi"),
    "nazi men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "nazi"),
    "nazi scholars of islam": ("scholars of islam", "nazi"),
    "nazi ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "nazi"),
    "nazi women's rights activists": ("women's rights activists", "nazi"),
    "protestant historical house music bloggers": ("historical house music bloggers", "protestant"),
    "shi'a muslims expatriates": ("expatriates", "shi'a muslims"),
    "yazidis abidat rma pianists": ("abidat rma pianists", "yazidis"),
    "yazidis abidat rma record producers": ("abidat rma record producers", "yazidis"),
    "yazidis abidat rma saxophonists": ("abidat rma saxophonists", "yazidis"),
    "yazidis abidat rma singer-songwriters": ("abidat rma singer-songwriters", "yazidis"),
    "yazidis classical europop cheerleaders": ("classical europop cheerleaders", "yazidis"),
    "yazidis classical europop composers": ("classical europop composers", "yazidis"),
    "yazidis convicted-of-murder": ("convicted-of-murder", "yazidis"),
    "yazidis expatriates": ("expatriates", "yazidis"),
    "yazidis historical house music bloggers": ("historical house music bloggers", "yazidis"),
    "yazidis historical objectivists": ("historical objectivists", "yazidis"),
    "yazidis historical opera authors": ("historical opera authors", "yazidis"),
    "yazidis men's sailing (sport) power forwards": ("men's sailing (sport) power forwards", "yazidis"),
    "yazidis men's sailing (sport) quarterbacks": ("men's sailing (sport) quarterbacks", "yazidis"),
    "yazidis men's sailing (sport) racing centers": ("men's sailing (sport) racing centers", "yazidis"),
    "yazidis scholars of islam": ("scholars of islam", "yazidis"),
    "yazidis ski-orienteering quarterbacks": ("ski-orienteering quarterbacks", "yazidis"),
    "yazidis women's rights activists": ("women's rights activists", "yazidis"),
    "zaydi historical house music bloggers": ("historical house music bloggers", "zaydi"),
    "zaydis historical house music bloggers": ("historical house music bloggers", "zaydis"),
}


@pytest.mark.parametrize("category, expected", data_religions.items(), ids=lambda x: x[0])
def test_religions(category, expected) -> None:
    # Test with a valid category and nat
    result = get_suffix(category, "religions")
    assert result == expected


data_nat = {
    "afghan competitors": ("competitors", "afghan"),
    "afghan diplomats": ("diplomats", "afghan"),
    "afghan emigrants": ("emigrants", "afghan"),
    "afghan expatriates": ("expatriates", "afghan"),
    "african national women's football teams": ("national women's football teams", "african"),
    "africanamerican history": ("history", "africanamerican"),
    "albanian sports coaches": ("sports coaches", "albanian"),
    "american award winners": ("award winners", "american"),
    "american basketball coaches": ("basketball coaches", "american"),
    "american basketball players": ("basketball players", "american"),
    "american cinema editors": ("cinema editors", "american"),
    "american cinema": ("cinema", "american"),
    "american comics": ("comics", "american"),
    "american culture": ("culture", "american"),
    "american films": ("films", "american"),
    "american men wheelchair racers": ("men wheelchair racers", "american"),
    "american men's wheelchair basketball players": ("men's wheelchair basketball players", "american"),
    "american national softball team managers": ("national softball team managers", "american"),
    "american national softball team": ("national softball team", "american"),
    "american national softball": ("national softball", "american"),
    "american nuclear medicine physicians": ("nuclear medicine physicians", "american"),
    "american people of": ("of", "american"),
    "american people": ("people", "american"),
    "american television episodes": ("television episodes", "american"),
    "american television seasons": ("television seasons", "american"),
    "american television series basedon british television series": (
        "television series basedon british television series",
        "american",
    ),
    "american television series basedon british": ("television series basedon british", "american"),
    "american television series debuts": ("television series debuts", "american"),
    "american television series endings": ("television series endings", "american"),
    "american television series": ("television series", "american"),
    "american television": ("television", "american"),
    "american wheelchair basketball players": ("wheelchair basketball players", "american"),
    "american wheelchair curlers": ("wheelchair curlers", "american"),
    "american wheelchair curling champions": ("wheelchair curling champions", "american"),
    "american wheelchair discus throwers": ("wheelchair discus throwers", "american"),
    "american wheelchair javelin throwers": ("wheelchair javelin throwers", "american"),
    "american wheelchair racers": ("wheelchair racers", "american"),
    "american wheelchair rugby players": ("wheelchair rugby players", "american"),
    "american wheelchair shot putters": ("wheelchair shot putters", "american"),
    "american wheelchair sports competitors": ("wheelchair sports competitors", "american"),
    "american wheelchair tennis players": ("wheelchair tennis players", "american"),
    "american wheelchair track and field athletes": ("wheelchair track and field athletes", "american"),
    "american wheelchair track": ("wheelchair track", "american"),
    "american women wheelchair racers": ("women wheelchair racers", "american"),
    "american women's wheelchair basketball players": ("women's wheelchair basketball players", "american"),
    "argentine multi instrumentalists": ("multi instrumentalists", "argentine"),
    "argentine multi-instrumentalists": ("multi-instrumentalists", "argentine"),
    "argentine songwriters": ("songwriters", "argentine"),
    "australian internet celebrities": ("internet celebrities", "australian"),
    "australian male sprinters": ("male sprinters", "australian"),
    "australian men wheelchair racers": ("men wheelchair racers", "australian"),
    "australian men's wheelchair basketball players": ("men's wheelchair basketball players", "australian"),
    "australian open by year – wheelchair events": ("open by year – wheelchair events", "australian"),
    "australian open by year – wheelchair": ("open by year – wheelchair", "australian"),
    "australian wheelchair basketball players": ("wheelchair basketball players", "australian"),
    "australian wheelchair racers": ("wheelchair racers", "australian"),
    "australian wheelchair rugby players": ("wheelchair rugby players", "australian"),
    "australian wheelchair tennis players": ("wheelchair tennis players", "australian"),
    "australian women wheelchair racers": ("women wheelchair racers", "australian"),
    "australian women's wheelchair basketball players": ("women's wheelchair basketball players", "australian"),
    "austrian men wheelchair racers": ("men wheelchair racers", "austrian"),
    "austrian wheelchair racers": ("wheelchair racers", "austrian"),
    "belgian athletics coaches": ("athletics coaches", "belgian"),
    "belgian men wheelchair racers": ("men wheelchair racers", "belgian"),
    "belgian wheelchair racers": ("wheelchair racers", "belgian"),
    "belgian women wheelchair racers": ("women wheelchair racers", "belgian"),
    "brazilian men wheelchair racers": ("men wheelchair racers", "brazilian"),
    "brazilian wheelchair racers": ("wheelchair racers", "brazilian"),
    "brazilian women wheelchair racers": ("women wheelchair racers", "brazilian"),
    "british editorial cartoonists": ("editorial cartoonists", "british"),
    "british men wheelchair racers": ("men wheelchair racers", "british"),
    "british men's wheelchair basketball players": ("men's wheelchair basketball players", "british"),
    "british rail": ("rail", "british"),
    "british reality television series": ("reality television series", "british"),
    "british television chefs": ("television chefs", "british"),
    "british television series characters by series": ("television series characters by series", "british"),
    "british television series characters": ("television series characters", "british"),
    "british television series": ("television series", "british"),
    "british wheelchair basketball players": ("wheelchair basketball players", "british"),
    "british wheelchair curlers": ("wheelchair curlers", "british"),
    "british wheelchair racers": ("wheelchair racers", "british"),
    "british wheelchair rugby players": ("wheelchair rugby players", "british"),
    "british wheelchair shot putters": ("wheelchair shot putters", "british"),
    "british wheelchair sports competitors": ("wheelchair sports competitors", "british"),
    "british wheelchair tennis players": ("wheelchair tennis players", "british"),
    "british wheelchair track and field athletes": ("wheelchair track and field athletes", "british"),
    "british wheelchair track": ("wheelchair track", "british"),
    "british women wheelchair racers": ("women wheelchair racers", "british"),
    "british women's wheelchair basketball players": ("women's wheelchair basketball players", "british"),
    "cameroonian men's wheelchair basketball players": ("men's wheelchair basketball players", "cameroonian"),
    "cameroonian wheelchair basketball players": ("wheelchair basketball players", "cameroonian"),
    "canadian male wheelchair basketball players": ("male wheelchair basketball players", "canadian"),
    "canadian men wheelchair racers": ("men wheelchair racers", "canadian"),
    "canadian men's wheelchair basketball players": ("men's wheelchair basketball players", "canadian"),
    "canadian nuclear medicine physicians": ("nuclear medicine physicians", "canadian"),
    "canadian sports businesspeople": ("sports businesspeople", "canadian"),
    "canadian wheelchair basketball players": ("wheelchair basketball players", "canadian"),
    "canadian wheelchair curlers": ("wheelchair curlers", "canadian"),
    "canadian wheelchair curling champions": ("wheelchair curling champions", "canadian"),
    "canadian wheelchair curling championships": ("wheelchair curling championships", "canadian"),
    "canadian wheelchair racers": ("wheelchair racers", "canadian"),
    "canadian wheelchair rugby players": ("wheelchair rugby players", "canadian"),
    "canadian wheelchair sports competitors": ("wheelchair sports competitors", "canadian"),
    "canadian women wheelchair racers": ("women wheelchair racers", "canadian"),
    "canadian women's wheelchair basketball players": ("women's wheelchair basketball players", "canadian"),
    "cape verdean football managers": ("football managers", "cape verdean"),
    "celtic mythology": ("mythology", "celtic"),
    "chinese men wheelchair racers": ("men wheelchair racers", "chinese"),
    "chinese wheelchair curlers": ("wheelchair curlers", "chinese"),
    "chinese wheelchair racers": ("wheelchair racers", "chinese"),
    "chinese women wheelchair racers": ("women wheelchair racers", "chinese"),
    "croatian nuclear medicine physicians": ("nuclear medicine physicians", "croatian"),
    "czech wheelchair racers": ("wheelchair racers", "czech"),
    "danish wheelchair curlers": ("wheelchair curlers", "danish"),
    "danish wheelchair racers": ("wheelchair racers", "danish"),
    "dutch explorers": ("explorers", "dutch"),
    "dutch men wheelchair racers": ("men wheelchair racers", "dutch"),
    "dutch men's wheelchair basketball players": ("men's wheelchair basketball players", "dutch"),
    "dutch wheelchair basketball players": ("wheelchair basketball players", "dutch"),
    "dutch wheelchair racers": ("wheelchair racers", "dutch"),
    "dutch wheelchair tennis players": ("wheelchair tennis players", "dutch"),
    "dutch women wheelchair racers": ("women wheelchair racers", "dutch"),
    "dutch women's wheelchair basketball players": ("women's wheelchair basketball players", "dutch"),
    "egyptian female sport shooters": ("female sport shooters", "egyptian"),
    "egyptian male sport shooters": ("male sport shooters", "egyptian"),
    "egyptian mythology": ("mythology", "egyptian"),
    "egyptian oncologists": ("oncologists", "egyptian"),
    "egyptian sport shooters": ("sport shooters", "egyptian"),
    "emirati football": ("football", "emirati"),
    "emirati wheelchair racers": ("wheelchair racers", "emirati"),
    "english men wheelchair racers": ("men wheelchair racers", "english"),
    "english wheelchair curlers": ("wheelchair curlers", "english"),
    "english wheelchair racers": ("wheelchair racers", "english"),
    "english women wheelchair racers": ("women wheelchair racers", "english"),
    "equatoguinean female footballers": ("female footballers", "equatoguinean"),
    "ethiopian basketball players": ("basketball players", "ethiopian"),
    "european national under 21 football teams": ("national under 21 football teams", "european"),
    "european national under-21 football teams": ("national under-21 football teams", "european"),
    "european rugby union by country": ("rugby union by country", "european"),
    "european rugby union": ("rugby union", "european"),
    "european wheelchair basketball championship": ("wheelchair basketball championship", "european"),
    "european wheelchair handball nations’ tournament": ("wheelchair handball nations’ tournament", "european"),
    "european women": ("women", "european"),
    "finnish men wheelchair racers": ("men wheelchair racers", "finnish"),
    "finnish wheelchair curlers": ("wheelchair curlers", "finnish"),
    "finnish wheelchair curling champions": ("wheelchair curling champions", "finnish"),
    "finnish wheelchair racers": ("wheelchair racers", "finnish"),
    "finnish women wheelchair racers": ("women wheelchair racers", "finnish"),
    "french comic strips": ("comic strips", "french"),
    "french comic": ("comic", "french"),
    "french men wheelchair racers": ("men wheelchair racers", "french"),
    "french men's wheelchair basketball players": ("men's wheelchair basketball players", "french"),
    "french open by year – wheelchair events": ("open by year – wheelchair events", "french"),
    "french open by year – wheelchair": ("open by year – wheelchair", "french"),
    "french tennis players": ("tennis players", "french"),
    "french wheelchair basketball players": ("wheelchair basketball players", "french"),
    "french wheelchair racers": ("wheelchair racers", "french"),
    "french wheelchair tennis players": ("wheelchair tennis players", "french"),
    "french women's wheelchair basketball players": ("women's wheelchair basketball players", "french"),
    "gabonese men wheelchair racers": ("men wheelchair racers", "gabonese"),
    "gabonese wheelchair racers": ("wheelchair racers", "gabonese"),
    "german footballers": ("footballers", "german"),
    "german men wheelchair racers": ("men wheelchair racers", "german"),
    "german men's wheelchair basketball players": ("men's wheelchair basketball players", "german"),
    "german nuclear medicine physicians": ("nuclear medicine physicians", "german"),
    "german wheelchair basketball players": ("wheelchair basketball players", "german"),
    "german wheelchair curlers": ("wheelchair curlers", "german"),
    "german wheelchair racers": ("wheelchair racers", "german"),
    "german wheelchair tennis players": ("wheelchair tennis players", "german"),
    "german women's wheelchair basketball players": ("women's wheelchair basketball players", "german"),
    "icelandic male athletes": ("male athletes", "icelandic"),
    "icelandic male runners": ("male runners", "icelandic"),
    "icelandic male steeplechase runners": ("male steeplechase runners", "icelandic"),
    "indian cricketers": ("cricketers", "indian"),
    "iranian nuclear medicine physicians": ("nuclear medicine physicians", "iranian"),
    "irish football managers": ("football managers", "irish"),
    "irish men wheelchair racers": ("men wheelchair racers", "irish"),
    "irish wheelchair racers": ("wheelchair racers", "irish"),
    "irish women wheelchair racers": ("women wheelchair racers", "irish"),
    "israeli men wheelchair racers": ("men wheelchair racers", "israeli"),
    "israeli men's wheelchair basketball players": ("men's wheelchair basketball players", "israeli"),
    "israeli people of": ("of", "israeli"),
    "israeli wheelchair basketball players": ("wheelchair basketball players", "israeli"),
    "israeli wheelchair racers": ("wheelchair racers", "israeli"),
    "israeli wheelchair tennis players": ("wheelchair tennis players", "israeli"),
    "israeli women's wheelchair basketball players": ("women's wheelchair basketball players", "israeli"),
    "italian defectors to the soviet union": ("defectors to the soviet union", "italian"),
    "italian defectors": ("defectors", "italian"),
    "italian wheelchair curlers": ("wheelchair curlers", "italian"),
    "italian wheelchair racers": ("wheelchair racers", "italian"),
    "ivorian american": ("american", "ivorian"),
    "ivorian descent": ("descent", "ivorian"),
    "ivorian diaspora": ("diaspora", "ivorian"),
    "ivorian emigrants": ("emigrants", "ivorian"),
    "ivorian expatriates": ("expatriates", "ivorian"),
    "japanese men wheelchair racers": ("men wheelchair racers", "japanese"),
    "japanese men's wheelchair basketball players": ("men's wheelchair basketball players", "japanese"),
    "japanese wheelchair basketball players": ("wheelchair basketball players", "japanese"),
    "japanese wheelchair curlers": ("wheelchair curlers", "japanese"),
    "japanese wheelchair racers": ("wheelchair racers", "japanese"),
    "japanese wheelchair rugby players": ("wheelchair rugby players", "japanese"),
    "japanese wheelchair tennis players": ("wheelchair tennis players", "japanese"),
    "japanese women wheelchair racers": ("women wheelchair racers", "japanese"),
    "kuwaiti men's wheelchair basketball players": ("men's wheelchair basketball players", "kuwaiti"),
    "kuwaiti wheelchair basketball players": ("wheelchair basketball players", "kuwaiti"),
    "kuwaiti wheelchair racers": ("wheelchair racers", "kuwaiti"),
    "latvian wheelchair curlers": ("wheelchair curlers", "latvian"),
    "lithuanian wheelchair racers": ("wheelchair racers", "lithuanian"),
    "macedonian wheelchair racers": ("wheelchair racers", "macedonian"),
    "mexican men wheelchair racers": ("men wheelchair racers", "mexican"),
    "mexican wheelchair racers": ("wheelchair racers", "mexican"),
    "mexican women wheelchair racers": ("women wheelchair racers", "mexican"),
    "moroccan competitors": ("competitors", "moroccan"),
    "moroccan male middle distance runners": ("male middle distance runners", "moroccan"),
    "moroccan male middle-distance runners": ("male middle-distance runners", "moroccan"),
    "north korean sport": ("sport", "north korean"),
    "north korean television": ("television", "north korean"),
    "northern ireland descent": ("descent", "northern ireland"),
    "northern ireland sport": ("sport", "northern ireland"),
    "norwegian figure skaters": ("figure skaters", "norwegian"),
    "norwegian male pair skaters": ("male pair skaters", "norwegian"),
    "norwegian male single skaters": ("male single skaters", "norwegian"),
    "norwegian pair skaters": ("pair skaters", "norwegian"),
    "norwegian short track speed skaters": ("short track speed skaters", "norwegian"),
    "norwegian wheelchair curlers": ("wheelchair curlers", "norwegian"),
    "norwegian wheelchair racers": ("wheelchair racers", "norwegian"),
    "omani football": ("football", "omani"),
    "pakistani psychiatrists": ("psychiatrists", "pakistani"),
    "peruvian television actors": ("television actors", "peruvian"),
    "philippine films": ("films", "philippine"),
    "polish businesspeople": ("businesspeople", "polish"),
    "polish wheelchair racers": ("wheelchair racers", "polish"),
    "polish women": ("women", "polish"),
    "portuguese healthcare managers": ("healthcare managers", "portuguese"),
    "puerto rican wheelchair sports competitors": ("wheelchair sports competitors", "puerto rican"),
    "puerto rican wheelchair track and field athletes": ("wheelchair track and field athletes", "puerto rican"),
    "puerto rican wheelchair track": ("wheelchair track", "puerto rican"),
    "republic-of ireland football managers": ("football managers", "the republic-of ireland"),
    "russian folklore characters": ("folklore characters", "russian"),
    "russian wheelchair curlers": ("wheelchair curlers", "russian"),
    "russian wheelchair racers": ("wheelchair racers", "russian"),
    "sammarinese wheelchair racers": ("wheelchair racers", "sammarinese"),
    "scottish popular culture": ("popular culture", "scottish"),
    "scottish traditions": ("traditions", "scottish"),
    "scottish wheelchair curlers": ("wheelchair curlers", "scottish"),
    "scottish wheelchair curling champions": ("wheelchair curling champions", "scottish"),
    "scottish wheelchair racers": ("wheelchair racers", "scottish"),
    "scottish women wheelchair racers": ("women wheelchair racers", "scottish"),
    "slovak wheelchair curlers": ("wheelchair curlers", "slovak"),
    "south african men wheelchair racers": ("men wheelchair racers", "south african"),
    "south african wheelchair basketball players": ("wheelchair basketball players", "south african"),
    "south african wheelchair racers": ("wheelchair racers", "south african"),
    "south american pan africanists": ("pan africanists", "south american"),
    "south american pan-africanists": ("pan-africanists", "south american"),
    "south korean television series": ("television series", "south korean"),
    "south korean wheelchair curlers": ("wheelchair curlers", "south korean"),
    "south korean wheelchair racers": ("wheelchair racers", "south korean"),
    "spanish men's wheelchair basketball players": ("men's wheelchair basketball players", "spanish"),
    "spanish sports broadcasters": ("sports broadcasters", "spanish"),
    "spanish wheelchair basketball players": ("wheelchair basketball players", "spanish"),
    "spanish wheelchair fencers": ("wheelchair fencers", "spanish"),
    "spanish wheelchair racers": ("wheelchair racers", "spanish"),
    "spanish wheelchair tennis players": ("wheelchair tennis players", "spanish"),
    "swedish oncologists": ("oncologists", "swedish"),
    "swedish wheelchair curlers": ("wheelchair curlers", "swedish"),
    "swedish wheelchair curling champions": ("wheelchair curling champions", "swedish"),
    "swedish wheelchair racers": ("wheelchair racers", "swedish"),
    "swedish wheelchair tennis players": ("wheelchair tennis players", "swedish"),
    "swiss men wheelchair racers": ("men wheelchair racers", "swiss"),
    "swiss men's wheelchair basketball players": ("men's wheelchair basketball players", "swiss"),
    "swiss wheelchair basketball players": ("wheelchair basketball players", "swiss"),
    "swiss wheelchair curlers": ("wheelchair curlers", "swiss"),
    "swiss wheelchair curling champions": ("wheelchair curling champions", "swiss"),
    "swiss wheelchair curling championship": ("wheelchair curling championship", "swiss"),
    "swiss wheelchair racers": ("wheelchair racers", "swiss"),
    "swiss wheelchair tennis players": ("wheelchair tennis players", "swiss"),
    "swiss women wheelchair racers": ("women wheelchair racers", "swiss"),
    "thai wheelchair racers": ("wheelchair racers", "thai"),
    "thai wheelchair tennis players": ("wheelchair tennis players", "thai"),
    "tunisian wheelchair racers": ("wheelchair racers", "tunisian"),
    "turkish expatriate sprtspeople": ("expatriate sprtspeople", "turkish"),
    "turkish men's wheelchair basketball players": ("men's wheelchair basketball players", "turkish"),
    "turkish wheelchair basketball players": ("wheelchair basketball players", "turkish"),
    "turkish wheelchair racers": ("wheelchair racers", "turkish"),
    "turkish wheelchair tennis players": ("wheelchair tennis players", "turkish"),
    "turkish women wheelchair racers": ("women wheelchair racers", "turkish"),
    "turkish women's wheelchair basketball players": ("women's wheelchair basketball players", "turkish"),
    "ugandan football": ("football", "ugandan"),
    "welsh men wheelchair racers": ("men wheelchair racers", "welsh"),
    "welsh wheelchair curlers": ("wheelchair curlers", "welsh"),
    "welsh wheelchair racers": ("wheelchair racers", "welsh"),
    "welsh women wheelchair racers": ("women wheelchair racers", "welsh"),
    "yemeni football teams": ("football teams", "yemeni"),
    "yemeni national football team managers": ("national football team managers", "yemeni"),
    "yemeni national football team": ("national football team", "yemeni"),
    "yemeni national football teams": ("national football teams", "yemeni"),
    "yemeni national football": ("national football", "yemeni"),
    "yemeni national softball team managers": ("national softball team managers", "yemeni"),
    "yemeni national softball team": ("national softball team", "yemeni"),
    "yemeni national softball": ("national softball", "yemeni"),
    "yemeni shi'a muslims": ("shi'a muslims", "yemeni"),
    "zambian wheelchair racers": ("wheelchair racers", "zambian"),
}


@pytest.mark.parametrize("category, expected", data_nat.items(), ids=lambda x: x[0])
def test_nat(category, expected) -> None:
    # Test with a valid category and nat
    result = get_suffix(category, "nat")
    assert result == expected
