"""
Tests
"""

import pytest

from ArWikiCats.make_bots.jobs_bots.bot_te_4 import (
    Jobs_in_Multi_Sports,
    nat_match,
    te_2018_with_nat,
)

fast_data = {
    "anti-haitian sentiment": "مشاعر معادية للهايتيون",
    "anti-palestinian sentiment": "مشاعر معادية للفلسطينيون",
    "anti-turkish sentiment": "مشاعر معادية للأتراك",
    "anti-american sentiment": "مشاعر معادية للأمريكيون",
    "anti-czech sentiment": "مشاعر معادية للتشيكيون",
    "anti-japanese sentiment": "مشاعر معادية لليابانيون",
    "anti-asian sentiment": "مشاعر معادية للآسيويين",
    "anti-slovene sentiment": "مشاعر معادية للسلوفينيون",
    "anti-ukrainian sentiment": "مشاعر معادية للأوكرانيون",
    "anti-chechen sentiment": "مشاعر معادية للشيشانيون",
    "anti-mexican sentiment": "مشاعر معادية للمكسيكيون",
    "anti-chinese sentiment": "مشاعر معادية للصينيون",
    "anti-christian sentiment": "مشاعر معادية للمسيحيون",
    "anti-serbian sentiment": "مشاعر معادية للصرب",
    "anti-armenian sentiment": "مشاعر معادية للأرمن",
    "anti-scottish sentiment": "مشاعر معادية للإسكتلنديون",
    "anti-iranian sentiment": "مشاعر معادية للإيرانيون",
    "anti-english sentiment": "مشاعر معادية للإنجليز",
    "anti-hungarian sentiment": "مشاعر معادية للمجريون",
    "anti-greek sentiment": "مشاعر معادية لليونانيون",
}

Multi_Sports_data = {
    "afc asian cup managers": "مدربون في كأس آسيا",
    "afc asian cup players": "لاعبون في كأس آسيا",
    "african games competitors": "منافسون في الألعاب الإفريقية",
    "african games judoka": "لاعبو جودو في الألعاب الإفريقية",
    "african games taekwondo practitioners": "لاعبو تايكوندو في الألعاب الإفريقية",
    "asian games alpine skiers": "متزحلقو منحدرات ثلجية في الألعاب الآسيوية",
    "asian games archers": "نبالون في الألعاب الآسيوية",
    "asian games athletes": "لاعبو قوى في الألعاب الآسيوية",
    "asian games badminton players": "لاعبو تنس ريشة في الألعاب الآسيوية",
    "asian games bowlers": "لاعبو بولينج في الألعاب الآسيوية",
    "asian games boxers": "ملاكمون في الألعاب الآسيوية",
    "asian games canoeists": "متسابقو قوارب الكانوي في الألعاب الآسيوية",
    "asian games chess players": "لاعبو شطرنج في الألعاب الآسيوية",
    "asian games competitors": "منافسون في الألعاب الآسيوية",
    "asian games cricketers": "لاعبو كريكت في الألعاب الآسيوية",
    "asian games divers": "غواصون في الألعاب الآسيوية",
    "asian games footballers": "لاعبو كرة قدم في الألعاب الآسيوية",
    "asian games golfers": "لاعبو غولف في الألعاب الآسيوية",
    "asian games handball players": "لاعبو كرة يد في الألعاب الآسيوية",
    "asian games judoka": "لاعبو جودو في الألعاب الآسيوية",
    "asian games karateka": "ممارسو كاراتيه في الألعاب الآسيوية",
    "asian games modern pentathletes": "متسابقو خماسي حديث في الألعاب الآسيوية",
    "asian games sambo practitioners": "ممارسو سامبو في الألعاب الآسيوية",
    "asian games shooters": "رماة في الألعاب الآسيوية",
    "asian games ski-orienteers": "متسابقو تزلج موجه في الألعاب الآسيوية",
    "asian games soft tennis players": "لاعبو كرة مضرب لينة في الألعاب الآسيوية",
    "asian games sport climbers": "متسلقون في الألعاب الآسيوية",
    "asian games swimmers": "سباحون في الألعاب الآسيوية",
    "asian games table tennis players": "لاعبو كرة طاولة في الألعاب الآسيوية",
    "asian games taekwondo practitioners": "لاعبو تايكوندو في الألعاب الآسيوية",
    "asian games tennis players": "لاعبو كرة مضرب في الألعاب الآسيوية",
    "asian games volleyball players": "لاعبو كرة طائرة في الألعاب الآسيوية",
    "asian games water polo players": "لاعبو كرة ماء في الألعاب الآسيوية",
    "asian games weightlifters": "رباعون في الألعاب الآسيوية",
    "asian games wrestlers": "مصارعون في الألعاب الآسيوية",
    "asian games xiangqi players": "لاعبو شطرنج صيني في الألعاب الآسيوية",
    "asian para games competitors": "منافسون في دورة الألعاب الآسيوية البارالمبية",
    "central american and caribbean games competitors": "منافسون في ألعاب أمريكا الوسطى والكاريبي",
    "commonwealth games athletes": "لاعبو قوى في ألعاب الكومنولث",
    "commonwealth games badminton players": "لاعبو تنس ريشة في ألعاب الكومنولث",
    "commonwealth games bowls players": "لاعبو بولينج في ألعاب الكومنولث",
    "commonwealth games boxers": "ملاكمون في ألعاب الكومنولث",
    "commonwealth games competitors": "منافسون في ألعاب الكومنولث",
    "commonwealth games divers": "غواصون في ألعاب الكومنولث",
    "commonwealth games fencers": "مبارزون في ألعاب الكومنولث",
    "commonwealth games field hockey players": "لاعبو هوكي ميدان في ألعاب الكومنولث",
    "commonwealth games gymnasts": "لاعبو جمباز في ألعاب الكومنولث",
    "commonwealth games rugby sevens players": "لاعبو سباعيات رجبي في ألعاب الكومنولث",
    "commonwealth games squash players": "لاعبو إسكواش في ألعاب الكومنولث",
    "commonwealth games swimmers": "سباحون في ألعاب الكومنولث",
    "commonwealth games triathletes": "لاعبو ترياثلون في ألعاب الكومنولث",
    "european games boxers": "ملاكمون في الألعاب الأوروبية",
    "european games competitors": "منافسون في الألعاب الأوروبية",
    "european games gymnasts": "لاعبو جمباز في الألعاب الأوروبية",
    "european games sambo practitioners": "ممارسو سامبو في الألعاب الأوروبية",
    "european games volleyball players": "لاعبو كرة طائرة في الألعاب الأوروبية",
    "islamic solidarity games competitors": "منافسون في ألعاب التضامن الإسلامي",
    "islamic solidarity games judoka": "لاعبو جودو في ألعاب التضامن الإسلامي",
    "islamic solidarity games swimmers": "سباحون في ألعاب التضامن الإسلامي",
    "islamic solidarity games taekwondo practitioners": "لاعبو تايكوندو في ألعاب التضامن الإسلامي",
    "maccabiah games competitors": "منافسون في الألعاب المكابيه",
    "maccabiah games gymnasts": "لاعبو جمباز في الألعاب المكابيه",
    "maccabiah games rugby union players": "لاعبو اتحاد رجبي في الألعاب المكابيه",
    "mediterranean games competitors": "منافسون في الألعاب المتوسطية",
    "pan american games archers": "نبالون في دورة الألعاب الأمريكية",
    "pan american games athletes": "لاعبو قوى في دورة الألعاب الأمريكية",
    "pan american games baseball players": "لاعبو كرة قاعدة في دورة الألعاب الأمريكية",
    "pan american games basketball players": "لاعبو كرة سلة في دورة الألعاب الأمريكية",
    "pan american games bowlers": "لاعبو بولينج في دورة الألعاب الأمريكية",
    "pan american games boxers": "ملاكمون في دورة الألعاب الأمريكية",
    "pan american games competitors": "منافسون في دورة الألعاب الأمريكية",
    "pan american games cyclists": "دراجون في دورة الألعاب الأمريكية",
    "pan american games equestrians": "فرسان خيول في دورة الألعاب الأمريكية",
    "pan american games field hockey players": "لاعبو هوكي ميدان في دورة الألعاب الأمريكية",
    "pan american games footballers": "لاعبو كرة قدم في دورة الألعاب الأمريكية",
    "pan american games gymnasts": "لاعبو جمباز في دورة الألعاب الأمريكية",
    "pan american games handball players": "لاعبو كرة يد في دورة الألعاب الأمريكية",
    "pan american games rugby sevens players": "لاعبو سباعيات رجبي في دورة الألعاب الأمريكية",
    "pan american games sailors": "بحارة في دورة الألعاب الأمريكية",
    "pan american games softball players": "لاعبو كرة لينة في دورة الألعاب الأمريكية",
    "pan american games swimmers": "سباحون في دورة الألعاب الأمريكية",
    "pan american games tennis players": "لاعبو كرة مضرب في دورة الألعاب الأمريكية",
    "pan american games track and field athletes": "رياضيو المسار والميدان في دورة الألعاب الأمريكية",
    "pan american games volleyball players": "لاعبو كرة طائرة في دورة الألعاب الأمريكية",
    "pan american games water polo players": "لاعبو كرة ماء في دورة الألعاب الأمريكية",
    "pan american games weightlifters": "رباعون في دورة الألعاب الأمريكية",
    "pan american games wrestlers": "مصارعون في دورة الألعاب الأمريكية",
    "paralympic alpine skiers": "متزحلقو منحدرات ثلجية في الألعاب البارالمبية",
    "paralympic archers": "نبالون في الألعاب البارالمبية",
    "paralympic athletes": "لاعبو قوى في الألعاب البارالمبية",
    "paralympic badminton players": "لاعبو تنس ريشة في الألعاب البارالمبية",
    "paralympic biathletes": "لاعبو بياثلون في الألعاب البارالمبية",
    "paralympic boccia players": "لاعبو بوتشيا في الألعاب البارالمبية",
    "paralympic coaches": "مدربون في الألعاب البارالمبية",
    "paralympic competitors": "منافسون في الألعاب البارالمبية",
    "paralympic cross-country skiers": "متزحلقون ريفيون في الألعاب البارالمبية",
    "paralympic cyclists": "دراجون في الألعاب البارالمبية",
    "paralympic equestrians": "فرسان خيول في الألعاب البارالمبية",
    "paralympic footballers": "لاعبو كرة قدم في الألعاب البارالمبية",
    "paralympic goalball players": "لاعبو كرة هدف في الألعاب البارالمبية",
    "paralympic judoka": "لاعبو جودو في الألعاب البارالمبية",
    "paralympic long jumpers": "لاعبو قفز طويل في الألعاب البارالمبية",
    "paralympic marathon runners": "عداؤو ماراثون في الألعاب البارالمبية",
    "paralympic powerlifters": "ممارسو رياضة القوة في الألعاب البارالمبية",
    "paralympic rowers": "مجدفون في الألعاب البارالمبية",
    "paralympic sailors": "بحارة في الألعاب البارالمبية",
    "paralympic shooters": "رماة في الألعاب البارالمبية",
    "paralympic sledge hockey players": "لاعبو هوكي مزلجة في الألعاب البارالمبية",
    "paralympic snooker players": "لاعبو سنوكر في الألعاب البارالمبية",
    "paralympic snowboarders": "متزلجون على الثلج في الألعاب البارالمبية",
    "paralympic swimmers": "سباحون في الألعاب البارالمبية",
    "paralympic table tennis players": "لاعبو كرة طاولة في الألعاب البارالمبية",
    "paralympic taekwondo practitioners": "لاعبو تايكوندو في الألعاب البارالمبية",
    "paralympic track and field athletes": "رياضيو المسار والميدان في الألعاب البارالمبية",
    "paralympic triple jumpers": "لاعبو وثب ثلاثي في الألعاب البارالمبية",
    "paralympic volleyball players": "لاعبو كرة طائرة في الألعاب البارالمبية",
    "paralympic weightlifters": "رباعون في الألعاب البارالمبية",
    "paralympic wheelchair basketball coaches": "مدربو كرة سلة على كراسي متحركة في الألعاب البارالمبية",
    "paralympic wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة في الألعاب البارالمبية",
    "paralympic wheelchair curlers": "لاعبو كيرلنغ على الكراسي المتحركة في الألعاب البارالمبية",
    "paralympic wheelchair fencers": "مبارزون على الكراسي المتحركة في الألعاب البارالمبية",
    "paralympic wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة في الألعاب البارالمبية",
    "paralympic wrestlers": "مصارعون في الألعاب البارالمبية",
    "paralympics people": "أشخاص في الألعاب البارالمبية",
    "parapan american games badminton players": "لاعبو تنس ريشة في ألعاب بارابان الأمريكية",
    "parapan american games competitors": "منافسون في ألعاب بارابان الأمريكية",
    "parapan american games judoka": "لاعبو جودو في ألعاب بارابان الأمريكية",
    "parapan american games wheelchair tennis players": "لاعبو كرة مضرب على كراسي متحركة في ألعاب بارابان الأمريكية",
    "sea games competitors": "منافسون في ألعاب البحر",
    "south american games competitors": "منافسون في ألعاب أمريكا الجنوبية",
    "summer olympics coaches": "مدربون في الألعاب الأولمبية الصيفية",
    "summer olympics competitors": "منافسون في الألعاب الأولمبية الصيفية",
    "summer world university games competitors": "منافسون في ألعاب الجامعات العالمية الصيفية",
    "winter olympics competitors": "منافسون في الألعاب الأولمبية الشتوية",
    "youth olympics biathletes": "لاعبو بياثلون في الألعاب الأولمبية الشبابية",
    "youth olympics ice hockey players": "لاعبو هوكي جليد في الألعاب الأولمبية الشبابية",
    "youth olympics nordic combined skiers": "متزحلقو تزلج نوردي مزدوج في الألعاب الأولمبية الشبابية",
}


data_2018_with_nat = {
    "american culture": "ثقافة أمريكية",
    "american zombie novels": "روايات زومبي أمريكية",
    "arab lgbtq people": "أعلام إل جي بي تي كيو عربية",
    "argentine adult animated television series": "مسلسلات تلفزيونية رسوم متحركة للكبار أرجنتينية",
    "argentine grand prix": "جائزة الأرجنتين الكبرى",
    "argentine tennis": "كرة مضرب أرجنتينية",
    "armenian television": "التلفزة الأرمينية",
    "armenian world music groups": "فرق موسيقى العالم أرمينية",
    "asian-american people": "أمريكيون آسيويين",
    "assassinated politicians": "سياسيون مغتالون",
    "austrian descent": "أصل نمساوي",
    "austrian musical groups": "مجموعات موسيقية نمساوية",
    "austrian rock": "روك نمساوي",
    "austrian television series": "مسلسلات تلفزيونية نمساوية",
    "austrian television series-endings": "مسلسلات تلفزيونية نمساوية انتهت في",
    "bangladeshi films": "أفلام بنغلاديشية",
    "bangladeshi politics": "السياسة البنغلاديشية",
    "belgian companies": "شركات بلجيكية",
    "bhutanese sport": "رياضة بوتانية",
    "brazilian football club seasons": "مواسم أندية كرة قدم برازيلية",
    "british mystery television series": "مسلسلات تلفزيونية غموض بريطانية",
    "british open": "المملكة المتحدة المفتوحة",
    "british women's sport": "رياضة بريطانية نسائية",
    "burmese names": "أسماء بورمية",
    "by benjamin britten": "بواسطة بنجامين بريتن",
    "by james cameron": "بواسطة جيمس كاميرون",
    "by raphael": "بواسطة رافاييل",
    "by vaikom muhammad basheer": "بواسطة محمد بشير",
    "byzantine titles": "ألقاب بيزنطية",
    "canadian films": "أفلام كندية",
    "canadian labour law": "قانون العمل الكندي",
    "canadian music": "موسيقى كندية",
    "canadian television series-endings": "مسلسلات تلفزيونية كندية انتهت في",
    "central american football": "كرة القدم الأمريكية الأوسطية",
    "chilean law": "قانون تشيلي",
    "chilean television series-endings": "مسلسلات تلفزيونية تشيلية انتهت في",
    "chinese hip-hop groups": "فرق هيب هوب صينية",
    "chinese lgbtq people": "أعلام إل جي بي تي كيو صينية",
    "chinese music": "موسيقى صينية",
    "chinese sports executives": "مدراء رياضية صينية",
    "christian saints": "قديسون",
    "christian texts": "نصوص مسيحية",
    "colombian children's animated television series": "مسلسلات تلفزيونية رسوم متحركة أطفال كولومبية",
    "coptic calendar": "تقويم قبطي",
    "croatian diaspora": "شتات كرواتي",
    "croatian ice hockey league": "الدوري الكرواتي لهوكي الجليد",
    "croatian music": "موسيقى كرواتية",
    "czech thrash metal musical groups": "فرق موسيقى ثراش ميتال تشيكية",
    "czech women's sport": "رياضة تشيكية نسائية",
    "danish adventure television series": "مسلسلات تلفزيونية مغامرات دنماركية",
    "danish black-and-white films": "أفلام أبيض وأسود دنماركية",
    "danish books": "كتب دنماركية",
    "dutch television-seasons": "مواسم تلفزيونية هولندية",
    "dutch tennis": "كرة مضرب هولندية",
    "east german sport": "رياضة ألمانية شرقية",
    "electro musicians": "موسيقيو موسيقى كهربائية",
    "emirati sport": "رياضة إماراتية",
    "english country music": "كانتري إنجليزي",
    "eritrean premier league": "الدوري الإريتري الممتاز",
    "estonian music people": "شخصيات موسيقية إستونية",
    "european american culture": "ثقافة أمريكية أوروبية",
    "european-argentine culture": "ثقافة أرجنتينية أوروبية",
    "explorers of": "مستكشفو",
    "fictional australian rules footballers": "لاعبو كرة قدم أسترالية خياليون",
    "filipino-american culture": "ثقافة أمريكية فلبينية",
    "film editors": "محررو أفلام",
    "finnish descent": "أصل فنلندي",
    "french rugby union leagues": "اتحاد دوري الرجبي الفرنسي",
    "gardeners": "مزارعو حدائق",
    "german literature": "أدب ألماني",
    "gothic architecture": "عمارة قوطية",
    "greek television series": "مسلسلات تلفزيونية يونانية",
    "hungarian diaspora": "شتات مجري",
    "hungarian sport": "رياضة مجرية",
    "hungarian websites": "مواقع ويب مجرية",
    "indian companies": "شركات هندية",
    "indonesian online encyclopedias": "موسوعات إنترنت إندونيسية",
    "iraqi diaspora": "شتات عراقي",
    "irish comedy": "كوميديا أيرلندية",
    "irish league": "الدوري الأيرلندي",
    "irish paintings": "لوحات أيرلندية",
    "irish universities": "جامعات أيرلندية",
    "israeli architecture awards": "جوائز عمارة إسرائيلية",
    "italian black metal musical groups": "فرق موسيقى بلاك ميتال إيطالية",
    "ivorian companies": "شركات إيفوارية",
    "ivorian people": "أعلام إيفواريون",
    "japanese folklore": "فلكور ياباني",
    "japanese lgbtq people": "أعلام إل جي بي تي كيو يابانية",
    "japanese martial arts terminology": "مصطلحات فنون قتالية يابانية",
    "japanese war crimes": "جرائم حرب يابانية",
    "javanese diaspora": "شتات جاوي",
    "jewish scottish history": "تاريخ إسكتلندي يهودي",
    "kazakh presidential election": "انتخابات الرئاسة الكازاخية",
    "kyrgyzstani sport": "رياضة قيرغيزستانية",
    "lebanese television series": "مسلسلات تلفزيونية لبنانية",
    "lithuanian films": "أفلام ليتوانية",
    "malawian websites": "مواقع ويب ملاوية",
    "maldivian people": "أعلام مالديفيون",
    "male models": "عارضو أزياء ذكور",
    "male sport shooters": "لاعبو رماية ذكور",
    "malian people": "أعلام ماليون",
    "maltese lgbtq people": "أعلام إل جي بي تي كيو مالطية",
    "mexican crime thriller films": "أفلام إثارة وجريمة مكسيكية",
    "mexican television series-endings": "مسلسلات تلفزيونية مكسيكية انتهت في",
    "mexican-american culture": "ثقافة أمريكية مكسيكية",
    "moroccan television series": "مسلسلات تلفزيونية مغربية",
    "moroccan tennis": "كرة مضرب مغربية",
    "music journalists": "صحفيو موسيقى",
    "nepali television": "التلفزة النيبالية",
    "nigerian football": "كرة القدم النيجيرية",
    "north korean literature": "أدب كوري شمالي",
    "norwegian comedy-drama films": "أفلام كوميديا درامية نرويجية",
    "norwegian folk music groups": "فرق موسيقى تقليدية نرويجية",
    "norwegian jews": "يهود نرويجيون",
    "olympic beach volleyball players": "لاعبو كرة طائرة شاطئية أولمبيون",
    "olympic divers": "غواصون أولمبيون",
    "olympic handball players": "لاعبو كرة يد أولمبيون",
    "olympic judoka": "لاعبو جودو أولمبيون",
    "olympic nordic combined skiers": "متزحلقو تزلج نوردي مزدوج أولمبيون",
    "ossetian descent": "أصل أوسيتي",
    "pakistani football": "كرة القدم الباكستانية",
    "peruvian descent": "أصل بيروي",
    "philippine football": "كرة القدم الفلبينية",
    "philippine presidential election": "انتخابات الرئاسة الفلبينية",
    "philippine television commercials": "إعلانات تجارية تلفزيونية فلبينية",
    "polish crime thriller films": "أفلام إثارة وجريمة بولندية",
    "polish epic films": "أفلام ملحمية بولندية",
    "polish television series-debuts": "مسلسلات تلفزيونية بولندية بدأ عرضها في",
    "polish television-seasons": "مواسم تلفزيونية بولندية",
    "polo players": "لاعبو بولو",
    "portuguese fantasy films": "أفلام فانتازيا برتغالية",
    "portuguese tennis": "كرة مضرب برتغالية",
    "puerto rican television series-debuts": "مسلسلات تلفزيونية بورتوريكية بدأ عرضها في",
    "qatari football ": "كرة القدم القطرية",
    "romanian clothing": "ملابس رومانية",
    "romanian restaurants": "مطاعم رومانية",
    "romanian sport": "رياضة رومانية",
    "russian politics": "السياسة الروسية",
    "rwandan political people": "أعلام سياسية رواندية",
    "samoan diaspora": "شتات ساموي",
    "saudi super cup": "كأس السوبر السعودي",
    "scottish islands": "جزر إسكتلندية",
    "serbian crime television series": "مسلسلات تلفزيونية جريمة صربية",
    "slovak eurodance groups": "فرق يورودانس سلوفاكية",
    "slovenian sport": "رياضة سلوفينية",
    "south african jews": "يهود جنوب إفريقيون",
    "south african provinces": "مقاطعات جنوبية إفريقية",
    "south korean tennis": "كرة مضرب كورية جنوبية",
    "soviet navy": "البحرية السوفيتية",
    "soviet war crimes": "جرائم حرب سوفيتية",
    "spanish action films": "أفلام حركة إسبانية",
    "spanish films": "أفلام إسبانية",
    "spanish jews": "يهود إسبان",
    "spanish television series-debuts": "مسلسلات تلفزيونية إسبانية بدأ عرضها في",
    "surinamese sport": "رياضة سورينامية",
    "swedish air force": "القوات الجوية السويدية",
    "swedish motorsport": "رياضة محركات سويدية",
    "swedish tennis": "كرة مضرب سويدية",
    "swiss businesspeople": "شخصيات أعمال سويسرية",
    "syrian websites": "مواقع ويب سورية",
    "thai television": "التلفزة التايلندية",
    "traditional pop music singers": "مغنو موسيقى بوب تقليدية",
    "trinidad and tobago football": "كرة القدم الترنيدادية",
    "turkish cookbooks": "كتب طبخ تركية",
    "turkish musical groups": "مجموعات موسيقية تركية",
    "ukrainian descent": "أصل أوكراني",
    "ukrainian-jewish descent": "أصل يهودي أوكراني",
    "vietnamese sport": "رياضة فيتنامية",
    "voice actresses": "ممثلات أداء صوتي",
    "yemeni civil war": "الحرب الأهلية اليمنية",
    "yemeni executions": "إعدامات يمنية",
    "yemeni sport": "رياضة يمنية",
    "yoruba names": "أسماء يوروبية",
    "yugoslav romantic drama films": "أفلام دراما رومانسية يوغوسلافية",
    "zimbabwean musical groups": "مجموعات موسيقية زيمبابوية",
    "zulu history": "تاريخ زولي",
}


@pytest.mark.parametrize("category, expected", fast_data.items(), ids=list(fast_data.keys()))
@pytest.mark.fast
def test_nat_match(category, expected) -> None:
    label = nat_match(category)
    assert label == expected


@pytest.mark.parametrize("category, expected", Multi_Sports_data.items(), ids=list(Multi_Sports_data.keys()))
@pytest.mark.fast
def test_Jobs_in_Multi_Sports(category, expected) -> None:
    label = Jobs_in_Multi_Sports(category)
    assert label == expected


@pytest.mark.parametrize("category, expected", data_2018_with_nat.items(), ids=list(data_2018_with_nat.keys()))
@pytest.mark.fast
def test_te_2018_with_nat(category, expected) -> None:
    label = te_2018_with_nat(category)
    assert label == expected
