"""
Tests
"""

import pytest

from src.make2_bots.countries_formats.p17_bot import (
    Get_P17,
)

get_p17_data = {
    "france international women's rugby sevens players": "لاعبات سباعيات رجبي دوليات من فرنسا",
    "spain national water polo team navigational boxes": "صناديق تصفح منتخب إسبانيا لكرة الماء",
    "soviet union national basketball team": "منتخب الاتحاد السوفيتي لكرة السلة",
    "australia national water polo team": "منتخب أستراليا لكرة الماء",
    "jamaica national women's football team navigational boxes": "صناديق تصفح منتخب جامايكا لكرة القدم للسيدات",
    "united states elections": "انتخابات الولايات المتحدة",
    "senegal national football team navigational boxes": "صناديق تصفح منتخب السنغال لكرة القدم",
    "germany national football team": "منتخب ألمانيا لكرة القدم",
    "democratic-republic-of-the-congo men's a' international footballers": "لاعبو منتخب جمهورية الكونغو الديمقراطية لكرة القدم للرجال للمحليين",
    "brazil national rugby league team": "منتخب البرازيل لدوري الرجبي",
    "norway football league": "دوري النرويج لكرة القدم",
    "wales national football team results": "نتائج منتخب ويلز لكرة القدم",
    "wales national women's rugby league team players": "لاعبات منتخب ويلز لدوري الرجبي للسيدات",
    "poland men's international footballers": "لاعبو منتخب بولندا لكرة القدم للرجال",
    "iceland national women's football team": "منتخب آيسلندا لكرة القدم للسيدات",
    "colombia national under-20 football team managers": "مدربو منتخب كولومبيا لكرة القدم تحت 20 سنة",
    "scotland football league": "دوري إسكتلندا لكرة القدم",
    "brazil national women's football team managers": "مدربو منتخب البرازيل لكرة القدم للسيدات",
    "san marino men's international footballers": "لاعبو منتخب سان مارينو لكرة القدم للرجال",
    "bolivia men's international footballers": "لاعبو منتخب بوليفيا لكرة القدم للرجال",
    "austria national basketball team": "منتخب النمسا لكرة السلة",
    "malaysia national football team results": "نتائج منتخب ماليزيا لكرة القدم",
    "hungary national men's ice hockey team": "منتخب المجر لهوكي الجليد للرجال",
    "romania national rugby union team": "منتخب رومانيا لاتحاد الرجبي",
    "cuba national football team navigational boxes": "صناديق تصفح منتخب كوبا لكرة القدم",
    "hong kong national football team matches": "مباريات منتخب هونغ كونغ لكرة القدم",
    "south korea national women's football team managers": "مدربو منتخب كوريا الجنوبية لكرة القدم للسيدات",
    "scotland national rugby union team": "منتخب إسكتلندا لاتحاد الرجبي",
    "soviet union national water polo team navigational boxes": "صناديق تصفح منتخب الاتحاد السوفيتي لكرة الماء",
    "france national football team": "منتخب فرنسا لكرة القدم",
    "united states national men's soccer team records": "سجلات منتخب الولايات المتحدة لكرة القدم للرجال",
    "united states national men's soccer team records and statistics": "سجلات وإحصائيات منتخب الولايات المتحدة لكرة القدم للرجال",
    "netherlands national rugby union team coaches": "مدربو منتخب هولندا لاتحاد الرجبي",
    "argentina national football team navigational boxes": "صناديق تصفح منتخب الأرجنتين لكرة القدم",
    "czech republic national women's football team managers": "مدربو منتخب التشيك لكرة القدم للسيدات",
    "russia national futsal team navigational boxes": "صناديق تصفح منتخب روسيا لكرة الصالات",
    "mauritania sports templates": "قوالب موريتانيا الرياضية",
    "mali summer olympics football": "كرة قدم مالي في الألعاب الأولمبية الصيفية",
    "oceania cup": "كأس أوقيانوسيا",
    "turkey national women's volleyball team coaches": "مدربو منتخب تركيا لكرة الطائرة للسيدات",
    "spain war": "حرب إسبانيا",
    "spain war and conflict": "حروب ونزاعات إسبانيا",
    "sweden national under-21 football team managers": "مدربو منتخب السويد لكرة القدم تحت 21 سنة",
    "moldova football manager history": "تاريخ مدربو كرة قدم مولدافيا",
    "ukraine women's international footballers": "لاعبات منتخب أوكرانيا لكرة القدم للسيدات",
    "fiji women's international rugby union players": "لاعبات اتحاد رجبي دوليات من فيجي",
    "aruba national football team navigational boxes": "صناديق تصفح منتخب أروبا لكرة القدم",
    "israel national football team matches": "مباريات منتخب إسرائيل لكرة القدم",
    "slovenia football league": "دوري سلوفينيا لكرة القدم",
    "slovakia sports templates": "قوالب سلوفاكيا الرياضية",
    "mexico women's international footballers": "لاعبات منتخب المكسيك لكرة القدم للسيدات",
    "soviet union national water polo team": "منتخب الاتحاد السوفيتي لكرة الماء",
    "switzerland national women's basketball team": "منتخب سويسرا لكرة السلة للسيدات",
    "democratic-republic-of-the-congo national football team matches": "مباريات منتخب جمهورية الكونغو الديمقراطية لكرة القدم",
    "canada national women's soccer team navigational boxes": "صناديق تصفح منتخب كندا لكرة القدم للسيدات",
    "peru national football team navigational boxes": "صناديق تصفح منتخب بيرو لكرة القدم",
    "australia national men's under-23 soccer team": "منتخب أستراليا لكرة القدم تحت 23 سنة للرجال",
    "canada national basketball team players": "لاعبو منتخب كندا لكرة السلة",
    "zambia women's international footballers": "لاعبات منتخب زامبيا لكرة القدم للسيدات",
    "croatia national football team": "منتخب كرواتيا لكرة القدم",
    "mauritius national women's football team": "منتخب موريشيوس لكرة القدم للسيدات",
    "philippines national women's football team navigational boxes": "صناديق تصفح منتخب الفلبين لكرة القدم للسيدات",
    "liberia national football team": "منتخب ليبيريا لكرة القدم",
    "tunisia men's a' international footballers": "لاعبو منتخب تونس لكرة القدم للرجال للمحليين",
    "mauritania national basketball team": "منتخب موريتانيا لكرة السلة",
    "croatia men's international footballers": "لاعبو منتخب كرواتيا لكرة القدم للرجال",
    "zambia men's youth international footballers": "لاعبو منتخب زامبيا لكرة القدم للشباب",
    "china university of": "جامعة الصين",
    "united states national field hockey team": "منتخب الولايات المتحدة لهوكي الميدان",
    "south africa national women's cricket team templates": "قوالب منتخب جنوب إفريقيا للكريكت للسيدات",
    "philippines national football team records": "سجلات منتخب الفلبين لكرة القدم",
    "philippines national football team records and statistics": "سجلات وإحصائيات منتخب الفلبين لكرة القدم",
    "scotland national field hockey team navigational boxes": "صناديق تصفح منتخب إسكتلندا لهوكي الميدان",
    "angola national football team lists": "قوائم منتخب أنغولا لكرة القدم",
    "canada national men's soccer team matches": "مباريات منتخب كندا لكرة القدم للرجال",
    "australia political leader": "قادة أستراليا السياسيون",
    "togo national women's basketball team": "منتخب توغو لكرة السلة للسيدات",
    "russia national handball team templates": "قوالب منتخب روسيا لكرة اليد",
    "guinea national football team": "منتخب غينيا لكرة القدم",
    "czech republic men's youth international footballers": "لاعبو منتخب التشيك لكرة القدم للشباب",
    "paraguay national women's football team navigational boxes": "صناديق تصفح منتخب باراغواي لكرة القدم للسيدات",
    "russia national volleyball team": "منتخب روسيا لكرة الطائرة",
    "malaysia women's international footballers": "لاعبات منتخب ماليزيا لكرة القدم للسيدات",
    "belgium national basketball team": "منتخب بلجيكا لكرة السلة",
    "morocco political leader": "قادة المغرب السياسيون",
    "china afc women's asian cup squad": "تشكيلات الصين في كأس آسيا للسيدات",
    "north korea men's international footballers": "لاعبو منتخب كوريا الشمالية لكرة القدم للرجال",
    "malawi men's international footballers": "لاعبو منتخب مالاوي لكرة القدم للرجال",
    "angola basketball cup": "كأس أنغولا لكرة السلة",
    "tanzania sports templates": "قوالب تنزانيا الرياضية",
    "kosovo national football team managers": "مدربو منتخب كوسوفو لكرة القدم",
    "syria political leader": "قادة سوريا السياسيون",
    "japan political leader": "قادة اليابان السياسيون",
    "rwanda political leader": "قادة رواندا السياسيون",
    "denmark national field hockey team navigational boxes": "صناديق تصفح منتخب الدنمارك لهوكي الميدان",
    "south korea national rugby sevens team coaches": "مدربو منتخب كوريا الجنوبية لسباعيات الرجبي",
    "denmark national men's ice hockey team": "منتخب الدنمارك لهوكي الجليد للرجال",
    "france national under-21 football team": "منتخب فرنسا لكرة القدم تحت 21 سنة",
    "england national women's rugby union team matches": "مباريات منتخب إنجلترا لاتحاد الرجبي للسيدات",
    "costa rica sports templates": "قوالب كوستاريكا الرياضية",
    "angola men's international footballers": "لاعبو منتخب أنغولا لكرة القدم للرجال",
    "fiji national rugby union team": "منتخب فيجي لاتحاد الرجبي",
    "bulgaria women's international footballers": "لاعبات منتخب بلغاريا لكرة القدم للسيدات",
    "mauritania men's under-20 international footballers": "لاعبو منتخب موريتانيا تحت 20 سنة لكرة القدم للرجال",
    "poland summer olympics football": "كرة قدم بولندا في الألعاب الأولمبية الصيفية",
    "maldives national women's football team": "منتخب جزر المالديف لكرة القدم للسيدات",
    "australia national netball team": "منتخب أستراليا لكرة الشبكة",
    "brazil national under-23 football team results": "نتائج منتخب البرازيل لكرة القدم تحت 23 سنة",
    "armenia national football team managers": "مدربو منتخب أرمينيا لكرة القدم",
    "palestine national football team": "منتخب فلسطين لكرة القدم",
    "italy national women's football team": "منتخب إيطاليا لكرة القدم للسيدات",
    "paraguay national handball team templates": "قوالب منتخب باراغواي لكرة اليد",
    "england football league": "دوري إنجلترا لكرة القدم",
    "ghana national football team": "منتخب غانا لكرة القدم",
    "italy national women's water polo team coaches": "مدربو منتخب إيطاليا لكرة الماء للسيدات",
    "ivory coast national football team navigational boxes": "صناديق تصفح منتخب ساحل العاج لكرة القدم",
    "united states national rugby league team coaches": "مدربو منتخب الولايات المتحدة لدوري الرجبي",
    "south africa national soccer team results": "نتائج منتخب جنوب إفريقيا لكرة القدم",
    "chad sports templates": "قوالب تشاد الرياضية",
    "lithuania men's under-21 international footballers": "لاعبو منتخب ليتوانيا تحت 21 سنة لكرة القدم للرجال",
    "uzbekistan afc asian cup squad": "تشكيلات أوزبكستان في كأس آسيا",
    "latvia men's youth international footballers": "لاعبو منتخب لاتفيا لكرة القدم للشباب",
    "serbia national men's basketball team": "منتخب صربيا لكرة السلة للرجال",
    "guam men's international footballers": "لاعبو منتخب غوام لكرة القدم للرجال",
    "tunisia political leader": "قادة تونس السياسيون",
    "china national football team results": "نتائج منتخب الصين لكرة القدم",
    "senegal national football team matches": "مباريات منتخب السنغال لكرة القدم",
    "germany national under-21 football team managers": "مدربو منتخب ألمانيا لكرة القدم تحت 21 سنة",
    "aruba men's under-20 international footballers": "لاعبو منتخب أروبا تحت 20 سنة لكرة القدم للرجال",
    "israel war": "حرب إسرائيل",
    "israel war and conflict": "حروب ونزاعات إسرائيل",
    "mauritius political leader": "قادة موريشيوس السياسيون",
    "georgia governorate": "حكومة جورجيا",
    "africa football league": "دوري إفريقيا لكرة القدم",
    "kazakhstan national handball team templates": "قوالب منتخب كازاخستان لكرة اليد",
    "switzerland national men's ice hockey team": "منتخب سويسرا لهوكي الجليد للرجال",
    "slovakia national handball team templates": "قوالب منتخب سلوفاكيا لكرة اليد",
    "qatar national football team navigational boxes": "صناديق تصفح منتخب قطر لكرة القدم",
    "new zealand national women's cricket team": "منتخب نيوزيلندا للكريكت للسيدات",
    "russia national women's basketball team": "منتخب روسيا لكرة السلة للسيدات",
    "england national women's cricket team": "منتخب إنجلترا للكريكت للسيدات",
    "iceland women's youth international footballers": "لاعبات منتخب آيسلندا لكرة القدم للشابات",
    "ecuador national football team results": "نتائج منتخب الإكوادور لكرة القدم",
    "nigeria professional football league": "دوري نيجيريا لكرة القدم للمحترفين",
    "south korea national volleyball team navigational boxes": "صناديق تصفح منتخب كوريا الجنوبية لكرة الطائرة",
    "switzerland men's youth international footballers": "لاعبو منتخب سويسرا لكرة القدم للشباب",
    "czech republic national futsal team navigational boxes": "صناديق تصفح منتخب التشيك لكرة الصالات",
    "finland national football team navigational boxes": "صناديق تصفح منتخب فنلندا لكرة القدم",
    "china national baseball team navigational boxes": "صناديق تصفح منتخب الصين لكرة القاعدة",
    "new zealand national women's football team managers": "مدربو منتخب نيوزيلندا لكرة القدم للسيدات",
    "new zealand national women's rugby league team": "منتخب نيوزيلندا لدوري الرجبي للسيدات",
    "south africa national water polo team navigational boxes": "صناديق تصفح منتخب جنوب إفريقيا لكرة الماء",
    "portugal national football team records": "سجلات منتخب البرتغال لكرة القدم",
    "portugal national football team records and statistics": "سجلات وإحصائيات منتخب البرتغال لكرة القدم",
    "england war": "حرب إنجلترا",
    "england war and conflict": "حروب ونزاعات إنجلترا",
    "india national women's football team": "منتخب الهند لكرة القدم للسيدات",
    "cyprus women's international footballers": "لاعبات منتخب قبرص لكرة القدم للسيدات",
    "cameroon national women's football team navigational boxes": "صناديق تصفح منتخب الكاميرون لكرة القدم للسيدات",
    "argentina national field hockey team navigational boxes": "صناديق تصفح منتخب الأرجنتين لهوكي الميدان",
    "mexico national women's football team navigational boxes": "صناديق تصفح منتخب المكسيك لكرة القدم للسيدات",
    "spain national women's water polo team coaches": "مدربو منتخب إسبانيا لكرة الماء للسيدات",
    "spain national rugby union team navigational boxes": "صناديق تصفح منتخب إسبانيا لاتحاد الرجبي",
    "guinea-bissau women's international footballers": "لاعبات منتخب غينيا بيساو لكرة القدم للسيدات",
    "guam women's international footballers": "لاعبات منتخب غوام لكرة القدم للسيدات",
    "peru men's youth international footballers": "لاعبو منتخب بيرو لكرة القدم للشباب",
}


@pytest.mark.parametrize("category, expected", get_p17_data.items(), ids=list(get_p17_data.keys()))
@pytest.mark.fast
def test_get_p17(category, expected) -> None:
    label = Get_P17(category)
    assert label == expected
