"""

TODO: write tests
TODO: search for (# Test with basic inputs)

"""

import pytest
from ArWikiCats.make_bots.matables_bots.bot import add_to_new_players
from ArWikiCats import resolve_arabic_category_label
from ArWikiCats.make_bots.matables_bots.data import Keep_it_last


@pytest.mark.fast
def test_add_to_new_players() -> None:
    # Test with basic inputs
    add_to_new_players("english", "arabic")

    # Test with empty strings (should not add anything)
    add_to_new_players("", "arabic")
    add_to_new_players("english", "")

    # Test with both empty (should not add anything)
    add_to_new_players("", "")


@pytest.mark.fast
def test_Keep_it_last() -> None:
    # Arabic translation of term "remakes of" ("معاد إنتاجها") should be at last:

    result = resolve_arabic_category_label("Category:remakes of historical documents")
    assert result == "تصنيف:وثائق تاريخية معاد إنتاجها"


fast_data = {
    "Category:American remakes of Argentine films": "x",
    "Category:American remakes of Belgian films": "x",
    "Category:American remakes of Brazilian films": "x",
    "Category:American remakes of British films": "x",
    "Category:American remakes of Canadian films": "x",
    "Category:American remakes of Danish films": "x",
    "Category:American remakes of Dutch films": "x",
    "Category:American remakes of foreign films": "x",
    "Category:American remakes of French films": "x",
    "Category:American remakes of German films": "x",
    "Category:American remakes of Hong Kong films": "x",
    "Category:American remakes of Indian films": "x",
    "Category:American remakes of Israeli films": "x",
    "Category:American remakes of Italian films": "x",
    "Category:American remakes of Japanese films": "x",
    "Category:American remakes of Mexican films": "x",
    "Category:American remakes of Norwegian films": "x",
    "Category:American remakes of South Korean films": "x",
    "Category:American remakes of Spanish films": "x",
    "Category:American remakes of Swedish films": "x",
    "Category:American remakes of Thai films": "x",
    "Category:Assamese-language remakes of Hindi films": "x",
    "Category:Assamese-language remakes of Malayalam films": "x",
    "Category:Bangladeshi remakes of American films": "x",
    "Category:Bangladeshi remakes of foreign films": "x",
    "Category:Bangladeshi remakes of Indian films": "x",
    "Category:Bangladeshi remakes of Tamil films": "x",
    "Category:British remakes of American films": "x",
    "Category:British remakes of French films": "x",
    "Category:British remakes of German films": "x",
    "Category:Bangladeshi remakes of Telugu films": "x",
    "Category:Bengali remakes of English films": "x",
    "Category:Bengali remakes of Hindi films": "x",
    "Category:Bengali remakes of Kannada films": "x",
    "Category:Bengali remakes of Malayalam films": "x",
    "Category:Bengali remakes of Marathi films": "x",
    "Category:Bengali remakes of Punjabi films": "x",
    "Category:Bengali remakes of Tamil films": "x",
    "Category:Bengali remakes of Telugu films": "x",
    "Category:Bhojpuri remakes of Tamil films": "x",
    "Category:Bhojpuri remakes of Telugu films": "x",
    "": "x",
    "Category:Chinese remakes of American films": "x",
    "Category:Chinese remakes of foreign films": "x",
    "Category:Chinese remakes of Japanese films": "x",
    "Category:Chinese remakes of South Korean films": "x",
    "Category:Dutch remakes of British films": "x",
    "Category:Dutch remakes of foreign films": "x",
    "Category:French remakes of American films": "x",
    "Category:Gujarati remakes of Marathi films": "x",
    "Category:Gujarati remakes of Tamil films": "x",
    "Category:Hindi remakes of Bengali films": "x",
    "Category:Hindi remakes of English films": "x",
    "Category:Hindi remakes of Gujarati films": "x",
    "Category:Hindi remakes of Kannada films": "x",
    "Category:Hindi remakes of Malayalam films": "x",
    "Category:Hindi remakes of Marathi films": "x",
    "Category:Hindi remakes of Odia films": "x",
    "Category:Hindi remakes of Punjabi films": "x",
    "Category:Hindi remakes of Rajasthani films": "x",
    "Category:Hindi remakes of silent films": "x",
    "Category:Hindi remakes of Tamil films": "x",
    "Category:Hindi remakes of Telugu films": "x",
    "Category:Hong Kong remakes of American films": "x",
    "Category:Indian remakes of American films": "x",
    "Category:Indian remakes of British films": "x",
    "Category:Indian remakes of foreign films": "x",
    "Category:Indian remakes of French films": "x",
    "Category:Indian remakes of Hong Kong films": "x",
    "Category:Indian remakes of Italian films": "x",
    "Category:Indian remakes of Japanese films": "x",
    "Category:Indian remakes of Pakistani films": "x",
    "Category:Indian remakes of South Korean films": "x",
    "Category:Indian remakes of Spanish films": "x",
    "Category:Indian remakes of Thai films": "x",
    "Category:Iranian remakes of American films": "x",
    "Category:Iranian remakes of foreign films": "x",
    "Category:Italian remakes of foreign films": "x",
    "Category:Italian remakes of French films": "x",
    "Category:Japanese remakes of American films": "x",
    "Category:Japanese remakes of foreign films": "x",
    "Category:Japanese remakes of South Korean films": "x",
    "Category:Kannada remakes of Bengali films": "x",
    "Category:Kannada remakes of Hindi films": "x",
    "Category:Kannada remakes of Malayalam films": "x",
    "Category:Kannada remakes of Marathi films": "x",
    "Category:Kannada remakes of Rajasthani films": "x",
    "Category:Kannada remakes of Tamil films": "x",
    "Category:Kannada remakes of Telugu films": "x",
    "Category:Malayalam remakes of Bengali films": "x",
    "Category:Malayalam remakes of Hindi films": "x",
    "Category:Malayalam remakes of Kannada films": "x",
    "Category:Malayalam remakes of Marathi films": "x",
    "Category:Malayalam remakes of Tamil films": "x",
    "Category:Malayalam remakes of Telugu films": "x",
    "Category:Maldivian remakes of Indian films": "x",
    "Category:Marathi remakes of Bengali films": "x",
    "Category:Marathi remakes of Hindi films": "x",
    "Category:Marathi remakes of Kannada films": "x",
    "Category:Marathi remakes of Malayalam films": "x",
    "Category:Marathi remakes of Rajasthani films": "x",
    "Category:Marathi remakes of Tamil films": "x",
    "Category:Marathi remakes of Telugu films": "x",
    "Category:Meitei remakes of Telugu films": "x",
    "Category:Odia remakes of Bengali films": "x",
    "Category:Odia remakes of Hindi films": "x",
    "Category:Odia remakes of Kannada films": "x",
    "Category:Odia remakes of Malayalam films": "x",
    "Category:Odia remakes of Marathi films": "x",
    "Category:Odia remakes of Punjabi films": "x",
    "Category:Odia remakes of Tamil films": "x",
    "Category:Odia remakes of Telugu films": "x",
    "Category:Pakistani remakes of American films": "x",
    "Category:Pakistani remakes of foreign films": "x",
    "Category:Pakistani remakes of Indian films": "x",
    "Category:Philippine remakes of foreign films": "x",
    "Category:Philippine remakes of South Korean films": "x",
    "Category:Punjabi remakes of Hindi films": "x",
    "Category:Punjabi remakes of Malayalam films": "x",
    "Category:Punjabi remakes of Marathi films": "x",
    "Category:Punjabi remakes of Tamil films": "x",
    "Category:Punjabi remakes of Telugu films": "x",
    "Category:Remakes of American films": "x",
    "Category:Remakes of Argentine films": "x",
    "Category:Remakes of Australian films": "x",
    "Category:Remakes of Austrian films": "x",
    "Category:Remakes of Belgian films": "x",
    "Category:Remakes of Brazilian films": "x",
    "Category:Remakes of British films": "x",
    "Category:Remakes of Burmese films": "x",
    "Category:Remakes of Canadian films": "x",
    "Category:Remakes of Chilean films": "x",
    "Category:Remakes of Chinese films": "x",
    "Category:Remakes of Danish films": "x",
    "Category:Remakes of Dutch films": "x",
    "Category:Remakes of Finnish films": "x",
    "Category:Remakes of French films": "x",
    "Category:Remakes of German films": "x",
    "Category:Remakes of Hong Kong films": "x",
    "Category:Remakes of Hungarian films": "x",
    "Category:Remakes of Icelandic films": "x",
    "Category:Remakes of Indian films": "x",
    "Category:Remakes of Indian television series": "x",
    "Category:Remakes of Indonesian films": "x",
    "Category:Remakes of Irish films": "x",
    "Category:Remakes of Italian films": "x",
    "Category:Remakes of Japanese films": "x",
    "Category:Remakes of Malaysian films": "x",
    "Category:Remakes of Mexican films": "x",
    "Category:Remakes of Norwegian films": "x",
    "Category:Remakes of Pakistani films": "x",
    "Category:Remakes of Philippine films": "x",
    "Category:Remakes of Russian films": "x",
    "Category:Remakes of South Korean films": "x",
    "Category:Remakes of Spanish films": "x",
    "Category:Remakes of Sri Lankan films": "x",
    "Category:Remakes of Swedish films": "x",
    "Category:Remakes of Taiwanese films": "x",
    "Category:Remakes of Thai films": "x",
    "Category:Remakes of Turkish films": "x",
    "Category:Sound film remakes of silent films": "x",
    "Category:South Korean remakes of Brazilian films": "x",
    "Category:South Korean remakes of foreign films": "x",
    "Category:South Korean remakes of Japanese films": "x",
    "Category:South Korean remakes of Spanish films": "x",
    "Category:South Korean remakes of Taiwanese films": "x",
    "Category:Spanish remakes of Argentine films": "x",
    "Category:Spanish remakes of foreign films": "x",
    "Category:Spanish remakes of French films": "x",
    "Category:Spanish remakes of Italian films": "x",
    "Category:Sri Lankan remakes of Indian films": "x",
    "Category:Taiwanese remakes of foreign films": "x",
    "Category:Taiwanese remakes of South Korean films": "x",
    "Category:Tamil remakes of Bengali films": "x",
    "Category:Tamil remakes of Hindi films": "x",
    "Category:Tamil remakes of Kannada films": "x",
    "Category:Tamil remakes of Malayalam films": "x",
    "Category:Tamil remakes of Marathi films": "x",
    "Category:Tamil remakes of Telugu films": "x",
    "Category:Television remakes of films": "x",
    "Category:Telugu remakes of Bengali films": "x",
    "Category:Telugu remakes of Gujarati films": "x",
    "Category:Telugu remakes of Hindi films": "x",
    "Category:Telugu remakes of Kannada films": "x",
    "Category:Telugu remakes of Malayalam films": "x",
    "Category:Telugu remakes of Marathi films": "x",
    "Category:Telugu remakes of Punjabi films": "x",
    "Category:Telugu remakes of Tamil films": "x",
    "Category:Thai remakes of foreign films": "x",
    "Category:Thai remakes of Taiwanese films": "x",
}


@pytest.mark.parametrize("category, expected", fast_data.items(), ids=list(fast_data.keys()))
@pytest.mark.fast
def test_Keep_it_last_extended(category: str, expected: str) -> None:
    # Arabic translation of term "remakes of" ("معاد إنتاجها") should be at last:

    label = resolve_arabic_category_label(category)
    assert label == expected
