nats = {
    "abkhaz": {"mens": "أبخاز", "womens": "أبخازيات"},
    "abkhazian": {"mens": "أبخازيون", "womens": "أبخازيات"},
    "zanzibari": {"mens": "زنجباريون", "womens": "زنجباريات"},
    "anguillan": {"mens": "أنغويلانيون", "womens": "أنغويلانيات"},
    "afghan": {"mens": "أفغان", "womens": "أفغانيات"},
    "french guianan": {"mens": "غويانيون فرنسيون", "womens": "غويانيات فرنسيات"},
    "bissau-guinean": {"mens": "غينيون بيساويون", "womens": "غينيات بيساويات"},
    "zaïrean": {"mens": "زائيريون", "womens": "زائيريات"},
    "turkmenistan": {"mens": "تركمانيون", "womens": "تركمانيات"},
    "democratic republic of the congo": {"mens": "كونغويون ديمقراطيون", "womens": "كونغويات ديمقراطيات"},
    "prussian": {"mens": "بروسيون", "womens": "بروسيات"},
    "north yemeni": {"mens": "يمنيون شماليون", "womens": "يمنيات شماليات"},
    "south yemeni": {"mens": "يمنيون جنوبيون", "womens": "يمنيات جنوبيات"},
}


Nat_mens = {x: v["mens"] for x, v in nats.items()}
Nat_Womens = {x: v["womens"] for x, v in nats.items()}

jobs_mens_data = {
    "scholars of islam": "باحثون عن الإسلام",
    "women's rights activists": "ناشطون في حقوق المرأة",
    "convicted-of-murder": "أدينوا بالقتل",
    "classical europop cheerleaders": "قادة تشجيع يوروبوب كلاسيكيون",
    "classical europop composers": "ملحنو يوروبوب كلاسيكيون",
    "abidat rma pianists": "عازفو بيانو عبيدات الرما",
    "abidat rma record producers": "منتجو تسجيلات عبيدات الرما",
    "historical objectivists": "موضوعيون تاريخيون",
    "historical opera authors": "مؤلفو أوبرا تاريخيون",
    "men's sailing (sport) power forwards": "مهاجمون أقوياء الجسم رياضة إبحار رجالية",
    "men's sailing (sport) quarterbacks": "أظهرة رباعيون رياضة إبحار رجالية",
    "men's sailing (sport) racing centers": "لاعبو وسط سباق رياضة إبحار رجالية",
    "ski-orienteering quarterbacks": "أظهرة رباعيون سباق تزلج موجه",
    "abidat rma saxophonists": "عازفو سكسفون عبيدات الرما",
    "abidat rma singer-songwriters": "مغنون وكتاب أغاني عبيدات الرما",
}

short_womens_jobs = {
    "scholars of islam": "باحثات عن الإسلام",
    "women's rights activists": "ناشطات في حقوق المرأة",
    "actresses": "ممثلات",
    "businesswomen": "سيدات أعمال",
    "deaf actresses": "ممثلات صم",
    "deafblind actresses": "ممثلات صم ومكفوفات",
    "film actresses": "ممثلات أفلام",
    "lesbians": "سحاقيات",
    "musical theatre actresses": "ممثلات مسرحيات موسيقية",
    "nuns": "راهبات",
    "pornographic film actresses": "ممثلات أفلام إباحية",
    "princesses": "أميرات",
    "radio actresses": "ممثلات راديو",
    "silent film actresses": "ممثلات أفلام صامتة",
    "sportswomen": "رياضيات",
    "women's water skiing players": "لاعبات تزلج على الماء نسائية",
    "women's water skiing racing players": "لاعبات سباق تزلج على الماء نسائية",
    "women's waterskiing players": "لاعبات تزلج على الماء نسائية",
    "women's waterskiing racing players": "لاعبات سباق تزلج على الماء نسائية",
    "women's weightlifting players": "لاعبات رفع أثقال نسائية",
    "women's weightlifting racing players": "لاعبات سباق رفع أثقال نسائية",
    "women's wheelchair basketball players": "لاعبات كرة سلة على كراسي متحركة نسائية",
    "women's wheelchair beach handball players": "لاعبات كرة يد شاطئية على كراسي متحركة نسائية",
    "stage actresses": "ممثلات مسرح",
    "television actresses": "ممثلات تلفزيون",
    "video game actresses": "ممثلات ألعاب فيديو",
    "voice actresses": "ممثلات أداء صوتي",
    "women in business": "سيدات أعمال",
    "women in politics": "سياسيات",
    "women's wrestling racing players": "لاعبات سباق مصارعة نسائية",
    "women's wushu players": "لاعبات ووشو نسائية",
    "women's wushu racing players": "لاعبات سباق ووشو نسائية",
    "women's xiangqi players": "لاعبات شطرنج صيني نسائية",
    "women's xiangqi racing players": "لاعبات سباق شطرنج صيني نسائية",
    "women's yacht racing players": "لاعبات سباقات يخوت نسائية",
}

NAT_BEFORE_OCC = [
    "convicted-of-murder",
    "murdered abroad",
    "contemporary",
    "tour de france stage winners",
    "deafblind",
    "deaf",
    "blind",
    "jews",
    "women's rights activists",
    "human rights activists",
    "imprisoned",
    "imprisoned abroad",
    "conservationists",
    "expatriate",
    "defectors",
    "scholars of islam",
    "scholars-of-islam",
    "amputees",
    "expatriates",
    "scholars of",
    "executed abroad",
    "emigrants",
]

RELIGIOUS_KEYS_PP = {
    "bahá'ís": {"mens": "بهائيون", "womens": "بهائيات"},
    "yazidis": {"mens": "يزيديون", "womens": "يزيديات"},
    "christians": {"mens": "مسيحيون", "womens": "مسيحيات"},
    "anglican": {"mens": "أنجليكيون", "womens": "أنجليكيات"},
    "anglicans": {"mens": "أنجليكيون", "womens": "أنجليكيات"},
    "episcopalians": {"mens": "أسقفيون", "womens": "أسقفيات"},
    "christian": {"mens": "مسيحيون", "womens": "مسيحيات"},
    "buddhist": {"mens": "بوذيون", "womens": "بوذيات"},
    "nazi": {"mens": "نازيون", "womens": "نازيات"},
    "muslim": {"mens": "مسلمون", "womens": "مسلمات"},
    "coptic": {"mens": "أقباط", "womens": "قبطيات"},
    "islamic": {"mens": "إسلاميون", "womens": "إسلاميات"},
    "hindus": {"mens": "هندوس", "womens": "هندوسيات"},
    "hindu": {"mens": "هندوس", "womens": "هندوسيات"},
    "protestant": {"mens": "بروتستانتيون", "womens": "بروتستانتيات"},
    "methodist": {"mens": "ميثوديون لاهوتيون", "womens": "ميثوديات لاهوتيات"},
    "jewish": {"mens": "يهود", "womens": "يهوديات"},
    "jews": {"mens": "يهود", "womens": "يهوديات"},
    "zaydis": {"mens": "زيود", "womens": "زيديات"},
    "zaydi": {"mens": "زيود", "womens": "زيديات"},
    "sufis": {"mens": "صوفيون", "womens": "صوفيات"},
    "religious": {"mens": "دينيون", "womens": "دينيات"},
    "muslims": {"mens": "مسلمون", "womens": "مسلمات"},
    "shia muslims": {"mens": "مسلمون شيعة", "womens": "مسلمات شيعيات"},
    "shi'a muslims": {"mens": "مسلمون شيعة", "womens": "مسلمات شيعيات"},
    "sunni muslims": {"mens": "مسلمون سنة", "womens": "مسلمات سنيات"},
    "shia muslim": {"mens": "مسلمون شيعة", "womens": "مسلمات شيعيات"},
    "shi'a muslim": {"mens": "مسلمون شيعة", "womens": "مسلمات شيعيات"},
    "sunni muslim": {"mens": "مسلمون سنة", "womens": "مسلمات سنيات"},
    "evangelical": {"mens": "إنجيليون", "womens": "إنجيليات"},
    "venerated": {"mens": "مبجلون", "womens": "مبجلات"},
    "saints": {"mens": "قديسون", "womens": "قديسات"},
}

NAT_BEFORE_OCC.extend(key for key in RELIGIOUS_KEYS_PP.keys())

MEN_WOMENS_WITH_NATO = {
    "eugenicists": {
        "mens": "علماء {nato} متخصصون في تحسين النسل",
        "womens": "عالمات {nato} متخصصات في تحسين النسل",
    },
    "politicians who committed suicide": {
        "mens": "سياسيون {nato} أقدموا على الانتحار",
        "womens": "سياسيات {nato} أقدمن على الانتحار",
    },
    "contemporary artists": {
        "mens": "فنانون {nato} معاصرون",
        "womens": "فنانات {nato} معاصرات",
    },
}
