"""
Tests
"""

import pytest

# from ArWikiCats.new_resolvers.jobs_resolvers.mens import mens_resolver_labels
from ArWikiCats import resolve_label_ar


test_data_0 = {
    "Male film score composers": "مؤلفو موسيقى أفلام",
    "American male film score composers": "مؤلفو موسيقى أفلام أمريكيون ذكور",
}

test_sport_data = {
    "Canadian male wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة ذكور كنديون",
    "Male long-distance runners": "عداؤو مسافات طويلة ذكور",
    "Male runners by nationality": "عداؤون ذكور حسب الجنسية",
    "Male steeplechase runners": "عداؤو موانع ذكور",
    "Moroccan male middle-distance runners": "عداؤو مسافات متوسطة ذكور مغاربة",
    "Norwegian male pair skaters": "متزلجون فنيون على الجليد ذكور نرويجيون",
    "Norwegian male single skaters": "متزلجون فرديون ذكور نرويجيون",
    "Australian male sprinters": "عداؤون سريعون ذكور أستراليون",
    "Egyptian male sport shooters": "لاعبو رماية ذكور مصريون",
    "Icelandic male athletes": "لاعبو قوى ذكور آيسلنديون",
    "Icelandic male runners": "عداؤون ذكور آيسلنديون",
    "Icelandic male steeplechase runners": "عداؤو موانع ذكور آيسلنديون",
}

test_data2 = {
    "Cultural depictions of male monarchs": "تصوير ثقافي عن ملكيين ذكور",
    "Male adult models": "عارضون بالغون ذكور",

    "19th century male composers by nationality": "ملحنون ذكور في القرن 19 حسب الجنسية",
    "male actors": "ممثلون ذكور",
    "male artists": "فنانون ذكور",
    "male composers": "ملحنون ذكور",
    "male musicians": "موسيقيون ذكور",
    "male singers": "مغنون ذكور",
    "male writers": "كتاب ذكور",
    "painters male muslims": "رسامون ذكور مسلمون",
    "nepalese male film actors": "ممثلو أفلام ذكور نيباليون",
    "japanese male film actors": "ممثلو أفلام ذكور يابانيون",

    "Male chefs from Northern Ireland": "طباخون ذكور من أيرلندا الشمالية",
    "Male fiddlers from Northern Ireland": "عازفو كمان ذكور من أيرلندا الشمالية",
    "Male sailors (sport) from Northern Ireland": "بحارة رياضيون ذكور من أيرلندا الشمالية",
    "Male sport shooters from Northern Ireland": "لاعبو رماية ذكور من أيرلندا الشمالية",
    "21st-century male artists from Northern Ireland": "فنانون ذكور من أيرلندا الشمالية في القرن 21",

    "Expatriate male actors in New Zealand": "ممثلون ذكور مغتربون في نيوزيلندا",
    "Expatriate male actors": "ممثلون ذكور مغتربون",
    "Male actors from Charleston, West Virginia": "ممثلون ذكور من تشارلستون (فرجينيا الغربية)",
    "Male actors from Fairfax, Virginia": "ممثلون ذكور من فيرفاكس (فرجينيا)",
    "Zimbabwean male film actors": "ممثلو أفلام ذكور زيمبابويون",
    "Male classical composers": "ملحنون كلاسيكيون ذكور",
    "Male classical composers from Northern Ireland": "ملحنون كلاسيكيون ذكور من أيرلندا الشمالية",
    "Romanian male classical composers": "ملحنون كلاسيكيون ذكور رومان",
    "Scottish male classical composers": "ملحنون كلاسيكيون ذكور إسكتلنديون",
    "Ukrainian male classical composers": "ملحنون كلاسيكيون ذكور أوكرانيون",
    "Lithuanian male classical composers": "ملحنون كلاسيكيون ذكور ليتوانيون",
    "Male classical composers by nationality": "ملحنون كلاسيكيون ذكور حسب الجنسية",
    "Male classical composers from Bohemia": "ملحنون كلاسيكيون ذكور من بوهيميا",
    "Greek male classical composers": "ملحنون كلاسيكيون ذكور يونانيون",
    "Israeli male classical composers": "ملحنون كلاسيكيون ذكور إسرائيليون",
    "Estonian male classical composers": "ملحنون كلاسيكيون ذكور إستونيون",
    "Egyptian male classical composers": "ملحنون كلاسيكيون ذكور مصريون",
    "Cuban male classical composers": "ملحنون كلاسيكيون ذكور كوبيون",
    "Argentine male classical composers": "ملحنون كلاسيكيون ذكور أرجنتينيون",
    "Armenian male classical composers": "ملحنون كلاسيكيون ذكور أرمن",
    "Brazilian male classical composers": "ملحنون كلاسيكيون ذكور برازيليون",
    "Bulgarian male classical composers": "ملحنون كلاسيكيون ذكور بلغاريون",
    "Chilean male classical composers": "ملحنون كلاسيكيون ذكور تشيليون",
    "Swiss male classical composers": "ملحنون كلاسيكيون ذكور سويسريون",
    "Welsh male classical composers": "ملحنون كلاسيكيون ذكور ويلزيون",
    "Norwegian male classical composers": "ملحنون كلاسيكيون ذكور نرويجيون",
    "Portuguese male classical composers": "ملحنون كلاسيكيون ذكور برتغاليون",
    "Finnish male classical composers": "ملحنون كلاسيكيون ذكور فنلنديون",
    "Hungarian male classical composers": "ملحنون كلاسيكيون ذكور مجريون",
    "Canadian male classical composers": "ملحنون كلاسيكيون ذكور كنديون",
    "African-American male classical composers": "ملحنون كلاسيكيون ذكور أمريكيون أفارقة",
    "Swedish male classical composers": "ملحنون كلاسيكيون ذكور سويديون",
    "American male classical composers": "ملحنون كلاسيكيون ذكور أمريكيون",
    "Australian male classical composers": "ملحنون كلاسيكيون ذكور أستراليون",
    "Austrian male classical composers": "ملحنون كلاسيكيون ذكور نمساويون",
    "Belgian male classical composers": "ملحنون كلاسيكيون ذكور بلجيكيون",
    "British male classical composers": "ملحنون كلاسيكيون ذكور بريطانيون",
    "Chinese male classical composers": "ملحنون كلاسيكيون ذكور صينيون",
    "Czech male classical composers": "ملحنون كلاسيكيون ذكور تشيكيون",
    "Danish male classical composers": "ملحنون كلاسيكيون ذكور دنماركيون",
    "Dutch male classical composers": "ملحنون كلاسيكيون ذكور هولنديون",
    "English male classical composers": "ملحنون كلاسيكيون ذكور إنجليز",
    "French male classical composers": "ملحنون كلاسيكيون ذكور فرنسيون",
    "German male classical composers": "ملحنون كلاسيكيون ذكور ألمان",
    "Irish male classical composers": "ملحنون كلاسيكيون ذكور أيرلنديون",
    "Italian male classical composers": "ملحنون كلاسيكيون ذكور إيطاليون",
    "Japanese male classical composers": "ملحنون كلاسيكيون ذكور يابانيون",
    "Mexican male classical composers": "ملحنون كلاسيكيون ذكور مكسيكيون",
    "Polish male classical composers": "ملحنون كلاسيكيون ذكور بولنديون",
    "Russian male classical composers": "ملحنون كلاسيكيون ذكور روس",
    "Soviet male classical composers": "ملحنون كلاسيكيون ذكور سوفيت",
    "Spanish male classical composers": "ملحنون كلاسيكيون ذكور إسبان",

    "Antigua and Barbuda male actors": "ممثلون ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male boxers": "ملاكمون ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male canoeists": "متسابقو قوارب الكانوي ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male cyclists": "دراجون ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male freestyle swimmers": "سباحو تزلج حر ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male sailors (sport)": "بحارة رياضيون ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male swimmers": "سباحون ذكور أنتيغويون وبربوديون",
    "Antigua and Barbuda male tennis players": "لاعبو كرة مضرب ذكور أنتيغويون وبربوديون",
    "South African male painters": "رسامون ذكور جنوب إفريقيون",
    "south african male non-fiction writers": "كتاب غير روائيين ذكور جنوب إفريقيون",
    "South African male non-fiction writers": "كتاب غير روائيين ذكور جنوب إفريقيون",
    "male actors from the west midlands (county)": "ممثلون ذكور من مقاطعة ميدلاند الغربية",
    "Indian male classical musicians": "موسيقيون كلاسيكيون ذكور هنود",
    "American male classical musicians": "موسيقيون كلاسيكيون ذكور أمريكيون",
    "Male opera composers": "ملحنو أوبرا ذكور",
    "male models": "عارضو أزياء ذكور",
    "male sport shooters": "لاعبو رماية ذكور",
    "male actors from west midlands (county)": "ممثلون ذكور من مقاطعة ميدلاند الغربية",
    "canadian male wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة ذكور كنديون",

    "Paintings of male saints": "لوحات عن قديسون ذكور",
    "Jewish male actors by nationality": "ممثلون ذكور يهود حسب الجنسية",
    "19th-century American male singers": "مغنون ذكور أمريكيون في القرن 19",
    "19th-century Austrian male musicians": "موسيقيون ذكور نمساويون في القرن 19",
    "19th-century Swiss male opera singers": "مغنو أوبرا ذكور سويسريون في القرن 19",
    "20th-century Democratic Republic of Congo male singers": "مغنون ذكور كونغويون ديمقراطيون في القرن 20",
    "20th-century Ukrainian male singers": "مغنون ذكور أوكرانيون في القرن 20",
    "21st-century Chilean male artists": "فنانون ذكور تشيليون في القرن 21",
    "21st-century male actors from Georgia (country)": "ممثلون ذكور من جورجيا في القرن 21",
    "Argentine male bobsledders": "متزلجون جماعيون ذكور أرجنتينيون",
    "Argentine male singer-songwriters": "مغنون وكتاب أغاني ذكور أرجنتينيون",
    "Argentine male singers": "مغنون ذكور أرجنتينيون",
    "Austrian male artistic gymnasts": "لاعبو جمباز فني ذكور نمساويون",
    "Bangladeshi male actors": "ممثلون ذكور بنغلاديشيون",
    "Bangladeshi male golfers": "لاعبو غولف ذكور بنغلاديشيون",
    "Belarusian male freestyle skiers": "ممارسو تزلج حر ذكور بيلاروسيون",
    "Belarusian male skiers": "متزحلقون ذكور بيلاروسيون",
    "British male actors by medium": "ممثلون ذكور بريطانيون حسب الوسط",
    "Bulgarian male stage actors": "ممثلو مسرح ذكور بلغاريون",
    "Comorian male canoeists": "متسابقو قوارب الكانوي ذكور قمريون",
    "Costa Rican male judoka": "لاعبو جودو ذكور كوستاريكيون",
    "Djiboutian male judoka": "لاعبو جودو ذكور جيبوتيون",
    "Djiboutian male martial artists": "ممارسو فنون قتالية ذكور جيبوتيون",
    "Egyptian male table tennis players": "لاعبو كرة طاولة ذكور مصريون",
    "Expatriate male actors in China": "ممثلون ذكور مغتربون في الصين",
    "Filipino male singer-songwriters": "مغنون وكتاب أغاني ذكور فلبينيون",
    "French male bass guitarists": "عازفو غيتار باس ذكور فرنسيون",
    "Ghanaian male Muay Thai practitioners": "ممارسو موياي تاي ذكور غانيون",
    "Ghanaian male kickboxers": "مقاتلو كيك بوكسنغ ذكور غانيون",
    "Guinean male swimmers": "سباحون ذكور غينيون",
    "Icelandic male stage actors": "ممثلو مسرح ذكور آيسلنديون",
    "Indian male equestrians": "فرسان خيول ذكور هنود",
    "Indian male playback singers": "مغنو أفلام ذكور هنود",
    "Irish male rappers": "مغنو راب ذكور أيرلنديون",
    "Israeli male classical pianists": "عازفو بيانو كلاسيكيون ذكور إسرائيليون",
    "Kazakhstani male weightlifters": "رباعون ذكور كازاخستانيون",
    "Latvian male novelists": "روائيون ذكور لاتفيون",
    "Latvian male poets": "شعراء ذكور لاتفيون",
    "Lebanese male radio actors": "ممثلو راديو ذكور لبنانيون",
    "Lists of male golfers": "قوائم لاعبو غولف ذكور",
    "Malagasy male weightlifters": "رباعون ذكور مدغشقريون",
    "Nepalese male actors": "ممثلون ذكور نيباليون",
    "Norwegian male ski jumpers": "متزلجو قفز ذكور نرويجيون",
    "Polish male biathletes": "لاعبو بياثلون ذكور بولنديون",
    "Puerto Rican male judoka": "لاعبو جودو ذكور بورتوريكيون",
    "Rhodesian male martial artists": "ممارسو فنون قتالية ذكور رودوسيون",
    "Serbian male short story writers": "كتاب قصة قصيرة ذكور صرب",
    "Soviet male swimmers": "سباحون ذكور سوفيت",
    "Spanish male classical pianists": "عازفو بيانو كلاسيكيون ذكور إسبان",
    "Spanish male pianists": "عازفو بيانو ذكور إسبان",
    "Thai male actors by medium": "ممثلون ذكور تايلنديون حسب الوسط",
    "Thai male composers": "ملحنون ذكور تايلنديون",
    "Thai male sailors (sport)": "بحارة رياضيون ذكور تايلنديون",
    "Ugandan male mixed martial artists": "مقاتلو فنون قتالية مختلطة ذكور أوغنديون",
    "Welsh male short story writers": "كتاب قصة قصيرة ذكور ويلزيون",
    "Male actors from Austrian Empire": "ممثلون ذكور من الإمبراطورية النمساوية",
    "Male actors from Basque Country (autonomous community)": "ممثلون ذكور من منطقة الباسك ذاتية الحكم",
    "Male actors from Brooklyn": "ممثلون ذكور من بروكلين",
    "Male actors from Calabasas, California": "ممثلون ذكور من كالاباساس (كاليفورنيا)",
    "Male actors from Cambridgeshire": "ممثلون ذكور من كامبريدجشير",
    "Male actors from Cook County, Illinois": "ممثلون ذكور من مقاطعة كوك (إلينوي)",
    "Male actors from Hastings": "ممثلون ذكور من هيستينغز",
    "Male actors from Illinois by county": "ممثلون ذكور من إلينوي حسب المقاطعة",
    "Male actors from Inverclyde": "ممثلون ذكور من إنفركلايد",
    "Male actors from Jackson County, Oregon": "ممثلون ذكور من مقاطعة جاكسون (أوريغن)",
    "Male actors from Kane County, Illinois": "ممثلون ذكور من مقاطعة كين (إلينوي)",
    "Male actors from Kent": "ممثلون ذكور من كنت",
    "Male actors from Lake County, Illinois": "ممثلون ذكور من مقاطعة ليك (إلينوي)",
    "Male actors from Lancaster, Pennsylvania": "ممثلون ذكور من لانكستر (بنسلفانيا)",
    "Male actors from Mecklenburg-Vorpommern": "ممثلون ذكور من مكلنبورغ فوربومرن",
    "Male actors from Monterey County, California": "ممثلون ذكور من مقاطعة مونتيري (كاليفورنيا)",
    "Male actors from Orange County, New York": "ممثلون ذكور من مقاطعة أورانج (نيويورك)",
    "Male actors from Oregon by county": "ممثلون ذكور من أوريغن حسب المقاطعة",
    "Male actors from Oyo State": "ممثلون ذكور من ولاية أويو",
    "Male actors from San Bernardino, California": "ممثلون ذكور من سان بيرناردينو (كاليفورنيا)",
    "Male actors from Trondheim": "ممثلون ذكور من تروندهايم",
    "Male actors from Yokohama": "ممثلون ذكور من يوكوهاما",
    "Male models from Massachusetts": "عارضو أزياء ذكور من ماساتشوستس",
    "Male television actors from Georgia (country)": "ممثلو تلفزيون ذكور من جورجيا",
    "Male voice actors from Sendai": "ممثلو أداء صوتي ذكور من سنداي",
    "Male field hockey goalkeepers": "حراس مرمى هوكي ميدان ذكور",
    "Kosovan sportsmen": "رياضيون رجال كوسوفيون",
    "Greek men": "رجال يونانيون",
    "Emirati men": "رجال إماراتيون",
    "Finnish men": "رجال فنلنديون",
}


non_fiction_data_male = {
    "male non-fiction writers by nationality": "كتاب غير روائيين ذكور حسب الجنسية",
    "male non-fiction writers from northern ireland": "كتاب غير روائيين ذكور من أيرلندا الشمالية",
    "male non-fiction writers": "كتاب غير روائيين ذكور",
    # "New Zealand male non-fiction writers": "كتاب غير روائيين ذكور نيوزيلنديون",
    "Turkish male non-fiction writers": "كتاب غير روائيين ذكور أتراك",
    "Argentine male non-fiction writers": "كتاب غير روائيين ذكور أرجنتينيون",
    "Albanian male non-fiction writers": "كتاب غير روائيين ذكور ألبان",
    "Estonian male non-fiction writers": "كتاب غير روائيين ذكور إستونيون",
    "Israeli male non-fiction writers": "كتاب غير روائيين ذكور إسرائيليون",
    "Scottish male non-fiction writers": "كتاب غير روائيين ذكور إسكتلنديون",
    "Pakistani male non-fiction writers": "كتاب غير روائيين ذكور باكستانيون",
    "Brazilian male non-fiction writers": "كتاب غير روائيين ذكور برازيليون",
    "Portuguese male non-fiction writers": "كتاب غير روائيين ذكور برتغاليون",
    "Puerto Rican male non-fiction writers": "كتاب غير روائيين ذكور بورتوريكيون",
    "Bolivian male non-fiction writers": "كتاب غير روائيين ذكور بوليفيون",
    "Peruvian male non-fiction writers": "كتاب غير روائيين ذكور بيرويون",
    "Trinidad and Tobago male non-fiction writers": "كتاب غير روائيين ذكور ترنيداديون",
    "Czech male non-fiction writers": "كتاب غير روائيين ذكور تشيكيون",
    "Chilean male non-fiction writers": "كتاب غير روائيين ذكور تشيليون",
    "Jamaican male non-fiction writers": "كتاب غير روائيين ذكور جامايكيون",
    "Russian male non-fiction writers": "كتاب غير روائيين ذكور روس",
    "Romanian male non-fiction writers": "كتاب غير روائيين ذكور رومان",
    "Soviet male non-fiction writers": "كتاب غير روائيين ذكور سوفيت",
    "Swiss male non-fiction writers": "كتاب غير روائيين ذكور سويسريون",
    "Serbian male non-fiction writers": "كتاب غير روائيين ذكور صرب",
    "Chinese male non-fiction writers": "كتاب غير روائيين ذكور صينيون",
    "Palestinian male non-fiction writers": "كتاب غير روائيين ذكور فلسطينيون",
    "Venezuelan male non-fiction writers": "كتاب غير روائيين ذكور فنزويليون",
    "Finnish male non-fiction writers": "كتاب غير روائيين ذكور فنلنديون",
    "Cuban male non-fiction writers": "كتاب غير روائيين ذكور كوبيون",
    "Colombian male non-fiction writers": "كتاب غير روائيين ذكور كولومبيون",
    "Luxembourgian male non-fiction writers": "كتاب غير روائيين ذكور لوكسمبورغيون",
    "Lithuanian male non-fiction writers": "كتاب غير روائيين ذكور ليتوانيون",
    "Hungarian male non-fiction writers": "كتاب غير روائيين ذكور مجريون",
    "Egyptian male non-fiction writers": "كتاب غير روائيين ذكور مصريون",
    "Mexican male non-fiction writers": "كتاب غير روائيين ذكور مكسيكيون",
    "Moldovan male non-fiction writers": "كتاب غير روائيين ذكور مولدوفيون",
    "Norwegian male non-fiction writers": "كتاب غير روائيين ذكور نرويجيون",
    "Austrian male non-fiction writers": "كتاب غير روائيين ذكور نمساويون",
    "Haitian male non-fiction writers": "كتاب غير روائيين ذكور هايتيون",
    "Dutch male non-fiction writers": "كتاب غير روائيين ذكور هولنديون",
    "Welsh male non-fiction writers": "كتاب غير روائيين ذكور ويلزيون",
    "Japanese male non-fiction writers": "كتاب غير روائيين ذكور يابانيون",
    "Greek male non-fiction writers": "كتاب غير روائيين ذكور يونانيون",
}


test_all_data = {
    **test_sport_data,
    **test_data2,
    **non_fiction_data_male,
}


@pytest.mark.parametrize("category,expected", test_all_data.items(), ids=test_all_data.keys())
@pytest.mark.fast
def test_jobs_resolvers_male_inte(category: str, expected: str) -> None:
    """Test all nat translation patterns."""
    result = resolve_label_ar(category)
    assert result == expected
