"""
TODO: write relegin_jobs_nats_jobs.py code
"""

import pytest
from ArWikiCats.make_bots.jobs_bots.relegin_jobs_nats_jobs import resolve_relegin_nats_jobs

test_data = {
    "American Episcopalians": "تصنيف:أمريكيون أسقفيون",
    "American Hindus": "تصنيف:أمريكيون هندوس",
    "American saints": "تصنيف:أمريكيون قديسون",
    "American Sufis": "تصنيف:أمريكيون صوفيون",
    "American Sunni Muslims": "تصنيف:أمريكيون مسلمون سنة",
    "Ancient Roman saints": "تصنيف:رومان قدماء قديسون",
    "Angolan Anglicans": "تصنيف:أنغوليون أنجليكيون",
    "Angolan Christians": "تصنيف:أنغوليون مسيحيون",
    "Arab Christians": "تصنيف:عرب مسيحيون",
    "Argentine Anglicans": "تصنيف:أرجنتينيون أنجليكيون",
    "Argentine Christians": "تصنيف:أرجنتينيون مسيحيون",
    "Argentine saints": "تصنيف:أرجنتينيون قديسون",
    "Armenian Christians": "تصنيف:أرمن مسيحيون",
    "Armenian saints": "تصنيف:أرمن قديسون",
    "Armenian Yazidis": "تصنيف:أرمن يزيديون",
    "Aruban Christians": "تصنيف:أروبيون مسيحيون",
    "Asian Christians": "تصنيف:آسيويين مسيحيون",
    "Asian Hindus": "تصنيف:آسيويين هندوس",
    "Asian Sufis": "تصنيف:آسيويين صوفيون",
    "Assyrian saints": "تصنيف:آشوريون قديسون",
    "Australian Anglicans": "تصنيف:أستراليون أنجليكيون",
    "Australian Christians": "تصنيف:أستراليون مسيحيون",
    "Australian Hindus": "تصنيف:أستراليون هندوس",
    "Australian saints": "تصنيف:أستراليون قديسون",
    "Australian Sufis": "تصنيف:أستراليون صوفيون",
    "Australian Sunni Muslims": "تصنيف:أستراليون مسلمون سنة",
    "Austrian Christians": "تصنيف:نمساويون مسيحيون",
    "Austrian saints": "تصنيف:نمساويون قديسون",
    "Austrian Sunni Muslims": "تصنيف:نمساويون مسلمون سنة",
    "Azerbaijani Christians": "تصنيف:أذربيجانيون مسيحيون",
    "Bahamian Anglicans": "تصنيف:بهاميون أنجليكيون",
    "Bahamian Christians": "تصنيف:بهاميون مسيحيون",
    "Bahraini Christians": "تصنيف:بحرينيون مسيحيون",
    "Bahraini Sufis": "تصنيف:بحرينيون صوفيون",
    "Bahraini Sunni Muslims": "تصنيف:بحرينيون مسلمون سنة",
    "Bangladeshi Anglicans": "تصنيف:بنغلاديشيون أنجليكيون",
    "Bangladeshi Christians": "تصنيف:بنغلاديشيون مسيحيون",
    "Bangladeshi Hindus": "تصنيف:بنغلاديشيون هندوس",
    "Bangladeshi Sufis": "تصنيف:بنغلاديشيون صوفيون",
    "Bangladeshi Sunni Muslims": "تصنيف:بنغلاديشيون مسلمون سنة",
    "Barbadian Anglicans": "تصنيف:بربادوسيون أنجليكيون",
    "Barbadian Christians": "تصنيف:بربادوسيون مسيحيون",
    "Barbadian Hindus": "تصنيف:بربادوسيون هندوس",
    "Belarusian Christians": "تصنيف:بيلاروسيون مسيحيون",
    "Belgian Christians": "تصنيف:بلجيكيون مسيحيون",
    "Belgian Hindus": "تصنيف:بلجيكيون هندوس",
    "Belgian saints": "تصنيف:بلجيكيون قديسون",
    "Belgian Sunni Muslims": "تصنيف:بلجيكيون مسلمون سنة",
    "Belizean Anglicans": "تصنيف:بليزيون أنجليكيون",
    "Belizean Christians": "تصنيف:بليزيون مسيحيون",
    "Trinidad and Tobago Anglicans": "تصنيف:ترنيداديون أنجليكيون",
    "Trinidad and Tobago Christians": "تصنيف:ترنيداديون مسيحيون",
    "Trinidad and Tobago Hindus": "تصنيف:ترنيداديون هندوس",
    "Tunisian Christians": "تصنيف:تونسيون مسيحيون",
    "Tunisian Sufis": "تصنيف:تونسيون صوفيون",
    "Tunisian Sunni Muslims": "تصنيف:تونسيون مسلمون سنة",
    "Turkish Christians": "تصنيف:أتراك مسيحيون",
    "Turkish Cypriot Sufis": "تصنيف:قبرصيون شماليون صوفيون",
    "Turkish Cypriot Sunni Muslims": "تصنيف:قبرصيون شماليون مسلمون سنة",
    "Turkish Sufis": "تصنيف:أتراك صوفيون",
    "Turkish Sunni Muslims": "تصنيف:أتراك مسلمون سنة",
    "Turkish Yazidis": "تصنيف:أتراك يزيديون",
    "Turkmenistan Sufis": "تصنيف:تركمانيون صوفيون",
    "Tuvaluan Christians": "تصنيف:توفاليون مسيحيون",
    "Ugandan Anglicans": "تصنيف:أوغنديون أنجليكيون",
    "Ugandan Christians": "تصنيف:أوغنديون مسيحيون",
    "Ugandan saints": "تصنيف:أوغنديون قديسون",
    "Ukrainian Christians": "تصنيف:أوكرانيون مسيحيون",
    "Ukrainian saints": "تصنيف:أوكرانيون قديسون",
    "Ukrainian Sunni Muslims": "تصنيف:أوكرانيون مسلمون سنة",
    "Uruguayan Christians": "تصنيف:أوروغويانيون مسيحيون",
    "Uruguayan saints": "تصنيف:أوروغويانيون قديسون",
    "Uzbek Sufis": "تصنيف:أوزبكيون صوفيون",
    "Uzbekistani Christians": "تصنيف:أوزبكستانيون مسيحيون",
    "Uzbekistani Hindus": "تصنيف:أوزبكستانيون هندوس",
    "Uzbekistani Sunni Muslims": "تصنيف:أوزبكستانيون مسلمون سنة",
    "Vanuatuan Anglicans": "تصنيف:فانواتيون أنجليكيون",
    "Vanuatuan Christians": "تصنيف:فانواتيون مسيحيون",
    "Venezuelan Christians": "تصنيف:فنزويليون مسيحيون",
    "Venezuelan Hindus": "تصنيف:فنزويليون هندوس",
    "Vietnamese Christians": "تصنيف:فيتناميون مسيحيون",
    "Vietnamese Hindus": "تصنيف:فيتناميون هندوس",
    "Vietnamese saints": "تصنيف:فيتناميون قديسون",
    "Welsh Anglicans": "تصنيف:ويلزيون أنجليكيون",
    "Welsh Christians": "تصنيف:ويلزيون مسيحيون",
    "Welsh Hindus": "تصنيف:ويلزيون هندوس",
    "Welsh saints": "تصنيف:ويلزيون قديسون",
    "Yemeni Christians": "تصنيف:يمنيون مسيحيون",
    "Yemeni Sufis": "تصنيف:يمنيون صوفيون",
    "Yemeni Sunni Muslims": "تصنيف:يمنيون مسلمون سنة",
    "Yemeni Zaydis": "تصنيف:يمنيون زيود",
    "Yugoslav Christians": "تصنيف:يوغوسلافيون مسيحيون",
    "Zambian Anglicans": "تصنيف:زامبيون أنجليكيون",
    "Zambian Christians": "تصنيف:زامبيون مسيحيون",
    "Zimbabwean Anglicans": "تصنيف:زيمبابويون أنجليكيون",
    "Zimbabwean Christians": "تصنيف:زيمبابويون مسيحيون",
    "Zimbabwean Hindus": "تصنيف:زيمبابويون هندوس",
    "Zimbabwean Sunni Muslims": "تصنيف:زيمبابويون مسلمون سنة"
}


@pytest.mark.parametrize("input_text,expected", test_data.items(), ids=test_data.keys())
@pytest.mark.skip2
def test_relegin_nats_jobs(input_text: str, expected: str) -> None:

    result = resolve_relegin_nats_jobs(input_text)
    assert result == expected, f"{expected=}, {result=}, {input_text=}"
