#!/usr/bin/python3
"""

"""


# import re
# ---
from .all_keys3 import albums_type

# ---
languages_key = {}
# "spanish" : "إسبانية",
# "arabic" : "عربية",
# }
# ---
languages_pop = {
    "balinese": "بالية",
    "pali": "بالية",
    "abkhazian": "أبخازية",
    "afar": "عفارية",
    # "afrikaans":"أفريقانية",
    "afrikaans": "إفريقية",
    "uralic": "أورالية",
    "akan": "أكانية",
    "albanian": "ألبانية",
    "alemannic": "أليمانية",
    "amharic": "أمهرية",
    "semitic": "سامية",
    "afroasiatic": "أفروآسيوية",
    "arabic": "عربية",
    "aragonese": "أراغونية",
    "armenian": "أرمنية",
    "assamese": "آسامية",
    "asturian": "أستورية",
    "avaric": "أوارية",
    "avestan": "أفستية",
    "azerbaijani": "أذربيجانية",
    # "azerbaijani":"أذرية",
    "bambara": "بمبرية",
    "bangla": "بنغالية",
    "bashkir": "باشقورية",
    "basque": "باسكية",
    # "basque":"بشكنشية",
    "belarusian": "بيلاروسية",
    "bengali": "بنغالية",
    "bhojpuri": "بهارية",
    "bishnupriya manipuri": "بيشنوبريا مانيبورية",
    "bislama": "بسلاما",
    "bosniak": "بوشناقية",
    "bosnian": "بوسنية",
    "breton": "بريتانية",
    "bulgarian": "بلغارية",
    "burmese": "بورمية",
    "cantonese": "كانتونية",
    "catalan": "كتلانية",
    "chamorro": "تسمورية",
    "chechen": "شيشانية",
    "chinese": "صينية",
    "chuvash": "تشوفاشيا",
    "classical syriac": "سريانية",
    "cornish": "كورنية",
    "corsican": "كورسيكية",
    "cree": "كرية",
    "croatian": "كرواتية",
    "czech": "تشيكية",
    "danish": "دنماركية",
    "dutch": "هولندية",
    "egyptian arabic": "مصرية",
    "english": "إنجليزية",
    "esperanto": "إسبرانتو",
    "estonian": "إستونية",
    "ewe": "إوية",
    "faroese": "فاروية",
    "fijian": "فيجية",
    "finnish": "فنلندية",
    "french": "فرنسية",
    "fulah": "فولانية",
    "galician": "جليقية",
    "georgian": "جورجية",
    "german": "ألمانية",
    "germanic": "جرمانية",
    "greek": "يونانية",
    "guarani": "غوارانية",
    "gujarati": "غوجاراتية",
    "hausa": "هوسية",
    "hebrew": "عبرية",
    "hindi": "هندية",
    "hungarian": "مجرية",
    "icelandic": "آيسلندية",
    "ido": "إيدوية",
    "indonesian": "إندونيسية",
    "inuktitut": "إنكتيتوتية",
    "irish": "أيرلندية",
    "italian": "إيطالية",
    "japanese": "يابانية",
    "javanese": "جاوية",
    "judaeo-spanish": "لادينو",
    "kalaallisut": "جرينلاندية",
    "kannada": "كنادية",
    "kanuri": "كانورية",
    "kashmiri": "كشميرية",
    "kazakh": "كازاخية",
    "khmer": "خميرية",
    "kinyarwanda": "روندية",
    "komi": "كومية",
    "kongo": "كونغو",
    "korean": "كورية",
    "kurdish": "كردية",
    "kyrgyz": "قيرغيزية",
    "lao": "لاوية",
    "latin": "لاتينية",
    "aramaic": "آرامية",
    "latvian": "لاتفية",
    "limburgish": "ليمبورغية",
    "lithuanian": "لتوانية",
    "luxembourgish": "لوكسمبورغية",
    "macedonian": "مقدونية",
    "malagasy": "ملغاشية",
    "malay": "ملايوية",
    "malayalam": "ماليالامية",
    "maltese": "مالطية",
    "manx": "منكية",
    "maori": "ماورية",
    "marathi": "ماراثية",
    "marshallese": "مارشالية",
    "mongolian": "منغولية",
    "nauru": "ناورونية",
    "neapolitan": "نابولية",
    "nepal bhasa": "نيوارية",
    "nepali": "نيبالية",
    "norwegian": "نرويجية",
    "occitan": "أکسيتانية",
    "ojibwa": "أوجيبوا",
    "oromo": "أورومية",
    "ossetic": "أوسيتية",
    "pashto": "بشتوية",
    "indo-european": "هندو أوروبية",
    "persian": "فارسية",
    "piedmontese": "بيدمونتية",
    "polish": "بولندية",
    "portuguese": "برتغالية",
    "punjabi": "بنجابية",
    "ripuarian": "ريبوارية",
    "romanian": "رومانية",
    "romansh": "رومانشية",
    "rundi": "كيروندية",
    "russian": "روسية",
    "samoan": "ساموية",
    "samogitian": "ساموجيتية",
    "sango": "سانغوية",
    "sanskrit": "سنسكريتية",
    "sardinian": "سردينية",
    "scots": "إسكتلندية",
    "serbian": "صربية",
    "serbo-croatian": "صربوكرواتية",
    "sichuan yi": "نؤوسوية",
    "sicilian": "صقلية",
    "silesian": "سيليسية",
    "sindhi": "سندية",
    "sinhala": "سنهالية",
    "slovak": "سلوفاكية",
    "slovene": "سلوفينية",
    "slovenian": "سلوفينية",
    "somali": "صومالية",
    "southern sotho": "سوتية",
    "spanish": "إسبانية",
    "sundanese": "سوندية",
    "swahili": "سواحلية",
    "swedish": "سويدية",
    "tagalog": "تاغالوغية",
    "tahitian": "تاهيتية",
    "tajik": "طاجيكية",
    "tamil": "تاميلية",
    "tatar": "تترية",
    "telugu": "تيلوغوية",
    "thai": "تايلندية",
    "tibetan": "تبتية",
    "tigrinya": "تغرينية",
    "tongan": "تونغية",
    "tsonga": "تسونجا",
    "tswana": "تسوانية",
    "turkish": "تركية",
    "turkmen": "تركمانية",
    "ukrainian": "أوكرانية",
    "urdu": "أردية",
    "uyghur": "أويغورية",
    "uzbek": "أوزبكية",
    "venda": "فيندية",
    "vietnamese": "فيتنامية",
    "volapük": "فولابوكية",
    "walloon": "والونية",
    "waray": "واراي واراي",
    "welsh": "ويلزية",
    "wolof": "ولوفية",
    "xhosa": "خوسية",
    "yiddish": "يديشية",
    # "yoruba":"يوربا",
    "zulu": "زولوية",
    "молдовеняскэ": "مولدوفية",
}
# ---
languages_pop2 = {
    "herero": "هيريرو",
    "hiri motu": "هيري موتو",
    "ido": "إيدو",
    "igbo": "إيجبو",
    "interlingua": "إنترلنغوا",
    # "yoruba" : "يوربا",
    "zhuang": "زهيونج",
    "interlingue": "إنترلينج",
    "inupiaq": "إينبياك",
    "kikuyu": "كيكيو",
    "kinyarwanda": "كينيارواندا",
    "kuanyama": "كيونياما",
    "lingala": "لينغالا",
    "luba-katanga": "تشيلوبا",
    "navajo": "نافاجو",
    "ndonga": "ندونجا",
    "odia": "أوريا",
    "quechua": "كتشوا",
    "shona": "شونا",
    "swati": "سوازي",
    "twi": "توي",
    "nyanja": "نيانجا",
    "aymara": "أيمارا",
    "bashkir": "باشقير",
    "chuvash": "تشوفاش",
    "divehi": "ديفهي",
    "dzongkha": "دزونكا",
    "ganda": "جاندا",
    "esperanto": "إسبرانتو",
}
# ---
lang_type = {
    # " language" : "لغة {}",
    "-language": "اللغة ال{}",
    " languages": "اللغات ال{}",
}
# ---
for x, xlab in languages_pop.items():
    x2 = x.lower()
    languages_key[f"{x2} language"] = f"لغة {xlab}"
    for mis, mis_lab in lang_type.items():
        keyy = f"{x2}{mis.lower()}"
        languages_key[keyy] = mis_lab.format(xlab)
# ---
languages_pop3 = {
    "west frisian": "فريزية غربية",
    "sorani": "كردية سورانية",
    "simple english": "إنجليزية بسيطة",
    "serbo-croatian": "صربية كرواتية",
    "northern sami": "سامي شمالية",
    "dutch low saxon": "هولندية سكسونية سفلى",
    "western frisian": "فريزية غربية",
    "south ndebele": "نديبلي جنوبية",
    "seselwa creole french": "كريولية سيشيلية",
    "scottish gaelic": "غيلية إسكتلندية",
    "north ndebele": "نديبيل شمالية",
    "norwegian bokmål": "نرويجية بوكمول",
    "norwegian nynorsk": "نرويجية نينوشك",
    "haitian creole": "كريولية هايتية",
    "church slavic": "سلافونية كنسية قديمة",
}
# ---
for x, lab in languages_pop3.items():
    x2 = x.lower()
    languages_key[f"{x2} language"] = f"لغة {lab}"
    lab = lab.replace(" ", " ال")
    # lab = re.sub(r" " , " ال" , lab )
    # languages_key[x2] = "ال%s" % lab
    languages_key[x2] = lab
    for mis in lang_type:
        keyy = f"{x2}{mis}"
        languages_key[keyy] = lang_type[mis].format(lab)
# ---
"""
"arabic surnames" : "ألقاب عربية",
"arabic-language surnames" : "ألقاب عربية",
"arabic language surnames" : "ألقاب عربية",
"arabic masculine given names" : "أسماء ذكور عربية",
"bosniak masculine given names" : "أسماء ذكور بوشناقية",
"bosnian masculine given names" : "أسماء ذكور بوسنية",
"iranian masculine given names" : "أسماء ذكور إيرانية",
"pakistani masculine given names" : "أسماء ذكور باكستانية",
"""
# ---
lang_key_m = {
    "grammar": "قواعد اللغة ال{}",
    "romanization": "رومنة {}",
    "writing system": "نظام كتابة {}",
    "dialects": "لهجات {}",
    # ---    "romanization of arabic" : "رومنة العربية",
    "surnames": "ألقاب {}",
    "masculine given names": "أسماء ذكور ب{}",
    "given names": "أسماء شخصية {}",
    # ---
    "varieties and styles": "أصناف وأساليب {}",
    "literature": "أدب {}",
    "culture": "ثقافة {}",
    "underground culture": "ثقافة باطنية {}",
    "mass media": "إعلام {}",
    "countries": "بلدان {}",
    "categories": "تصنيفات {}",
    "education": "تعليم {}",
    # "Bible translations
    # "Compositions مؤلفات موسيقية
    # "tirukkural translations" : " ب{}",
}
# ---
cccccc_m = {
    "words and phrases": "كلمات وجمل",
    "academic journals": "دوريات أكاديمية",
    "albums": "ألبومات",
    "books": "كتب",
    "comic book": "كتب قصص مصورة",
    "comic strips": "شرائط مصورة",
    "comic": "قصص مصورة",
    "comics": "قصص مصورة",
    "marvel comics": "مارفال كومكس",
    "dictionaries": "قواميس",
    "encyclopedias": "موسوعات",
    "films": "أفلام",
    "given names": "أسماء شخصية",
    "graphic novels": "روايات مصورة",
    "inscriptionss": "نقوش وكتابات",
    "literary awards": "جوائز أدبية",
    # "literary critics" : "نقد أدبي",
    "magazines": "مجلات",
    "manga": "مانغا",
    "media": "إعلام",
    "medieval literature": "أدب العصور الوسطى",
    "mmagazines": "مجلات",
    "music": "موسيقى",
    "musicians": "موسيقيون",
    "names": "أسماء",
    "newspapers": "صحف",
    "novels": "روايات",
    "novellas": "روايات قصيرة",
    "operas": "أوبيرات",
    "people": "أشخاص",
    "plays": "مسرحيات",
    "poems": "قصائد",
    "publications": "منشورات",
    "radio stations": "محطات إذاعية",
    "short stories": "قصص قصيرة",
    "songs": "أغان",
    "surnames": "ألقاب",
    "telenovelas": "تيلينوفيلا",
    "television seasons": "مواسم تلفزيونية",
    "television episodes": "حلقات تلفزيونية",
    "television series": "مسلسلات تلفزيونية",
    "film series": "سلاسل أفلام",
    "television shows": "عروض تلفزيونية",
    "television networks": "شبكات تلفزيونية",
    "television programs": "برامج تلفزيونية",
    "television programmes": "برامج تلفزيونية",
    "television stations": "محطات تلفزيونية",
    "television": "تلفاز",
    "verbs": "أفعال",
    "video games": "ألعاب فيديو",
    "webcomic": "ويب كومكس",
    "webcomics": "ويب كومكس",
    "websites": "مواقع ويب",
    "works": "أعمال",
    # "Bible translations
    # "Compositions مؤلفات موسيقية
    # "tirukkural translations" : "",
}
# ---
for x in albums_type:
    cccccc_m[f"{x} albums"] = f"ألبومات {albums_type[x]}"
# ---
for x in cccccc_m:
    lang_key_m[x.lower()] = "%s ب{}" % cccccc_m[x]
# ---
lang_ttty = {
    "poems": "قصائد %s",
    "phonology": "نطقيات %s",
    "mythology": "أساطير %s",
    "texts": "نصوص %s",
    "prose texts": "نصوص نثرية %s",
}
# ---