"""
Tests
"""

import pytest

from src.make2_bots.ma_bots.ar_lab import get_con_lab


@pytest.mark.fast
def test_get_con_lab_data_one():
    label = get_con_lab(preposition=" of ", country="11th government of turkey", start_get_country2=True)
    assert label != "حكومة تركيا"


data = [
    {"tito2": "about", "country": "busan", "output": "بوسان"},
    {"tito2": "about", "country": "chefs", "output": "طباخون"},
    {"tito2": "about", "country": "chinese canadians", "output": "كنديون صينيون"},
    {"tito2": "about", "country": "slavery", "output": "العبودية"},
    {"tito2": "about", "country": "south carolina", "output": "كارولاينا الجنوبية"},
    {"tito2": "about", "country": "south dakota", "output": "داكوتا الجنوبية"},
    {"tito2": "about", "country": "the american civil war", "output": "الحرب الأهلية الأمريكية"},
    {"tito2": "about", "country": "the united states navy", "output": "البحرية الأمريكية"},
    {"tito2": "about", "country": "the vietnam war", "output": "حرب فيتنام"},
    {"tito2": "about", "country": "weather", "output": "الطقس"},
    {"tito2": "adapted for", "country": "other media", "output": "وسائط أخرى"},
    {"tito2": "adapted into", "country": "films", "output": "أفلام"},
    {"tito2": "against", "country": "the united states", "output": "الولايات المتحدة"},
    {"tito2": "and", "country": "architecture", "output": "هندسة معمارية"},
    {"tito2": "and", "country": "united states treaties", "output": "معاهدات الولايات المتحدة"},
    {"tito2": "and", "country": "värmland county", "output": "محافظة ورملاند"},
    {"tito2": "at", "country": "yemen", "output": "اليمن"},
    {"tito2": "based in", "country": "aomori prefecture", "output": "محافظة آوموري"},
    {"tito2": "based in", "country": "belarus", "output": "روسيا البيضاء"},
    {"tito2": "based in", "country": "illinois by populated place", "output": "إلينوي حسب المكان المأهول"},
    {"tito2": "basedon", "country": "american comics", "output": "قصص مصورة أمريكية"},
    {"tito2": "basedon", "country": "british television series", "output": "مسلسلات تلفزيونية بريطانية"},
    {"tito2": "basedon", "country": "comics", "output": "قصص مصورة"},
    {"tito2": "basedon", "country": "egyptian mythology", "output": "أساطير مصرية"},
    {"tito2": "between", "country": "national teams", "output": "منتخبات وطنية"},
    {"tito2": "built-in", "country": "montreal", "output": "مونتريال"},
    {"tito2": "built-in", "country": "poland", "output": "بولندا"},
    {"tito2": "by", "country": "by academic discipline", "output": "حسب التخصص الأكاديمي"},
    {"tito2": "by", "country": "by american artists", "output": "بواسطة فنانون أمريكيون"},
    {"tito2": "by", "country": "by andy warhol", "output": "بواسطة آندي وارهول"},
    {"tito2": "by", "country": "by athletic event", "output": "حسب حدث ألعاب القوى"},
    {"tito2": "by", "country": "by under-20 national team", "output": "حسب المنتخب الوطني تحت 20 سنة"},
    {"tito2": "by", "country": "by year templates", "output": "قوالب حسب السنة"},
    {"tito2": "by-car-bomb", "country": "in the united kingdom", "output": "في المملكة المتحدة"},
    {"tito2": "closed in", "country": "1420", "output": "1420"},
    {"tito2": "closed in", "country": "20th century", "output": "القرن 20"},
    {"tito2": "completed in", "country": "1420s", "output": "عقد 1420"},
    {"tito2": "completed in", "country": "2nd century", "output": "القرن 2"},
    {"tito2": "concerning", "country": "eritrea", "output": "إريتريا"},
    {"tito2": "convicted of", "country": "crimes", "output": "جرائم"},
    {"tito2": "convicted of", "country": "kidnapping", "output": "الخطف"},
    {"tito2": "created in", "country": "1420", "output": "1420"},
    {"tito2": "demolished in", "country": "1420", "output": "1420"},
    {"tito2": "described in", "country": "1420", "output": "1420"},
    {"tito2": "described in", "country": "20th century", "output": "القرن 20"},
    {"tito2": "discovered in", "country": "1420", "output": "1420"},
    {"tito2": "disestablished in", "country": "1420 by country", "output": "1420 حسب البلد"},
    {"tito2": "disestablished in", "country": "14th century bc", "output": "القرن 14 ق م"},
    {"tito2": "during", "country": "world-war-ii by nationality", "output": "الحرب العالمية الثانية حسب الجنسية"},
    {"tito2": "during", "country": "world-war-ii", "output": "الحرب العالمية الثانية"},
    {"tito2": "established in", "country": "1420s", "output": "عقد 1420"},
    {"tito2": "established in", "country": "14th century", "output": "القرن 14"},
    {"tito2": "executed by", "country": "jamaica", "output": "جامايكا"},
    {"tito2": "executed by", "country": "nazi germany", "output": "ألمانيا النازية"},
    {"tito2": "executed by", "country": "new spain", "output": "إسبانيا الجديدة"},
    {"tito2": "executed by", "country": "utah by firing squad", "output": "يوتا رميا بالرصاص"},
    {"tito2": "extended to", "country": "curaçao", "output": "كوراساو"},
    {"tito2": "filmed in", "country": "algeria", "output": "الجزائر"},
    {"tito2": "filmed in", "country": "jiangsu", "output": "جيانغسو"},
    {"tito2": "for", "country": "for argentina", "output": "الأرجنتين"},
    {"tito2": "for", "country": "for australia", "output": "أستراليا"},
    {"tito2": "for", "country": "for german-language films", "output": "أفلام باللغة الألمانية"},
    {"tito2": "for", "country": "for germany", "output": "ألمانيا"},
    {"tito2": "for", "country": "for national teams", "output": "للمنتخبات الوطنية"},
    {"tito2": "for", "country": "for women's football", "output": "كرة القدم للسيدات"},
    {"tito2": "from", "country": "aden", "output": "عدن"},
    {"tito2": "from", "country": "ahrweiler (district)", "output": "أرفيلر"},
    {"tito2": "from", "country": "georgia (country)", "output": "جورجيا"},
    {"tito2": "from", "country": "georgia (u.s. state)", "output": "ولاية جورجيا"},
    {"tito2": "from", "country": "northern ireland of canadian descent", "output": "أيرلندا الشمالية من أصل كندي"},
    {"tito2": "hosted by", "country": "argentina", "output": "الأرجنتين"},
    {"tito2": "imprisoned-in", "country": "germany", "output": "ألمانيا"},
    {"tito2": "in", "country": "1420 all-africa games", "output": "ألعاب عموم إفريقيا 1420"},
    {"tito2": "in", "country": "1420 world games", "output": "الألعاب العالمية 1420"},
    {"tito2": "in", "country": "1420–51", "output": "1420–51"},
    {"tito2": "in", "country": "abkhazia", "output": "أبخازيا"},
    {"tito2": "in", "country": "afghanistan", "output": "أفغانستان"},
    {"tito2": "in", "country": "german novels of 20th century", "output": "روايات ألمانية في القرن 20"},
    {"tito2": "in", "country": "mandatory syria", "output": "الانتداب الفرنسي على سوريا ولبنان"},
    {"tito2": "in", "country": "the socialist republic-of macedonia", "output": "جمهورية مقدونيا الاشتراكية"},
    {"tito2": "in", "country": "the universiade navigational boxes", "output": "صناديق تصفح الألعاب الجامعية"},
    {"tito2": "in-sports-in", "country": "california", "output": "كاليفورنيا"},
    {"tito2": "in-sports-in", "country": "delaware", "output": "ديلاوير"},
    {"tito2": "introduced in", "country": "21st century", "output": "القرن 21"},
    {"tito2": "involving", "country": "north macedonia", "output": "مقدونيا الشمالية"},
    {"tito2": "involving the", "country": "united states", "output": "الولايات المتحدة"},
    {"tito2": "killed in", "country": "the second italo-ethiopian war", "output": "الحرب الإيطالية الإثيوبية الثانية"},
    {"tito2": "murdered in", "country": "1420", "output": "1420"},
    {"tito2": "murdered in", "country": "india by state or union territory", "output": "الهند حسب الولاية أو الإقليم الاتحادي"},
    {"tito2": "named after", "country": "american explorers", "output": "مستكشفون أمريكيون"},
    {"tito2": "named after", "country": "american novelists", "output": "روائيون أمريكيون"},
    {"tito2": "named after", "country": "canadian awards", "output": "جوائز كندية"},
    {"tito2": "named after", "country": "indian politicians", "output": "سياسيون هنود"},
    {"tito2": "named after", "country": "populated places in latvia", "output": "أماكن مأهولة في لاتفيا"},
    {"tito2": "named after", "country": "populated places in portugal", "output": "أماكن مأهولة في البرتغال"},
    {"tito2": "named after", "country": "religious organizations", "output": "منظمات دينية"},
    {"tito2": "named after", "country": "slovak musicians", "output": "موسيقيون سلوفاكيون"},
    {"tito2": "of", "country": "1420 films", "output": "أفلام 1420"},
    {"tito2": "of", "country": "british television series characters", "output": "شخصيات مسلسلات تلفزيونية بريطانية"},
    {"tito2": "of", "country": "ottoman–persian wars", "output": "الحروب العثمانية الفارسية"},
    {"tito2": "of", "country": "prime ministers of malaysia", "output": "رؤساء وزراء ماليزيا"},
    {"tito2": "of", "country": "westchester county, new york", "output": "مقاطعة ويستتشستر (نيويورك)"},
    {"tito2": "on", "country": "buildings and structures", "output": "مبان ومنشآت"},
    {"tito2": "on", "country": "diplomatic missions", "output": "بعثات دبلوماسية"},
    {"tito2": "on", "country": "the moon", "output": "القمر"},
    {"tito2": "on", "country": "the-national-register-of-historic-places", "output": "السجل الوطني للأماكن التاريخية"},
    {"tito2": "opened in", "country": "19th century", "output": "القرن 19"},
    {"tito2": "originating in", "country": "turkey", "output": "تركيا"},
    {"tito2": "produced by", "country": "brian wilson", "output": "بريان ويلسون"},
    {"tito2": "produced in", "country": "alberta", "output": "ألبرتا"},
    {"tito2": "published in", "country": "finland", "output": "فنلندا"},
    {"tito2": "published in", "country": "western australia", "output": "أستراليا الغربية"},
    {"tito2": "related to", "country": "the future", "output": "المستقبل"},
    {"tito2": "remadein", "country": "other languages", "output": "لغات أخرى"},
    {"tito2": "scored by", "country": "spanish composers", "output": "ملحنون إسبان"},
    {"tito2": "sentenced to", "country": "death", "output": "الموت"},
    {"tito2": "set in", "country": "10th century", "output": "القرن 10"},
    {"tito2": "set in", "country": "australia by city", "output": "أستراليا حسب المدينة"},
    {"tito2": "shot in", "country": "china by city", "output": "الصين حسب المدينة"},
    {"tito2": "to", "country": "american samoa", "output": "ساموا الأمريكية"},
    {"tito2": "to", "country": "north korea", "output": "كوريا الشمالية"},
    {"tito2": "to", "country": "the united states house-of-representatives from missouri territory", "output": "مجلس النواب الأمريكي من إقليم ميزوري"},
    {"tito2": "to", "country": "the united states", "output": "الولايات المتحدة"},
    {"tito2": "to", "country": "togo", "output": "توغو"},
    {"tito2": "to", "country": "venezuela", "output": "فنزويلا"},
    {"tito2": "to", "country": "zimbabwe", "output": "زيمبابوي"},
    {"tito2": "who died in", "country": "prison custody", "output": "السجن"},
    {"tito2": "with screenplays by", "country": "matt damon", "output": "مات ديمون"},
    {"tito2": "written by", "country": "lady gaga", "output": "ليدي غاغا"},
]


@pytest.mark.parametrize("tab", data, ids=lambda x: f"{x['tito2']} {x['country']}")
# @pytest.mark.fast
def test_get_con_lab_data(tab) -> None:
    label = get_con_lab(
        preposition=f" {tab['tito2']} ",
        country=tab["country"],
        start_get_country2=True
    )
    assert label.strip() == tab["output"]


data_test = [
    ("based in", "alaska by populated place", "ألاسكا حسب المكان المأهول"),
    ("based in", "ivory coast by subject", "ساحل العاج حسب الموضوع"),
    ("based in", "north america by country", "أمريكا الشمالية حسب البلد"),
    ("based in", "south america by country", "أمريكا الجنوبية حسب البلد"),
    ("basedon", "works by gotthold ephraim lessing", "أعمال بواسطة إفرايم ليسينغ"),
    ("basedon", "works by leo tolstoy", "أعمال بواسطة ليو تولستوي"),
    ("basedon", "works by osamu tezuka", "أعمال بواسطة أوسامو تزوكا"),
    ("by", "by century and occupation", "حسب القرن والمهنة"),
    ("by", "by century of closing", "حسب قرن الاغلاق"),
    ("by", "by city in colombia", "حسب المدينة في كولومبيا"),
    ("by", "by city in northern-ireland", "حسب المدينة في أيرلندا الشمالية"),
    ("by", "by club or team", "حسب النادي أو الفريق"),
    ("by", "by county in taiwan", "حسب المقاطعة في تايوان"),
    ("by", "by educational institution in derbyshire", "حسب الهيئة التعليمية في داربيشير"),
    ("by", "by hong kong producers", "بواسطة منتجون هونغ كونغيون"),
    ("by", "by league in the united states", "حسب الدوري في الولايات المتحدة"),
    ("by", "by location and occupation", "حسب الموقع والمهنة"),
    ("by", "by ludwig van beethoven", "بواسطة لودفيج فان بيتهوفن"),
    ("by", "by nation and year", "حسب الموطن والسنة"),
    ("by", "by occupation and region", "حسب المهنة والمنطقة"),
    ("by", "by period of introduction", "حسب حقبة الاستحداث"),
    ("by", "by populated place and decade", "حسب المكان المأهول والعقد"),
    ("by", "by populated place and occupation", "حسب المكان المأهول والمهنة"),
    ("by", "by province or territory", "حسب المقاطعة أو الإقليم"),
    ("by", "by robert louis stevenson", "بواسطة روبرت لويس ستيفنسون"),
    ("by", "by sport and year", "حسب الرياضة والسنة"),
    ("by", "by state or territory", "حسب الولاية أو الإقليم"),
    ("by", "by state or union territory", "حسب الولاية أو الإقليم الاتحادي"),
    ("by", "by team in the united states", "حسب الفريق في الولايات المتحدة"),
    ("by", "by university or college in beijing", "حسب الجامعة أو الكلية في بكين"),
    ("by", "by university or college in guatemala", "حسب الجامعة أو الكلية في غواتيمالا"),
    ("by", "by university or college in india", "حسب الجامعة أو الكلية في الهند"),
    ("by", "by university or college in mauritius", "حسب الجامعة أو الكلية في موريشيوس"),
    ("by", "by university or college in nebraska", "حسب الجامعة أو الكلية في نبراسكا"),
    ("by", "by university or college in north carolina", "حسب الجامعة أو الكلية في كارولاينا الشمالية"),
    ("by", "by university or college", "حسب الجامعة أو الكلية"),
    ("by", "by year and continent", "حسب السنة والقارة"),
    ("by", "by year of disestablishment", "حسب سنة الانحلال"),
    ("by", "by year of introduction", "حسب سنة الاستحداث"),
    ("established in", "the 7th millennium bc", "الألفية السابعة ق م"),
    ("executed by", "ukraine by firing squad", "أوكرانيا رميا بالرصاص"),
    ("for", "for malta ", "مالطا"),
    ("for", "for the british virgin islands", "جزر العذراء البريطانية"),
    ("for", "for the russian empire", "الإمبراطورية الروسية"),
    ("for", "for the soviet union", "الاتحاد السوفيتي"),
    ("for", "for the united states", "الولايات المتحدة"),
    ("from", " kingdom-of asturias", "مملكة أستورياس"),
    ("from", "alphen aan den rijn", "ألفن آن دن راين"),
    ("from", "the city of westminster", "مدينة وستمنستر"),
    ("from", "the london borough of lambeth", "لامبيث"),
    ("from", "the province of valencia", "بلنسية (مقاطعة)"),
    ("from", "the west midlands (county)", "مقاطعة ميدلاند الغربية"),
    ("from", "vila nova de gaia", "فيلا نوا دغايا"),
    ("in", " kingdom-of hanover", "مملكة هانوفر"),
    ("in", " kingdom-of sardinia", "مملكة سردينيا"),
    ("in", " kingdom-of sicily", "مملكة صقلية"),
    ("in", "1789 asian winter games", "الألعاب الآسيوية الشتوية 1789"),
    ("in", "1789 british empire games", "دورة ألعاب الإمبراطورية البريطانية 1789"),
    ("in", "1789 fifa women's world cup", "كأس العالم لكرة القدم للسيدات 1789"),
    ("in", "1789 fifa world cup", "كأس العالم لكرة القدم 1789"),
    ("in", "1789 pan american games", "دورة الألعاب الأمريكية 1789"),
    ("in", "buildings and structures in africa", "مبان ومنشآت في إفريقيا"),
    ("in", "gautam buddh nagar district", "مقاطعة جوتام بوذا نجر"),
    ("in", "insular areas of united states", "المناطق المعزولة في الولايات المتحدة"),
    ("in", "israeli reality television series", "مسلسلات تلفزيونية واقعية إسرائيلية"),
    ("in", "saint vincent and the grenadines", "سانت فينسنت والغرينادين"),
    ("in", "santa maria da feira", "سانتا ماريا دا فييرا"),
    ("in", "south african rugby union", "اتحاد الرجبي الجنوب الإفريقي"),
    ("in", "south american women's football", "كرة قدم أمريكية جنوبية نسائية"),
    ("in", "south korean women's sport", "رياضة كورية جنوبية نسائية"),
    ("in", "special region of yogyakarta", "يوجياكرتا"),
    ("in", "the american civil war", "الحرب الأهلية الأمريكية"),
    ("in", "the asian para games", "دورة الألعاب الآسيوية البارالمبية"),
    ("in", "the australian capital territory", "إقليم العاصمة الأسترالية"),
    ("in", "the basque country (autonomous community)", "منطقة الباسك ذاتية الحكم"),
    ("in", "the bay of plenty region", "إقليم خليج بانتي"),
    ("in", "the british virgin islands", "جزر العذراء البريطانية"),
    ("in", "the capital region of denmark", "إقليم هوفدستادن"),
    ("in", "the central african republic", "جمهورية إفريقيا الوسطى"),
    ("in", "the city of westminster", "مدينة وستمنستر"),
    ("in", "the cocos (keeling) islands", "جزر كوكوس"),
    ("in", "the collectivity of saint martin", "تجمع سان مارتين"),
    ("in", "the croatian war of independence", "الحرب الكرواتية في استقلال"),
    ("in", "the federated states-of micronesia", "ولايات ميكرونيسيا المتحدة"),
    ("in", "the french colonial empire", "الإمبراطورية الاستعمارية الفرنسية"),
    ("in", "the holy roman empire", "الإمبراطورية الرومانية المقدسة"),
    ("in", "the irish free state", "الدولة الأيرلندية الحرة"),
    ("in", "the northern mariana islands", "جزر ماريانا الشمالية"),
    ("in", "the peerage of ireland", "نبلاء إيرلندا"),
    ("in", "the real estate industry", "صناعة عقارية"),
    ("in", "the region of southern denmark", "إقليم سيد دنمارك"),
    ("in", "the socialist republic-of macedonia", "جمهورية مقدونيا الاشتراكية"),
    ("in", "the spanish east indies", "جزر الهند الشرقية الإسبانية"),
    ("in", "the summer olympics ", "الألعاب الأولمبية الصيفية"),
    ("in", "the summer olympics navigational boxes", "صناديق تصفح الألعاب الأولمبية الصيفية"),
    ("in", "the summer world university games", "ألعاب الجامعات العالمية الصيفية"),
    ("in", "the turks and caicos islands", "جزر توركس وكايكوس"),
    ("in", "the united arab emirates", "الإمارات العربية المتحدة"),
    ("in", "the united states virgin islands", "جزر العذراء الأمريكية"),
    ("in", "the university of galway", "جامعة جلوي"),
    ("in", "the world aquatics championships", "بطولة العالم للرياضات المائية"),
    ("in", "the world athletics championships", "بطولة العالم لألعاب القوى"),
    ("in", "udham singh nagar district", "مقاطعة اودهام سينغ نجر"),
    ("in", "ústí nad labem region", "إقليم أوستي ناد لابم"),
    ("involving the", "islamic state of iraq and the levant", "تنظيم داعش"),
    ("named after", "organizations based in gabon", "منظمات مقرها في الغابون"),
    ("named after", "populated places in uruguay", "أماكن مأهولة في الأوروغواي"),
    ("named after", "universities and colleges in ghana", "جامعات وكليات في غانا"),
    ("named after", "universities and colleges in uruguay", "جامعات وكليات في الأوروغواي"),
    ("of", " kingdom-of italy (1789–1789)", "مملكة إيطاليا (1789–1789)"),
    ("of", " kingdom-of montenegro", "مملكة الجبل الأسود"),
    ("of", "aviation accidents or incidents", "حوادث طيران"),
    ("of", "azerbaijan soviet socialist republic", "الجمهورية الأذرية السوفيتية الاشتراكية"),
    ("of", "bosnia and herzegovina people", "بوسنيون"),
    ("of", "bosnia and herzegovina politicians", "سياسيون بوسنيون"),
    ("of", "companies of georgia (country)", "شركات في جورجيا"),
    ("of", "companies of southeast asia", "شركات في جنوب شرق آسيا"),
    ("of", "eighteenth dynasty of egypt", "الأسرة المصرية الثامنة عشر"),
    ("of", "federal subjects of russia", "كيانات روسيا الاتحادية"),
    ("of", "government of burkina faso", "حكومة بوركينا فاسو"),
    ("of", "indian schools and colleges", "مدارس وكليات هندية"),
    ("of", "indigenous peoples of americas", "شعوب أصلية في الأمريكتين"),
    ("of", "london borough of ealing", "إيلنغ"),
    ("of", "mexican drama television series episodes", "حلقات مسلسلات تلفزيونية درامية مكسيكية"),
    ("of", "mexican drama television series", "مسلسلات تلفزيونية درامية مكسيكية"),
    ("of", "order of british empire", "وسام الإمبراطورية البريطانية"),
    ("of", "parliament of england 1789", "برلمان إنجلترا 1789"),
    ("of", "parliament of great britain", "برلمان بريطانيا العظمى"),
    ("of", "parliament of northern ireland 1789–1789", "برلمان أيرلندا الشمالية 1789–1789"),
    ("of", "pays de la loire", "وادي اللوار"),
    ("of", "rochester institute of technology", "معهد روشيستر للتكنولوجيا"),
    ("of", "royal navy of oman", "البحرية السلطانية العمانية"),
    ("of", "são tomé and príncipe", "ساو تومي وبرينسيب"),
    ("of", "ukrainian soviet socialist republic", "جمهورية أوكرانيا السوفيتية الاشتراكية"),
    ("of", "united states air force", "القوات الجوية الأمريكية"),
    ("of", "united states gubernatorial elections", "انتخابات حكام الولايات المتحدة"),
    ("of", "united states virgin islands", "جزر العذراء الأمريكية"),
    ("of", "verkhovna rada of ukrainian soviet socialist republic", "المجلس الأعلى الأوكراني في جمهورية أوكرانيا السوفيتية الاشتراكية"),
    ("of", "water of coquimbo region", "مياه في إقليم كوكيمبو"),
    ("of", "water of hambantota district", "مياه في مديرية هامبانتوتا"),
    ("of", "water of matale district", "مياه في مديرية ماتال"),
    ("of", "water of wilkes land", "مياه في ويلكس لاند"),
    ("set in", "north america by country", "أمريكا الشمالية حسب البلد"),
    ("to", "insular areas of united states", "المناطق المعزولة في الولايات المتحدة"),
    ("to", "saint kitts and nevis", "سانت كيتس ونيفيس"),
    ("to", "the parliament of united kingdom", "برلمان المملكة المتحدة"),
    ("to", "the united arab emirates", "الإمارات العربية المتحدة"),
    ("to", "the united nations in geneva", "الأمم المتحدة في جنيف"),
    ("transferred-from", "the united states navy to the royal navy", "البحرية الأمريكية إلى البحرية الملكية"),
]


@pytest.mark.parametrize("preposition, country, output", data_test, ids=[x[1] for x in data_test])
@pytest.mark.fast
def test_get_con_lab_data2(preposition, country, output) -> None:
    label = get_con_lab(
        preposition=preposition,
        country=country,
        start_get_country2=True
    )
    assert label == output
