import pytest

test_data = {
    "April 1983 events in Europe": "أحداث أبريل 1983 في أوروبا",
    "July 2018 events by continent": "أحداث يوليو 2018 حسب القارة",
    "2000s films": "أفلام إنتاج عقد 2000",
    "00s establishments in the Roman Empire": "تأسيسات عقد 00 في الإمبراطورية الرومانية",
    "1000s disestablishments in Asia": "انحلالات عقد 1000 في آسيا",
    "1950s criminal comedy films": "أفلام كوميديا الجريمة عقد 1950",
    "1960s black comedy films": "أفلام كوميدية سوداء عقد 1960",
    "1960s criminal comedy films": "أفلام كوميديا الجريمة عقد 1960",
    "1970s black comedy films": "أفلام كوميدية سوداء عقد 1970",
    "1970s criminal comedy films": "أفلام كوميديا الجريمة عقد 1970",
    "1980s black comedy films": "أفلام كوميدية سوداء عقد 1980",
    "1980s criminal comedy films": "أفلام كوميديا الجريمة عقد 1980",
    "1990s BC disestablishments in Asia": "انحلالات عقد 1990 ق م في آسيا",
    "1990s disestablishments in Europe": "انحلالات عقد 1990 في أوروبا",
    "1980 sports events in Europe": "أحداث 1980 الرياضية في أوروبا",
    "1650s controversies": "خلافات عقد 1650",
    "12th-century Indian books": "كتب هندية القرن 12",
    "20th-century Ukrainian literature": "أدب أوكراني القرن 20",
    "21st-century Ukrainian literature": "أدب أوكراني القرن 21",

    "18th-century slaves in Morocco": "عبيد في المغرب في القرن 18",
    "19th-century actors": "ممثلون في القرن 19",
    "19th-century actors by religion": "ممثلون في القرن 19 حسب الدين",
    "19th-century people by religion": "أشخاص في القرن 19 حسب الدين",
    "20th-century railway accidents": "حوادث سكك حديد في القرن 20",
    "18th-century people of the Dutch Empire": "أشخاص من الإمبراطورية الهولندية القرن 18",
    "20th-century disestablishments in India": "انحلالات القرن 20 في الهند",
    "21st-century films": "أفلام إنتاج القرن 21",
    "13th century establishments in the Roman Empire": "تأسيسات القرن 13 في الإمبراطورية الرومانية",
    "14th-century establishments in India": "تأسيسات القرن 14 في الهند",
    "19th-century publications": "منشورات القرن 19",
    "Category:Sports events sidebar templates": "تصنيف:قوالب أشرطة جانبية أحداث رياضية",
    "Category:Video games sidebar templates": "تصنيف:قوالب أشرطة جانبية ألعاب فيديو",
    "20th-century men from Northern Ireland": "رجال من أيرلندا الشمالية في القرن 20",
    "21st-century men from Northern Ireland": "رجال من أيرلندا الشمالية في القرن 21",
    "Category:20th-century railway accidents": "تصنيف:حوادث سكك حديد في القرن 20",
    "Category:1st-millennium literature": "تصنيف:أدب الألفية 1",
    "Category:19th-century publications": "تصنيف:منشورات القرن 19",
    "Category:1650s science fiction works": "تصنيف:أعمال خيال علمي عقد 1650",
    "Category:1640s essays": "تصنيف:مقالات عقد 1640",
    "Category:1640s operas": "تصنيف:أوبيرات عقد 1640",
    "Category:1650s operas": "تصنيف:أوبيرات عقد 1650",
    "Category:1670s operas": "تصنيف:أوبيرات عقد 1670",
    "Category:1680s essays": "تصنيف:مقالات عقد 1680",
    "Category:1680s operas": "تصنيف:أوبيرات عقد 1680",
    "Category:1630s operas": "تصنيف:أوبيرات عقد 1630",
    "Category:1630s science fiction works": "تصنيف:أعمال خيال علمي عقد 1630",
    "Category:1610s essays": "تصنيف:مقالات عقد 1610",
    "Category:1610s operas": "تصنيف:أوبيرات عقد 1610",
    "Category:1620s operas": "تصنيف:أوبيرات عقد 1620",
    "Category:2026 ballot measures in the United States": "تصنيف:إجراءات اقتراع في الولايات المتحدة 2026",
    "Category:2026 in politics by country": "تصنيف:سياسة في 2026 حسب البلد",
    "Category:2026 state legislature elections in the United States": "تصنيف:انتخابات المجالس التشريعية للولايات في الولايات المتحدة 2026",
    "Category:Qualification for the 2026 Winter Olympics": "تصنيف:تصفيات مؤهلة إلى الألعاب الأولمبية الشتوية 2026",
    "Category:14th-century lords of Monaco": "تصنيف:لوردات موناكو القرن 14",
    "Category:15th-century lords of Monaco": "تصنيف:لوردات موناكو القرن 15",
    "Category:16th-century lords of Monaco": "تصنيف:لوردات موناكو القرن 16",
    "Category:16th-century rabbis in Jerusalem": "تصنيف:حاخامات في القدس في القرن 16",
    "Category:17th-century lords of Monaco": "تصنيف:لوردات موناكو القرن 17",
    "Category:18th-century Buddhist temples in Thailand": "تصنيف:معابد بوذية في تايلاند القرن 18",
    "Category:18th-century princes of Monaco": "تصنيف:أمراء موناكو القرن 18",
    "Category:1990s landslides": "تصنيف:انهيارات أرضية عقد 1990",
    "Category:19th-century princesses of Wales": "تصنيف:أميرات ويلز القرن 19",
    "Category:2000s Singaporean television series debuts": "تصنيف:مسلسلات تلفزيونية سنغافورية بدأ عرضها في عقد 2000",
    "Category:2020s revolutions": "تصنيف:ثورات عقد 2020",
    "Category:2020s Taiwanese television series debuts": "تصنيف:مسلسلات تلفزيونية تايوانية بدأ عرضها في عقد 2020",
    "Category:20th-century House of Habsburg": "تصنيف:آل هابسبورغ القرن 20",
    "Category:21st-century executions by Somalia": "تصنيف:إعدامات في الصومال في القرن 21",
    "Category:21st-century terrorist incidents in Denmark": "تصنيف:حوادث إرهابية في الدنمارك القرن 21",
    "Category:1520s censuses": "تصنيف:تعداد السكان في عقد 1520",
    "Category:1920s in politics by country": "تصنيف:سياسة في عقد 1920 حسب البلد",
    "Category:5th-century BC kings of Tyre": "تصنيف:ملوك صور القرن 5 ق م",
    "Category:8th-century dukes of Spoleto": "تصنيف:دوقات سبوليتو القرن 8",
    "Category:1690s essays": "تصنيف:مقالات عقد 1690",
    "Category:1690s operas": "تصنيف:أوبيرات عقد 1690",
    "Category:Works by musicians from Northern Ireland": "تصنيف:أعمال موسيقيون من أيرلندا الشمالية",
}

test_data_2 = {
    "10th-century Buddhist temples": "تصنيف:معابد بوذية القرن 10",
    "10th-century Hindu temples": "تصنيف:معابد هندوسية القرن 10",
    "11th-century Buddhist temples": "تصنيف:معابد بوذية القرن 11",
    "11th-century Hindu temples": "تصنيف:معابد هندوسية القرن 11",
    "12th-century Buddhist temples": "تصنيف:معابد بوذية القرن 12",
    "12th-century Hindu temples": "تصنيف:معابد هندوسية القرن 12",
    "13th-century Buddhist temples": "تصنيف:معابد بوذية القرن 13",
    "13th-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 13",
    "13th-century Hindu temples": "تصنيف:معابد هندوسية القرن 13",
    "14th-century Buddhist temples": "تصنيف:معابد بوذية القرن 14",
    "14th-century Hindu temples": "تصنيف:معابد هندوسية القرن 14",
    "15th-century Buddhist temples in China": "تصنيف:معابد بوذية في الصين القرن 15",
    "15th-century Buddhist temples": "تصنيف:معابد بوذية القرن 15",
    "15th-century Hindu temples": "تصنيف:معابد هندوسية القرن 15",
    "16th-century Anglican bishops in Ireland": "تصنيف:أساقفة أنجليكيون في أيرلندا في القرن 16",
    "16th-century Buddhist temples": "تصنيف:معابد بوذية القرن 16",
    "16th-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 16",
    "16th-century Hindu temples": "تصنيف:معابد هندوسية القرن 16",
    "17th-century Anglican bishops in Ireland": "تصنيف:أساقفة أنجليكيون في أيرلندا في القرن 17",
    "17th-century Buddhist temples": "تصنيف:معابد بوذية القرن 17",
    "17th-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 17",
    "17th-century Hindu temples": "تصنيف:معابد هندوسية القرن 17",
    "18th-century Anglican bishops in Ireland": "تصنيف:أساقفة أنجليكيون في أيرلندا في القرن 18",
    "18th-century Anglican bishops in North America": "تصنيف:أساقفة أنجليكيون في أمريكا الشمالية في القرن 18",
    "18th-century Anglican bishops in United States": "تصنيف:أساقفة أنجليكيون في الولايات المتحدة في القرن 18",
    "18th-century Buddhist temples in China": "تصنيف:معابد بوذية في الصين القرن 18",
    "18th-century Buddhist temples": "تصنيف:معابد بوذية القرن 18",
    "18th-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 18",
    "18th-century Hindu temples": "تصنيف:معابد هندوسية القرن 18",
    "19th-century Anglican bishops in Africa": "تصنيف:أساقفة أنجليكيون في إفريقيا في القرن 19",
    "19th-century Anglican bishops in Asia": "تصنيف:أساقفة أنجليكيون في آسيا في القرن 19",
    "19th-century Anglican bishops in Australia": "تصنيف:أساقفة أنجليكيون في أستراليا في القرن 19",
    "19th-century Anglican bishops in Caribbean": "تصنيف:أساقفة أنجليكيون في الكاريبي في القرن 19",
    "19th-century Anglican bishops in China": "تصنيف:أساقفة أنجليكيون في الصين في القرن 19",
    "19th-century Anglican bishops in Ireland": "تصنيف:أساقفة أنجليكيون في أيرلندا في القرن 19",
    "19th-century Anglican bishops in Middle East": "تصنيف:أساقفة أنجليكيون في الشرق الأوسط في القرن 19",
    "19th-century Anglican bishops in New Zealand": "تصنيف:أساقفة أنجليكيون في نيوزيلندا في القرن 19",
    "19th-century Anglican bishops in North America": "تصنيف:أساقفة أنجليكيون في أمريكا الشمالية في القرن 19",
    "19th-century Anglican bishops in Oceania": "تصنيف:أساقفة أنجليكيون في أوقيانوسيا في القرن 19",
    "19th-century Anglican bishops in Sierra Leone": "تصنيف:أساقفة أنجليكيون في سيراليون في القرن 19",
    "19th-century Anglican bishops in United States": "تصنيف:أساقفة أنجليكيون في الولايات المتحدة في القرن 19",
    "19th-century Anglican bishops of Gibraltar": "تصنيف:أساقفة أنجليكيون من جبل طارق القرن 19",
    "19th-century Buddhist temples": "تصنيف:معابد بوذية القرن 19",
    "19th-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 19",
    "19th-century Hindu temples": "تصنيف:معابد هندوسية القرن 19",
    "1st-century BC Hindu temples": "تصنيف:معابد هندوسية القرن 1 ق م",
    "1st-century Hindu temples": "تصنيف:معابد هندوسية القرن 1",
    "20th-century Anglican bishops in Africa": "تصنيف:أساقفة أنجليكيون في إفريقيا في القرن 20",
    "20th-century Anglican bishops in Asia": "تصنيف:أساقفة أنجليكيون في آسيا في القرن 20",
    "20th-century Anglican bishops in Australia": "تصنيف:أساقفة أنجليكيون في أستراليا في القرن 20",
    "20th-century Anglican bishops in Bermuda": "تصنيف:أساقفة أنجليكيون في برمودا في القرن 20",
    "20th-century Anglican bishops in Canada": "تصنيف:أساقفة أنجليكيون في كندا في القرن 20",
    "20th-century Anglican bishops in Caribbean": "تصنيف:أساقفة أنجليكيون في الكاريبي في القرن 20",
    "20th-century Anglican bishops in China": "تصنيف:أساقفة أنجليكيون في الصين في القرن 20",
    "20th-century Anglican bishops in Europe": "تصنيف:أساقفة أنجليكيون في أوروبا في القرن 20",
    "20th-century Anglican bishops in Ghana": "تصنيف:أساقفة أنجليكيون في غانا في القرن 20",
    "20th-century Anglican bishops in India": "تصنيف:أساقفة أنجليكيون في الهند في القرن 20",
    "20th-century Anglican bishops in Ireland": "تصنيف:أساقفة أنجليكيون في أيرلندا في القرن 20",
    "20th-century Anglican bishops in Malawi": "تصنيف:أساقفة أنجليكيون في ملاوي في القرن 20",
    "20th-century Anglican bishops in Mexico": "تصنيف:أساقفة أنجليكيون في المكسيك في القرن 20",
    "20th-century Anglican bishops in Middle East": "تصنيف:أساقفة أنجليكيون في الشرق الأوسط في القرن 20",
    "20th-century Anglican bishops in New Zealand": "تصنيف:أساقفة أنجليكيون في نيوزيلندا في القرن 20",
    "20th-century Anglican bishops in Nigeria": "تصنيف:أساقفة أنجليكيون في نيجيريا في القرن 20",
    "20th-century Anglican bishops in North America": "تصنيف:أساقفة أنجليكيون في أمريكا الشمالية في القرن 20",
    "20th-century Anglican bishops in Oceania": "تصنيف:أساقفة أنجليكيون في أوقيانوسيا في القرن 20",
    "20th-century Anglican bishops in Sierra Leone": "تصنيف:أساقفة أنجليكيون في سيراليون في القرن 20",
    "20th-century Anglican bishops in South America": "تصنيف:أساقفة أنجليكيون في أمريكا الجنوبية في القرن 20",
    "20th-century Anglican bishops in Tanzania": "تصنيف:أساقفة أنجليكيون في تنزانيا في القرن 20",
    "20th-century Anglican bishops in Uganda": "تصنيف:أساقفة أنجليكيون في أوغندا في القرن 20",
    "20th-century Anglican bishops in United States": "تصنيف:أساقفة أنجليكيون في الولايات المتحدة في القرن 20",
    "20th-century Anglican bishops of Gibraltar": "تصنيف:أساقفة أنجليكيون من جبل طارق القرن 20",
    "20th-century Buddhist temples": "تصنيف:معابد بوذية القرن 20",
    "20th-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 20",
    "20th-century Hindu temples": "تصنيف:معابد هندوسية القرن 20",
    "20th-century Islamic terrorist incidents": "تصنيف:حوادث إرهابية منسوبة للمسلمين القرن 20",
    "21st-century Anglican bishops in Africa": "تصنيف:أساقفة أنجليكيون في إفريقيا في القرن 21",
    "21st-century Anglican bishops in Asia": "تصنيف:أساقفة أنجليكيون في آسيا في القرن 21",
    "21st-century Anglican bishops in Australia": "تصنيف:أساقفة أنجليكيون في أستراليا في القرن 21",
    "21st-century Anglican bishops in Bermuda": "تصنيف:أساقفة أنجليكيون في برمودا في القرن 21",
    "21st-century Anglican bishops in Canada": "تصنيف:أساقفة أنجليكيون في كندا في القرن 21",
    "21st-century Anglican bishops in Caribbean": "تصنيف:أساقفة أنجليكيون في الكاريبي في القرن 21",
    "21st-century Anglican bishops in China": "تصنيف:أساقفة أنجليكيون في الصين في القرن 21",
    "21st-century Anglican bishops in Ghana": "تصنيف:أساقفة أنجليكيون في غانا في القرن 21",
    "21st-century Anglican bishops in India": "تصنيف:أساقفة أنجليكيون في الهند في القرن 21",
    "21st-century Anglican bishops in Ireland": "تصنيف:أساقفة أنجليكيون في أيرلندا في القرن 21",
    "21st-century Anglican bishops in Malawi": "تصنيف:أساقفة أنجليكيون في ملاوي في القرن 21",
    "21st-century Anglican bishops in Mexico": "تصنيف:أساقفة أنجليكيون في المكسيك في القرن 21",
    "21st-century Anglican bishops in Middle East": "تصنيف:أساقفة أنجليكيون في الشرق الأوسط في القرن 21",
    "21st-century Anglican bishops in New Zealand": "تصنيف:أساقفة أنجليكيون في نيوزيلندا في القرن 21",
    "21st-century Anglican bishops in Nigeria": "تصنيف:أساقفة أنجليكيون في نيجيريا في القرن 21",
    "21st-century Anglican bishops in North America": "تصنيف:أساقفة أنجليكيون في أمريكا الشمالية في القرن 21",
    "21st-century Anglican bishops in Oceania": "تصنيف:أساقفة أنجليكيون في أوقيانوسيا في القرن 21",
    "21st-century Anglican bishops in Sierra Leone": "تصنيف:أساقفة أنجليكيون في سيراليون في القرن 21",
    "21st-century Anglican bishops in South America": "تصنيف:أساقفة أنجليكيون في أمريكا الجنوبية في القرن 21",
    "21st-century Anglican bishops in Tanzania": "تصنيف:أساقفة أنجليكيون في تنزانيا في القرن 21",
    "21st-century Anglican bishops in Uganda": "تصنيف:أساقفة أنجليكيون في أوغندا في القرن 21",
    "21st-century Anglican bishops in United States": "تصنيف:أساقفة أنجليكيون في الولايات المتحدة في القرن 21",
    "21st-century Anglican bishops of Gibraltar": "تصنيف:أساقفة أنجليكيون من جبل طارق القرن 21",
    "21st-century Buddhist temples": "تصنيف:معابد بوذية القرن 21",
    "21st-century Hindu philosophers and theologians": "تصنيف:فلاسفة هندوس ولاهوتيون القرن 21",
    "21st-century Hindu temples": "تصنيف:معابد هندوسية القرن 21",
    "21st-century Islamic terrorist incidents": "تصنيف:حوادث إرهابية منسوبة للمسلمين القرن 21",
    "21st-century Methodist bishops in United States": "تصنيف:أساقفة ميثوديون لاهوتيون في الولايات المتحدة في القرن 21",
    "2nd-century BC Hindu temples": "تصنيف:معابد هندوسية القرن 2 ق م",
    "2nd-century Hindu temples": "تصنيف:معابد هندوسية القرن 2",
    "3rd-century BC Hindu temples": "تصنيف:معابد هندوسية القرن 3 ق م",
    "3rd-century Buddhist temples": "تصنيف:معابد بوذية القرن 3",
    "4th-century Buddhist temples": "تصنيف:معابد بوذية القرن 4",
    "4th-century Hindu temples": "تصنيف:معابد هندوسية القرن 4",
    "5th-century BC Hindu temples": "تصنيف:معابد هندوسية القرن 5 ق م",
    "5th-century Buddhist temples": "تصنيف:معابد بوذية القرن 5",
    "5th-century Hindu temples": "تصنيف:معابد هندوسية القرن 5",
    "6th-century Buddhist temples": "تصنيف:معابد بوذية القرن 6",
    "6th-century Hindu temples": "تصنيف:معابد هندوسية القرن 6",
    "7th-century Buddhist temples": "تصنيف:معابد بوذية القرن 7",
    "7th-century Hindu temples": "تصنيف:معابد هندوسية القرن 7",
    "8th-century Buddhist temples": "تصنيف:معابد بوذية القرن 8",
    "8th-century Hindu temples": "تصنيف:معابد هندوسية القرن 8",
    "9th-century Buddhist temples": "تصنيف:معابد بوذية القرن 9",
    "9th-century Hindu temples": "تصنيف:معابد هندوسية القرن 9",
    "Lists of Buddhist buildings and structures": "تصنيف:قوائم مبان ومنشآت بوذية",
    "Lists of Hindu buildings and structures": "تصنيف:قوائم مبان ومنشآت هندوسية",
    "Lists of Islamic buildings and structures": "تصنيف:قوائم مبان ومنشآت إسلامية",
    "Lists of Jewish buildings and structures": "تصنيف:قوائم مبان ومنشآت يهودية"
}
