#!/usr/bin/python3
"""
!
"""

from typing import Dict

CHANGE_KEY_MAPPINGS: Dict[str, str] = {
    # TODO: find why this used in the code
    "players in": "playerss in",

    r"\’": "'",

    r" \– men's tournament": " mens tournament",
    r" \– women's tournament": " womens tournament",

    r" \- women's tournament": " womens tournament",
    r" \- men's tournament": " mens tournament",

    r"athletes \(track and field\)": "track and field athletes",
    r"publishers \(people\)": "publisherspeople",
    "publishers (people)": "publisherspeople",
    r"football \(soccer\)": "football",
    r"us open \(tennis\)": "us open tennis",
    r"\(tennis\)": "tennis",

    "adaptations of works": "adaptations-of-works",
    # "people of ottoman empire" :"people-of-ottoman-empire",
    # "sentenced to death" :"sentenced-to-death",
    "africa cup of nations": "africa cup-of-nations",
    "health care": "healthcare",
    "child soldiers": "child-soldiers",
    "labour and social security": "labour-and-social security",
    "accidents and incidents": "accidents-and-incidents",
    "for member of parliament": "for member-of-parliament",
    "in northern ireland": "in northern-ireland",
    "manufactured in": "manufactured-in",
    "manufactured by": "manufactured-by",
    "association football afc": "association-football afc",
    "imprisoned in": "imprisoned-in",
    "launched in": "launched-in",
    "launched by": "launched-by",
    "transferred from": "transferred-from",
    "built in": "built-in",
    "built by": "built-by",
    "caribbean people": "caribbeans people",
    "world war ii": "world-war-ii",
    "world war i": "world-war-i",
    "killed in action": "killed-in-action",
    "city of liverpool f.c.": "city-of-liverpool f.c.",
    "medallists": "medalists",
    "saudi arabian": "saudiarabian",
    "athletes (track and field)": "track and field athletes",
    "world championships in athletics": "world championships-in-athletics",
    "murderers of children": "murderersofchildren",
    "prisoners of conscience": "prisoners-of-conscience",
    "convicted of murder by ": "convicted-of-murder-by ",
    "convicted-of-murder by ": "convicted-of-murder-by ",
    "university of reading": "university-of-reading",
    "university of science and technology": "university-of-science and technology",
    "governance of policing": "governance policing",
    # "university of " :"university-of ",
    "university of technology": "university-of-technology",
    "refusing to convert to christianity": "refusing-to-convert-to-christianity",
    "refusing to convert to islam": "refusing-to-convert-to-islam",
    # "austria-hungary" :"austriahungary",
    "convicted of murder": "convicted-of-murder",
    # "university of" :"university-of",
    "presidential elections": "presidential-elections",
    "presidential primaries": "presidential-primaries",
    "general elections": "general-elections",
    "local elections": "local-elections",
    "early modern": "early-modern",
    "sports culture": "sprts culture",
    "by firearm in": "by-firearm-in",
    "military equipment": "military-equipment",
    "military terminology": "military-terminology",
    "shot dead by law enforcement officers": "shot dead-by-law enforcement officers",
    "west coast of united states": "west coast-of-united states",
    "future elections": "future-elections",
    "sports media": "sports-media",
    "by car bomb": "by-car-bomb",
    "television series endings": "television series-endings",
    "television series debuts": "television series-debuts",
    "television miniseries endings": "television miniseries-endings",
    "television miniseries debuts": "television miniseries-debuts",
    "television films endings": "television films-endings",
    "television films debuts": "television films-debuts",
    "basedon non-": "basedon non ",
    "television seasons": "television-seasons",
    "ministers for": "ministers-for",
    "sport ministers": "sport-ministers",
    "sports ministers": "sports-ministers",
    "british hong kong": "british-hong-kong",
    "scholars of islam": "scholars-of-islam",
    # "sports events" : "sports-events",
    "united states house of representatives": "united states house-of-representatives",
    "sports events": "sports-events",
    "war of ": "war-of ",
    # "paintings by" : "paintings-by",
    "sportspeople": "sports-people",
    "architecture schools": "architecture-schools",
    " labor ": " labour ",
    "elections, ": "elections ",
    "harrow on hill": "harrow-on-hill",
    "city of london": "city-of-london",
    "^labor ": "labour ",
    " labor$": " labour",
    "executions by": "executions in",
    "african american": "africanamerican",
    "african-american": "africanamerican",
    "in sports in": "in-sports-in",
    # "ancient romans" :"ancient-romans",
    "ancient roman": "ancient-roman",
    "ancient greek": "ancient-greek",
    "ancient macedonian": "ancient-macedonian",
    "in sport in": "in-sport-in",
    "kingdom of": "kingdom-of",
    "national register of historic places": "national-register-of-historic-places",
    # "executed by guillotine" : "executed-guillotine",
    "executed by burning": "executed-burning",
    "executed by hanging": "executed-hanging",
    "executed by decapitation": "executed-decapitation",
    "executed by firearm": "executed-firearm",
    # " executed by " :" executed-by ",
    "emirate of": "emirate-of",
    "republic of": "republic-of",
    "duchy of": "duchy-of",
    "states of": "states-of",
    "comedy-": "comedy ",
    "domain of": "domain-of",
    "crown of": "crown-of",
    "county of": "county-of",
    "protectorate of": "protectorate-of",
    "canton of": "canton-of",
    "march of": "march-of",
    "margraviate of": "margraviate-of",
    "colony of": "colony-of",
    # "province of" :"province-of",
    "realm of": "realm-of",
    "isle of": "isle-of",
    "viceroyalty of": "viceroyalty-of",
}
# ---

CHANGE_KEY_SECONDARY: Dict[str, str] = {
    " for deafblind$": " for-deafblind",
    "charter airlines": "charter-airlines",
    " for blind$": " for-blind",
    " for deaf$": " for-deaf",
    " for blind ": " for-blind ",
    " for deaf ": " for-deaf ",
    "term of Iranian Majlis": "Iranian Majlis",
    "orgadnisation for prohibition of chemical weapons": "opcw",
    "country of residence": "country-of-residence",
    "serbia and montenegro": "serbia-and-montenegro",
    " at 2": " in 2",
    "^tour de ": "tour of ",
    "game of thrones": "game-of-thrones",
    "green party of quebec": "green party-of-quebec",
    "libertarian party of canada": "libertarian party-of-canada",
    "declarations of independence": "declarations-of-independence",
    "united states declaration of independence": "united-states-declaration-of-independence",
    "house of commons": "house-of-commons",
    "house of representatives": "house-of-representatives",
    " at 1": " in 1",
    " executed people$": " executed-people",
    r" \- men's tournament": " mens tournament",
    r" \- women's tournament": " womens tournament",
    " - men's tournament": " mens tournament",
    " - women's tournament": " womens tournament",
    "historians of philosophy": "historians-of-philosophy",
    " at ": " in ",
    " women's footballers$": " female footballers",
    "^women's footballers ": "female footballers ",
    "^women's footballers": "female footballers",
    " remade in ": " remadein ",
    " based on ": " basedon ",
    r"^men\’s events ": "mensvents",
}
# ---

# Backwards compatibility exports
Change_key = CHANGE_KEY_MAPPINGS
Change_key2 = CHANGE_KEY_SECONDARY
