"""
Tests
"""

import pytest

from ArWikiCats.legacy_bots.legacy_resolvers_bots.con2_lab import get_type_lab

data = [
    (" by ", "national-register-of-historic-places in north carolina", "السجل الوطني للأماكن التاريخية في كارولاينا الشمالية", ),
    (" from ", "federalist party members of united states house-of-representatives", "أعضاء الحزب الفيدرالي الأمريكي في مجلس النواب الأمريكي", ),
    (" from ", "know-nothing members of united states house-of-representatives", "أعضاء حزب لا أدري في مجلس النواب الأمريكي", ),
    (" from ", "whig party members of united states house-of-representatives", "أعضاء حزب اليمين في مجلس النواب الأمريكي", ),
    (" in ", "agricultural buildings and structures on the-national-register-of-historic-places", "مبان ومنشآت زراعية في السجل الوطني للأماكن التاريخية", ),
    (" in ", "bank buildings on the-national-register-of-historic-places", "مباني بنوك في السجل الوطني للأماكن التاريخية", ),
    (" in ", "buildings and structures on the-national-register-of-historic-places", "مبان ومنشآت في السجل الوطني للأماكن التاريخية", ),
    (" in ", "railway stations on the-national-register-of-historic-places", "محطات السكك الحديدية في السجل الوطني للأماكن التاريخية", ),
    (" involving ", "military operations of war in afghanistan (1789–1789)", "عمليات عسكرية في الحرب في أفغانستان (1789–1789)", ),
    (" based in ", "medical and health organizations", "منظمات طبية وصحية"),
    (" by ", "1789 crimes in africa", "جرائم 1789 في إفريقيا"),
    (" by ", "1789 elections in the united states", "انتخابات 1789 في الولايات المتحدة"),
    (" by ", "1789 establishments in india", "تأسيسات سنة 1789 في الهند"),
    (" by ", "1789 in asian sport", "رياضة آسيوية في 1789"),
    (" by ", "1789 in brazilian sport", "رياضة برازيلية في 1789"),
    (" by ", "1789 in chinese sport", "رياضة صينية في 1789"),
    (" by ", "1789 in men's football", "كرة قدم رجالية في 1789"),
    (" by ", "1789 in north america", "أمريكا الشمالية في 1789"),
    (" by ", "1789 in south america", "أمريكا الجنوبية في 1789"),
    (" by ", "1789 in south american football", "كرة القدم الأمريكية الجنوبية في 1789"),
    (" by ", "1789 in the united kingdom", "المملكة المتحدة في 1789"),
    (" by ", "1789 in women's sport", "رياضة نسائية في 1789"),
    (" by ", "1789 in youth football", "كرة قدم شبابية في 1789"),
    (" by ", "anglican bishops in asia", "أساقفة أنجليكيون في آسيا"),
    (" by ", "basketball players in lebanon", "لاعبو كرة سلة في لبنان"),
    (" by ", "buildings and structures in georgia (u.s. state)", "مبان ومنشآت في ولاية جورجيا"),
    (" by ", "buildings and structures in idaho", "مبان ومنشآت في أيداهو"),
    (" by ", "buildings and structures in prince edward island", "مبان ومنشآت في جزيرة الأمير إدوارد"),
    (" by ", "burials in washington (state)", "مدفونون في ولاية واشنطن"),
    (" by ", "christianity in the united states", "المسيحية في الولايات المتحدة"),
    (" by ", "disestablishments in georgia (u.s. state)", "انحلالات في ولاية جورجيا"),
    (" by ", "electronic dance music albums", "ألبومات موسيقى الرقص الإلكترونية"),
    (" by ", "establishments in southeast asia", "تأسيسات في جنوب شرق آسيا"),
    (" by ", "ethnic groups in china", "مجموعات عرقية في الصين"),
    (" by ", "female field hockey players", "لاعبات هوكي ميدان"),
    (" by ", "field hockey players in germany", "لاعبو هوكي ميدان في ألمانيا"),
    (" by ", "food and drink in europe", "أطعمة ومشروبات في أوروبا"),
    (" by ", "historic districts in massachusetts", "المناطق التاريخية في ماساتشوستس"),
    (" by ", "history of austria hungary", "تاريخ الإمبراطورية النمساوية المجرية"),
    (" by ", "history of central african republic", "تاريخ جمهورية إفريقيا الوسطى"),
    (" by ", "history of north america", "تاريخ أمريكا الشمالية"),
    (" by ", "history of northern ireland", "تاريخ أيرلندا الشمالية"),
    (" by ", "history of nova scotia", "تاريخ نوفا سكوشا"),
    (" by ", "lists of bosnia and herzegovina people", "قوائم بوسنيون"),
    (" by ", "lists of country subdivisions", "قوائم تقسيمات البلد"),
    (" by ", "male actors from the west midlands (county)", "ممثلون ذكور من مقاطعة ميدلاند الغربية"),
    (" by ", "nations in the summer olympics", "بلدان في الألعاب الأولمبية الصيفية"),
    (" by ", "netball in north america", "كرة الشبكة في أمريكا الشمالية"),
    (" by ", "parks in south america", "متنزهات في أمريكا الجنوبية"),
    (" by ", "people from west sumatra", "أشخاص من سومطرة الغربية"),
    (" by ", "port cities and towns", "مدن وبلدات ساحلية"),
    (" by ", "protected areas of georgia (u.s. state)", "مناطق محمية في ولاية جورجيا"),
    (" by ", "railway stations in romania", "محطات السكك الحديدية في رومانيا"),
    (" by ", "railway stations in the philippines", "محطات السكك الحديدية في الفلبين"),
    (" by ", "rivers of united states", "أنهار الولايات المتحدة"),
    (" by ", "road incident deaths in the united states", "وفيات حوادث الطرق في الولايات المتحدة"),
    (" by ", "rugby union players from west yorkshire", "لاعبو اتحاد رجبي من غرب يوركشاير"),
    (" by ", "skyscrapers in the united arab emirates", "ناطحات سحاب في الإمارات العربية المتحدة"),
    (" by ", "sports governing bodies in north america", "هيئات تنظيم رياضية في أمريكا الشمالية"),
    (" by ", "sports-people in västmanland county", "رياضيون في مقاطعة فستمانلاند"),
    (" by ", "taiwanese football club seasons", "مواسم أندية كرة قدم تايوانية"),
    (" by ", "tanks of united states", "دبابات الولايات المتحدة"),
    (" by ", "tourism in republic-of ireland", "سياحة في جمهورية أيرلندا"),
    (" by ", "trade unions in the caribbean", "نقابات عمالية في الكاريبي"),
    (" by ", "transport infrastructure in south america", "البنية التحتية للنقل في أمريكا الجنوبية"),
    (" by ", "transportation buildings and structures in new hampshire", "مبان ومنشآت نقل في نيوهامشير"),
    (" by ", "unincorporated communities in alaska", "مجتمعات فردية في ألاسكا"),
    (" by ", "united states senate candidates", "مرشحو مجلس الشيوخ الأمريكي"),
    (" by ", "universities and colleges in andhra pradesh", "جامعات وكليات في أندرا برديش"),
    (" by ", "universities and colleges in texas", "جامعات وكليات في تكساس"),
    (" by ", "universities and colleges in ukraine", "جامعات وكليات في أوكرانيا"),
    (" by ", "volleyball competitions in asia", "منافسات كرة طائرة في آسيا"),
    (" by ", "weapons of mass destruction", "أسلحة دمار شامل"),
    (" by ", "welsh rugby union players", "لاعبو اتحاد رجبي ويلزيون"),
    (" by ", "women's footballers in ireland", "لاعبات كرة قدم في أيرلندا"),
    (" closed in ", "railway stations in albania", "محطات السكك الحديدية في ألبانيا"),
    (" closed in ", "railway stations in france", "محطات السكك الحديدية في فرنسا"),
    (" closed in ", "railway stations in germany", "محطات السكك الحديدية في ألمانيا"),
    (" closed in ", "railway stations in new zealand", "محطات السكك الحديدية في نيوزيلندا"),
    (" closed in ", "railway stations in northern-ireland", "محطات السكك الحديدية في أيرلندا الشمالية"),
    (" closed in ", "railway stations in republic-of ireland", "محطات السكك الحديدية في جمهورية أيرلندا"),
    (" completed in ", "religious buildings and structures", "مبان ومنشآت دينية"),
    (" concerning ", "united nations security council resolutions", "قرارات مجلس الأمن التابع للأمم المتحدة"),
    (" disestablished in ", "art museums and galleries", "متاحف فنية ومعارض"),
    (" disestablished in ", "television channels and stations", "قنوات وشبكات تلفزيونية"),
    (" established in ", "art museums and galleries", "متاحف فنية ومعارض"),
    (" established in ", "australian rules football clubs", "أندية كرة قدم أسترالية"),
    (" established in ", "military units and formations", "وحدات وتشكيلات عسكرية"),
    (" established in ", "sports clubs and teams", "أندية وفرق رياضية"),
    (" for ", "african games bronze medalists", "فائزون بميداليات برونزية في الألعاب الإفريقية"),
    (" for ", "african games silver medalists", "فائزون بميداليات فضية في الألعاب الإفريقية"),
    (" for ", "central american and caribbean games medalists", "فائزون بميداليات ألعاب أمريكا الوسطى والكاريبي"),
    (" for ", "commonwealth games bronze medalists", "فائزون بميداليات برونزية في ألعاب الكومنولث"),
    (" for ", "islamic solidarity games silver medalists", "فائزون بميداليات فضية في ألعاب التضامن الإسلامي"),
    (" for ", "olympic field hockey players", "لاعبو هوكي ميدان أولمبيون"),
    (" for ", "olympic table tennis players", "لاعبو كرة طاولة أولمبيون"),
    (" for ", "pan american games medalists", "فائزون بميداليات دورة الألعاب الأمريكية"),
    (" from ", "democratic party united states senators", "أعضاء مجلس الشيوخ الأمريكي من الحزب الديمقراطي"),
    (" from ", "major league baseball players", "لاعبو دوري كرة القاعدة الرئيسي"),
    (" from ", "players of american football", "لاعبو كرة قدم أمريكية"),
    (" from ", "united states house-of-representatives", "مجلس النواب الأمريكي"),
    (" hosted by ", "international field hockey competitions", "منافسات هوكي ميدان دولية"),
    (" hosted by ", "international ice hockey competitions", "منافسات هوكي جليد دولية"),
    (" in ", "art museums and galleries", "متاحف فنية ومعارض"),
    (" in ", "attacks on buildings and structures", "هجمات على مبان ومنشآت"),
    (" in ", "attacks on diplomatic missions", "هجمات على بعثات دبلوماسية"),
    (" in ", "attacks on military installations", "هجمات على منشآت عسكرية"),
    (" in ", "australian rules football clubs", "أندية كرة قدم أسترالية"),
    (" in ", "brazilian expatriate basketball people", "أعلام كرة سلة برازيليون مغتربون"),
    (" in ", "buildings and structures under construction", "مبان ومنشآت تحت بناء"),
    (" in ", "bulgarian expatriate basketball people", "أعلام كرة سلة بلغاريون مغتربون"),
    (" in ", "by university or college", "حسب الجامعة أو الكلية"),
    (" in ", "christian buildings and structures", "مبان ومنشآت مسيحية"),
    (" in ", "church of jesus christ of latter-day saints", "كنيسة يسوع المسيح لقديسي الأيام الأخيرة"),
    (" in ", "croatian expatriate basketball people", "أعلام كرة سلة كروات مغتربون"),
    (" in ", "defunct sports clubs and teams", "أندية وفرق رياضية سابقة"),
    (" in ", "demolished buildings and structures", "مبان ومنشآت مهدمة"),
    (" in ", "expatriates from northern ireland", "مغتربون من أيرلندا الشمالية"),
    (" in ", "former buildings and structures", "مبان ومنشآت سابقة"),
    (" in ", "french expatriate rugby union players", "لاعبو اتحاد رجبي فرنسيون مغتربون"),
    (" in ", "golf clubs and courses", "نوادي الغولف والدورات"),
    (" in ", "history of petroleum industry", "تاريخ صناعة بترولية"),
    (" in ", "impact of covid-19 pandemic", "تأثيرات جائحة فيروس كورونا"),
    (" in ", "installations of united states air force", "منشآت في القوات الجوية الأمريكية"),
    (" in ", "lists of buildings and structures", "قوائم مبان ومنشآت"),
    (" in ", "lists of mayors of places", "قوائم رؤساء بلديات"),
    (" in ", "lists of universities and colleges", "قوائم جامعات وكليات"),
    (" in ", "lithuanian expatriate basketball people", "أعلام كرة سلة ليتوانيون مغتربون"),
    (" in ", "military and war museums", "متاحف عسكرية وحربية"),
    (" in ", "military operations of war", "عمليات عسكرية في الحرب"),
    (" in ", "military units and formations", "وحدات وتشكيلات عسكرية"),
    (" in ", "olympic silver medalists for the united states", "فائزون بميداليات فضية أولمبية من الولايات المتحدة"),
    (" in ", "parliament of united kingdom", "برلمان المملكة المتحدة"),
    (" in ", "port cities and towns", "مدن وبلدات ساحلية"),
    (" in ", "private universities and colleges", "جامعات وكليات خاصة"),
    (" in ", "religious buildings and structures", "مبان ومنشآت دينية"),
    (" in ", "riots and civil disorder", "شغب وعصيان مدني"),
    (" in ", "roman catholic church buildings", "مبان كنائس رومانية كاثوليكية"),
    (" in ", "russian expatriate volleyball players", "لاعبو كرة طائرة روس مغتربون"),
    (" in ", "senegalese expatriate basketball people", "أعلام كرة سلة سنغاليون مغتربون"),
    (" in ", "south african expatriate sports-people", "رياضيون جنوب إفريقيون مغتربون"),
    (" in ", "south korean expatriate sports-people", "رياضيون كوريون جنوبيون مغتربون"),
    (" in ", "spanish expatriate handball players", "لاعبو كرة يد إسبان مغتربون"),
    (" in ", "sports clubs and teams", "أندية وفرق رياضية"),
    (" in ", "swiss expatriate basketball people", "أعلام كرة سلة سويسريون مغتربون"),
    (" in ", "track and field athletes", "رياضيو المسار والميدان"),
    (" in ", "transport buildings and structures", "مبان ومنشآت نقل"),
    (" in ", "transportation buildings and structures", "مبان ومنشآت نقل"),
    (" in ", "tunisian expatriate basketball people", "أعلام كرة سلة تونسيون مغتربون"),
    (" in ", "united states air force", "القوات الجوية الأمريكية"),
    (" in ", "united states house-of-representatives elections", "انتخابات مجلس النواب الأمريكي"),
    (" in ", "victims of aviation accidents or incidents", "ضحايا حوادث طيران"),
    (" in ", "years of 16th century", "سنوات القرن 16"),
    (" in ", "years of 17th century", "سنوات القرن 17"),
    (" in ", "years of 18th century", "سنوات القرن 18"),
    (" in ", "years of 19th century", "سنوات القرن 19"),
    (" in ", "years of 20th century", "سنوات القرن 20"),
    (" in ", "years of 21st century", "سنوات القرن 21"),
    (" involving ", "battles of napoleonic wars", "معارك الحروب النابليونية"),
    (" involving ", "battles of vietnam war", "معارك حرب فيتنام"),
    (" involving the ", "military operations of syrian civil war", "عمليات عسكرية في الحرب الأهلية السورية"),
    (" of ", " university of", "جامعة"),
    (" of ", "forests and woodlands of", "غابات"),
    (" of ", "ports and harbours of", "مرافئ وموانئ"),
    (" on ", "agricultural buildings and structures", "مبان ومنشآت زراعية"),
    (" opened in ", "railway stations in austria", "محطات السكك الحديدية في النمسا"),
    (" opened in ", "railway stations in bangladesh", "محطات السكك الحديدية في بنغلاديش"),
    (" opened in ", "railway stations in denmark", "محطات السكك الحديدية في الدنمارك"),
    (" opened in ", "railway stations in germany", "محطات السكك الحديدية في ألمانيا"),
    (" opened in ", "railway stations in great britain", "محطات السكك الحديدية في بريطانيا العظمى"),
    (" opened in ", "railway stations in hong kong", "محطات السكك الحديدية في هونغ كونغ"),
    (" opened in ", "railway stations in indonesia", "محطات السكك الحديدية في إندونيسيا"),
    (" opened in ", "railway stations in japan", "محطات السكك الحديدية في اليابان"),
    (" opened in ", "railway stations in latvia", "محطات السكك الحديدية في لاتفيا"),
    (" opened in ", "railway stations in northern-ireland", "محطات السكك الحديدية في أيرلندا الشمالية"),
    (" opened in ", "railway stations in poland", "محطات السكك الحديدية في بولندا"),
    (" opened in ", "railway stations in russia", "محطات السكك الحديدية في روسيا"),
    (" opened in ", "railway stations in serbia", "محطات السكك الحديدية في صربيا"),
    (" opened in ", "railway stations in south korea", "محطات السكك الحديدية في كوريا الجنوبية"),
    (" opened in ", "railway stations in spain", "محطات السكك الحديدية في إسبانيا"),
    (" opened in ", "railway stations in sweden", "محطات السكك الحديدية في السويد"),
    (" opened in ", "railway stations in the netherlands", "محطات السكك الحديدية في هولندا"),
    (" opened in ", "railway stations in the russian empire", "محطات السكك الحديدية في الإمبراطورية الروسية"),
    (" opened in ", "railway stations in the united states", "محطات السكك الحديدية في الولايات المتحدة"),
    (" to ", "ambassadors of federated states-of micronesia", "سفراء ولايات ميكرونيسيا المتحدة"),
    (" to ", "ambassadors of south africa", "سفراء جنوب إفريقيا"),
    (" to ", "ambassadors of united states", "سفراء الولايات المتحدة"),
    (" to ", "emigrants from the russian empire", "مهاجرون من الإمبراطورية الروسية"),
    (" to ", "permanent representatives of bahrain", "مندوبو البحرين الدائمون"),
    (" to ", "permanent representatives of jamaica", "مندوبو جامايكا الدائمون"),
    (" to ", "permanent representatives of kazakhstan", "مندوبو كازاخستان الدائمون"),
    (" to ", "permanent representatives of kyrgyzstan", "مندوبو قيرغيزستان الدائمون"),
    (" to ", "trinidad and tobago emigrants", "ترنيداديون مهاجرون"),
]


@pytest.mark.parametrize("preposition, category, output", data, ids=[x[1] for x in data])
@pytest.mark.fast
def test_get_type_lab_data(preposition: str, category: str, output: str) -> None:
    label = get_type_lab(category)
    assert label.strip() == output.strip()
